### ISSUE TITLE
Feature request: Prevent messages from being auto read

### ISSUE THREAD

**Issue by lukenowakcom** [GetStream/stream-chat-android#100]
In our app `ChatFragment` is only one of many fragments alive at the same time in the main screen. When user is not looking at the `ChatFragment` at the moment, we tend to display number of unread messages on the chat navigation icon. 

**1.** Since `ChatFragment` doesn't go to sleep while browsing other fragment, nor it gets destroyed, the `MessageListView` is marking all messages read as soon as they arrive.
https://github.com/GetStream/stream-chat-android/blob/ec030a8b3dfc02f415d3e76301e4e438d3b14638/library/src/main/java/com/getstream/sdk/chat/view/MessageListView.java#L416

**2.** I'm not entirely sure about this one, but I think that `ChannelViewModel` is marking the messages as read too, even before `MessageListView` does.
https://github.com/GetStream/stream-chat-android/blob/master/library/src/main/java/com/getstream/sdk/chat/viewmodel/ChannelViewModel.java#L531

It would be great to have some kind of flag on (possibly) `ChannelViewModel` that would block `markLastMessageRead()` from executing.

**Comment by tbarbugli** [comment]
what instead we detect if the message list is visible on the screen and only then we mark the message as read?

**Comment by lukenowakcom** [comment]
If the fragment is in ViewPager and still `RESUMED` then it will technically be visible all the time so it's not the best solution. But I guess I could make it work by simply switching the whole list visibility to `INVISIBLE` based on the 
```java
override fun setUserVisibleHint(isVisibleToUser: Boolean) {
        super.setUserVisibleHint(isVisibleToUser)
    }
```
calls in Fragment, or maybe navigaton controller state 🤔

**Comment by adrian09h** [comment]
Got it. We need to add enable/disable option about `markLastMessageRead()` so you can handle it on `setMenuVisibility(boolean visible)` from your fragment.
Is it correct @lukenowakcom ?

**Comment by lukenowakcom** [comment]
On `setUserVisibleHint(isVisibleToUser: Boolean)` yes, that would be great to have enable/disable option to control it manually

**Comment by adrian09h** [comment]
Got it. will finish soon.

**Comment by tschellenbach** [comment]
I would prefer this syntax:

```
messageList.disableMarkRead();
messageList.enableMarkRead(); // the default
```

To disable/enable the mark read...
