### ISSUE TITLE
"notification.message_new" doesn't provide channel name

### ISSUE THREAD

**Issue by Kravet** [GetStream/stream-chat-android#1045]
I use "notification.message_new" in order to show the Notification when the app is opened. I need the notification to include the channel name, but NotificationMessageNewEvent contains only channelId.

**SDK version**
- 4.4.7
- android kotlin sdk

**To Reproduce**
1. subscribe to chatClient.subscribeFor(NOTIFICATION_MESSAGE_NEW)
2. By new message from another user and another device.
3. 3. NotificationMessageNewEvent is received, but there is no way to get  the channel name. 

**Device:**
 - Oneplus5t
 - Android Q

**Screenshots**
<img width="917" alt="NotificationMessageNew no channel" src="https://user-images.githubusercontent.com/7354769/102495390-b1531080-407e-11eb-86ec-89621e3aeeb8.png">

**Comment by JcMinarro** [comment]
Hello @Kravet 

The API doesn't provide this information into our events.
If you need the channel info, you will need to query for it to the server.
You can use the following code:
```
ChatClient.instance()
                        .queryChannel(channelType, channelId, QueryChannelRequest())
                        .enqueue {
                            if (it.isSuccess) {
                                val channel = it.data()
                                // Do what you need with channel
                            } else {
                                println("There was an error: ${it.error()}")
                            }
                        }
```

**Comment by Kravet** [comment]
@JcMinarro Hello. 
I see. It seems like a bit an overhead to make additional api call each time user get the **notification.message.new**. Because it might take some time depending on response time and internet connection on the device, as result notification will be delayed.

But the thing is IOS SDK does provide the channel with all info inside within the same event **notification.message.new**. Don't you use the same API calls for Android SDK?

**Comment by tschellenbach** [comment]
adding @tbarbugli and @thesyncim for visibility

**Comment by zsmb13** [comment]
The PR above ^ adds a `channel` property to the event that you'll be able to access to grab its name. This will ship in our next release (4.4.10, coming soon).

**Comment by zsmb13** [comment]
The new version that contains this update is 4.5.0, please try it when you can.

**Comment by JcMinarro** [comment]
Hello @Kravet 
We have released a new version that includes it.
Could you update to the last version and check if it is working for you?
