### ISSUE TITLE
onSetUserCompleted issue

### ISSUE THREAD

**Issue by tschellenbach** [GetStream/stream-chat-android#106]
- queryChannels never completes
- its waiting for the onSetUserCompleted
- the logs show that the client did in fact connect (health check events are there)

This is affecting Tourlina. 

It's a real issue but I haven't found a way to replicate it. 
- pixel 3, api version 29

code for the channel activity fragment and layout:

**Comment by savked** [comment]
Here is the ChatFragment and the layout file we're using. As requested.

[ChatFragment.zip](https://github.com/GetStream/stream-chat-android/files/3698817/ChatFragment.zip)

**Comment by tschellenbach** [comment]
i can have a look at this tomorrow in more detail (unless someone in the amsterdam timezone beats me to it)

**Comment by tschellenbach** [comment]
Manged to replicate it, loading icon goes forever (though the data shows up for me). On the `bug/infinite` branch @tbarbugli 

![image](https://user-images.githubusercontent.com/265409/66364493-24270e80-e947-11e9-81c5-ab6be36c71f9.png)

**Comment by tschellenbach** [comment]
Fixed on the `bug/infinite` branch, there were 2 issues:

- the lifecycle is different for fragments and we didn't handle that correctly
- the lifecycle owner wasn't set in your fragment

**Comment by tschellenbach** [comment]
Added some extra safety on the setUserCompleted handlers, less room for errors now.
