### ISSUE TITLE
Expose live count from channel view model

### ISSUE THREAD

**Issue by tbarbugli** [GetStream/stream-chat-android#119]
We should make it easier to get the unread count for a channel.

Proposal:

- expose a `int getUnreadCount` that returns current count
- expose a LiveData object `LiveData<Number> getLiveUnreadCount`

@tschellenbach what do you think, shall we expose both or just the live data?

**Comment by tschellenbach** [comment]
Channel or channel state should expose the integer

Channel view model should expose the livedata

**Comment by tschellenbach** [comment]
This is done in 2.2.1
