### ISSUE TITLE
Inconsistent and wrong number of channel unread count

### ISSUE THREAD

**Issue by bibibilu** [GetStream/stream-chat-android#1226]
I am using 4.5.0. I am trying to observe unread count for each channel but the channel unread count are not consistent and the sum up for that of all the channel is not equal to the total unread count shown on the bottom tab badge from time to time, as shown in the video. Do you have any ideal to make it work properly? Thanks!

https://user-images.githubusercontent.com/55115952/104872093-bd422480-5901-11eb-9545-e14bc50fab92.mp4

The code used to fetch total unread count 
```
val count = ChatClient.instance().getCurrentUser()?.totalUnreadCount ?: 0
badge.isVisible = count > 0
badge.number = count

ChatDomain.instance().totalUnreadCount.observe(viewLifecycleOwner, Observer {
  badge.isVisible = it > 0
  badge.number = it      
})
```
The code used to fetch channel unread count 
```
ChannelListItemViewHolder holder = new ChannelListItemViewHolder(view) {
      @Override
      public void bind(@NotNull Channel channel, int i, @NotNull ChannelItemPayloadDiff channelItemPayloadDiff) {
        super.bind(channel, i, channelItemPayloadDiff);
        LifecycleOwner lifecycleOwner = (LifecycleOwner) itemView.getContext();
        ChatDomain.instance().getTotalUnreadCount().observe(lifecycleOwner, num -> {
          TextView count = view.findViewById(R.id.channelUnreadCountTextView);
          unreadBadge.setVisibility(channel.getUnreadCount() == 0 ? View.GONE : View.VISIBLE);
          unreadBadge.setVisibility(View.GONE);
          count.setText(String.valueOf(channel.getUnreadCount()));
        });
      }
    };
```

**Comment by bychkovdmitry** [comment]
@bibibilu, thank you for reporting this

As for total unread count, you are doing it correctly here:
```
ChatDomain.instance().totalUnreadCount.observe(viewLifecycleOwner, Observer {
  badge.isVisible = it > 0
  badge.number = it      
})
``` 

What about channel unread count, I see that you are registering lifecycle observer in `bind` method. Obviously you should not be doing that as it creates a memory leak (every time `bind` method is invoked a new observer is registered, but the old one is not disposed). My best guess is that the following code was not working for you:
```
ChannelListItemViewHolder holder = new ChannelListItemViewHolder(view) {
      @Override
      public void bind(@NotNull Channel channel, int i, @NotNull ChannelItemPayloadDiff channelItemPayloadDiff) {
        super.bind(channel, i, channelItemPayloadDiff);
          TextView count = view.findViewById(R.id.channelUnreadCountTextView);
          unreadBadge.setVisibility(channel.getUnreadCount() == 0 ? View.GONE : View.VISIBLE);
          count.setText(String.valueOf(channel.getUnreadCount()));
      }
    };
```

I've just checked, and indeed, our `Channle.unreadCount` field doesn't always contain up-to-date value. The fix is here and hopefully will make it to the next release: [#1227](https://github.com/GetStream/stream-chat-android/pull/1227)

**Comment by bibibilu** [comment]
Thanks for this advice! So is there any way to directly observe a channel's unread message count?

**Comment by bibibilu** [comment]
btw is 4.5.1 the fixed version for incorrect channel unread count?

**Comment by bychkovdmitry** [comment]
@bibibilu 
 It is not very clear how your ViewHolder is used. I assume that you are using a custom `ChannelViewHolderFactory` which returns your custom `ChannelListItemViewHolder`, and your `ChannelsView` is properly bound to our `ChannelsViewModel`. Then starting with 4.5.1  you can simply use the snippet below:
 
```
@Override
public void bind(@NotNull Channel channel, int i, @NotNull ChannelItemPayloadDiff channelItemPayloadDiff) {
    super.bind(channel, i, channelItemPayloadDiff);
    TextView count = view.findViewById(R.id.channelUnreadCountTextView);
    // fixed in 4.5.1, channel.getUnreadCount() contains the most recent value
    unreadBadge.setVisibility(channel.getUnreadCount() == 0 ? View.GONE : View.VISIBLE);
    count.setText(String.valueOf(channel.getUnreadCount()));
}
```
 
 If you want to observe only the unread count, then your `ViewModel` should contain something like that:
 ```
private val _unreadCount = MediatorLiveData<Int>()
public val unreadCount: LiveData<Int> = _unreadCount // observe this `LiveData` from your view
 
 init {
     chatDomain.useCases.watchChannel(cid, 0).enqueue { channelControllerResult ->
            if (channelControllerResult.isSuccess) {
                val channelController = channelControllerResult.data()
                _unreadCount.addSource(channelController.unreadCount) { _unreadCount.value = it }
            }
        }
}
 ```
 
 **Note**: there is one more fix coming which resolves an internal race condition which might also help to resolve this issue:
 [#1234](https://github.com/GetStream/stream-chat-android/pull/1234)

**Comment by bychkovdmitry** [comment]
Closing this for now. Feel free to reopen if the problem still exists in `4.5.2`.

**Comment by bibibilu** [comment]
Hi! I have try this on 4.5.3 and it seems still exist.
As shown in the video, the total unread count at the bottom is correct, but channel unread count is inconsistent (not always happen, can be from time to time reproduced by refresh / reopen the app/ receiving new message)

https://user-images.githubusercontent.com/55115952/107104318-eb66a600-67d5-11eb-8b21-8d2fc53f279a.mp4
