### ISSUE TITLE
Strange behavior at getReactions() method

### ISSUE THREAD

**Issue by kstanislav** [GetStream/stream-chat-android#1286]
Hello there. Need an advice with "Reactions" functionality in mobile SDK (Kotlin).
When I try to receive list of ALL reactions, related to some message using code below

`chatClient.getReactions(messageId, offset, pageSize)`

i receive only MY reactions (left by "current" user)

**SDK version**
- 4.5.1

**Expected behavior**
Receive list of ALL Reactions related to this message (Which reaction was sent by which channel member)

Is there a way to reach this? (I plan to make list by each reaction - who sent what)

**Comment by JcMinarro** [comment]
Hello @kstanislav 

We have been reviewing the behavior of our SDK and it seems is working fine.
After checking it with the Backend Team, it seems there is any issue with the configuration you are using with your ApiKey.
Could you send us the APIKey and the user you are using to support@getstream.io ?
Then we can check your configuration and help you.

Thanks
