### ISSUE TITLE
Remove old typing indicators

### ISSUE THREAD

**Issue by tschellenbach** [GetStream/stream-chat-android#129]
Verify that we do something like this:

![image](https://user-images.githubusercontent.com/265409/66536600-ba3f6e00-eada-11e9-91fe-ff8b985159c5.png)

**Comment by tbarbugli** [comment]
@tschellenbach we do this on `ChannelViewModel` already; did you find a bug with that?

**Comment by tschellenbach** [comment]
I noticed we didnt store event.received at..

**Comment by tschellenbach** [comment]
fixed it in master
