### ISSUE TITLE
Showing and playing gifs

### ISSUE THREAD

**Issue by harrunisk** [GetStream/stream-chat-android#1315]
**Describe the bug**
Showing and playing gifs is not working properly.

**SDK version**
- 4.5.0  
- 4.5.2

**To Reproduce**
1. Go to 'channel'
2. Send 'gif'

**Expected behavior**
Preview in the message list and playing gif in full screen or preview.

**Device:**
 - Pixel 2 API 29 Emulator
 - Xiaomi Redmi Note 5

https://user-images.githubusercontent.com/31736480/106709863-2ade9800-6606-11eb-9789-241c93542bc1.mp4

**Comment by adasiewiczr** [comment]
Hello @harrunisk,  thanks for reporting that issue.
It was fixed in the PR mentioned above it will be shipped in our next release (4.5.3).

**Comment by harrunisk** [comment]
thanks for your effort @adasiewiczr

**Comment by JcMinarro** [comment]
Hello @harrunisk 
We have released a new version that contains this patch.
I'm closing this issue
