### ISSUE TITLE
Group Chat - App crashes after sending "/" character

### ISSUE THREAD

**Issue by serbeys** [GetStream/stream-chat-android#1351]
**Describe the bug**
Group Chat - App crashes after sending "/" character

**SDK version**
- 4.5.2

**To Reproduce**
2. post / and send it

Expected result:
/ is posted

Actual result:
Chat craches

**Device:**
 - Vendor and model: Samsung S8
 - Android version: 9

**Comment by JcMinarro** [comment]
Hello @serbeys 
We have fixed it on #1359
It will be added on the next release
