### ISSUE TITLE
issue while sending message for the first time using attachment url transformer

### ISSUE THREAD

**Issue by abhirup-patra** [GetStream/stream-chat-android#1352]
when sending a message for the first time using attachment url transformer, the message is not getting delivered to the other user but the message view is getting updated. When trying to reload the chat screen, the app gets ANR.

Build used 4.4.6

**Comment by ogkuzmin** [comment]
Hello, @abhirup-patra 
We released[ the 4.5.3 version](https://github.com/GetStream/stream-chat-android/releases/tag/4.5.3) last Friday. Please could you try to update your Stream SDK dependencies to the latest ones and reproduce the bug on it?
If you'll still get this issue on 4.5.3. Please share:
1) Some video with bug reproduction
2) Code snippet where you invoke sending attachments logic
3) Any other related stuff (maybe some exception in logcat) if you have any
