### ISSUE TITLE
[Channels] How to change filter in ChannelsViewModel?

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1369]
I am using `ChannelsViewModel` to show list of `messaging` channels. However, this filter is created during the creation of `ChannelsViewModelFactory`, which internally initializes `ChannelsViewModel` using the filter and sort.

How to change filter after viewmodel is created and list is fetched? For e.g. show hidden channels or change the sort.

Do I need to create the viewmodel again?

**Comment by zsmb13** [comment]
Yes, in this case we'd recommend dropping the ViewModel instance and creating a new one. Since data is being paged here, the already loaded data can't simply be re-sorted if sort options change (there might be more data to show inbetween, etc.), so we have to reload everything instead.

**Comment by rupinderjeet** [comment]
Ok, what about searching channel list? That will require switching viewmodels for every search term, right?

**Comment by zsmb13** [comment]
That's correct for the time being, we don't have specific support for searching channels (only for message search), and you'd have to create new ViewModels for it. We'll look into adding this support.

**Comment by rupinderjeet** [comment]
Yes, just realized about missing search feature. Thanks.

**Comment by JcMinarro** [comment]
Change filter into our ViewModel is not a feasible update in our current implementation, you will need to change the  the ViewModel itselft.
About post-filtering on the ChannelsView after the data comes from the ViewModel is already possible by `ChannelListView::setChannelListItemPredicate` method implemented on #1586

**Comment by lemberh** [comment]
What would you guys recommend to use when I want to filter channels by name, I use direct channels the name is generated from members field.

**Comment by zsmb13** [comment]
@lemberh Please open a new issue (or better yet, [a Discussion](https://github.com/GetStream/stream-chat-android/discussions)) for your question.
