### ISSUE TITLE
[Channels] Last unread message's date text styles aren't used correctly

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1370]
I am writing about styles of last read message and unread message. Both are using styles from read-message attributes.

```
streamLastMessageDateTextSize
streamLastMessageDateTextColor
streamLastMessageDateTextFontAssets
```

![Screenshot 2021-02-08 at 4.49.25 PM.png](https://user-images.githubusercontent.com/14011726/107470228-0ef06e80-6b91-11eb-9b73-02a72e4e7dec.png)

Even though similar attributes exist for last unread message as well.

![Screenshot 2021-02-10 at 11.09.43 AM.png](https://user-images.githubusercontent.com/14011726/107470281-2af41000-6b91-11eb-8318-e2732cb87b44.png)

Styles for last unread message should be used correctly.

**Comment by zsmb13** [comment]
For the size and font, we expect those to be the same in the read and unread cases, so both can be set via the same attributes.

However, the colour and text style might differ for unread messages, and while the style is handled correctly, `streamLastMessageDateUnreadTextColor` is not being parsed correctly at the moment - we'll fix that!

**Comment by zsmb13** [comment]
Fixed by the PR above, will be there in the next release (4.5.4). Let me know if you have any more questions about these styles.
