### ISSUE TITLE
[Channels] Drawable attribute for item separator is unused

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1371]
I use `streamChannelsItemSeparatorDrawable` on `ChannelsView` to set a drawble for separating items.

![Screenshot 2021-02-08 at 5.08.08 PM.png](https://user-images.githubusercontent.com/14011726/107470901-2845ea80-6b92-11eb-9416-169f85436133.png)

However, in code, this drawable is never assigned to `iv_separator` in `stream_item_channel.xml` because it is never accessed.

![Screenshot 2021-02-10 at 11.19.09 AM.png](https://user-images.githubusercontent.com/14011726/107470967-4b709a00-6b92-11eb-9658-7456db01479b.png)

**Comment by zsmb13** [comment]
Fixed by the PR above, will be there in the next release (4.5.4).
