### ISSUE TITLE
[SDK] Support for light and dark themes

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1375]
Readme file from this github repository mentions that light and dark themes are a supported feature.

![Screenshot 2021-02-10 at 5.39.07 PM.png](https://user-images.githubusercontent.com/14011726/107508935-bb4d4780-6bc7-11eb-9920-1a21349304be.png)

I have looked into `ChatUI.Builder` and documentation, but couldn't find anything relavant. I have tried enabling dark theme from device's status bar tray. I have, also, tried creating night styles for app (using MaterialComponents.DayNight)

![Screenshot 2021-02-10 at 5.41.16 PM.png](https://user-images.githubusercontent.com/14011726/107509058-e768c880-6bc7-11eb-9c0a-2daca5be776a.png)

How do I access this functionality to set chat theme?

**Comment by zsmb13** [comment]
The `stream-chat-android` SDK has just very basic support for dark mode, which appears automatically if you switch the system theme to dark.

We have a new UI implementation that will be released soon (`stream-chat-android-ui-components`) which will have full support for dark mode (also depending on the system theme).

**Comment by zsmb13** [comment]
Closing this for now, let us know if you have more questions about this.

**Comment by cutiko** [comment]
@zsmb13 can the dark mode be disabled? Useful if the rest of the application is not supporting dark mode.

**Comment by bychkovdmitry** [comment]
Hello @cutiko,
Currently, there is no way to force UI components to use light theme. As a workaround, you could try forcing light theme programmatically in your application class:

```
class App : Application() {

    override fun onCreate() {
        super.onCreate()
        AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_NO)
    }
}
```

https://developer.android.com/reference/androidx/appcompat/app/AppCompatDelegate#setDefaultNightMode(int)

**Comment by cutiko** [comment]
Hello @bychkovdmitry 

I can confirm the workaround does work.

Sorry for the delay response and thanks for your quick reply.
