### ISSUE TITLE
Can't subscribe to multiple chat events

### ISSUE THREAD

**Issue by soethan98** [GetStream/stream-chat-android#1398]
**Describe the bug**
Can't subscribe to multiple chat events

**SDK version**
- 4.5.4 (streamchat-client)

**To Reproduce**
show error when calling client.subscribeFor(ConnectedEvent::class,DisconnectedEvent::class,{}) mentioned in document. [https://getstream.io/chat/docs/android/event_listening/?language=kotlin](url)

**Expected behavior**
It was working fine in version 4.5.0

**Comment by bychkovdmitry** [comment]
Hello @soethan98 
Could you describe the error in more detail? Is it a compile time error? If yes, then make sure you have the correct import:
`import io.getstream.chat.android.client.subscribeFor`. If it is a runtime error, could you provide the stacktrace?

**Comment by soethan98** [comment]
Solved.
It show as error but it can run. I thinks it's my IDE error.
thanks
