### ISSUE TITLE
No way to set background color for attachment suggestions box in MessageInputView

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1399]
`MessageInputView` uses `stream_view_message_input.xml` as the UI. This xml has a RecyclerView with id `rvSuggestions`. This RecyclerView's background color comes from `stream_round_thread_toolbar.xml`, which just says that the background color is white.

There's no attr to override this color. 

If I declare a new `stream_round_thread_toolbar.xml` file in my project and override stream's drawable, will it effect the project anywhere else?

I am aware that you're working on supporting most of android's ui components already. 

What is your take on this? What is the best way to do it?

![Screenshot 2021-02-15 at 10.35.00 AM.png](https://user-images.githubusercontent.com/14011726/107907918-df6ba880-6f7a-11eb-8e7d-3ec9f42a8050.png)

**Comment by rupinderjeet** [comment]
Also, internal method `showAttachmentMenu()` in `MessageInputView` sets this xml as its own background. So, I guess this even fails setting something like

```
android:background="@color/notwhite"
```

**Comment by rupinderjeet** [comment]
Same for `messageActionButtons`

![Screenshot 2021-02-15 at 11.07.00 AM.png](https://user-images.githubusercontent.com/14011726/107909521-6cfcc780-6f7e-11eb-8851-04ad3b6a4e8d.png)

I understand that these are past mistakes or quick implementations. But, I would love to see them supported in next release.

**Comment by JcMinarro** [comment]
Hello @rupinderjeet 
We are going to add some custom attribute to allow you to customize it.

**Comment by adasiewiczr** [comment]
Hey @rupinderjeet, thanks for reporting this issue, The PR mentioned above introduces new attributes that allow configuring each mentioned background separately. It will be shipped in the next release (4.5.5).
When it comes to overriding `stream_round_thread_toolbar.xml` - the drawable is being used in two places: one is an `Attachments menu` visible on the attached screenshot and the second one is `suggestions` view (which is visible when you type @). Overriding the resource should do the job but it won't be needed after the next release.

**Comment by JcMinarro** [comment]
Hello @rupinderjeet 
New version with the patch that Rafal did is already released.
I'm closing this issue.
Feel free to open another one if something is not working as expected

**Comment by rupinderjeet** [comment]
Hello @JcMinarro & @adasiewiczr 

Thanks for quick help. There is one issue I didn't think of before. 

![Screenshot 2021-02-16 at 10.21.20 AM.png](https://user-images.githubusercontent.com/14011726/108019970-59fefb80-7041-11eb-84b5-5aca49b32d73.png)

I am unable to set a foreground color for message actions UI.

Sorry for late response, I guess our timezones are different.
