### ISSUE TITLE
How to set notification handler when I am using Chat SDK?

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1400]
I followed chat documentation for Android. It seems to be outdated.

![Screenshot 2021-02-15 at 1.17.29 PM.png](https://user-images.githubusercontent.com/14011726/107919018-ab02e700-6f90-11eb-93d8-62b9dd7425d4.png)

Currently, only `ChatClient` has an option to set a `notificationHandler`. 

I am setting it on `ChatClient`. Is it the right thing to do when I am using Chat SDK? (aka not low level client directly)

**Comment by zsmb13** [comment]
Hey, that's correct, notification settings should always be set on `ChatClient`, regardless of which of the libraries you're using. [The documentation](https://getstream.io/chat/docs/android/push_android/?language=kotlin#setting-up-notification-data-payload-at-stream-dashboard) has been updated to reflect this.
