### ISSUE TITLE
How to set foreground for Message Action Buttons UI in MessageListView?

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1406]
Hello @JcMinarro & @adasiewiczr 

Thanks for quick help on last issue #1399

There is one related issue I didn't think of before. 

![Screenshot 2021-02-16 at 10.21.20 AM.png](https://user-images.githubusercontent.com/14011726/108019970-59fefb80-7041-11eb-84b5-5aca49b32d73.png)

I am unable to set a foreground color for message actions UI.

In `MessageInputView`, I am able to set this using `streamInputBackgroundTextColor` attr. But, not in `MessageListView` for foreground on MessageActionButtons UI.

Opened this as new issue as you suggested. Sorry for late response, I guess our timezones are different.

**Comment by adasiewiczr** [comment]
Hey @rupinderjeet, thanks for reporting this.
PR mentioned above adds multiple attributes that allow configuring text style and icons tint on the mentioned screen.
It will be shipped in the next release.

**Comment by rupinderjeet** [comment]
Thank you.

**Comment by zsmb13** [comment]
These attributes shipped in [4.6.0](https://github.com/GetStream/stream-chat-android/releases/tag/4.6.0), please update to that latest version.
