### ISSUE TITLE
Channels Listing Issue

### ISSUE THREAD

**Issue by harrunisk** [GetStream/stream-chat-android#1407]
**Describe the bug**
Created channels without `extraData: Map<String, Any>` info are not available in the channels list.   

Example request from SDK logs.  
`https://chat-proxy-singapore.stream-io-api.com/channels?api_key=XXXX&user_id=88937&client_id=cc738a56-425e-4b3c-8ccd-52143591435d&payload={"filter_conditions":{"$and":[{"type":"messaging"},{"members":{"$in":["88937"]}},{"draft":{"$ne":true}}]},"limit":30,"member_limit":30,"message_limit":1,"offset":0,"presence":false,"sort":[{"field":"last_updated","direction":-1}],"state":true,"watch":true}`

**SDK version**
- 4.5.4

**To Reproduce**
1.Create channel without `extradata`
2.Observe channel list

**Expected behavior**
Get all channels.

**Device:**
 - Pixel 2 Api 30

**Comment by bychkovdmitry** [comment]
Hello @harrunisk 
Could you tell us the exact method you are calling to create channels?

**Comment by harrunisk** [comment]
Hello @bychkovdmitry you can find our channel creation method as the following:
```
 val channelController = ChatClient.instance().channel("messaging", "")
 channelController.create(memberList, extraData)
    .enqueue {
        if (it.isSuccess) {
        
        }
    }

```

**Comment by bychkovdmitry** [comment]
@harrunisk
Couple of questions:
- Does `channelController.create` complete successfully? If it doesn't, could you share the error?
- From your channel query I see that your current user id is `88937`. Do you include this user in your `memberList`?
- How many members are there in `memberList`? There should be at least 2 members.
- Do you already have a group chat with this particular members? The API ensures that only one channel for the members you specified exists. Therefore, if this channel already exists and wasn't used for a while, it can be absent in the first page of `queryChannels` response. The `channelController.create` call will not "bump" it to the top of the list.

**Comment by harrunisk** [comment]
1. We don't have any problem with creating a channel  
2. Yes we include this user in `memberList`  
3. We include at least 2 users  
4. Even when we try to create a chat channel with newly created users If we don't use extra data the channel is not available in `query channels` response.

**Comment by harrunisk** [comment]
We can close the issue. The channels are available in the channel list now.  @bychkovdmitry thanks for your effort

**Comment by zsmb13** [comment]
@harrunisk What ended up solving your issue?
