### ISSUE TITLE
Read status not updating in MessageListView

### ISSUE THREAD

**Issue by kplanz** [GetStream/stream-chat-android#1411]
**Describe the bug**
We currently have an issue in the `MessageListView` where the read status is just not updated live. So when we reload the view the read state is always accurate, but when we stay on the screen and the read status of my last messages changes, the avatar indicator does not move to the bottom. 

We can see the `message.read` events coming in the logs but the view never updates (it still updates when we scroll to the top which triggers some loading of previous messages, then scroll down).

Interesting is that as soon as we debug and set breakpoints in the `MessageListItemViewHolder` or in the `IndicatorConfigurator` and cycle through the `bind()` calls, the view updates correctly without any reloading. Not sure what side effect that might be but it could point to some sort of race condition or weird timing issue.

In general we use the View and ViewModel like in the docs and demos, so nothing special. We have our own `MessageListItemViewHolder`, but even without that we monitor the same behavior. 

**SDK version**
- 4.5.5

**To Reproduce**
1. Go to a `MessageListView`
2. Send a message
3. Wait for the message to be read by the other user
4. Read indicator (avatar of the other user) does not move to the message

**Expected behavior**
The read indicator should move to the new message automatically as soon as we receive the read event

**Device:**
 - Vendor and model: Google Pixel 3 XL
 - Android version: 11

**Comment by zsmb13** [comment]
[4.6.0](https://github.com/GetStream/stream-chat-android/releases/tag/4.6.0) contains the fix for this bug. Let us know if you have any issues with that new version.
