### ISSUE TITLE
How to handle Channel Members and Events?

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1426]
My config has offline disabled and user-presence enabled.

I have been having trouble handling how channel behaves to its events and members. For e.g. When a user is removed from chat, or a user deletes the channel.

First, I am creating channels from android side with `ChatClient`. Only "user" roles are assigned this way I think. So, I am just assuming that user returned by `channel.createdBy` is Channel Admin(Moderator?). And, with that check, I allow this user to add or remove members, and delete the channel. For all other users, I do not show the UI to manage the channel.

But, if other users tried with the underlying API, they are allowed to add/remove the members. They can, I have tested. They can even delete the channel, and all members lose access to that channel.

Removed members can still send messages to channel. And, they do not show in members listing of a channel. This way users have permanent access to a channel. Removed user can still the see channel in channel listing even after refreshing it. Only when I call `disconnect()` and `setUser()` again,  channel is removed from listing.

Another issue is listening to events happening in channel. I can't define which channel's or user's events am I subscribing for. Consider two channel users are talking #NotDirectMessaging. One of them is kinda Admin (Channel Creator). Admin/Moderator user removes the other user. But, other user's channel doesn't receive the `member.removed` event. I am listening with 

```
ChatClient.instance()
    .subscribeFor(EventType.MEMBER_REMOVED) { chatEvent ->
    Timber.d("Unhandled Event Received: $chatEvent")
}
```

All of these issues I think are related to how user roles work and how channel events are sent.

Please guide me if I am doing something wrong.

**Comment by rupinderjeet** [comment]
My bad. I had to look at roles for `Member` (which is null) instead of role of `User` (which is always `user`).

I will try to understand how this works by implementing it first. And, I will close the issue if this solves my problem.

**Comment by JcMinarro** [comment]
Hello @rupinderjeet 
I have been talking with the backend team and it is a bug on the backend side that they are working on.
Channel Permissions are detailed [here](https://getstream.io/chat/docs/android/channel_permission_policies/?language=kotlin), on the case you describe, only Admins and moderators can remove members.

**Comment by rupinderjeet** [comment]
Hello @JcMinarro

Are you guys addressing the issue of "null" roles for channel members? Or their access? Like adding/removing members, sending messages to channel where you're not a member, etc.

This will help me target correct implementations on my end meanwhile.

**Comment by JcMinarro** [comment]
Hi @rupinderjeet 
It seems related with the other issue.
We will verify it as well when the previous one is completed

**Comment by rupinderjeet** [comment]
Hello @JcMinarro 

Until we solve this issue, can you tell me if I need to specify member role when creating a channel? For e.g. I want channel-creator to have a role of `admin` for channel, and other members to have role of `channel_member`. How can I do this?

Also, should this channel-creation logic be on client side(android), or server-side?

**Comment by samiuelson** [comment]
The primary backend issue is fixed. Normal users can't remove others now. 

In order to grant admin or moderator privileges to the user, you need to use server-side api since this is not supported by Android SDK due to safety reasons.

Let us know if you have any other issues.
