### ISSUE TITLE
totalUnreadCount not updated for currently set user

### ISSUE THREAD

**Issue by lukenowakcom** [GetStream/stream-chat-android#143]
Continuation of https://github.com/GetStream/stream-chat-android/issues/100

The currently set user is not updated when new messages from other users arrive, leaving the `totalUnreadCount` stick to the value received when the user was initialised, up until the point when this user sends some message himself.

It checks out with this piece of code in `Client.java`
```java
public void onAnyEvent(Event event) {
                    // if an event contains the current user update it
                    // this also captures notification.mutes_updated
                    if (event.getMe() != null) {
                        state.setCurrentUser(event.getMe());
                    }
                    if (event.getType() == EventType.NOTIFICATION_MUTES_UPDATED) {
                        Log.i(TAG, "Mutes updated");
                    }

                    // if an event contains a user update that user
                    // handles user updates, presence changes etc.
                    if (event.getUser() != null) {
                        state.updateUser(event.getUser());
                    }

                    // update the unread count if it is present on the event
                    if (event.getTotalUnreadCount() != null) {
                        state.setTotalUnreadCount(event.getTotalUnreadCount().intValue());
                    }
                    if (event.getUnreadChannels() != null) {
                        state.setUnreadChannels(event.getUnreadChannels().intValue());
                    }

                    // if an event contains an updated channel write the update
                    if (event.getChannel() != null) {
                        state.updateUsersForChannel(event.getChannel().getChannelState());
                    }
                }
```

Could you give me a hint how can I update the currently set user every time new message is received/deleted or read? Is the `client.queryUsers()` way to go here?

**Comment by tschellenbach** [comment]
Do you want the total unread message count for that user, or the number of unread channels? Here are some docs for the unread counts (we didn't publish these yet). 

![image](https://user-images.githubusercontent.com/265409/66763299-d6d60000-ee64-11e9-83c2-39c4245de065.png)

**Comment by tschellenbach** [comment]
From the description so far I think either client.getState().getTotalUnreadCount() or StreamChat.getTotalUnreadMessages() is what you're looking for (depending on whether you are using livedata or not)

**Comment by lukenowakcom** [comment]
I think `client.getState().getTotalUnreadCount()` is exactly what I've been looking for. Thanks! 👏 🙏

**Comment by tschellenbach** [comment]
👍
