### ISSUE TITLE
[UI] Unable to download unrecognised files by OS

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1448]
When I upload a file using `MessageInputView`'s `Upload a File` option, uploaded file's name is not shown in the UI. If the file format is not recognised by OS, there's no option to download the file as it is, which makes sending files kinda useless. When I tap it, there's no error message either.

If we can't allow downloads of those files, it will help to show an error message if the file can't be opened/downloaded.

<img src="https://user-images.githubusercontent.com/14011726/108662000-4cd78600-74f3-11eb-8cef-dcfaf8a5b263.png" width="40%" title="no file names" />

Uploading large image files of `.heic` format (2.01 MB) do not show any upload indicator. And, whether the file is uploaded, or failed to upload, all I see is this:

<img src="https://user-images.githubusercontent.com/14011726/108663173-f1f35e00-74f5-11eb-8c71-2a4489517707.png" width="40%" title="device-2021-02-22-100707" />

Last message is supposed to be a file upload, but there is no file shown to sender.

<img src="https://user-images.githubusercontent.com/14011726/108663328-51ea0480-74f6-11eb-9c5f-56ac698a42d6.png" width="40%" title="device-2021-02-22-101031" />

This is what receiver sees on their end.

Tried with: `.bin`, `.heic`

**Comment by JcMinarro** [comment]
Hello @rupinderjeet 

It seems that for some reason the attachments have not sent properly.
Could you check the logcat if there is any error and shared with us?

On the other hand, by default, we only provide support to some known file types and allow you to open them (pictures, video, pdf documents...) but you are able to customize this behavior.

Into our `ChatUI` instance you can inject a custom `ChatNavigationHandler` that will be used to handle navigation of every attachments.

You can also customize the behavior of an attachment click into our `MessageListView` by using `MessageListView::setAttachmentClickListener`

**Comment by rupinderjeet** [comment]
Sure, I will reply back with logs, if any, tomorrow morning.

Also, thanks for attachment click insight. I remember I read it somewhere in the sample docs, will try to use it.

**Comment by rupinderjeet** [comment]
Here's the log. I hope it helps.

[chat-failed-attachment-log](https://github.com/GetStream/stream-chat-android/files/6033750/chat-failed-attachment-log.zip)

What did I do:
- Opened messages page in a channel
- Opened add attachment dialog
- Selected Upload File option
- Selected a .heic file
- Tapped on send message button


There are some error logs about some object adapter. Search with `E/Chat` 

If you need anything else, message back and I will try.

**Comment by JcMinarro** [comment]
Hi @rupinderjeet 
A new version has been released that fixes it
