### ISSUE TITLE
[UI] How to handle dialog theme changes when a message is long pressed?

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1449]
In #1399 & #1406, we added ui improvements to a message's options dialog. When I open this same dialog, it changes color for status bar and navigation bar. How can I handle it to either not change them or set my own theme?

Attached Video:
https://user-images.githubusercontent.com/14011726/108665130-32ed7180-74fa-11eb-9507-7d48f7f64aa5.mp4

**Comment by rupinderjeet** [comment]
Also, I have dark-theme enabled in my `Application` class:

```AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES)```

**Comment by JcMinarro** [comment]
Hello @rupinderjeet 
It seems thatthere is some issues on the Theme that Dialog is using.
We will fix it

**Comment by JcMinarro** [comment]
Hello @rupinderjeet 
We have already updated the theme used when this dialog is shown to use the same PrimaryColor and PrimaryDarkColor as the rest of the components.
You can update to the last version now.
BTW, We are releasing new UI-Components to help you to to build a chat with a great UX.
You can check how it looks and test the sample app [here](https://github.com/GetStream/stream-chat-android/tree/main/stream-chat-android-ui-components-sample)

**Comment by rupinderjeet** [comment]
Sure, we are considering the new update. Thank you.
