### ISSUE TITLE
[MessageInputView] Unable to unselect selected MP4 attachment file

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1450]
Behaviour:
In attachment-options dialog, for `Upload a file` option, when I select a `.mp4` file, I am unable to unselect this file. Tapping `x` button next to selected file does nothing. Tapping `x` button on attachment-options dialog, closes the dialog, but keeps the selected file visible to user.

Expectation:
Tapping `x` button unselects the selected file.

Attached Video:
https://user-images.githubusercontent.com/14011726/108696091-174c9000-7527-11eb-9328-d440b293bd7d.mp4

**Comment by JcMinarro** [comment]
Hello @rupinderjeet 
We are investigating it, but it seems the issue is because of the touchable area of the button.
I am updating this view size

**Comment by rupinderjeet** [comment]
Hello @JcMinarro 

It works for other file types. Just not for MP4s. I will try to reproduce it tomorrow morning with visible Layout Bounds.

**Comment by JcMinarro** [comment]
The same View and the same logic is using for all file types. It shouldn't affect only to mp4 files

**Comment by zsmb13** [comment]
The bugfix was shipped in [4.6.0](https://github.com/GetStream/stream-chat-android/releases/tag/4.6.0), please update to that version.
