### ISSUE TITLE
[UI-Components-Sample] Unable to resolve dokka dependency

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1464]
Hello 👋

I am trying to run the new sample. But, gradle fails syncing because it is unable resolve dokka dependency.

![Screenshot 2021-02-24 at 10.56.54 AM.png](https://user-images.githubusercontent.com/14011726/108953065-93aeb280-7690-11eb-9476-ca5ac7a9dd75.png)

The link just says that quota has exceeded.

![Screenshot 2021-02-24 at 10.59.07 AM.png](https://user-images.githubusercontent.com/14011726/108953110-a45f2880-7690-11eb-8a4a-f0edb14e97cc.png)

As of now, I am not familiar with what dokka is and what it does. Can you help me get past this somehow?

**Comment by zsmb13** [comment]
Hey, thanks for reporting the issue. Dokka is a documentation generation tool we use. We're looking into this and will update you soon.

**Comment by zsmb13** [comment]
You can temporarily remove the Dokka dependency of the project by making these changes to it: https://github.com/GetStream/stream-chat-android/commit/8e7dce2bc3f744aa05abf5d8f3abe7e155985292

We're working on a permanent fix.

**Comment by rupinderjeet** [comment]
Thank you, 

I have explored a bit about the dependency. It seems interesting & useful (learned something new today). 👍🏼

**Comment by zsmb13** [comment]
We've updated our Dokka version in the project, the fix has been merged to the `main` branch now. Should fix the issues permanently. https://github.com/GetStream/stream-chat-android/commit/9fa9cf7ea1f78d8dd48221c19664bb60c020bf4a

**Comment by JcMinarro** [comment]
@rupinderjeet We have updating the Dokka dependency and it should be working fine now on `main` branch.
Could you pull the last commits?
