### ISSUE TITLE
[Old UI] Channel List doesn't update if current-user is removed from a channel

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1473]
When current-user is on channel-list page, and he gets removed from one of the channels, channel list doesn't update. But, if he is added to a channel, channel list updates to show the new channel. Channel list, also, updates if channel is deleted.

Keeping the channel history visible to removed user might be an intention. But, there is nothing like `readOnlyMode` in `MessageListView`, right? Also, if I disconnect the chat-client and set the user again, channel (from which user was removed) disappears. So, this doesn't seem like planned intention.

**Comment by rupinderjeet** [comment]
This is how I remove a member from the channel:

```
chatClient
    .channel(request.channelId)
    .removeMembers(request.targetMemberId)
    .execute()
```

**Comment by JcMinarro** [comment]
Hello @rupinderjeet 
Channel should be removed from the list, because you are not a member anymore.
We are going to investigate it.
Second time you set the user, because the current user is not a member anymore it is fine to not be shown

**Comment by rupinderjeet** [comment]
> We are going to investigate it.

Just adding that I am able to reproduce this in new ui-components-sample as well.

**Comment by adasiewiczr** [comment]
Hey @rupinderjeet,
thanks for reporting this issue. It was fixed in the PR mentioned above and will be shipped in the next release.
