### ISSUE TITLE
[Channel] Best way to find if a user is in a given channel

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1474]
I am trying to find if a user is in a given channel. This is how I am doing it:

```
val filter = Filters.and(
	Filters.eq("id", request.channelId),
	Filters.eq("type", request.channelType),
	Filters.`in`("members", listOf(request.targetUserId))
)

val queryChannelsRequest = QueryChannelsRequest(
	filter,
	offset = 0,
	limit = 1,
	sort = QuerySort<Channel>().asc("last_message_at")
)

val result = chatClient.queryChannels(queryChannelsRequest).execute()
if (result.isSuccess) {

	val channel = result.data().firstOrNull()
	if (channel?.cid == request.channelId) {
		return channel
	}

	throw ChannelAccessException("You are not a part of this chat.")
}
```

By doing this, I am trying to verify if the user has access(as a member) to this channel or not. Is there an alternative available?

**Comment by JcMinarro** [comment]
Hi @rupinderjeet 
This code should be fine.
You can use the [Query Member](https://getstream.io/chat/docs/android/query_members/?language=javascript&q=member) method as well.

BTW, Can you explain to us your use case to need to do this check on your side?

**Comment by thesyncim** [comment]
@rupinderjeet, here's a query that returns channels where both user X and user Y are members

```js
{$and:[{members:{$in:[X]}, members:{$in:[y]}]}]}
```

**Comment by rupinderjeet** [comment]
[Usecase] Stream Chat 4.5.5

The app I am working on doesn't have chat as a primary feature. So, I am mixing it in with other features, and also, trying to receive chat events using a bound service. In chat, I have ChannelListActivity, ChannelMessagesActivity and ChannelInfoActivity.

When a channel member is looking at ChannelMessagesActivity or ChannelInfoActivity, he can be removed from a channel by someone else. Or, the channel itself can be deleted. So, I have to tell the user that he is no longer part of this channel and close these activities. I start listening to `chatClient.events()` in a bound service in these activities and filter out `NotificationRemovedFromChannelEvent` & `NotificationChannelDeletedEvent`. If I receive any of both, I close ChannelMessagesActivity and ChannelInfoActivity. I will be referring to this channel as a _jinxed_ channel because either I am no longer in it or it was deleted.

After closing these pages, I come back to `ChannelListActivity`. But, the _jinxed_ channel is still there in the list(due to #1463). I can still open the channel, send messages, react to other messages, receive typing events etc. This is very unexpected. So, here, I need to check if I am really a part of that channel or not, hence I asked the question via this issue. If I am not part of the channel, I will show error on ChannelMessagesActivity, but I will still receive typing-events from _jinxed_ channel in ChannelListActivity.

This will, only, work as long as my internet is working, and only if I actually receive these events. So, even when ChannelMessagesActivity is open, I need to observe connectivity-changes to make sure user still has access to the channel when internet becomes available. I will, also, need to check channel access when an Activity resumes, right?

As of now, I can’t upgrade to release 4.6.0 until my employer decides to put time in its implementation. So, I am worried about if support for pre-4.6.0 versions is affected or is limited in some way.

If there is an alternative or better way, please help.

**Comment by rupinderjeet** [comment]
@thesyncim not the case, but thanks for this snippet, might be useful in future.
