### ISSUE TITLE
Wrong implementation of Channel.isDirectMessaging internally?

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1490]
There's an extension function in `com.getstream.sdk.chat.utils.extensions.Channel.kt` to find out if a channel is DM or not.

```
@InternalStreamChatApi
public fun Channel.isDirectMessaging(): Boolean = getUsers(excludeCurrentUser = true).size == 1
```

But, if a user in multi-user channel removes all members but one, this MUC channel will return `true` for above function, right?

Isn't `Channel.isDirectMessaging()` a wrong implementation in this case? I think uses in `AvatarView` are valid where we just need to determine the image we're showing. How does it affect me as a developer?

Also, is your definition of DM channels just that me and another user is chatting?

Edited: removed false claim

**Comment by adasiewiczr** [comment]
Hey @rupinderjeet,
our SDK gives you a possibility to create channels:
1. Based on _Channel Id_ (https://getstream.io/chat/docs/android/creating_channels/?language=kotlin#1.-creating-a-channel-using-a-channel-id)
2. Based on _Member List_ (https://getstream.io/chat/docs/android/creating_channels/?language=kotlin#2.-creating-a-channel-for-a-list-of-members).  
The main difference between these two is that if you create a members-based channel, you can be sure that the conversation for that group of users is unique.
`Channel.isDirectMessaging()` extension function is used to display different options (e.g. different labels in `MessageInputView`) depends on how many users are inside the channel. Its usage and implementation look correct -  we can have "based on member list" channel with multiple users and on the other hand, we can have "based on channel id" channel with only one user.
Let me know if you have any further questions.

**Comment by rupinderjeet** [comment]
Hello @adasiewiczr 

Thank you for clearing this. I have one more question.

If someone else creates a channel with me, how can I find out if this channel is a unique channel where no member can be added or if this channel is an id-based channel where I can add members?

**Comment by adasiewiczr** [comment]
Hey @rupinderjeet, 
the easiest way is to check the channel's id - if the channel is created based on member list, its `id` is prefixed with `!members`

**Comment by rupinderjeet** [comment]
Thank you.
