### ISSUE TITLE
.exhaustive method is not internal so it pollutes the auto complete for every object

### ISSUE THREAD

**Issue by rjaylwar** [GetStream/stream-chat-android#1517]
**Describe the bug**
The library includes an extension `T.exhaustive` method, likely used internally to make sure when {} calls are exhaustive. The problem is that this method is defined on T and the method is public instead of internal it shows up in the auto complete for every object in every project that depends on this library. 

It is such a simple method even if the library had to include multiple copies of it in each module and could therefore mark it as internal it would be worth it to avoid exposing it. There are also many other approaches to ensuring when functions are exhaustive (https://github.com/cashapp/exhaustive documents most of them) that wouldn't add a method to the auto complete for every object. 

The lack of a centralized solution for this is problem with the language as a whole, but you can imagine if every library an app depends on exposes a method like this one and the autocomplete just has a list of multiple `.exhaustive` methods it could become quite cluttered. 

```kotlin
package io.getstream.chat.android.core.internal

@InternalStreamChatApi
public inline val <T> T.exhaustive: T
    get() = this
```

**SDK version**
- 4.6.0

**Comment by zsmb13** [comment]
Hiding this from clients completely would require us to duplicate some things inside the library.

May I suggest solving this through tooling? (Alt+Enter / Option+Enter to toggle this popup)

![image](https://user-images.githubusercontent.com/12054216/110254723-982c7280-7f90-11eb-9116-da89c91751eb.png)

You can view/edit the list of excluded things in Settings:

![image](https://user-images.githubusercontent.com/12054216/110254714-8cd94700-7f90-11eb-9d63-ac6b67f73ab8.png)
