### ISSUE TITLE
Looper should perhaps be part of the client and not the channel view model

### ISSUE THREAD

**Issue by tschellenbach** [GetStream/stream-chat-android#154]
This seems like a better approach. @tbarbugli what do you think?

**Comment by elevenetc** [comment]
I have two concerns:
- `Looper` is only need when channel is opened, so there is no need to have it inside `Client`
- But if developers don't want or can't use our `ChannelViewModel` then they will need to implement something similar from scratch (or copy and try to integrate into their solution)

So it seems `Looper` should be an external service. Which should be launched and stopped when a channel is opened by user.

**Comment by tschellenbach** [comment]
for JS we only have a looper at the client level which cleans up for all active channels.

lets think about all the differences...

* But if developers don't want or can't use our ChannelViewModel then they will need to implement something similar from scratch (or copy and try to integrate into their solution)

* If you close a channel the current looper approach stops cleaning up data.
