### ISSUE TITLE
When adding new channel to ChannelListView, SDK doesn't check if filter matches new channel

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1549]
I have a ViewPager(supported by a linked TabLayout). ViewPager shows two fragments containing ChannelListView.

```
internal class MessagingChannelsFragment: ChannelsFragment() {

	override fun createFilter(currentUser: User): FilterObject {

		return Filters.and(
			Filters.eq("type", ChannelType.MESSAGING),
			Filters.`in`("members", listOf(currentUser.id))
		)
	}
}
```

```
internal class GlobalChannelsFragment: ChannelsFragment() {

	override fun createFilter(currentUser: User): FilterObject {
		return Filters.eq("type", ChannelType.GLOBAL)
	}
}
```

Here's how I create view-model
```
val channelsViewModel = ChannelsViewModelFactory(
	filter = createFilter(currentUser)
).create(ChannelsViewModel::class.java)
```

Initially, channel-lists are shown correctly. `messaging` channels and `global` channels appear in respective fragments. But, when I create a *new* `messaging` *channel* with someone, new channel appears in both of the fragments.

Global channels fragment shouldn't show this new channel because it doesn't match the applied filter.

**Comment by rupinderjeet** [comment]
You can, also, test this with a single fragment which requests different channel-type for channel-listing than the channel-type it creates.

**Comment by JcMinarro** [comment]
Hi @rupinderjeet 
It is an issue related with #1369
Currently filtering is delegated to the server, and in that case, when the channel arrives it is not filtered.
We are improving our local process to handle it, but it is not ready yet.

**Comment by rupinderjeet** [comment]
Hello @JcMinarro 

I was able to avoid this using a `ChannelViewHolderFactory` that depends on applied-filter in `ChannelsViewModel`. And, when a channel doesn't fit the defined filter, I return following `ViewHolder`

```
if (viewType == BAD_CHANNEL_TYPE) {
	
	val itemView = View(context)
	itemView.layoutParams = RecyclerView.LayoutParams(
		width = 0,
		height = 0
	)
	return BadChannelTypeViewHolder(itemView)
}
```

Also, it would be cool if you could let me filter channels-list before `ChannelsViewModel` submits them to UI, by some kind of inheritance logic.

For the time, this is working for me. But, if you do fix this, please let me know here.

**Comment by JcMinarro** [comment]
Hi @rupinderjeet 

I think we can follow the same approach we have on [MessageListView](https://github.com/GetStream/stream-chat-android/blob/main/stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt#L671)

I will add it

**Comment by JcMinarro** [comment]
Hello @rupinderjeet 
It has been fixed and it is ready on the [last release](https://github.com/GetStream/stream-chat-android/releases/latest)
Could you check it?
