### ISSUE TITLE
channel.update syntax is weird (you would expect it to use the data from your channel object, not the hashmap you pass)

### ISSUE THREAD

**Issue by tschellenbach** [GetStream/stream-chat-android#155]
`client.updateChannel(channelData)` would make sense or `channel.update()`

The current approach of `channel.update(channelData` looks weird to me @tbarbugli thoughts?

**Comment by tbarbugli** [comment]
it should be something like this

```java
client.updateChannel(channel, callback);

channel.update(callback);
```

**Comment by bevzaanton** [comment]
#178
