### ISSUE TITLE
Android promotion milestone

### ISSUE THREAD

**Issue by tschellenbach** [GetStream/stream-chat-android#162]
- Java/Kotlin docs
- Update tutorial to work with latest version

**Comment by adrian09h** [comment]
> Update tutorial to work with latest version

- Java Tutorial for 2.3.0
https://www.notion.so/getstream/Java-Tutorial-for-2-3-0-552b4d32a5034db7b8a55ed3b83408c3

- Kotlin Tutorial for 2.3.0
https://www.notion.so/getstream/Kotlin-Tutorial-for-2-3-0-6ad16541d2d94d038c307313404b8f97
