### ISSUE TITLE
Paste dialog is not well aligned

### ISSUE THREAD

**Issue by tbarbugli** [GetStream/stream-chat-android#165]
![image](https://user-images.githubusercontent.com/88735/66917961-a5a12f80-f01e-11e9-9b86-72649be3da43.png)

**Comment by elevenetc** [comment]
Hm, that's a system menu, we can't really control it. Looks like a system bug.

**Comment by tbarbugli** [comment]
never had this on my phone; we probably do something wrong with it ourselves

**Comment by adrian09h** [comment]
It has to do with AppTheme.
Will update it.

**Comment by elevenetc** [comment]
Indeed, that's interesting.
