### ISSUE TITLE
[4.8.0] Request to add some attributes for Views

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1656]
We are going to target v4.8.0 release since it has latest bug fixes and improvements. However, I need some
 new `attr` values for next release. It will be huge help if you include these with next updates. If there are other better alternatives to these, please let me know.

**I will keep this comment/message updated by editing it to include more suggestions as I adopt the latest release.**

#### MessageListHeaderView
- Change drawable for back button
- Set a background color for whole header (currently ConstraintLayout(from view-parent) in ConstraintLayout(from binding) instead of `<merge>` tag)

#### MessageListVIew
- `streamUiCopyMessageActionEnabled` has `color` as attr format (it should be a `boolean`)
- After muting a user from message-actions ui, text doesn't change to show "Unmute". Same for block-user option.
- When file is being upload, we shouldn't show red-warning (exclamation) icon which symbolizes an error. https://imgur.com/a/U2DAmq9

#### Following are minor usability issues
- AvatarView: Images aren't perfectly rounded. https://imgur.com/a/M8clpzx
- MessageListHeaderView: when title is tapped, there is no touch feedback i.e. something like ripple or hover effect
- MessageListHeaderView: set subtitle-view to gone if subtitle is blank. Title is not vertically located in center if there is no subtitle.

#### Following values are present in legacy UX. Please tell me new alternatives for these.
- ChannelsView: `streamChannelsEmptyStateLabelText`
- ChannelsView: `streamChannelWithOutNameTitleText`

**Comment by leandroBorgesFerreira** [comment]
hi @rupinderjeet. About `streamChannelWithOutNameTitleText` how are you using the parameter? Right now you can override the `R.string.stream_ui_stream_channel_unknown_title` string, but we currently use the name of the participants of the chanel to create the name, when the channel doesn't have a name. thes `tream_ui_stream_channel_unknown_title` is only used the the method to create a new fails.

**Comment by leandroBorgesFerreira** [comment]
for `streamChannelsEmptyStateLabelText` you can either override `stream_ui_channels_empty_state_label` or set a custom empty state view using `ChannelListView::setEmptyStateView`

**Comment by leandroBorgesFerreira** [comment]
The requests that you made make sense. Wait a little and we will add then in the next release.

**Comment by rupinderjeet** [comment]
Yes, sure. Thank you.

About unknown channel-name attribute, I use it in case our backend creates a custom non-messaging channel without name. These channels do not have any members, as they are "open" for all.

So, for these channels, I have to show something like "Unnamed Group" just to plug the loophole.

Yes, I will override string resource for now. I was skeptical about overriding sdk's resources because it is not a defined way in the documentation. Hence, future releases of stream-chat might change something, I have overridden, unexpectedly.

**Comment by leandroBorgesFerreira** [comment]
We have this method for the channel name:
```
public fun Channel.getDisplayName(context: Context): String =
    name.takeIf { it.isNotEmpty() }
        ?: getUsers()
            .joinToString { it.name }
            .takeIf { it.isNotEmpty() }
        ?: context.getString(R.string.stream_ui_stream_channel_unknown_title)
```

If your channel has no name, the name will be the join of the members in it.

**Comment by rupinderjeet** [comment]
You're right. But, it is possible for channels to exist without member listing. We have some channels where `channel.members` returns empty list, but at the same time a lot of users are already chatting. It is a sort of a global channel about a region or topic where users do not need to join or leave the channel, but they can chat and send messages.

See this comment for reference:
https://github.com/GetStream/stream-chat-android/issues/1585#issuecomment-804659868

**Comment by leandroBorgesFerreira** [comment]
Oh ok. For this case, you can override `stream_ui_stream_channel_unknown_title`. We still need to document better this, but this is going to be the default way to customise our SDK. No need to worry about fields going away from one version to the other, we deprecate fields 3 months before they are actually deleted and you can keep track here: https://github.com/GetStream/stream-chat-android/blob/main/DEPRECATIONS.md

**Comment by rupinderjeet** [comment]
Thank you for the support & assurance.

**Comment by leandroBorgesFerreira** [comment]
No worries @rupinderjeet. Thank you for posting this improvements.

**Comment by rupinderjeet** [comment]
- After muting a user from message-actions ui, text doesn't change to show "Unmute". Same for block-user option.

Added to issue description as well.

**Comment by adasiewiczr** [comment]
Hey @rupinderjeet, thanks for reporting those issues. Would you mind dividing this one big issue into smaller ones and close this one (e.g. styles for one type of view, issues with message actions, etc.)? It would be much easier and faster to track and apply required changes.

**Comment by rupinderjeet** [comment]
Yes, sure. Give me an hour.

**Comment by rupinderjeet** [comment]
Hello @adasiewiczr 

> MessageListHeaderView: when title is tapped, there is no touch feedback i.e. something like ripple or hover effect

I am not adding an issue for this one. I will dim their text-colors a bit when they are in `pressed` state using `streamUiMessageListHeaderTitleTextColor` & `streamUiMessageListHeaderDefaultLabelTextColor` attribute.

**Comment by petyosi** [comment]
Hi @rupinderjeet ,

Thank you very much for your ongoing feedback on our product. I am the frontend SDK PM in Stream, and I would like to learn more about your project and what you are building, so that we can make our product better - will it be convenient for you to contact me at petyo@getstream.io, so that we can arrange a quick call with me and a member of our technical team? Thank you in advance!

**Comment by rupinderjeet** [comment]
Hello @petyosi 

Sure, we will try to contact you for a discussion on your email. Thank you as well.
