### ISSUE TITLE
Reactions and replies are available in the long press menu even if they are disabled in the channel settings

### ISSUE THREAD

**Issue by julioromano** [GetStream/stream-chat-android#1657]
**Describe the bug**
Reactions and replies are still available in the long press menu even if they are disabled in the channel settings.

**SDK version**
- 4.8.0

**To Reproduce**
1. Create a channel type which has reactions and replies disabled.
2. Open that channel in the android UI client SDK.
3. Long press any message in the channel.
4. A menu which allows to reply or reaction is available.
5. Trying to add a reaction will result in the reaction visible on the android client but it won't be visible from the web. Closing and reopening the Android App will not show the reaction anymore, as if the reaction itself wasn't actually propagated to the server side.

**Expected behavior**
If the channel disallows reactions and replies, the client shouldn't show them as available actions.

**Device:**
 - Vendor and model: Pixel 3a
 - Android version: 11

**Comment by leandroBorgesFerreira** [comment]
Hi @julioromano I just tested with a test dashboard and also using our XML configuration and both worked for me. How are you configuring this?

**Comment by julioromano** [comment]
It is a custom channel type. In the dashboard the switches for "Custom events" , "Reactions", "Replies", URL Enrichment" are off.

I double checked the cid and it is correct, it is like "mycustomchanneltype:something". 

I'm not passing any special config to `MessageListView` , just binding it with `messageListViewModel.bindView(messageListView, lifecycleOwner)`

Is there anything else I can try?

**Comment by leandroBorgesFerreira** [comment]
You can use the XML configuration to disable replies and reactions (and many other properties of the chat). 
You can add this:
```
app:streamUiReplyEnabled="false"
app:streamUiReactionsEnabled="false"
```
to your `<io.getstream.chat.android.ui.message.list.MessageListView`. 
You can check all the possible ways to configure your MessageListView in the XML here: https://github.com/GetStream/stream-chat-android/blob/main/stream-chat-android-ui-components/src/main/res/values/attrs_message_list_view.xml

**Comment by leandroBorgesFerreira** [comment]
This will solve your problem, but at the same time I'll check if we have a problem with the configuration of custom channels in the dashboard

**Comment by julioromano** [comment]
> You can use the XML configuration to disable replies and reactions (and many other properties of the chat).
> You can add this:
> 
> ```
> app:streamUiReplyEnabled="false"
> app:streamUiReactionsEnabled="false"
> ```
> 
> to your `<io.getstream.chat.android.ui.message.list.MessageListView`.
> You can check all the possible ways to configure your MessageListView in the XML here: https://github.com/GetStream/stream-chat-android/blob/main/stream-chat-android-ui-components/src/main/res/values/attrs_message_list_view.xml

Is it possible to set those attributes programmatically? I'm not using XMLs, I could, but only if there's no way around them.

**Comment by leandroBorgesFerreira** [comment]
At the moment you can disable only replies using `MessageListViewStyle`... but that wouldn't work for the reactions. 
If you still want to use it, you can set it like this: 
```
TransformStyle.messageListStyleTransformer = StyleTransformer { defaultViewStyle ->
    // Modify default view style
    defaultViewStyle.copy(reactionsEnabled = false)
}
```
You can set this in your `Application` class. We are still adding configuration in this way... so replies are still not supported.

**Comment by leandroBorgesFerreira** [comment]
Sorry, my mistake. You can also configure the `MessageListView` directly. There are the methods:
`MessageListView::setRepliesEnabled` and `MessageListView::setReactionsEnabled`. You can use then to configure you view programatically.

**Comment by julioromano** [comment]
Cool thanks, for the moment we sorted this out with `messageListView.setMessageLongClickListener {}` since we don't really need to show the long press menu right now.
