### ISSUE TITLE
[4.8.0][ChannelListView] If predicate prevents all items to be drawn, no empty-view is shown

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1658]
Here's the predicate

```
binding.channelListView.setChannelListItemPredicate { item ->
    false
}
```

This causes the empty-view to not be shown.

**Comment by leandroBorgesFerreira** [comment]
This is tricky... It can be misleading to present the the empty view when the channelList exists, but it was just filtered out. Can you describe how you are using this feature?

**Comment by leandroBorgesFerreira** [comment]
Actually, nevermind. You can customise your empty view as you prefer to you can avoid misleading your users. Let us check this bug.

**Comment by zsmb13** [comment]
We're fixing this in the PR above, and it'll be part of the next release.

**Comment by JcMinarro** [comment]
Hi @rupinderjeet 
It has been fixed and we already released a [new versión](https://github.com/GetStream/stream-chat-android/releases/latest)
I'm closing this issue
