### ISSUE TITLE
How to set default drawable for AvatarView when channel.image is blank?

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1659]
We want to show default drawables when `channel.image` is not available depending on whether the channel is distinct or not.

It would be awesome if I could do something like:

```
binding.channelListView.avatar().setDefaultDrawable(resource)
binding.channelListHeaderView.avatar().setDefaultDrawable(resource)
binding.messageListHeaderView.avatar().setDefaultDrawable(resource)
```

or something to intervene default behaviour of showing member images in a collage(?). 

I guess it is not possible to use my own custom view in place of AvatarView.

**Comment by iosiappmemes** [comment]
hold on.. I just found AvatarBitmapFactory. I will close the issue if I am successful.
