### ISSUE TITLE
[4.8.0][MessageListView] setUserClickListener is not working

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1662]
Click listener is not fired when I tap user-avatar or user-name text for a message.

**Comment by leandroBorgesFerreira** [comment]
Hello @rupinderjeet Thanks for reporting. Let us take a look and work in a solution

**Comment by JcMinarro** [comment]
Hi @rupinderjeet 
It has been fixed and we already released a [new versión](https://github.com/GetStream/stream-chat-android/releases/latest)
I'm closing this issue
