### ISSUE TITLE
BaseMessageItemViewHolder.bindData() not called when only data.message.extraData changes

### ISSUE THREAD

**Issue by julioromano** [GetStream/stream-chat-android#1671]
**Describe the bug**
We're using a custom `MessageListItemViewHolderFactory` and therefore subclassed `BaseMessageItemViewHolder` in order to render some chat messages with a custom UI.
The custom UI is driven with data passed inside `data.message.extraData`.

Everything works fine when we get new messages, we parse the `extraData` and render the UI accordingly.

A problem arises when some messages are edited remotely (server side) and only their `extraData` content being changed (while the rest of the message object stays the same).

In this case `BaseMessageItemViewHolder.bindData()` is not called and the message is not updated on screen.

Reloading the `MessageListView` brings the rendering up to date.

**SDK version**
- 4.8.0

**Device:**
 - Vendor and model: Pixel 3a
 - Android version: 11

**Comment by leandroBorgesFerreira** [comment]
I don't see extraData in the `MessageUpdatedEvent` and `Message` has `@IgnoreDeserialisation` so it must be updated manually. Perhaps we need to add extra data to this event.

**Comment by leandroBorgesFerreira** [comment]
Thanks for reporting this @julioromano. We will investigate and come up with a solution.

**Comment by bychkovdmitry** [comment]
@julioromano 
Thanks for reporting this. The root cause was our diff callback which doesn't compare all the fields. As a result, not all updates are propagated to the UI. Created a small PR to fix this particular issue with `extraData` field. We are thinking how to make out `DiffUtil` callbacks extensible to prevent similar issues in future...

**Comment by samiuelson** [comment]
@julioromano Please check the new SDK release (version 4.9.0) which contains the fix. Let us know if you have any further issues.
