### ISSUE TITLE
Channel List and EmptyView are shown at the same time 

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1673]
When there's one channel in ChannelListView, and there comes an update event for channel that makes it so that this one channel no longer fits defined filter for ChannelListView, empty-view is shown. But, ChannelListView's adapter is not cleared. So, this channel is still shown along with empty-view.

ChannelListView has following filter along with `messaging` type and self as member filters:
```
Filters.ne("lit", true)
```
This shows channels with `lit` being absent or `false`.

I update channel to add `lit` to `true` in `extraData` and come back to fragment with ChannelListView. Here, now `lit` channel is visible along with empty-view.

**Comment by zsmb13** [comment]
Hey, thanks for reporting the issue, we'll get this fixed soon.

**Comment by zsmb13** [comment]
We're fixing this in the PR above, and it'll be part of the next release.

**Comment by JcMinarro** [comment]
Hi @rupinderjeet 
It has been fixed and we already released a [new versión](https://github.com/GetStream/stream-chat-android/releases/latest)
I'm closing this issue
