### ISSUE TITLE
Can we add partial-updates for Android too?

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1676]
Form the [docs](https://getstream.io/chat/docs/android/channel_update/?language=kotlin#partial-update), as of now, we are allowing Python, JS, and Flutter(?) to use partial-update API. 

If there's no technical restriction, can we add it for mobile-platforms too? 

If we add it, I will use it to add/update `channel.extraData` keys in channel. As of know, I am doing it as below:

```
val updatesMap = request.channel.extraData
updatesMap["local.deleted"] = true

val updatesMessage = "${currentUser.name} marked the chat as deleted."

val result = chatClient
	.channel(request.channel.cid)
	.update(
		message = Message(updatesMessage),
		extraData = updatesMap
	)
	.execute()
```

But, sometimes, I do not have access to this `channel` instance, but only a `cid`. So, I have to request channel using `querychannels` and, then update the `extradata`.

Also, Full Update (overwrite) kinda seems scary when it says "**Any data that is present on the channel and not included in a full update will be deleted.**" in bold.

**Comment by bychkovdmitry** [comment]
The functionality is implemented here https://github.com/GetStream/stream-chat-android/pull/1713 and will be shipped with the next release (4.8.2).

**Comment by rupinderjeet** [comment]
Thank you, that's awesome.

**Comment by samiuelson** [comment]
Please check the new SDK release (version 4.9.0) which contains the feature. Let us know if you have any further issues.
