### ISSUE TITLE
[MessageInputView] Attachment files list shows folders and crashes when selected & sent

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1679]
Here's the screenshot:
![Screenshot 2021-04-05 at 7 00 45 PM](https://user-images.githubusercontent.com/14011726/113578976-446d8180-9641-11eb-9333-6d178935458a.png)

Here's the crash [log](https://github.com/GetStream/stream-chat-android/files/6258346/crash.txt)

**Comment by adasiewiczr** [comment]
Hey, thanks for reporting the issue, we'll get this fixed soon.

**Comment by adasiewiczr** [comment]
Hey @rupinderjeet, the issue was fixed in the PR mentioned above and will be shipped in the next release.

**Comment by JcMinarro** [comment]
Hi @rupinderjeet 
It has been fixed and we already released a [new versión](https://github.com/GetStream/stream-chat-android/releases/latest)
I'm closing this issue
