### ISSUE TITLE
[MessageListHeaderView] Add ability to change background color & back-icon's drawable

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1687]
As of 4.8.0. I am unable to change drawable for back-icon through `attr` values. Please add an `attr` for changing this drawable.

Also, I am not able to change background color for whole header because we aren't using `<merge>` tag in child binding. We are using a ConstraintLayout(from parent view) inside a ConstraintLayout(from binding).

_source: https://github.com/GetStream/stream-chat-android/issues/1656_

**Comment by leandroBorgesFerreira** [comment]
Hello @rupinderjeet. this will be in the next release, the PR was already merged. https://github.com/GetStream/stream-chat-android/pull/1665

**Comment by JcMinarro** [comment]
Hi @rupinderjeet 
It has been fixed and we already released a [new versión](https://github.com/GetStream/stream-chat-android/releases/latest)
I'm closing this issue
