### ISSUE TITLE
[MessageListView] Change UI to show result of mute and block user options in message-actions

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1688]
When I mute a user, message-actions UI doesn't change its UI to show that user was muted i.e. either don't show mute-option again or show option to "unmute" user. Same for block user.

_source: https://github.com/GetStream/stream-chat-android/issues/1656_

**Comment by zsmb13** [comment]
Thanks for asking about it, we'll be working on this feature in the coming weeks.

**Comment by rupinderjeet** [comment]
Hello @zsmb13 

I understand that this isn't in the plan yet. But, do you think #1691 is possible?

I have tried to handle some issues with  `findViewById`. But, this is a dialog, I don't think I can access its view and hide the options with some stealth.

**Comment by zsmb13** [comment]
Yes, we'll also be picking up that task in the next two weeks.

**Comment by adasiewiczr** [comment]
Hey @rupinderjeet thanks for reporting that. It was fixed in the PR mentioned above and will be shipped in the next release

**Comment by samiuelson** [comment]
Please check the new SDK release (version 4.9.0) which contains the fix. Let us know if you have any further issues.
