### ISSUE TITLE
[MessageListView] When a file is being uploaded, wrong icon is displayed.

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1689]
When file is being uploaded, we shouldn't show red-warning (exclamation) icon which symbolizes an error. 
https://imgur.com/a/U2DAmq9

Instead of this, we should show an icon that symbolizes progress of upload.

If we are unable to do this, please add an attribute so that I can change the icon when the file upload is in progress.

_source: https://github.com/GetStream/stream-chat-android/issues/1656_

**Comment by JcMinarro** [comment]
Hi @rupinderjeet 
It has been fixed and we already released a [new versión](https://github.com/GetStream/stream-chat-android/releases/latest)
I'm closing this issue
