### ISSUE TITLE
[MessageListView] Is block-user option available to everyone?

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1690]
When a message is long pressed, a message-actions UI appears. This UI has option to block a user. In actual, it shadow-bans a user when tapped. But, from docs, it seems like shadow-ban is a moderation level tool which might only be available to channel moderators.

So, why show block-user option to users with just `channel_member` role? Is this left for developers to take over, or is it a bug?

**Comment by ogkuzmin** [comment]
Hello, @rupinderjeet!
In the next release, we're disabling the block user option completely because right now it's available to everyone that it's not right. We also have plans to improve it with a proper permission system. But can't say a particular date. Thanks for your question!

**Comment by rupinderjeet** [comment]
Thank you.
