### ISSUE TITLE
[MessageListView] How to remove mute-user and block-user option from message-actions UI?

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1691]
We have options to change icons for mute-user using `streamUiMuteOptionIcon` and for block-user using `streamUiBlockOptionIcon`. But, how can I remove mute-user and block-user functionality. 

If this isn't controlled from backend, can we add something similar to `streamUiCopyMessageActionEnabled` which is used to disable copy-message action?

We have a different app-only UI to address this functionality.

**Comment by samiuelson** [comment]
The missing attributes for message options visibility settings will be added in the upcoming release. You can expect it today/tomorrow.
