### ISSUE TITLE
[AvatarView] Images aren't being displayed perfectly rounded

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1692]
Images loaded in `AvatarView` are cut from all sides. Maybe this is because of some space for something like border-width. Or just view-size?

Check here: https://imgur.com/a/M8clpzx

_source: https://github.com/GetStream/stream-chat-android/issues/1656_

**Comment by ogkuzmin** [comment]
Thanks for your report! We fixed this, the patch will be available with our next release!

**Comment by samiuelson** [comment]
Please check the new SDK release (version 4.9.0) which contains the fix. Let us know if you have any further issues.
