### ISSUE TITLE
Youtube invalid link crash and preview issue

### ISSUE THREAD

**Issue by elevenetc** [GetStream/stream-chat-android#171]
1. If I try to edit `Youtube` message with invalid link the app crashes:

```
E  FATAL EXCEPTION: main
E  Process: io.getstream.chat.sdk, PID: 15733
E  java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
E      at com.getstream.sdk.chat.view.MessageInputView.a(:4)
E      at f.e.a.a.b0.x.a(Unknown Source:4)
E      at androidx.lifecycle.LiveData.a(Unknown Source:29)
E      at androidx.lifecycle.LiveData.b(Unknown Source:44)
E      at androidx.lifecycle.LiveData.b(Unknown Source:14)
E      at d.m.q.b(Unknown Source:0)
E      at androidx.lifecycle.LiveData$a.run(Unknown Source:18)
E      at android.os.Handler.handleCallback(Handler.java:883)
E      at android.os.Handler.dispatchMessage(Handler.java:100)
E      at android.os.Looper.loop(Looper.java:214)
E      at android.app.ActivityThread.main(ActivityThread.java:7356)
E      at java.lang.reflect.Method.invoke(Native Method)
E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

2. `Youtube` and `Unsplash` messages with invalid links looks differently:
<img width="570" alt="Screenshot 2019-10-16 at 16 58 40" src="https://user-images.githubusercontent.com/1069159/66936139-7fd75300-f03d-11e9-86cc-70054d11d656.png">
<img width="514" alt="Screenshot 2019-10-16 at 17 49 35" src="https://user-images.githubusercontent.com/1069159/66936140-7fd75300-f03d-11e9-80aa-d8a4a1698982.png">

Used `Youtube` link: https://www.youtube.com/watch?v=K0x-jSKOoR
Used `Unsplash` link: https://unsplash.com/photos/kAK7A

**Comment by adrian09h** [comment]
@elevenetc , I can't reproduce this crash.
After sending invalid URLs, can't see any crash.
![20191016_221406](https://user-images.githubusercontent.com/11132956/66955458-a65bb500-f062-11e9-86bc-88e3c814c602.gif)

**Comment by elevenetc** [comment]
It's not about sending. It's about editing:
1. Paste invalid youtube link.
2. Long press on the message
3. Crash
