### ISSUE TITLE
Allow to set the user as invisible without having to disconnect

### ISSUE THREAD

**Issue by julioromano** [GetStream/stream-chat-android#1710]
**Describe the bug**
I'd like to programmatically set/unset the user `visible` parameter.

Right now this is only possible when calling `ChatClient.instance().connectUser()` for the first time, subsequent calls to `ChatClient.instance().connectUser()` will not change any user's properties.

The only way around it is to call `ChatClient.instance().disconnect()` and then re-call `ChatClient.instance().connectUser()`.

Please add an API to change a user's properties programmatically while connected.

**SDK version**
- 4.8.0

**Comment by adasiewiczr** [comment]
Hey @julioromano,
thanks for reporting that.
Did you try updating the user using `ChatClient::updateUser` method?

**Comment by julioromano** [comment]
Yes, it seems it has no effect.

Code I tried:

```
        ChatClient.instance().updateUser(
          user = User(
            id = "someUserId",
            invisible = true,
          )
        ).enqueue()
```

**Comment by adasiewiczr** [comment]
Could you share the response you get after running this call?

**Comment by julioromano** [comment]
HTTP FAILED: streamCode: 4, statusCode: 400, message: UpdateUsers failed with error: "users[xxxxxxxxx].invisible is a reserved field"

**Comment by adasiewiczr** [comment]
hey @julioromano, sorry for the late response. 
Currently, the only possible option to change `invisible` parameter is through creating a new connection, so as you said -you need to disconnect the current user and connect it again.

**Comment by bychkovdmitry** [comment]
Hello @julioromano 
As @adasiewiczr mentioned, creating a new connection is the only option now. Thanks for the suggestion, updating the `visible` parameter while connected seems like a nice feature. However, this feature is not our priority right now as it requires significant changes on the backend side.

**Comment by 6879756e** [comment]
Hello @bychkovdmitry 
I was wondering whether this is still the case? I ask because the [documentation](https://getstream.io/chat/docs/android/presence_format/?language=kotlin#invisible) gives the impression that it's possible (though it may just be for web). Thanks!
