### ISSUE TITLE
Question: How to infer a user's chat presence

### ISSUE THREAD

**Issue by julioromano** [GetStream/stream-chat-android#1711]
We'd like to be able to check for a given Stream user's chat presence.
By "presence" I mean if a user is actually chatting in any channel.

A user may be connected from multiple clients at the same time (e.g. from different web browsers, iphone app, android app, ipad app...).

Is there any way to accomplish this using Stream SDK ?

Some Examples:
a) A user is connected both from Android app and iPhone app, is chatting on the Android app, but not on the iPhone app => User's "presence" value should be `true`.

b) A user is connected both from Android app and iPhone app, is not chatting on both devices => User's "presence" value should be `false`.

Thanks in advance.

**Comment by tschellenbach** [comment]
Note that watchers indicate if someone is watching a specific channel:
https://getstream.io/chat/docs/android/watch_channel/?language=kotlin#watchers-vs-members

User presence indicates if someone is watching any channel in an app. 
https://getstream.io/chat/docs/android/presence_format/?language=kotlin

So if you have two channels:

* Channel:a
* Channel:b

And 3 users. user 1, user 2, user

* user 1 is watching both channel a and b. he is in the watchers list for both channel and online=true
* user 2 is watching channel b. he is in the watchers for channel b, and he is online=true
* user 3 is not watching anything. he is not in the watchers list and online=false

From your question it wasn't entirely clear to me if you want to know if a user is watching any channel (IE online in the chat app) or watching a specific channel. Can you clarify?

**Comment by julioromano** [comment]
> From your question it wasn't entirely clear to me if you want to know if a user is watching any channel (IE online in the chat app) or watching a specific channel. Can you clarify?

Following your explanation I can clarify we'd like to know if a user is "online". Thanks.

Problem is that right now our users are marked as online as long as their Android or iOS chat app is open, regardless if the user is actually having the chat screen open.

Is it possible to make it such that the "online" property is set to:
 - false: user may be disconnected OR may be connected but with no chat screens open.
 - true: user is connected AND has at least one chat screen on at least one of his/her devices open.
 
 Or does the Stream SDK allows to achieve this same thing in another way?

**Comment by julioromano** [comment]
After some more thought I think we may need both:

### Online
Stream's SDK default behvior is to set the user as online when the app UI is visible (foreground) and set it as offline when the UI is not visible (background). Correct me if I'm wrong but this was the behavior observed using Stream's Anroid SDK v4.8.1.

Q1: Is it possible to customize this behavior and programmatically tell the SDK when set the user online/offline?


### Watchers
I couldn't find any info regarding watchers of a given channel on the Stream Dasbhoard.

Q2: Does the Stream Android SDK set/unset a user's watcher state when opening closing the relative `MessageListView` ? Or is it something we have to explicitly do programmatically?

**Comment by julioromano** [comment]
> From your question it wasn't entirely clear to me if you want to know if a user is watching any channel (IE online in the chat app) or watching a specific channel. Can you clarify?

Neither, it's something in between.

The issue is less apparent on mobile phones because of their single task nature (there can only ever be one app visible on the screen at the same time) which effectively enables only 2 states:
a) The chat app is in the foreground, in which case Stream reports the user as `online: true`.
b) The chat app is in the background, in which case Stream reports the user as `online: false`.

But on Desktop PCs there can be multiple windows open at any given time and our app's window can be buried below other windows, so there are more states:
1) The chat app window is open and is the frontmost window, in which case Stream reports the user as `online: true`.
2) The chat app window is open but is not the frontmost window, in which case Stream still reports the user as `online: true`.
3) The chat app window has been closed, in which case Stream reports the user as `online: false`.


For mobile apps we just need to look at the `user.online` property and we can reliably infer wheter a user is using the chat (state 'a') app or not (state 'b').
For desktop apps this same approach is not valid anymore, because when `user.online == true` we can't reliably infer whether the user is using the chat app (state '1') or he/she simply has left it open behind some other windows (state '2').


We are looking for a way to detect when a user is in state '2'.

**Comment by tschellenbach** [comment]
There are 2 ways in which you can do this:

- you could call client.disconnect on the browser based chat whenever the tab loses focus.
- alternatively you could send custom events on the channel for when the tab loses focus.

So this is not directly supported, but I think you have 2 viable workarounds.
