### ISSUE TITLE
Hidden channel, that became visible after new message, is removed from ChannelListView again

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1716]
I am hiding a channel with `clearHistory=true`, and it works. When a new message is received, `ChannelListView` shows channel again. But, when I return to page with `ChannelListView` after reading new message, channel disappears again.

Suppose you're chatting with Carter,

- Create a direct/unique channel with Carter.
- Hide the channel with `clearHistory` enabled. Channel is hidden from ChannelListView. 
- Carter sends you a new message, channel is shown in ChannelListView
- Tap the channel, read the message & go back to ChannelListView.
- Channel is removed from ChannelListView.

Here's a quote from documentation page:
> Hiding a channel will remove it from query channel requests for that user until a new message is added. Please keep in mind that hiding a channel is only available to members of that channel.

So, does this mean the channel is marked hidden again after all new messages are read?

I am using v4.8.1

**Comment by ogkuzmin** [comment]
Thanks for submitting an issue. We're going to investigate it and fix it

**Comment by ogkuzmin** [comment]
We merged the fix for this issue. The patch will be available with next release

**Comment by rupinderjeet** [comment]
Hello @ogkuzmin 

I tested These commits break the "clearHistory" functionality. 

As of now, messages from history are displayed. Sometimes these messages are visible for like 5 seconds, and then they disappear when MessageListView blinks.

**Comment by ogkuzmin** [comment]
@rupinderjeet 
Seems we need some improvements to the message list. Could you upload a video with such a side effect?

**Comment by samiuelson** [comment]
@rupinderjeet Please check the new SDK release (version 4.9.0) which contains the fix. Let us know if you have any further issues.
