### ISSUE TITLE
Wrong flag-user command input when using SuggestionsListView

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1719]
1. Tap on lightning-icon in MessageInputView. It shows two commands as received in `channel.config.commands`
2. Select flag-user command. MessageInputView updates UI to show that flag-user command is active.
3. Type a username starting with "@" symbol so that SuggestionsListView can show you user-suggestions.
4. Tap one of shown user-suggestions. MessageInputView's input changes to `/flag @selectedUserName`
5. Send message. Sent message's text is `/flag /flag @selectedUserName`

Here's a video recording of the issue:
https://user-images.githubusercontent.com/14011726/114547520-2b398600-9c7c-11eb-838d-1d67f365e4d2.mp4

v4.8.1

**Comment by ogkuzmin** [comment]
Hey @rupinderjeet 
Thanks for submitting the issue. We fixed this, patch will be available with next release

**Comment by samiuelson** [comment]
Please check the new SDK release (version 4.9.0) which contains the fix. Let us know if you have any further issues.
