### ISSUE TITLE
Command message to flag-user always fails with "unrecognized command flag"

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1721]
Channel's config has two commands that I can use. Giphy command works fine. But, flag-user command always fails. 

I have tried with following commands:
- /flag username
- /flag @username
- /flag [@username]

Here's the message printed by API call.
> E/Chat:ChatDomain ChannelController: Failed to send message with id some-long-long-long-message-id and text /flag winnie: ChatNetworkError http status 400, stream error code 4: SendMessage failed with error: "unrecognized command flag"

v4.8.1

**Comment by ogkuzmin** [comment]
Hello @rupinderjeet!
Thanks for submitting this issue. The problem is that the flag command requires `userId` as an argument. We should make some changes in platform to translate request with `username` to request with `userId`

**Comment by rupinderjeet** [comment]
Hello @ogkuzmin 

Thanks for the update.

Do you think the suggested solution might cause problems for stream-clients that do not have unique usernames?

**Comment by ogkuzmin** [comment]
@rupinderjeet Do not worry!) We'll find a good way to handle it!

**Comment by bychkovdmitry** [comment]
Hello @rupinderjeet 
Sorry for the delayed response. We are still considering ways of handling this on the backend. So, the fix might take some time...

**Comment by bychkovdmitry** [comment]
Hi @rupinderjeet 

Sorry for the confusion. Even though the "flag" command is in the list of available commands, it is not implemented on the backend. I would suggest removing the "flag" command in the dashboard.
