### ISSUE TITLE
[MessageListView]  Message Lacks Horizontal Margin

### ISSUE THREAD

**Issue by Dumblydore** [GetStream/stream-chat-android#1740]
Using a MessageListView the messages themselves lack horizontal margin. Here's what the layout code looks like:
```
   <com.getstream.sdk.chat.view.MessageListView
            android:id="@+id/liveStream.playback.chat.list"
            android:layout_marginHorizontal="0dp"
            android:clipToPadding="false"
            style="@style/AppTheme.Chat.MessageList"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
```
Is there something I'm not doing correctly? Thanks in advance.
**SDK version**
- 4.8.1

**Expected behavior**

**Device:**
 - Vendor and model: Google Pixel 4a
 - Android version: 10

**Screenshots**
https://imgur.com/a/BoDMjOt

**Comment by ogkuzmin** [comment]
Hello, @Dumblydore 
Could you show whole xml layout?
Also, we launched [new UI components](https://github.com/GetStream/stream-chat-android/tree/main/stream-chat-android-ui-components) at the beginning of this year, you can try them!

**Comment by samiuelson** [comment]
Hi, @Dumblydore,

If you build your chat from scratch we recommend using the new ui-components artifact (https://github.com/GetStream/stream-chat-android/tree/main/stream-chat-android-ui-components). Old UI components implementation is going to be deprecated.

Let me know if you have any other issues.
