### ISSUE TITLE
[MessageListView] Multi-line messages are shown in single line

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1746]
On messages page,

1. Type a word "Hello" into `MessageInputView`. Hit next-line.
2. Type another word "World". Hit send.
3. Sent message is shown in a single line.

Here's a video showing the issue: https://user-images.githubusercontent.com/14011726/115190231-59e4b000-a105-11eb-9572-1516911ddf34.mp4

If there's something I can do on my side, please guide me.

v4.8.1

**Comment by samiuelson** [comment]
Thanks for the report, we're looking into it.

**Comment by samiuelson** [comment]
@rupinderjeet Please check the new SDK release (version 4.9.0). The new lines are supported now. At the moment it's not possible to have multiple new lines and they are merged into a single new line. We will try to support it in the future.
