### ISSUE TITLE
Rate Limiting for Create Device API call

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1750]
We are being hit with rate-limiting for Create Device API (_aka addDevice_). I have found two places this API could be called from:

- `chatClient.addDevice()` is one way to add devices. But, I am not using it since ChatClient is handling notifications for me.
- `ChatNotifications.onSetUser()` is another way for this API to be called internally. ChatClient calls this API whenever a `connected` event is received.

The [documentation for Create Device API](https://getstream.io/chat/docs/rest/#devices-createdevice) mentions following:
> Adds a new device to a user, if the same device already exists the call will have no effect

I think every call is being counted towards rate-limiting even if it had no effect, which is valid. But, at the same time, it is unfair to me because I have no option to skip this API call.

I suggest that whenever we call this API, we cache last *successfully* sent device(token?) in persistent storage. This way, next time we are about to hit this API, we can just compare current device(token?) with last cached device, and avoid the API call.

**Comment by rupinderjeet** [comment]
I initialize chat-setup in `Application` class as instructed in [UI-Cookbook](https://github.com/GetStream/stream-chat-android/wiki/UI-Cookbook#initialize-sdk). The above mentioned API will hit every-time one of the following happens:

- app crashes & reopens
- chat socket reconnects to Stream
- user internet connection changes
- a user regularly closing & opening app

These scenarios are very common. Almost every app goes through them. For e.g. in the past, due to an app crash in chat-notifications, large number of apps/devices will reconnect to stream-chat at the same time, which may cause overflow for rate-limiting.

Stream helped us by elevating this limit to 900 calls per minute. But, we are still experiencing this issue. Please guide me if I can do something on my end.

**Comment by samiuelson** [comment]
Thanks for reporting this. We are looking into the solutions and we will fix the initialization in one of the upcoming releases.

**Comment by tschellenbach** [comment]
Things we can do to optimize this:

- we only need to register once, not every time you connect
- customers that don't use push don't need this API call at all, so there should be a way to disable it

**Comment by JcMinarro** [comment]
Hi @rupinderjeet 
A new version has been released that fixes it
