### ISSUE TITLE
Crash when switching users (ChatDomain)

### ISSUE THREAD

**Issue by beckmartin** [GetStream/stream-chat-android#1753]
**Describe the bug**
When switching (Google accounts) the app crashes with

`E/UncaughtException: java.util.InputMismatchException: received connect event for user with id *insert id here* while chat domain is configured for user with id *another id here* create a new chatdomain when connecting a different user.
        at io.getstream.chat.android.livedata.ChatDomainImpl.updateCurrentUser$stream_chat_android_offline_release(ChatDomainImpl.kt:309)
        at io.getstream.chat.android.livedata.EventHandlerImpl.updateOfflineStorageFromEvents$stream_chat_android_offline_release(EventHandlerImpl.kt:262)
        at io.getstream.chat.android.livedata.EventHandlerImpl$updateOfflineStorageFromEvents$1.invokeSuspend(Unknown Source:12)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)`

**SDK version**
- 'com.github.GetStream:stream-chat-android:4.7.0'

**To Reproduce**
1. Login with Google Account 1
2. Fetch channel list
3. Logout from Google Acc 1
4. Login with Google Account 2
5. Fetch channel list again, crashes with 

**Expected behavior**
Loads channels without crashing

**Device:**
 - Samsung S9
 - Android 11

**Comment by beckmartin** [comment]
I connect like so:

```
    val client = ChatClient.Builder(mSharedPreferenceApi!!.get(Constants.CHAT_API_KEY, String::class.java), activity.applicationContext)
                .logLevel(ChatLogLevel.ALL)
                .notifications(ChatNotificationHandler(activity.applicationContext, notificationsConfig))
                .build()
```

        val firebaseUser = FirebaseAuth.getInstance().currentUser
        val chatToken = mSharedPreferenceApi!!.get(Constants.CHAT_TOKEN, String::class.java) as String
        val firebaseUID = mSharedPreferenceApi!!.get(Constants.FIREBASE_UID_STREAM, String::class.java) as String

        val user = User(firebaseUID).apply {
            extraData["name"] = firebaseUser?.displayName.toString()
            extraData["image"] = firebaseUser?.photoUrl.toString()
        }

        val domain = ChatDomain.Builder(client, activity.applicationContext).build()

        client.connectUser(
                user = user,
                token = chatToken
        ).enqueue { result ->
            if (result.isSuccess) {
                // TODO Handle success
            } else {
                // TODO Handler error
            }
        }

When I log out from my Google Account I call _ChatClient.instance().disconnect()_ is there anything else that I need to do?

**Comment by samiuelson** [comment]
Hi @beckmartin,

Your crash is caused by the user token that you use. Looks like you're trying to use the same user token for different `User` instances.

The user token is supposed to be a JWT token and must be unique per user. You can use our manual [tool](https://getstream.io/chat/docs/react/token_generator/) for token generation or generate them using one of the available libraries. For more info about JWT go [here](https://jwt.io/).

I'm going to update our docs to make it more clear. Let me know if you have any further problems.

**Comment by beckmartin** [comment]
Seems like several callback call onConnected which leads to this error, I also use dispose() to get rid of listeners but it doesn't seem to have any impact, when reinstating the Fragment it should be a new ChatDomain, no ?

**Comment by beckmartin** [comment]
As for this case, we have 3 fragments in a view pager and whenever I change accounts this error occurs

**Comment by beckmartin** [comment]
As you saw we save backend tokens and such in the shared.prefs and load then everytime the Fragment is attached

**Comment by beckmartin** [comment]
The error displayed suggests that a new ChatDomain has to be instantiated but that's what happening everytime we switch to that Fragment

**Comment by samiuelson** [comment]
ChatDomain is alive as long as the app's process is not killed. No need to do anything with ChatDomain when switching user. ChatDomain is update automatically with the new user data once `ChatClient.connectUser()` is called. 

Can you double check if you are using valid `userId` with `userToken` pairs? They must be unique. What is you way of generating JWT tokens for user ids?

**Comment by beckmartin** [comment]
Double checked on the uniqueness of.  userId and userToken pairs and there was a mismatch indeed, this was not that clear to me, Thanks for the hint to that!
