### ISSUE TITLE
Message extraData deserializes integer numbers as floating point

### ISSUE THREAD

**Issue by julioromano** [GetStream/stream-chat-android#1766]
**Describe the bug**
Additional data placed inside `io.getstream.chat.android.client.models.Message.extraData` always transforms numbers to floating point (even if they don't have any decimal separator in the JSON data).

**SDK version**
- 4.9.0

Seems to be a regression as with v.4.8.x this was not happening (numbers were correctly recognized as integers).

Perhaps this has something to do with: https://github.com/GetStream/stream-chat-android/issues/1671 ?

Thanks,
Bye,
Marco

**Comment by bychkovdmitry** [comment]
Hello @julioromano 
Thanks for letting us know. Unfortunately, the pure JSON does not distinguish between integers and doubles and therefore your values are deserialized as floating-point numbers ([Moshi issue](https://github.com/square/moshi/issues/192#issuecomment-248996450)). You can store your integers as string and decode to your preferred format. Please let us know if this works for you.

**Comment by julioromano** [comment]
We can't really store our integers as String because the same extraData is used by other platforms (iOS and Web) which instead don't have this issue.

Would it be possible to get the RAW JSON data of the `Message.extraData` so that I can do my own parsing?
