### ISSUE TITLE
Deleting command messages doesn't update the UI

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1774]
Because of #1721, I am unable to send command messages for now. So, when I type a flag command message and hit enter,  UI shows me that message is not sent. If I try to delete this unsent message (with deletion-confirmation), UI doesn't update to show that message was deleted. I can try to delete this message again, and it is not updated. If I try to resend this message after failing attempts of deletion, UI updates and shows that message was deleted.

I am able to delete regular messages properly. 

v4.9.0

**Comment by JcMinarro** [comment]
Hello @rupinderjeet 
The problem here is that the message has not been sent to backend, and when we ask backend to remove it, it doesn't exist.
We need to update the delete process to handle it.

Thanks for reporting it

**Comment by JcMinarro** [comment]
Hello Rupinderjeet, it has been fixed on #1803 and will be ready on the next release

**Comment by JcMinarro** [comment]
Hi @rupinderjeet 
A new version has been released that fixes it
