### ISSUE TITLE
channel.memberCount always return 0

### ISSUE THREAD

**Issue by workspace** [GetStream/stream-chat-android#1778]
**Describe the bug**
channel.memberCount always return 0

**SDK version**
- 4.9.0

**To Reproduce**
Steps to check the behavior:
1. Add breakpoint to [this line](https://github.com/GetStream/stream-chat-android/blob/main/stream-chat-android/src/main/java/com/getstream/sdk/chat/viewmodel/channels/ChannelsViewModelBinding.kt#L21)
2. Run stream-chat-android-sample
3. Open channel list
4. See debug console

**Expected behavior**
return member count for channel

**Screenshots**
![image](https://user-images.githubusercontent.com/7759511/116176260-d6524100-a74c-11eb-9260-cd057e634825.png)

**Comment by JcMinarro** [comment]
Hi @workspace Thanks for reporting it.
It has been fixed on #1799 and will be ready on the next release

**Comment by JcMinarro** [comment]
Hi @workspace  
A new version has been released that fixes it
