### ISSUE TITLE
Unable to send .tiff files

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1786]
Hello, I am unable to send .tiff files from list of files (or file-picker). It always fails and shows UI with 0-byte as content. This failed message doesn't show an option to resend it.

I understand that .tiff is an image media, and I am not looking for you to support it as an image. I am interested in general upload/download of the file in a message.

I used samples from: https://file-examples.com/index.php/sample-images-download/sample-tiff-download/

Here's a video recording of the issue:
https://user-images.githubusercontent.com/14011726/116408057-05051000-a850-11eb-8620-fb3251bb458f.mp4

There might be other such file types. If there is any list of supported/unsupported file types from your end, please give me a link to it so that I can show appropriate UI when a user tries to send such a file.

v4.9.0

**Comment by JcMinarro** [comment]
Hello @rupinderjeet 
Thanks for reporting it. Let me chek it.

**Comment by JcMinarro** [comment]
Hi @rupinderjeet 
Some updates here.
Our backend has a list of supported image types they accept.
`.tiff` files are not supported as "image" but it is supported as file.
We need to do some updates on our side to allow you to send this kind of image.
The image will be sent "as file", instead of "as image"

**Comment by rupinderjeet** [comment]
Yes, sure, thanks for the update.

**Comment by bychkovdmitry** [comment]
Hello @rupinderjeet 
We've made some improvements here [#1839](https://github.com/GetStream/stream-chat-android/pull/1839). Now images, unsupported by the Stream CDN are sent as files. The update will be shipped with the next release.

**Comment by rupinderjeet** [comment]
Thank you.

Were you able to find out if the issue was indeed because of .tiff extension? 

I am experiencing similar issues with .mp4 files as well. I have checked the logs, and it seems the coroutine job, used to upload the file, is canceled somehow before upload completes. Okhttp prints Http Canceled message and one of the message APIs are hit with `file_size` as `0`, even though `content-length` in post request shows actual file size. If upload is successful, I don't see any http cancelation message.

If this github issue is indeed just because of .tiff extension, then I can post above explained issue in a different github issue. Let me know please.

p.s. been away for some days

**Comment by bychkovdmitry** [comment]
Hello @rupinderjeet,
Yes, the list of supported image mime types when using `ChannelClient::sendImage` method:
- image/bmp
- image/gif
- image/jpeg
- image/png
- image/webp
- image/heic
- image/heic-sequence
- image/heif
- image/heif-sequence
- image/svg+xml

Other image types and files should be sent via `ChannelClient::sendFile` method.

**Comment by JcMinarro** [comment]
Hello @rupinderjeet 

A new version that handle it for you is already released.
If you are using our UI Components to send attachments, dpendeing on the file you are sending, it will be sent as image or as file
