### ISSUE TITLE
channel.create does not exist

### ISSUE THREAD

**Issue by tbarbugli** [GetStream/stream-chat-android#179]
In a way this is confusing (query / watch are both not great names) on another why would want to create without fetching state and watch? @tschellenbach what do you think?

**Comment by tschellenbach** [comment]
.create makes sense to me for a backend cronjob creating channels

**Comment by tbarbugli** [comment]
exactly, but this is the Android client :)

**Comment by tschellenbach** [comment]
yeah so why do you want to have it?

**Comment by tbarbugli** [comment]
it's weird not to have a method called `channel.create()`. Atm we have: `update`, `watch` and `query`. I can imagine some users getting confused

**Comment by tbarbugli** [comment]
same as: lot of people get very confused because there is no `feed.create`

**Comment by psylinse** [comment]
I'm confused by this. The [docs](https://getstream.io/chat/docs/initialize_channel/?language=js) say you can call `.create`:

```
Here’s how you can initialize a single channel for later use. Please note that this will only create a channel object without making any API call. Once the channel is initialized you can use one of these methods: query, watch, create.
```

The reason I want this is all my backend does is generates a frontend token. I want to set the name and image before joining the channel so the user doesn't see "Channel without name". I also don't want to go through my backend to do this. It seems like I should be able to create the channel directly from the client without having to do an empty `query` w/ `update`. FWIW, probably `update` should just create the channel too? It's suprising that `update` it fails with a 404 not found but every other method lazily creates the channel.

**Comment by psylinse** [comment]
Here is the awkward code: https://github.com/psylinse/stream-android-encrypted-chat/blob/master/android/app/src/main/java/io/getstream/encryptedchat/ChannelActivity.kt#L45-L69
