### ISSUE TITLE
Suggestion: add messageLimit parameter for ChannelListViewModel

### ISSUE THREAD

**Issue by workspace** [GetStream/stream-chat-android#1812]
We'd like to select last message in channel list (ex. show only message which is not reply or not system message), however, ChannelListViewModel execute query channels with default messageLimit(=1) value.

https://github.com/GetStream/stream-chat-android/blob/main/stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/viewmodel/ChannelListViewModel.kt#L49

**Comment by bychkovdmitry** [comment]
Hello @workspace 
The fix will be shipped with the next release. You will be able to pass the `messageLimit` parameter to `ChannelListViewModel` / `ChannelListViewModelFactory` constructors.

**Comment by workspace** [comment]
@bychkovdmitry Thank you!

**Comment by JcMinarro** [comment]
Hello @workspace 

a [new version](https://github.com/GetStream/stream-chat-android/releases/latest) has been released with the fix.
