### ISSUE TITLE
QueryChannelsController with filter, currentUserId in members, drop some result.

### ISSUE THREAD

**Issue by workspace** [GetStream/stream-chat-android#1836]
**Describe the bug**
QueryChannelsController with filter, currentUserId in members, drop some result.

**SDK version**
- 4.9.2

**To Reproduce**
0. ChatDomain.offlineDisabled() (we decided to disable offline due to sync message list bug in some situation)
1. make channel with members count > 100 (any big number) and add user to channel
2. use ChannelListViewModel and ChannelListView for listing user's channels with 
```kotlin
private val filter: FilterObject = Filters.`in`(
    "members", listOf(chatDomain.currentUser.id)
)
```
3. in this line https://github.com/GetStream/stream-chat-android/blob/main/stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/querychannels/QueryChannelsController.kt#L251
some channel.members do not contain currentUser, so some channel is filtered by newChannelEventFilter.

**Expected behavior**
get current user's channel list without filtering

**Comment by workspace** [comment]
![image](https://user-images.githubusercontent.com/7759511/116950573-5e41c900-acc0-11eb-8b74-58275afa11b8.png)
currentUser.id(3387) is a member of newChanne[0], however, newChannelEventFilter return false because channel.members do not contain all members

**Comment by bychkovdmitry** [comment]
Hello @workspace,

Thanks for reporting it. Let me check it.

**Comment by leandroBorgesFerreira** [comment]
Hello @workspace. There was a problem related to channels filter in our SDK which was causing some channels to be dropped. A fix was added to the filter, please check the next version of our SDK, it should fix this issue.

**Comment by zsmb13** [comment]
Looks like this one is resolved, so I'll close the issue. @workspace let us know if you're still experiencing this problem.
