### ISSUE TITLE
Sometimes file upload requests are canceled when in progress

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1844]
I am experiencing file upload issues with .mp4 files. I have checked the logs, and it seems the coroutine job, used to upload the file, is canceled somehow before upload completes. `Okhttp` prints "Http Canceled" message and one of the message APIs are hit with `file_size` as `0`, even though `content-length` in post request shows actual file size. If upload is successful, I don't see any http cancelation message.

Similar Issue: #1786

v4.9.1

**Comment by rupinderjeet** [comment]
Video-recording of the issue:
https://user-images.githubusercontent.com/14011726/117270522-ed90dd00-ae76-11eb-9351-39a02873c92a.mp4

Logs around this issue:
[stream-chat-android-1844.txt](https://github.com/GetStream/stream-chat-android/files/6433160/stream-chat-android-1844.txt)

**Comment by bychkovdmitry** [comment]
Hi @rupinderjeet 
Thanks for submitting this issue. I'll check it today.

**Comment by rupinderjeet** [comment]
Just adding that this happens with image files as well (about 60% success rate when uploading any kind of attachments)

**Comment by bychkovdmitry** [comment]
Hello @rupinderjeet 
Could you try the latest version (4.10.0, released May 11). We increased default upload timeout to 30 seconds. Let us know if this issue still exists.

**Comment by rupinderjeet** [comment]
Hello @bychkovdmitry 

Sorry for late reply. Yes, sure, I will try it out, and let you know, thanks.

**Comment by zsmb13** [comment]
@rupinderjeet Did you have a chance to try your uploads with the latest version?

**Comment by rupinderjeet** [comment]
Hello @zsmb13 

I tested the update of v4.10.0 for this issue quickly. I was able to reproduce it on an emulator. I have recorded a video to show you the upload behavior, but I am holding onto it until I test it on a physical device properly.

After comparing the issue on both emulator and physical device, I will upload the recorded video.

Almost every upload fails with SocketTimeout error, but the attachment message is sent with 0 file-size. So, the user can't retry this failed upload.

Another strange finding is that for a 3mb MP4 file, first 1.5~2.0mb is uploaded really  fast, then it is stuck on this progress, and fails eventually.

p.s. Sorry, been busy. Sadly, I am no longer assigned to chat tasks. But, I will help out with my opened issues, this and others. 👍🏼

**Comment by rupinderjeet** [comment]
Hello @zsmb13 

I have tried about 4 times, and I am not able to reproduce the issue on physical device now. It seems that issue is only due to emulator or it got fixed.

> So, the user can't retry this failed upload.

But, when uploaded `file_size` is `0`, we should mark the message as "not-sent", so that I can retry uploading the file.

**Comment by adasiewiczr** [comment]
Hey @rupinderjeet,
we've improved attachment handling in the latest releases. 
Could you check how it works with the latest version?

**Comment by rupinderjeet** [comment]
Hello @adasiewiczr 

I will be able to adopt v4.12.* release in next week. I will add feedback after testing.

**Comment by zsmb13** [comment]
Hey @rupinderjeet, did you have a chance to check in new versions?

**Comment by rupinderjeet** [comment]
Hello @adasiewiczr and @zsmb13,

Not really possible for me as of now. You can close this issue. If I encounter this issue after updating to latest version, I will report a new one, or post a comment here.

I wish I could help here.

**Comment by zsmb13** [comment]
Thank you @rupinderjeet. We assume that the recent improvements have fixed this then.
