### ISSUE TITLE
ChannelClient::queryBannedUsers get failed with new serialization

### ISSUE THREAD

**Issue by workspace** [GetStream/stream-chat-android#1864]
**Describe the bug**
JsonDataException
Required value 'shadow' missing at $.ban[]

**SDK version**
- 4.10.0

**To Reproduce**
1. use ChannelClient::queryBannedUsers

**Screenshots**
![image](https://user-images.githubusercontent.com/7759511/118350028-78688a80-b58f-11eb-991b-23f600a9149e.png)

**Comment by zsmb13** [comment]
Thanks for reporting this! We'll patch this up in the next release. Please opt-out of new serialization until then as described in the [release notes for 4.10.0](https://github.com/GetStream/stream-chat-android/releases/tag/4.10.0).

**Comment by zsmb13** [comment]
We've addressed this problem in the PR above, the fix will be shipped in the next release.

**Comment by JcMinarro** [comment]
Hello @workspace 
A new version has been released with the fix. You can check it [here](https://github.com/GetStream/stream-chat-android/releases/latest)
