### ISSUE TITLE
I do not receive any notifications after calling stopSelf() in CustomFirebaseMessagingService

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1880]
Related documentation Url:
https://getstream.io/chat/docs/android/push_android/?language=kotlin#handling-notifications-from-multiple-backend-services

I have setup the push-notifications as defined in above docs. It suggests to stop the `FirebaseMessagingService` in `onMessageReceived()` by calling `stopSelf()`. What is the reason behind stopping the service?

When I include `stopSelf()` statement, I receive one chat-notification only for first message. Messages sent after that do not show a notification.

If I comment out `stopSelf()` statement, I receive notifications for all messages(almost within 10s to 60s). 

v4.9.2 (p.s. upgrading soon)

**Comment by rupinderjeet** [comment]
Also,  

* When app process is in background (alive), I receive all the notifications. 
* When app is killed, I receive only one notification for one message. Android Studio starts showing that app process is alive in logcat. All subsequent messages, I send, aren't received in `onMessageReceived()`. But, rather in logcat, I see a text that starts like this:

```
I/Chat:Events: {"type":"notification.message_new","cid":"messaging: ... .... ... ... 
```

Since, `onMessageReceived()` is not called after first message, I believe this might be a decision on firebase's end to not deliver us the notification perhaps. But, I can't stop wondering if I am doing something wrong.

Also (2):

I am using following code to retrieve firebase-token:
```
FirebaseMessaging.getInstance().token.addOnCompleteListener { task -> } 
```
whereas stream-chat-sdk is using following code (which is deprecated):
```
FirebaseInstanceId.getInstance().instanceId.addOnCompleteListener {} 
```

even though, the tokens generated in both cases are same.

**Comment by adasiewiczr** [comment]
Hey @rupinderjeet,
regarding `stopSelf()` feel free to remove it if it works for you.
From what I see from logs - after receiving the first notification, the web socket connection is established and in that case, you won't receive any new push notifications because they are only sent when the user is disconnected from the web socket.
We are currently working on improving push notifications handling, so stay tuned for upcoming releases.

**Comment by rupinderjeet** [comment]
Hello @adasiewiczr,

Thank you for the insight & feel free to close the issue if the mentioned updates are not planned for next version.

**Comment by JcMinarro** [comment]
Hello @rupinderjeet 
A new version has been released with the fix. You can check it [here](https://github.com/GetStream/stream-chat-android/releases/latest)
