### ISSUE TITLE
UpdateChannelPartial doesn't like Channel.cid

### ISSUE THREAD

**Issue by SeanOThomas** [GetStream/stream-chat-android#1887]
**Describe the bug**
When attempting to update a channel using the `updateChannelPartial` method, we get the following error:

```
ChatNetworkError http status 400, stream error code 4: UpdateChannelPartial failed with error: "id `messaging:cae497bd-5374-6b3d-d3a1-f9595359a2f8` is not a valid channel id. a-z, 0-9 and _- are allowed."
```

The Channel object is created with the id `cae497bd-5374-6b3d-d3a1-f9595359a2f8` so the SDK seems to be prefixing the `Channel.cid` with `messaging:` underneath the hood.

**SDK version**
- io.getstream:stream-chat-android-ui-components:4.9.2

**To Reproduce**
1. Create a channel
2. Update the channel using `updateChannelPartial`. Be sure to use the `Channel.cid`
3. See error above

**Expected behavior**
The channel should update without erroring

**Device:**
 - Google Pixel 4

**Comment by ogkuzmin** [comment]
@SeanOThomas Thanks for submitting the issue! I tried to reproduce it, and for me, it works fine. Right now this `updateChannelPartial ` is available via the low-level client library. For that you should get `ChannelClient`, could you show your code snippets where you obtain `ChannelClient` and make `updateChannelPartial`

**Comment by SeanOThomas** [comment]
Sure, I'm basically listening for the first message, then adding a started flag to the extra data. 

```
class ChatViewModel @Inject constructor(
    private val chatRepository: ChatRepository,
) : ViewModel() {

    fun init(channelId: String) {
        viewModelScope.launch {
            val result = ChatDomain.instance().watchChannel(channelId, 2).await()
            if (result.isSuccess) {
                result.data().messages.collect {
                    LogUtil.log(Log.INFO, TAG, "message size: ${it.size}")
                    when{
                        it.size == 1 && result.data().channelData.value.isStarted().not() -> {
                            // the channel has not been started
                            LogUtil.log(Log.INFO, TAG, "start channel")
                            chatRepository.startChannel(channelId)
                        }
                    }
                }
            } else {
                throw IllegalStateException("there's not a channel to watch")
            }
        }
    }

    private fun ChannelData.isStarted() = extraData[IS_STARTED] == true

    companion object {
        private const val TAG = "ChatViewModel"
    }
}
```

That channel ID is the same one used on the chat screen. 

```
    companion object {
        private const val CID_KEY = "key:cid"

        fun newIntent(context: Context, channel: Channel): Intent =
            Intent(context, ChatActivity::class.java).putExtra(CID_KEY, channel.cid)
    }
```

**Comment by SeanOThomas** [comment]
Repository code
```
    override suspend fun startChannel(hashedChannelId: String) {
        updateChannel(
            hashedChannelId, mapOf(
                IS_STARTED to true
            )
        )
    }

    private suspend fun updateChannel(hashedChannelId: String, mapToAdd: Map<String, Any>) {
        LogUtil.log(Log.INFO, TAG, "updateChannel: $mapToAdd, id: $hashedChannelId" )
        val result = streamClient.updateChannelPartial(
            MESSAGING,
            hashedChannelId,
            mapToAdd
        ).await()
        if (result.isSuccess) {
            LogUtil.log(Log.INFO, TAG, "updated channel")
        } else {
            LogUtil.log(Log.ERROR, TAG, "failed to update channel: ${result.error()}")
        }
    }
    ```

**Comment by ogkuzmin** [comment]
@SeanOThomas actually what you name as `channelId` in your ViewModel isn't `channelId`, it's `Channel::cid`. It's required in invocation of `ChatDomain::watchChannel` and it works fine in your sample. CID is a combination of `channelType:channelId`. So for `updateChannelPartial ` you need to pass exactly `channelId` and `channelType`. 
You can obtain it from `ChannelController` which is result of `ChatDomain::watchChannel`

**Comment by tbarbugli** [comment]
@ogkuzmin the Swift SDK has a ChannelCID type (a String type alias) that validates the format, perhaps we can improve ease of use with typing here as well?
