### ISSUE TITLE
Inconsistency in library with documentation

### ISSUE THREAD

**Issue by Chikrix** [GetStream/stream-chat-android#190]
In the documentation, it shows how we could do something(s) which isn't available in the dependency. For example, I'm not able to update channel name or add/remove members, but the documentation shows how to do this. Please how can I go about implementing those?

**Comment by tschellenbach** [comment]
Which version of the library are you using..?

**Comment by Chikrix** [comment]
I'm using alpha version `com.github.getstream:stream-chat-android:2.2.0-alpha5`.

**Comment by Chikrix** [comment]
Found that it's been added in the latest stable version for adding/removing members.

**Comment by tschellenbach** [comment]
👍
