### ISSUE TITLE
How i can customize ChannelActionsDialogFragment theme color ?

### ISSUE THREAD

**Issue by MostafaAnter** [GetStream/stream-chat-android#1935]
**Describe the bug**
I have a different dark color than you use so each bottom sheet in my app use the same color except channel action
bottom sheet has no control to change the background color of the bottom sheet.

**SDK version**
- 4.10.0

**Screenshots**
![Screenshot 2021-02-08 at 13 45 42](https://user-images.githubusercontent.com/9489649/120894535-34f6be80-c619-11eb-8058-126fa972b10f.jpeg)

**Comment by JcMinarro** [comment]
Hello @MostafaAnter 
Thanks to reporting it, we are improving the customization of all internal views by themes, and it will be ready on the following versions

**Comment by adasiewiczr** [comment]
Hello @MostafaAnter,
We've released a new version with the fix mentioned above. You can check it [here](https://github.com/GetStream/stream-chat-android/releases/tag/4.12.0).
