### ISSUE TITLE
Memory Leak because of FileAttachmentsView

### ISSUE THREAD

**Issue by MostafaAnter** [GetStream/stream-chat-android#1936]
**Describe the bug**
When started to attach images files to chat memory had been leaked  
**SDK version**
- 4.10.0

**To Reproduce**
1. Go to the chat page
2. Click on the 
3. attache images
4. wait until images progress end
5. run leak canary and Dump Heap you will get a leak as you can see in my screen shots

**Screenshots**
<img src="https://user-images.githubusercontent.com/9489649/120908183-21bf0f80-c668-11eb-82db-90c10915379f.png" width="300">
<img src="https://user-images.githubusercontent.com/9489649/120908223-516e1780-c668-11eb-915a-5c4e0ef1c324.png" width="300">
<img src="https://user-images.githubusercontent.com/9489649/120908225-5d59d980-c668-11eb-9cd0-57d80e9521bc.png" width="300">
<img src="https://user-images.githubusercontent.com/9489649/120908228-60ed6080-c668-11eb-9737-579f33981e08.png" width="300">
<img src="https://user-images.githubusercontent.com/9489649/120908237-706ca980-c668-11eb-9754-e07d8e5bf58c.png" width="300">

**Comment by JcMinarro** [comment]
Hello @MostafaAnter 
We’re looking at this issue, thanks for reporting it

**Comment by bychkovdmitry** [comment]
Hello @MostafaAnter,
Sorry for the delayed response. We are giving higher priority to this issue and we will start making progress on it tomorrow.

**Comment by ogkuzmin** [comment]
@MostafaAnter this issue was fixed. Fixed new versions 4.15.1 is already available
