### ISSUE TITLE
Image preview page has a purple status bar color 🤔

### ISSUE THREAD

**Issue by MostafaAnter** [GetStream/stream-chat-android#1944]
**Describe the bug**
image preview page has an uncontrol purple status bar color I don't want to change or have control of changing status bar color but at least follow the same stream SDK scheme 

**SDK version**
- last and previous versions

**Expected behavior**
follow the same stream SDK scheme.

**Screenshots**
<img src="https://user-images.githubusercontent.com/9489649/121173784-7d9cba80-c859-11eb-8127-d66cfd7325de.png" width="300">

**Comment by JcMinarro** [comment]
Hello @MostafaAnter 

It is the default `colorPrimaryDark` declared by the default theme applied to this activity.
We are updating how themes will be configured on our SDK, but for now what you can do is override the one used on those activities.
You will need to declared the following activities in your AndroidManifest and assign a new Theme to them:
```
<activity
    android:name=".gallery.AttachmentGalleryActivity"
    android:theme="@style/StreamUiAttachmentGalleryActivityStyle"
    />
<activity
    android:name=".gallery.AttachmentMediaActivity"
    android:theme="@style/StreamUiAttachmentMediaActivityStyle"
    />
<activity
    android:name=".gallery.AttachmentActivity"
    android:theme="@style/StreamUiAttachmentActivityStyle"
    />
```
