### ISSUE TITLE
Message background overdraw 

### ISSUE THREAD

**Issue by elevenetc** [GetStream/stream-chat-android#195]
Performance of drawing message background might be improved. `Telegram` comparison is attached.
![Screenshot_20191021-013230](https://user-images.githubusercontent.com/1069159/67168283-3f603800-f3a3-11e9-91e2-436e6afaf953.jpg)
![Screenshot_20191021-013154](https://user-images.githubusercontent.com/1069159/67168282-3ec7a180-f3a3-11e9-8b93-da8ed7659fe3.jpg)

**Comment by tbarbugli** [comment]
any idea what we are doing wrong here?

**Comment by elevenetc** [comment]
Not yet, might be several reasons: from complicated view hierarchy to unnecessary  `onLayout/onDraw` calls.

**Comment by adrian09h** [comment]
I have tried to reduce complicated view hierarchy already.
Please check it again. ;)

**Comment by tschellenbach** [comment]
seems like the message layout could use more constraint layouts to reduce the depth.
