### ISSUE TITLE
How to handle push-notifications for stream-chat in 4.11.0?

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1968]
Hello, I have following questions.

#### 1.
What is the new way of calling following function? I used it to check if the message is for stream-chat or not. If stream-chat is not the *sender*, I can log such a message to be reviewed. Although, I think chat-sdk is only verifying specific-keys in data payload for it to be valid.
```
PushMessageSyncHandler(service).isStreamMessage(message)
```

#### 2.
[Updated chat documentation](https://getstream.io/chat/docs/android/push_android/?language=kotlin#handling-notifications-from-multiple-providers) mentions that I have to override `onFirebaseMessage(..)` and return `true` for remoteMessage to be handled by chat-sdk
```
class CustomChatNotificationHandler(context: Context, notificationConfig: NotificationConfig) : 
    ChatNotificationHandler(context, notificationConfig) { 
 
    override fun onFirebaseMessage(message: RemoteMessage): Boolean { 
        // Handle remote message and return true if message should be handled by SDK 
        return true 
    } 
}
```

But, the code in `ChatNotifications` suggests otherwise:
https://github.com/GetStream/stream-chat-android/blob/5084b1528f15530782648de559d58de6d55045d5/stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/ChatNotifications.kt#L79-L82

If I return `true`,  chat-sdk will ignore the message, right?

#### 3.
> CustomChatNotificationHandler.onFirebaseMessage(..)

Is this method only called when remote-message is valid for chat-sdk?

**Comment by adasiewiczr** [comment]
Hey @rupinderjeet, thanks for reporting that:
1. You can use `ChatClient.isValidRemoteMessage()` to check if the remote message can be handled by the SDK
2. You're right, it's a bug in our docs. I'll fix it, thanks!
3. Method should be always called, no matter if the remote message is valid for the SDK. However, if you return `false` - the message won't be processed if it's not valid for SDK.

One more important thing - make sure that `ChatClient` is initialized before push notification is being handled

**Comment by rupinderjeet** [comment]
Hi @adasiewiczr 

Thank you for the information. 

About verifying `ChatClient`'s initialization, I am using `ChatClient.isInitialized`. I think this is better than using `try-catch` because I have nothing to do if client is not initialized.
