### ISSUE TITLE
Wrong information in release-log for v4.11.0?

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1969]
Hello, I think following information is wrong in release-log.

> Deprecated ChatClient.handleRemoteMessage

> Added ChatNotificationHandler::getFirebaseInstallations() method in place of > > ChatNotificationHandler::getFirebaseInstanceId().
It should be used now to fetch Firebase token in the following way: handler.getFirebaseInstallations()?.getToken(true)?.addOnCompleteListener {...}.

Please help me by confirming so that I can finish updating to latest chat-sdk.

**Comment by samiuelson** [comment]
Indeed,  this was a mistake on our side. The [release](https://github.com/GetStream/stream-chat-android/releases/tag/4.11.0) notes are now updated with the corrected information. The release is ready to use!
