### ISSUE TITLE
ChatClient throws IllegalStateException when internet is not available

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1971]
Code:
```
ChatClient.instance()
	.channel(request.channelId)
	.query(QueryChannelRequest())
	.execute()
```

If I call this method after disabling internet, I receive following error:
> java.lang.IllegalStateException: Failed to perform job. Waiting for set user completion was too long. Limit of attempts was reached.

I think `ChatClient` should throw a connection exception instead, something like `UnknownHostException` or `SocketTimeoutException`. This will help me show correct error-message to user.

**Comment by ogkuzmin** [comment]
Hey @rupinderjeet. It's not exactly because we don't have a connection. For channels querying, we need to have established connection with user credentials. We have the feature when you just set user and immediately after queried channels without awaiting of set user to be complete. It reduces annoying callback invocation and to write code in more synchronous imperative way. 
So when you disabled the internet connection you lost user connected to our BE and you can't perform queries

**Comment by rupinderjeet** [comment]
Hello @ogkuzmin 

I am sorry I didn't understand.

I am able to query a channel with channel-id using above code. Here's what is happening:

1. Execute `ChatClient#query(QueryChannelRequest)` > result is success
2. Pull down status bar, disable internet.
3. Execute `ChatClient#query(QueryChannelRequest)` > result is above exception
4. Pull down status bar, enable internet.
5. Execute `ChatClient#query(QueryChannelRequest)` > result is success

> Waiting for set user completion was too long. Limit of attempts was reached.

This message suggests that `setUser` hasn't completed, which means I am not authenticated to chat, right? But, I am able to receive channel if I enable internet without setting user again.

> when you disabled the internet connection you lost user connected to our BE and you can't perform queries

Do you mean to say that we need an active chat-connection (socket?) for query-execution? But, isn't `ChatClient` using Retrofit for these API calls?

I think, if this is the case, I should just wrap every ChatClient usage with `ChatClient#isSocketConnected()` and throw relevant exceptions myself.

**Comment by ogkuzmin** [comment]
@rupinderjeet Yes, you're right.  Despite making a request through Retrofit we require an active socket connection to make such calls as `ChatClient#query(QueryChannelRequest)`.
