### ISSUE TITLE
Is there a way to customize how we show max-length error in MessageInputView?

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1972]
![Screenshot 2021-06-11 at 5 31 31 PM](https://user-images.githubusercontent.com/14011726/121685175-3cb4d800-cadd-11eb-92ba-bce40c737aa9.png)

I am trying to customize this error UI. As of now, chat-sdk is setting `error` on `EditText` in `MessageInputFieldView`. I couldn't find a way to override this, or listen to changes in text input.

Our user-feedback suggests that it is hard to adjust the text when the error message is always displayed. They can't choose what to remove, and end-up using external app to edit the text and ensure the text-limit.

**Comment by rupinderjeet** [comment]
It will be awesome if I can set a listener on when the error is triggered, this will help me show my own TextView. If the listener doesn't consume the trigger, you can continue showing the error as you do now.

or a listener on when the letter-count changes, but even then, I will need to override the default error logic.

**Comment by adasiewiczr** [comment]
Hey @rupinderjeet, thanks for reporting that. We'll consider adding the possibility to customize it in the following releases.

**Comment by adasiewiczr** [comment]
Hey @rupinderjeet, the future request was added in the PR mentioned above and will be shipped in an upcoming release.

**Comment by adasiewiczr** [comment]
Hey @rupinderjeet,
We've released a new version with the fix mentioned above. You can check it [here](https://github.com/GetStream/stream-chat-android/releases/tag/4.14.0).
