### ISSUE TITLE
Sample app: markdown parsing issue for block code

### ISSUE THREAD

**Issue by Bogdan-D** [GetStream/stream-chat-android#198]
When testing sample app I've found some issues with markdown parsing.

To reproduce it I've copied markdown source from https://markdown-it.github.io/

As you can see there is problem starting from section `Code`. 

![Screenshot_20191021-124735_ChatSample](https://user-images.githubusercontent.com/7849405/67201265-3785af80-f406-11e9-8ca6-b8405b7ed45f.jpg)
![Screenshot_20191021-124702_Chrome](https://user-images.githubusercontent.com/7849405/67201269-3a80a000-f406-11e9-9269-51ef75778e36.jpg)

**Comment by adrian09h** [comment]
fixed
