### ISSUE TITLE
onNewToken is not implemented

### ISSUE THREAD

**Issue by elevenetc** [GetStream/stream-chat-android#201]
```
@Override
public void onNewToken(String token) {
   Log.d(TAG, "Device TokenService: " + token);
}
```
When new token is received it must be delivered to backend. That's a rare case, but if it's not implemented users might miss push messages.

**Comment by tbarbugli** [comment]
We should add this to sample apps' BaseApplication class, right?

**Comment by elevenetc** [comment]
No, it's a method of `CCFirebaseMessagingService: FirebaseMessagingService`.
By the way, I just realised that `CCFirebaseMessagingService` is not a part of `SDK`. Shouldn't we include it into SDK? Delivering notifications sounds like a core feature.
It contains message parsing:
```
title = remoteMessage.getData().get("title");
sendNotification(remoteMessage.getData().get("body"), title);
```
And that's implementation details, I would not expose it to developers for now, format of messages might  change.
And also we then need to support extra documentation of how to implement notifications.
