### ISSUE TITLE
JWTAuth error on setting user. 

### ISSUE THREAD

**Issue by Chikrix** [GetStream/stream-chat-android#207]
Whenever I set a user, I get an error code `5` with the message `JWTAuth error: json: cannot unmarshal object into Go struct field StreamJWTClaims.exp of type int64`. I have no idea what could be the cause or how I can resolve it. I believe I'm using a valid token because I'm making the request to get the token and use the `tokenSuccessListener.onSuccess` to get my token while setting the user. Any idea how I can resolve this?

**Comment by tschellenbach** [comment]
@tbarbugli

**Comment by tbarbugli** [comment]
@Chikrix can you share the token here? you can redact a token by stripping out the last section of the token.

`somevery.weirdbase64.token` -> `somevery.weirdbase64.`

**Comment by tbarbugli** [comment]
also, it would be great if you could share the code you used to generate the token. Looking at the error I'd say something is off with the `exp` field

**Comment by Chikrix** [comment]
@tbarbugli here's my code snippet
```
val streamClient: Client by lazy { StreamChat.getInstance(application) }
myService.fetchAuthToken()
    .subscribe({ authToken ->
        val user = User(currentMemberId)
        streamClient.setUser(user, {tokenSuccessListener ->
             tokenSuccessListener.onSuccess(authToken)
        })
    }, { ... })

streamClient.onSetUserCompleted(object: ClientConnectionCallback {
    override fun onSuccess(user: User) {
         ...
    }
      
     // Where I get the error 
     override fun onError(errMsg: String?, errCode: Int) {
              Log.exception(IllegalStateException("Message $errMsg with code $errCode"))      
     }
})
```

**Comment by tbarbugli** [comment]
@Chikrix `exp` must be a timestamp (ie. something like this ```Carbon::now()->addMinutes(1440)->timestamp```) ;  @pterk can you add docs and a test to the PHP client?

**Comment by Chikrix** [comment]
Thanks @tbarbugli . Would try that.

**Comment by pterk** [comment]
FTR, a note, a check and a test were added to the PHP client so it should be easier to debug this in future.
