### ISSUE TITLE
SDK Modularity

### ISSUE THREAD

**Issue by elevenetc** [GetStream/stream-chat-android#209]
Do we need modularity? I was thinking at least about few parts of SDK which might be useful to have optionally outside of the core:
- `RxJava` adapters instead of callbacks. Callbacks look inconvenient and outdated especially in Kotlin.
- `Storage`. Do developers need to have encrypted storage? Or just their own implementation? Do they even need to have offline storage?
- Currently we support `MVVM`, but unfortunately on Android developers use `MVI`, `MVP`, `MVP`, `MVC` and some other architecture approaches.
- Analytics
- Debug logging
```kotlin
val client = Client.Builder()
    .add(Storage())
    .add(RxAdapter())
    .add(Logger())
    .add(Analytics())
    .build()
```
```groovy
implementation 'com.github.getstream:stream-chat-rx-storage:3.0.0'
implementation 'com.github.getstream:stream-chat-rx-adapters:3.0.0'
implementation 'com.github.getstream:stream-chat-viewmodel:3.0.0'
implementation 'com.github.getstream:stream-chat-presenter:3.0.0'
```
Advantages of modular architecture are obvious: testability, development independence, flexibility, release frequency. Disadvantages are also exist: development alignment, extra support resources.

**Comment by tschellenbach** [comment]
- on/off seems fine for offline storage. don't think we need anything more complex
- CDN backend is already configurable

- RxJava and Kotlin are huge, we should try to support both (first priority is making sure we work well with the current google/livedata setup, but good to keep in mind that we want to support those 2 eventually)

**Comment by tschellenbach** [comment]
https://github.com/square/retrofit/tree/master/retrofit-adapters/rxjava2

**Comment by tschellenbach** [comment]
https://github.com/android/architecture-components-samples/tree/master/BasicRxJavaSample

**Comment by adrian09h** [comment]
I completely agree with @tschellenbach 's comment.

**Comment by bevzaanton** [comment]
I think @elevenetc is right. Switching to RxJava significantly simplified and reduced the amount of code. Moreover, we need to finish working with an offline database where AsyncTasks are currently used what is not a good approach.
Also now a big problem is the weird system of dependency classes. It is a bit complicated and not testable now. I think using Dependency Injection could help a lot. Including the transition to a modular system.
