### ISSUE TITLE
[Compose] - Sort, organize, rename string resources

### ISSUE THREAD

**Issue by zsmb13** [GetStream/stream-chat-android#2104]
Look at the UI Components strings for structure, e.g. everything prefixed with the name of the relevant component, no generic strings like "Yes"

https://github.com/GetStream/stream-chat-android/blob/main/stream-chat-android-ui-components/src/main/res/values/strings_message_list.xml

**Comment by filbabic** [comment]
Closing this issue as it's an ongoing process - we've already started applying it, will be more consistent in the future!
