### ISSUE TITLE
[Compose] - Fix image file thumbnails in file lists

### ISSUE THREAD

**Issue by zsmb13** [GetStream/stream-chat-android#2106]
We can reuse this kind of logic https://github.com/GetStream/stream-chat-android/blob/e5c311a9aad6c74c5cc33c1a83c77255a6bdc509/stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/internal/AttachmentUtils.kt#L26_L50

**Comment by filbabic** [comment]
I think this one is resolved by #2244 @zsmb13.

Can you verify so we can close this ticket?

**Comment by zsmb13** [comment]
Yup, this is solved already!
