### ISSUE TITLE
[Compose] - Image Preview 

### ISSUE THREAD

**Issue by petyosi** [GetStream/stream-chat-android#2108]
- [ ] Support sharing an image
- [ ] With multiple images, support gestures for navigation
- [ ] Panning, zooming
- [ ] Gestures for dismissing, if applicable and conventional
- [ ] Additional actions (say, download to the device)
- [ ] Navigate back to the message in the chat
- [ ] Ability to scroll to the image 

Use the classic Android gallery and our Figma as a guideline.

**Comment by filbabic** [comment]
Closing this one off as it's been covered in #2120
