### ISSUE TITLE
Research Markdown support

### ISSUE THREAD

**Issue by filbabic** [GetStream/stream-chat-android#2114]
Currently we're missing Markdown support in the Compose SDK.

We need to do more research on how to support MD OoB or if we need to build a custom solution.

**Comment by aldefy** [comment]
what does OoB stand for ?

while researching for compose had run into this article : https://www.hellsoft.se/rendering-markdown-with-jetpack-compose/

**Comment by filbabic** [comment]
OoB - out of the box (OotB I guess :shrug:).

Nicely done - we can do more research when we get around to it but this seems like a good starting point.

**Comment by filbabic** [comment]
Closing this item as it's been a long time and still no markdown support.
