### ISSUE TITLE
`ChatClient::pinMessage` deletes text content from the message

### ISSUE THREAD

**Issue by xzhorikx** [GetStream/stream-chat-android#2129]
**Describe the bug**
Calling `ChatClient::pinMessage` causes message to empty its text content. 

* After calling `ChatClient::pinMessage` a client receives `io.getstream.chat.android.client.events.MessageUpdatedEvent`. Its `Message::text` field is empty. (`text=""`)
* Whenever `QueryChannelRequest().withMessages(...)` is called all previously pinned messages have `text=""` as its content.

It seems like the 'pin message' request empties the text content of the message on GetStream's end, meaning it's not the `MessageUpdatedEvent` that has incorrect content, but rather the whole message content just disappears in the database.

**SDK version**
- 4.8.0

**To Reproduce**
1. Create a channel
2. Start observing channel events in Flow
```
    suspend fun observeEvents(cid: String): Flow<ChatEvent> {
        client.channel(cid).watch().asDeferred().await()
        return callbackFlow {
            val subscription = client.channel(cid).subscribe { event ->
                // Setup a breakpoint here to check contents of the event
                sendBlocking(event)
            }
            awaitClose { subscription.dispose() }
        }.onCompletion { client.channel(cid).stopWatching().asDeferred().await() }
    }
```
3. Send a text message to the channel using `ChatClient::sendMessage`
4. Save the `Id` of the sent message
5. Make sure that flow from `observeEvents` fired with the `NewMessageEvent` event and its text content is not empty
6. Pin the message by calling
```
val message = Message(id = messageId)
client.pinMessage(message, expirationDate = null).asDeferred().await()
```
7. Make sure that flow from `observeEvents` fired with the `MessageUpdatedEvent` event and its text content is empty

**Expected behavior**
Calling `ChatClient::pinMessage` expected to only change a `isPinned` field to `true`

**Device:**
 - Vendor and model: Samsung S6, Sony Xperia 10 plus
 - Android version: 6.0.1; 10;

**Screenshots**
Not applicable

**Comment by bychkovdmitry** [comment]
Hello @xzhorikx

Thank you for reporting this. Indeed, the `ChatClient::pinMessage` method is not very convenient to use. Internally, it fully replaces the message contents on the backend. As a result, in the example below the message text is lost:

```kotlin
val message = Message(id = messageId) // full message object with all the fields is expected here
client.pinMessage(message, expirationDate = null).asDeferred().await()
```

We've improved the pin related methods to use "partial" message updates in this PR: https://github.com/GetStream/stream-chat-android/pull/2135 We will ship the improvement with the next release.

**Comment by xzhorikx** [comment]
@bychkovdmitry thank you for the clarification. We've updated our codebase to include the `text` parameter in the `Message` object constructor and it seems to work as expected.

PS `ChatClient::unpinMessage` has a similar issue: `text` parameter needs to be passed, otherwise, it disappears upon unpinning.

**Comment by adasiewiczr** [comment]
Hey @xzhorikx,
We've released a new version with the fix mentioned above. You can check it [here](https://github.com/GetStream/stream-chat-android/releases/tag/4.15.1).
