### ISSUE TITLE
Introduce element transitions and animations

### ISSUE THREAD

**Issue by petyosi** [GetStream/stream-chat-android#2139]
Adding a certain amount of movement to elements appearing/disappearing drastically improves the usability and the perception of the UI. [The Material article](https://material.io/design/navigation/navigation-transitions.html) is a good starting point.

**Comment by filbabic** [comment]
Discuss with the core Android team if someone has ideas on what we can implement.

**Comment by filbabic** [comment]
Closing as a good number of these have been implemented in the sample app. We don't want to push animations on our users, as they might not like the behavior and enabling/disabling it is very dirty (code-wise).
