### ISSUE TITLE
Getting error while upgrading SDK 4.15.1

### ISSUE THREAD

**Issue by bibinkrishnan** [GetStream/stream-chat-android#2151]
**Describe the bug**
Im getting error while upgrading io.getstream:stream-chat-android-ui-components: from 4.10.0 to 4.15.1. How can I resolve it?

**SDK version**
- 4.15.1

**Comment by ogkuzmin** [comment]
@bibinkrishnan Hello!
What kind of error do you have?

**Comment by bibink874** [comment]
All the getstream imports are in red color
![Capture](https://user-images.githubusercontent.com/82039830/128364037-eb6da5c1-9b63-420d-9cdb-663ca8d2f523.PNG)

**Comment by bibinkrishnan** [comment]
Hi Can you give a help to solve this?

**Comment by ogkuzmin** [comment]
@bibink874 @bibinkrishnan  Does it still happen for you? Could be a temporary issue with release. It works for me

**Comment by ogkuzmin** [comment]
Please also clean cache of your IDE, restart and resync Gradle dependencies

**Comment by bibinkrishnan** [comment]
updated the android studio to latest solved this issue, Thanks
