### ISSUE TITLE
Support attachment file type / mime type app configuration

### ISSUE THREAD

**Issue by petyosi** [GetStream/stream-chat-android#2166]
Those settings are accessible the /app endpoint. [The settings are documented in the REST API. ](https://getstream.io/chat/docs/other-rest/app_setting_overview/#file-uploads)

Based on that, the attachment pickers should act in the following way. up to the limitations of the platform:

hide or display as disabled (grayed out) the files which are not valid according to the specified settings, so that the user cannot select them. 

if that's not possible, display an informative and concrete error message and remove the invalid images/files after the user confirms their selection. Work with Francesco Mastrogiacomo on the matter.

At any case, the SDK should do the best possible actions to avoid sending files that are not going to be accepted by the backend. 

- [ ] Fetch available/blocked types and extensions from API.
- [ ] Filter out files which are blocked.
- [ ] Decouple this behavior to be reused in UI Components / Compose.

**Comment by filbabic** [comment]
@MarinTolic Can you please check with @adasiewiczr if we support this API call already?

Thanks!

**Comment by MarinTolic** [comment]
> @MarinTolic Can you please check with @adasiewiczr if we support this API call already?
> 
> Thanks!

We don't have it currently but it is slated for implementation.
That means this task is blocked until the core team finishes implementing it on their end.

Related core GitHub Issue can be seen here: https://github.com/GetStream/stream-chat-android/issues/2877
