### ISSUE TITLE
Notification : Not able to recieve/parse the extra when notification is clicked and activity is opened .

### ISSUE THREAD

**Issue by VyasPM** [GetStream/stream-chat-android#2181]
**Describe the bug**
I've Implemented the Notification flow as described and I am receiving notification also upon clicking the  notification the mentioned activity is also opening but the extra i am sending is not getting received 

**SDK version**
- io.getstream:stream-chat-android-client:4.11.0

**To Reproduce**
1. Send message 
2. Click on notification Activity mentioned will open up
3. Try to fetch the parameters send from the Intent ,observe null is received .

**Expected behavior**
When the parameters are passed from intent then they should be received as they are.  

**Device:**
 - All the Devices
 - Android version: [e.g. 9,10]

** Implementation **

1) Manifest 

  ```
    <activity
            android:name="HomeActivity"
            android:screenOrientation="portrait"
            android:theme="@style/AppTheme"
            android:windowSoftInputMode="stateHidden|adjustPan">
            <intent-filter>
                <action android:name="OPEN_ACTIVITY_1" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>
  
```     
```
<service
            android:name="io.getstream.chat.android.client.notifications.ChatFirebaseMessagingService"
            android:exported="false"
            >
            <intent-filter android:priority="-2" >
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
```

2) ChatInitializer

```
fun init(apiKey: String) {
        val notificationConfig =
            NotificationConfig(
                firebaseMessageIdKey = "message_id",
                firebaseChannelIdKey = "channel_id",
                firebaseChannelTypeKey = "channel_type",
                smallIcon = R.mipmap.ic_launcher
            )
        val notificationHandler = SampleNotificationHandler(context, notificationConfig)
        val logLevel = if (BuildConfig.DEBUG) ChatLogLevel.ALL else ChatLogLevel.NOTHING
        val client = ChatClient.Builder(apiKey, context)
            .loggerHandler(FirebaseLogger)
            .notifications(notificationHandler)
            .logLevel(logLevel)
            .build()

        val domain = ChatDomain.Builder(client, context)
            .userPresenceEnabled()
            .offlineEnabled()
            .build()
    }
```

3) SampleNotificationHandler 

```
override fun getNewMessageIntent(
        messageId: String,
        channelType: String,
        channelId: String
    ): Intent {
        val intent = Intent(context, HomeActivity::class.java)
        intent.putExtra(EXTRA_CHANNEL_ID, channelId)
        intent.putExtra(EXTRA_CHANNEL_TYPE, channelType)
        intent.putExtra(EXTRA_MESSAGE_ID, messageId)
        return intent
    }
```

4) HomeActivity 
 ```
val channelId = intent?.getStringExtra(EXTRA_CHANNEL_ID)
            val channelType = intent?.getStringExtra(EXTRA_CHANNEL_TYPE)
            val messageId = intent?.getStringExtra(EXTRA_MESSAGE_ID)
```

In this HomeActivity I am trying to fetch channelId, ChannelType and MessageId ,can you please guid me through what is wrong here and how would i get the desired params.

**Comment by adasiewiczr** [comment]
Hey @VyasPM,
the code looks correct. One small thing - you don't have to redeclare our  `ChatFirebaseMessagingService ` in `AndroidManifest` - it should be automatically included in the merged manifest, but this shouldn't be a problem.
Did you try to add additional flags to the intent created inside `getNewMessageIntent` (`flags = Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TASK`) just to be sure that you don't create new Activity after clicking on notification?
Could you tell me if you see any errors in the Logcat with `Chat:` prefix?

**Comment by VyasPM** [comment]
@adasiewiczr 
Hello , 
Thanks for the quick reply , 
1) I have commented the ChatFirebaseMessagingService redeclaration in the manifest , however these are the some tags i am still using ,please let me know if I've to comment this out too
  ```
 <meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@drawable/ic_charge_notification_icon" />

        <meta-data
            android:name="com.google.firebase.messaging.default_notification_color"
            android:resource="@color/colorAccent" />
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_channel_id"
            android:value="@string/default_notification_channel_id" />
```
2) No, I haven't used any additional flag to the intent .

```
class SampleNotificationHandler(context: Context, notificationConfig: NotificationConfig) :
    ChatNotificationHandler(context, notificationConfig) {

    override fun getNewMessageIntent(
        messageId: String,
        channelType: String,
        channelId: String
    ): Intent {
        val intent = Intent(context, HomeActivity::class.java)
        intent.putExtra(EXTRA_CHANNEL_ID, channelId)
        intent.putExtra(EXTRA_CHANNEL_TYPE, channelType)
        intent.putExtra(EXTRA_MESSAGE_ID, messageId)
        return intent
    }

}
```
Logcat Error 

```
E/Chat:Events: onFailure ChatNetworkError http status -1, stream error code 1002: Server closed connection
W/FirebaseMessaging Notification Channel set in AndroidManifest.xml has not been created by the app. Default value will be used.
E/Chat:Client: Failed to connect user. Please check you don't have connected user already
```

**Comment by adasiewiczr** [comment]
It seems there were some problems with connecting the user.
Are you able to see message text inside notification or rather generic `You've received new message` text?
Where are you calling `ChatInitializer::init` and `connectUser` methods?

**Comment by VyasPM** [comment]
Hello, 
Regarding Connection yes it seems there is some problem may be i am trying connect user multiple time will refactor this issue , but despite of connect user issue I am able to chat properly every message and attachments are working fine, Also I am getting proper notification too , even clicking the notification does opens HomeActivity which is perfect as per my requirement , the only thing I am facing is the three parameters are getting null value and because of it further app logic/flow  remains pending.
please refer to the attachment of notification getting displayed properly 
![Screenshot 2021-08-11 at 9 24 08 AM](https://user-images.githubusercontent.com/88429762/128967741-31854504-74d6-4fe4-9497-7bee82e0e610.png)

**Comment by samiuelson** [comment]
Hi @VyasPM, did you manage to solve the issue? Let me know if you need any further help!

**Comment by bychkovdmitry** [comment]
Hello @VyasPM 
Closing the issue for now. Feel free to reopen if you are still experiencing the issue.
