### ISSUE TITLE
User with id 'me'(probably for all id) doesn't update in table when user.updated event arrived. -> outdated user data will overwrite data

### ISSUE THREAD

**Issue by workspace** [GetStream/stream-chat-android#2197]
**Describe the bug**
user with id 'me' doesn't update in table when user.updated event arrived. 
(user's data is changed by our backend.)

### 1. user.updated event arrived
![image](https://user-images.githubusercontent.com/7759511/129032877-803417b9-cff4-4852-9aec-72b516e9f2ed.png)
### 2. user is not updated in table
![image](https://user-images.githubusercontent.com/7759511/129033440-db9b229d-0d72-4bf4-bac5-5157a94149a5.png)
### 3. then... client try to sync outdated data when socket reconnected
![image](https://user-images.githubusercontent.com/7759511/129033850-70c6cbe9-0c9f-410f-a54f-060045c1c5d2.png)

**SDK version**
- 4.14.2 ~ 4.15.1

**To Reproduce**
1. change user data with stream api
2. check user table (via Android Studio inspector) -> user is not updated
3. reconnect socket (via ChatClient's lifecycle observer) -> outdated user data is overwritten.

**Expected behavior**
user data is sync well 

**Device:**
 - Vendor and model: Samsung Galaxy S21 Ultra
 - Android version: 11

**Comment by workspace** [comment]
Here is my suggestion.

### Handle `UserUpdatedEvent`
https://github.com/GetStream/stream-chat-android/blob/main/stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/event/EventHandlerImpl.kt#L155
```
(when user.id == currentUser.id)
domainImpl.updateCurrentUser(event.user)
```

**Comment by adasiewiczr** [comment]
Hey @workspace, thanks for reporting that. We'll investigate this

**Comment by adasiewiczr** [comment]
Hey @workspace , 
We've released a new version with the fix mentioned above. You can check it [here](https://github.com/GetStream/stream-chat-android/releases).
