### ISSUE TITLE
[Improvment] Compose - Change MessageComposerViewModel buildNewMessage to be public API

### ISSUE THREAD

**Issue by aldefy** [GetStream/stream-chat-android#2214]
**Describe the bug**
The new api in  `MessageComposerViewModel` has an `internal` scope on the function :  buildNewMessage 

This should be public function if the client app for the SDK needs to capture the `message` and then send 
Contract for `sendMessage` has changed too 

**SDK version**
- 4.16.0

**To Reproduce**
1. Go to `MessageComposerViewModel` check the function `buildNewMessage` 

**Expected behavior**
The new mechanism to `sendMessage` should have `buildNewMessage` exposed too if the client wishes to customize

**Comment by filbabic** [comment]
Not required after all.
