### ISSUE TITLE
[Compose] - Adjust scroll-to-bottom button to match design

### ISSUE THREAD

**Issue by zsmb13** [GetStream/stream-chat-android#2218]
We currently have a placeholder implementation for the scroll-to-bottom button in the message list
![image](https://user-images.githubusercontent.com/12054216/129360970-28276484-6328-4fdc-b50a-df41809abed5.png)

Replace this with a FAB as per the design.

**Comment by filbabic** [comment]
Design: https://www.figma.com/file/ekifwChR9tR7zRJg1QEzSM/Chat-Sample-App?node-id=12097%3A4295

**Comment by filbabic** [comment]
Change from a bottom bubble to a Floating Action Button (as per the design).

Add a badge to show how many new messages there are.
- Show # of messages from other people (unread count)
- Explore the core SDK for this logic

**Comment by zsmb13** [comment]
Logic in the UI Components SDK is here https://github.com/GetStream/stream-chat-android/blob/main/stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/internal/MessageListScrollHelper.kt
