### ISSUE TITLE
[Compose] - Enable customization of enforce unique for reactions

### ISSUE THREAD

**Issue by filbabic** [GetStream/stream-chat-android#2225]
We need to expose configuration for reactions, which enables or disables users from enforcing unique reactions in their apps.

**Comment by AhmedNTS** [comment]
You can create a custom extension for MessageListViewModelBinding.kt and change the enforcing para FOR NOW

**Comment by filbabic** [comment]
Hey @AhmedNTS !

Thanks for your input! This was actually a Compose SDK task and we don't use the `MessageListViewModelBinding` at all, because we have separate locations of where we keep this config.

That being said, this ticket should be closed, given that we've enabled a way to enforce unique reactions! :]
