### ISSUE TITLE
Unable to get some channel from ChatDomain.queryChannels

### ISSUE THREAD

**Issue by ping-anil** [GetStream/stream-chat-android#2226]
**Describe the bug**
Not getting all the channels using Android Ui Component
Following : https://getstream.io/chat/docs/sdk/android/ui/components/channel-list/

I am able to get complete list using
ChatClient.instance().queryChannels(query).await()

but while using Android UI Component (io.getstream.chat.android.ui.channel.list.ChannelListView) 
and ChatDomain some channels are missing from the list

 chatDomain.queryChannels(filter, sort, limit, messageLimit).execute() not providing list of all channels

**SDK version**
- io.getstream:stream-chat-android-ui-components:4.10.0

**To Reproduce**
Execute Statement -> chatDomain.queryChannels(filter, sort, limit, messageLimit).execute()

**Expected behavior**
Should get list of all channels

**Device:**
 - Multiple
 - Multiple

**Comment by tschellenbach** [comment]
Can you provide the API keys, user id, filter and sort to enable our team to replicate this issue?

**Comment by samiuelson** [comment]
Are you sure you're using the correct `userToken`, how are you generating it? Are channels visible at Stream Dashboard?

**Comment by ping-anil** [comment]
Key -> zyhzx9gcdvjq
User id-> 60eee49083ab09e5dbf731e5

// this method provide incomplete list
// a chanel is missing
fun someMethod(chatDomain: ChatDomain){

val filter: FilterObject = Filters.and(
    eq("type", "messaging"),
    Filters.`in`("members", listOf(user.id)),
)

val sort =QuerySort.desc("last_updated")
val messageLimit = 1
val limit = 30
val result = chatDomain.queryChannels(filter, sort, limit,
messageLimit).execute()


}


//this method works fine
// provide complete list
suspend fun getUserChannels(userId: String?,page:Int): Result<List<Channel>> {
    var limit = 30
    var skip = page*limit
    val query = QueryChannelsRequest(
        filter = Filters.and(
            Filters.`in`("members", listOf(userId ?: "")),
        ),
        offset = skip,
        limit = limit,
    ).apply {
        presence = true
    }
    return ChatClient.instance().queryChannels(query).await()
}

**Comment by ping-anil** [comment]
@samiuelson  only one channel is missing rest all is working

Channel is missing only when trying to fetch from Ui component
Please refer previous response

**Comment by samiuelson** [comment]
@ping-anil 
Recently we've made improvements to local channel filtering. Can you update to the latest [release](https://github.com/GetStream/stream-chat-android/releases)?

**Comment by samiuelson** [comment]
If you encounter the problem again after upgrading to 4.17.2. Please share a json response of the `Client.queryChannels()` call so that we can test `ChatDomain` against it. Json response can be found in the logs of the app's debug build variant.
