### ISSUE TITLE
  Transparent corners are displayed as black

### ISSUE THREAD

**Issue by thesyncim** [GetStream/stream-chat-android#224]
![image](https://user-images.githubusercontent.com/916501/67401069-82d6c400-f5a6-11e9-88b3-39272ccd965b.png)
![imgur-images-sample](https://user-images.githubusercontent.com/1069159/67573989-e0e7e080-f739-11e9-97ef-15547c4f36bc.png)

**Comment by elevenetc** [comment]
Reproduced on:
```
Stream SDK 1.10.1
Samsung Galaxy S8
Android version 7.0
```

**Comment by tbarbugli** [comment]
@elevenetc your link is not public

I can reproduce on my mobile as well:

Sony xperia z5 compact
Android 7.1.1

**Comment by elevenetc** [comment]
@tbarbugli the photo is high resolution actual user photo, so don't want to share it publicly. It should be available if you login into google drive with stream account.
