### ISSUE TITLE
[Compose] - Set up Crashlytics in the sample app

### ISSUE THREAD

**Issue by zsmb13** [GetStream/stream-chat-android#2243]
Track crashes via Crashlytics like in the UI Components sample app

**Comment by petyosi** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/14420'>Zendesk ticket #14420</a>:<br><br>Hi,

Thanks for reaching out. How can I help you here?

Best,
Ryan
<br><p><em><small>°°°</small></em></p>

**Comment by filbabic** [comment]
@zsmb13 I'm guessing we can close this one since it's done? :D
