### ISSUE TITLE
Ability to disable SDK logs

### ISSUE THREAD

**Issue by elevenetc** [GetStream/stream-chat-android#227]
Currently SDK has lots of logs and it could be inconvenient for developers to see their own logs. Possible solution is to have some method to enable logs and internal logger, which by default doesn't log anything:
```Kotlin
StreamChat.Builder()
  .enableLogs()
  .build()
```
```Kotlin

val logger = SilentStreamLogger()  

fun enableLogs(){
  logger = StreamLogger()
}
```

**Comment by tbarbugli** [comment]
sounds good to me, go for it!

**Comment by elevenetc** [comment]
Moved to Jira.
