### ISSUE TITLE
message order  change sometimes

### ISSUE THREAD

**Issue by spvince** [GetStream/stream-chat-android#2279]
**Describe the bug**
The order of message change in channel object. Sometimes first message is in first position in list and in the other time first message is in last position in list.

```         
ChannelListViewModelFactory(
            filter = and(eq(STREAM_FILTER_FIELD_TYPE, ModelType.channel_messaging), `in`(STREAM_FILTER_FIELD_MEMBERS, mSpUser?.id.toString())),
            sort = QuerySort<Channel>()
                .desc(Channel::hasUnread)
                .desc(Channel::lastMessageAt)
        )
``` 

**SDK version**
- 4.17.0

**To Reproduce**

**Expected behavior**
Always first message in first position

**Device:**
 - Vendor and model: pixel 2 xl
 - Android version: 11

**Screenshots**
**Order of message is good**
![Capture d’écran 2021-08-26 à 15 54 09](https://user-images.githubusercontent.com/63065444/130977525-b7d51181-b3e4-4601-9fae-4d99c8d47f14.png)

**Order of message is reversed**
![Capture d’écran 2021-08-26 à 15 55 54](https://user-images.githubusercontent.com/63065444/130977538-229def7e-e72d-4953-a0e0-11d9530f8f94.png)

**Comment by bychkovdmitry** [comment]
Hello @spvince,

Sorry for the delayed response. We were able to reproduce the issue and are investigating it. As a workaround, you can use the method to get the latest message from the new UI components (stream-chat-android-ui-components):

```kotlin
public fun Channel.getLastMessage(): Message? =
    messages.asSequence()
        .filter { it.createdAt != null || it.createdLocallyAt != null }
        .filter { it.deletedAt == null }
        .filter { !it.silent }
        .filter { it.user.isCurrentUser() || !it.shadowed }
        .filter { it.isRegular() || it.isSystem() }
        .maxByOrNull { it.getCreatedAtOrThrow() }
```
