### ISSUE TITLE
Resending media attachments is broken

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#2305]
I have encountered following bugs when sending multiple files (6):-
1. Files with more than 20 MB are sent in upload queue without size check, which never succeeds.
2. If one of the file fails to be uploaded, and you try to resend it, even the files with successful uploads are re-uploaded.
3. When resending a failed file, initial selection size (6) increases by the number of failed file upload count. This adds duplicate files to upload queue.

Reproduce:
1. Select 6 image files. One of them needs to be of memory size more than 20 MB.
2. Send them. File with large size fails, or never shows a non-zero progress.
3. Reopen messages page. Message shows that some files are uploaded, and some failed.
4. Resend failed file. All files are re-uploaded.
5.  File with large size fails to be sent again, along with others perhaps.
6. Reopen messages page. File count is no longer 6. Duplicate files appear in upload queue.

Proof:
https://user-images.githubusercontent.com/14011726/131992967-88f81636-95da-4213-8874-76891155b758.mp4

Expected Behaviour: Chill file uploading experience 🥶

v4.17.2
If I am doing something wrong, please let me know.

**Comment by ogkuzmin** [comment]
Hey @rupinderjeet !
Thanks for submitting this issue. I also reproduced this bug. We need some time to investigate it deeper. Will come back to you soon

**Comment by ogkuzmin** [comment]
This issue was related to the violation of max possible attachment size. We iterated over this use case and if you have such large attachments you'll see the alert about it. This fix will be available in our next version (we're going to release in the beginning of the next week)

**Comment by bychkovdmitry** [comment]
Hello @rupinderjeet 
We have released a new version that should fix your issue.
Could you check the [latest version](https://github.com/GetStream/stream-chat-android/releases/latest)?
