### ISSUE TITLE
[Compose] - How to compile a release

### ISSUE THREAD

**Issue by koval01** [GetStream/stream-chat-android#2309]
It's me again

I have a question how to assemble a messenger with its API token in the design - **stream-chat-android-ui-components-sample**?

**Comment by ogkuzmin** [comment]
Hello! @koval01 
Could you specify more exactly what is your question? 
**stream-chat-android-ui-components-sample** is open source sample based on our SDK using our **ui-components** library. The default appearance is available out-of-box in our **ui-components**.
Our compose components is the newest addition adoption this compose approach for UI and it's also built on top of our SDK. 
You can take a look to our website and find docs there. 
[This is docs related to our ui-components lib.](https://getstream.io/chat/docs/sdk/android/ui/overview/)
[And here docs for compose components](https://getstream.io/chat/docs/sdk/android/compose/overview/)

**Comment by koval01** [comment]
Hello again. I need you to give me instructions on how to build a messenger with my API key, in the same design as the provided sample - stream-chat-android-ui-components-sample. I am very little familiar with Android Studio, mobile development is new to me, so the documentation from your site does not help much for me.

**Comment by ogkuzmin** [comment]
@koval01 
Unfortunately we don't provide learning services for android development. You can follow [Google resources](https://developer.android.com/training/basics/firstapp) and [codelabs](https://codelabs.developers.google.com/) for that.
Also, we have the [tutorial](https://getstream.io/tutorials/android-chat/) with step-by-step guide how to create sample app based on our ui-component. And there is [compose tutorial](https://getstream.io/chat/compose/tutorial/).
If you want to get free API key you can register for free [here](https://getstream.io/try-for-free/)
