### ISSUE TITLE
unable to sort QuerySort<Member>().updated_at field

### ISSUE THREAD

**Issue by pinichi** [GetStream/stream-chat-android#2321]
Hello. getStream-team!  I'd like to sort MemberList  by `Member.updated_at`

I try this..
```kotlin
val chatDomain = ChatDomain.instance()

val result = chatDomain.queryMembers(
    cid = cid,
    offset = 0,
    limit = 100,
    sort = QuerySort<Member>().desc("updated_at")
).await()

result.onSuccess { memberList ->
  Log.d("memberList", memberList.toString)
}
```

Logging memberList

```
[Member(user=User(id=1, role=user, ..., createdAt=Thu Jun 10 14:20:46 GMT+09:00 2021, updatedAt=Mon Aug 02 10:59:19 GMT+09:00 2021, ...), 
Member(user=User(id=2, role=user, ..., createdAt=Mon Sep 06 20:48:01 GMT+09:00 2021, updatedAt=Mon Sep 06 20:50:31 GMT+09:00 2021, ...), 
Member(user=User(id=3, role=user, ..., createdAt=Thu Jun 10 14:20:25 GMT+09:00 2021, updatedAt=Wed Sep 01 17:44:13 GMT+09:00 2021, ...), 
Member(user=User(id=4, role=user, ..., createdAt=Thu Jun 10 14:21:06 GMT+09:00 2021, updatedAt=Thu Sep 02 11:47:39 GMT+09:00 2021, ...)]
```

my expectation: user2 -> user4 -> user3 -> user1
response(Logging): user1 -> user2 -> user3 -> user4

- Doesn't it support to queryMember() sorting by `updated_at` field? is it a bug?
(I can't find querySort.desc(Member::updatedAt) at [queryMembersTest.kt](https://github.com/GetStream/stream-chat-android/blob/f5e62f5811ac05e308b7b33aed3839e0079a7dff/stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/usecase/QueryMembersTest.kt) 

- You guys have any plan to support to sort memberList by User's online or offline?
(ex. sort group by online-member-group, offline-member-group) 

**SDK version**
- 4.17.3

**Comment by ogkuzmin** [comment]
1. Sorting works fine for me. The member class contains `updatedAt` field that it gets sorted, but member also contains user with similar field. I believe it is what you saw in your log.  Could you make this printing and insure that it works?
```kotlin
result.onSuccess { memberList ->
                memberList.forEach {
                    Log.d("MemberList", "member: name = ${it.user.name}, updatedAt = ${it.updatedAt}, user.updatedAt = ${it.user.updatedAt}")
                }
            }
```
2. I don't think that we're going support sorting on this attribute. Only locally we can do it, since in backend there is no such data if user online or offline

**Comment by adasiewiczr** [comment]
hey @pinichi,
I'm closing this issue. Feel free to reopen it if the issue still exists.
