### ISSUE TITLE
Provide search option which is absolutely necessary for an chat history 

### ISSUE THREAD

**Issue by anjuarevero** [GetStream/stream-chat-android#2334]
Describe the feature you'd like to see in the SDK
Provide search option which is absolutely necessary for an chat history . Need a search option to find an existing person from chat history , otherwise user need to scroll down and find out the person/message from older chat

**Comment by adasiewiczr** [comment]
Hey @anjuarevero,
Our SDK components library provides a `Search View` that can be used to search for different messages. You can find the docs [here](https://getstream.io/chat/docs/sdk/android/ui/components/search-view/).
We don't provide a standalone component for searching users, but our `ChatClient` exposes methods for [querying users](https://getstream.io/chat/docs/react/query_users/?language=kotlin) and [searching messages](https://getstream.io/chat/docs/react/search/?language=kotlin), so it should be possible to build your own component with the requested functionality. 
Let me know if you have any further questions.

**Comment by adasiewiczr** [comment]
Hey @anjuarevero,
I'm closing this issue. Feel free to open a new issue or discussion if you have any further questions.
