### ISSUE TITLE
Channel list not loading, Showing no channels available

### ISSUE THREAD

**Issue by JayeshMohan4** [GetStream/stream-chat-android#2335]
**Describe the bug**
I tried to open channel list activity from notification click. But after redirecting to Channel list. Its showing "No Channels Available" message. 

On Log its printing like below mentioned :

I/Chat:ChatDomain QueryChannelsController: Query with filter AndFilterObject(filterObjects=[EqualsFilterObject(fieldName=type, value=messaging), InFilterObject(fieldName=members, values=[id])]) failed, marking it as recovery needed

**SDK version**
- 4.17.3

**To Reproduce**
1. Receive a notification
2. Click on notification
3. Redirected to channel list page
4. Showing error " No Channels Available"

**Expected behavior**
Need to display channels

**Device:**
 - All Device

**Comment by adasiewiczr** [comment]
Hey @JayeshMohan4,
how are you initializing the SDK? Are you doing that in `Application` class?
Can you make sure that the user is connected before entering the `ChannelList` screen?

**Comment by JayeshMohan4** [comment]
Yes I am initializing SDK in application class. While I am going background the connection of user is disconnecting. Once I click the notification and going to channel list activity I logged like mentioned below

 Log.e("connection", String.valueOf(client.isSocketConnected()));

the connection result is false.

**Comment by JayeshMohan4** [comment]
I am getting all instance in channel list but not displaying any channels. user is connected as well.

**Comment by JayeshMohan4** [comment]
This is what I get on "**client.getCurrentUser()**"  when I minimise app and open app via click notification.

User(id=bkrishnan, role=, invisible=false, banned=false, devices=[], online=false, createdAt=null, updatedAt=null, lastActive=null, totalUnreadCount=0, unreadChannels=0, mutes=[], teams=[], channelMutes=[], extraData={})

Everything is empty, the user gets disconnected when I minimise app. So that the channel is not displaying in screen after I came from notification click.

Why the user is getting disconnected while minimising application?

**Comment by adasiewiczr** [comment]
Our SDK keeps the socket connection when the app is in the foreground and disconnects while in the background. The reconnection should be done automatically when returning to the foreground unless the app was killed.
Push notifications are only received when the socket is disconnected. You can read more about this [here](https://getstream.io/chat/docs/sdk/android/client/guides/push-notifications/).
If the app was killed, you need to make sure that `connectUser` was called before showing the channel list.

**Comment by JayeshMohan4** [comment]
App is not killed. Just goes to background.

**Comment by JcMinarro** [comment]
Hello @JayeshMohan4 
Could you share with us how you are initializing our ChatClient?
Are you calling it from your `App::onCreate` method?
Do you have any customization over the PushNotifications feature?
