### ISSUE TITLE
ChatUI ui-mode is broken !!

### ISSUE THREAD

**Issue by AhmedNTS** [GetStream/stream-chat-android#2345]
When I set "ChatUI.uiMode = UiMode.LIGHT" it sets the app uimode to Light but I lose clicks and touches on the MessagesListView component 

**SDK version**
- 4.11.3

**Comment by adasiewiczr** [comment]
hey @AhmedNTS,
thanks for reporting that. We'll check that and come back to you shortly

**Comment by samiuelson** [comment]
Hey 👋🏼 The new [release](https://github.com/GetStream/stream-chat-android/releases/tag/4.19.0) containing the fix is now available. Please check it and let us know if you have any issues.
