### ISSUE TITLE
Logical error: Messages with attachments should have another sync status

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#2346]
**Describe the bug**

This is a crash report from Crashlytics (34 crashes by 7 users).
```
Fatal Exception: java.lang.IllegalArgumentException
Logical error. Messages with attachments should have another sync status!

io.getstream.chat.android.offline.ChatDomainImpl.retryMessagesWithoutAttachments (ChatDomainImpl.kt:748)
io.getstream.chat.android.offline.ChatDomainImpl.access$retryMessagesWithoutAttachments (ChatDomainImpl.kt:134)
io.getstream.chat.android.offline.ChatDomainImpl$retryMessagesWithoutAttachments$1.invokeSuspend (Unknown Source:14)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:106)
kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely (CoroutineScheduler.kt:571)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask (CoroutineScheduler.kt:750)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker (CoroutineScheduler.kt:678)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run (CoroutineScheduler.kt:665)
```

**SDK version**
- 4.17.2

**To Reproduce**
This happens when user launches the app. Upon launch, I initialize `ChatClient` in `Application` class. (I have doubts about doing it here though). I am unable to reproduce it on my end.

**Expected behavior**
ChatClient is `initialized`.

**Device:**
 - Vendor and model: HUAWEI Y6 Pro (2019) (armeabi-v7a)
 - Android version: 9

**Screenshots**
NA

Additional Information:
Huawei Y6 Pro (2019) has appeared in #2333 as well

#### Also, do you use something like work-manager to resend failed messages?

**Comment by adasiewiczr** [comment]
hey @rupinderjeet,
thanks for reporting, we are going to check that.
We recommend initializing our SDK in the `Application` class.

**Comment by samiuelson** [comment]
Hey 👋🏼 The new [release](https://github.com/GetStream/stream-chat-android/releases/tag/4.19.0) containing the fix is now available. Please check it and let us know if you have any issues.
