### ISSUE TITLE
Unable to view pdf

### ISSUE THREAD

**Issue by bibinkrishnan** [GetStream/stream-chat-android#2359]
Hi I updated SDK to the latest 4.18.0, but still unable to view pdf, this is the url response, but I can able to download it.

https://docs.google.com/gview?embedded=true&url=https://us-east.stream-io-cdn.com/1116822/attachments/245b5f67-7cd5-4d6e-9d00-336039d05d7b.sample.pdf?dl=sample.pdf&Expires=1633082630&Signature=RJUyjmEezYc1nx1xQ2aMixgxtlGBscHo-rW9UgmknTKfq-BgJjh3rnnbtU4WS2Vp~CBdyHgpEmBbqhAqmm3EzxTY-SBpxezlm5xXDOoZkV7pEGCsog-AZWKA6gH4aINcX1nmmFHgBhuQ9WOJKvRiUixNY1n3MMmTdt9SB6m5he90WE-2lT7OEbVgSRlD99invaBp4dxZe51-Miob4ATulb~iuoGAOOm2Vxfaus2axGtxqv5-5LjuY7qPOprwuuwTmtE3Q2msRg1Ctm1oWCAUS65oXzEcU~26sXxi3u1ElUnODgXhll7K1pCWLVbctr6D3wGiPT2EA5YPIGFmeuz5Nw__&Key-Pair-Id=APKAIHG36VEWPDULE23Q

**SDK version**
- 4.18.0

![screenshot-2021-09-17_06 37 46 754](https://user-images.githubusercontent.com/17172496/133770195-99a35797-d9c5-4c13-a757-7e9663855c83.png)

**Comment by bibinkrishnan** [comment]
Url that Im getting from your sdk after uploading 
https://docs.google.com/gview?embedded=true&url=https://us-east.stream-io-cdn.com/1116822/attachments/245b5f67-7cd5-4d6e-9d00-336039d05d7b.sample.pdf?dl=sample.pdf&Expires=1633082630&Signature=RJUyjmEezYc1nx1xQ2aMixgxtlGBscHo-rW9UgmknTKfq-BgJjh3rnnbtU4WS2Vp~CBdyHgpEmBbqhAqmm3EzxTY-SBpxezlm5xXDOoZkV7pEGCsog-AZWKA6gH4aINcX1nmmFHgBhuQ9WOJKvRiUixNY1n3MMmTdt9SB6m5he90WE-2lT7OEbVgSRlD99invaBp4dxZe51-Miob4ATulb~iuoGAOOm2Vxfaus2axGtxqv5-5LjuY7qPOprwuuwTmtE3Q2msRg1Ctm1oWCAUS65oXzEcU~26sXxi3u1ElUnODgXhll7K1pCWLVbctr6D3wGiPT2EA5YPIGFmeuz5Nw__&Key-Pair-Id=APKAIHG36VEWPDULE23Q

here is the pdf

https://us-east.stream-io-cdn.com/1116822/attachments/245b5f67-7cd5-4d6e-9d00-336039d05d7b.sample.pdf?dl=sample.pdf&Expires=1633082630&Signature=RJUyjmEezYc1nx1xQ2aMixgxtlGBscHo-rW9UgmknTKfq-BgJjh3rnnbtU4WS2Vp~CBdyHgpEmBbqhAqmm3EzxTY-SBpxezlm5xXDOoZkV7pEGCsog-AZWKA6gH4aINcX1nmmFHgBhuQ9WOJKvRiUixNY1n3MMmTdt9SB6m5he90WE-2lT7OEbVgSRlD99invaBp4dxZe51-Miob4ATulb~iuoGAOOm2Vxfaus2axGtxqv5-5LjuY7qPOprwuuwTmtE3Q2msRg1Ctm1oWCAUS65oXzEcU~26sXxi3u1ElUnODgXhll7K1pCWLVbctr6D3wGiPT2EA5YPIGFmeuz5Nw__&Key-Pair-Id=APKAIHG36VEWPDULE23Q

**Comment by samiuelson** [comment]
Hi @bibinkrishnan, I confirm this is an issue in our SDK. We're working on fixing this. We'll keep you updated about the fix.

**Comment by Kravet** [comment]
Hello. I'm using version 4.25.0 and I still can't see the preview of the pdf file.

![image](https://user-images.githubusercontent.com/7354769/151421105-86e982bf-15dd-422c-ba82-9a107c32a47c.png)

![image](https://user-images.githubusercontent.com/7354769/151421291-02a776e7-09f5-4964-a294-f4bb6388e4ac.png)

My gradle dependecies:
```
//stream chat deps
    implementation "io.getstream:stream-chat-android-ui-components:4.25.0"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.4.0"
    implementation "io.coil-kt:coil:1.4.0"
    implementation 'androidx.activity:activity-ktx:1.4.0'
```

I use this code to present the list of message, where I click to the PDF file in the chat.
```
<io.getstream.chat.android.ui.message.list.MessageListView
        android:id="@+id/messageListView"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:clipToPadding="false"
        android:paddingBottom="16dp"
        app:layout_constraintBottom_toTopOf="@+id/messageInputView"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/headerDividerView" />
```
