### ISSUE TITLE
Localization within the library

### ISSUE THREAD

**Issue by savked** [GetStream/stream-chat-android#237]
I have to implement the support for German and Spanish language to your library, however I noticed that your strings.xml file is only in English and that you support only English for now. Is it possible for me to add these translated strings files somehow or make a pull request to your repository or how should I approach this? Thanks in advance.

**Comment by Chikrix** [comment]
Any reason why this is closed?

**Comment by tbarbugli** [comment]
@elevenetc

**Comment by elevenetc** [comment]
@Chikrix apparently @savked either decided to translate the app (but not SDK) or found another solution :slightly_smiling_face:
My opinion about localisation is that it should not be a part of SDK. The main reason is that any language requires support of a native speaker or at least the person who knows the language really well. And that person should be either in development team or be some contractor who can translate texts quickly.

**Comment by adrian09h** [comment]
@savked , you can translate all [verbals](https://github.com/GetStream/stream-chat-android/blob/master/library/src/main/res/values/strings.xml) of SDK in your application.
Please refer [this](https://developer.android.com/studio/write/translations-editor)

Sample app has a feature for localization with library.
For example: 
- German and Spanish language
https://github.com/GetStream/stream-chat-android/blob/master/sample/src/main/res/values-de/strings.xml
https://github.com/GetStream/stream-chat-android/blob/master/sample/src/main/res/values-es/strings.xml

**Comment by adrian09h** [comment]
@savked and @Chikrix , do you have any question about this issue yet?

**Comment by Chikrix** [comment]
@adrian09h yeah I'm good now. Thanks
