### ISSUE TITLE
Image Order Unstable

### ISSUE THREAD

**Issue by jisusushi** [GetStream/stream-chat-android#2464]
**Describe the bug**
Order between multiple images isn't preserved. This happens both in `Chat Sample Android` and `Chat Sample Compose`. 

https://user-images.githubusercontent.com/52556621/136897814-f081ec7e-c784-410f-966e-690f8b26ce95.mp4

**SDK version**
- 4.18.0

**To Reproduce**
You can refer to the video above. 

**Expected behavior**
In that case, the images should be placed as  

1   |   2
3   |   4

**Device:**
 - Vendor and model: S21
 - Android version: 11

**Screenshots**
at the 'describe the bug' section.

**Comment by adasiewiczr** [comment]
hey @jisusushi,
could you test if the issue still exists on the `develop` branch?

**Comment by jisusushi** [comment]
it works well now. Thanks for your update
