### ISSUE TITLE
Failed uploads do not update channel-messages UI to show error

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#2473]
**Describe the bug**

I am using a custom `FileUploader` like this:
```
val client = ChatClient.Builder(API_KEY, applicationContext)
	.notifications(notificationHandler)
	.fileUploader(SadFileUploader())
	.build()
```

In `SadFileUploader`, I fail all uploads. To do this, I use following code in all `send*` methods:
```
val chatError = ChatError("File uploads are sad!")
progressCallback.onError(chatError)
return Result.error(chatError)
```

Sent channel message keeps showing "Uploading 0 B / 4 MB" with a progress drawable. 

**SDK version**
- 4.17.2

**To Reproduce**
1. Use above mentioned FileUploader
2. Try to upload a file in a channel
3. Observe that UI does not show any update about the error. 

**Expected behavior**
Show the error symbols. 
![Screenshot 2021-10-13 at 7 18 10 PM](https://user-images.githubusercontent.com/14011726/137145758-ae406254-4cca-4b51-899a-d3e46cf2c3d5.png)

**Device:**
 - Google Pixel 4 XL (Android 11) EMULATOR

**Screenshots**
Self explanatory.

**Comment by adasiewiczr** [comment]
hey @rupinderjeet ,
thanks for reporting that. We are currently working on the fix that should be included in upcoming releases

**Comment by rupinderjeet** [comment]
Hello @adasiewiczr 

Is just returning a `Result` enough? `ProgressCallback` has methods for success and error. Should I call them too?

**Comment by SchramboVida** [comment]
In a related question… is it **safe** to invoke the progress callback method on a **background** thread? 🤔
