### ISSUE TITLE
Hardcoded channel type in ApiService.java

### ISSUE THREAD

**Issue by lukenowakcom** [GetStream/stream-chat-android#25]
## What did you do?
I tried to send messages to channel which type is `commerce`

## What did you expect to happen?
That the messages will be sent and appear correctly on receiving end.

## What happened instead?
Messages were sent successfully but with channel type `messaging` which is hardcoded for almost every endpoint in ApiService.java, hence the messages were never received by anyone else.

## GetStream Environment
**GetStream Chat version:** 1.8.7
**Android version:** Any
**Android studio version:** Any
**Device:** Any

**Comment by tschellenbach** [comment]
Thanks for letting us know, we'll release a fix for this in the coming days.

**Comment by ashlyrclark** [comment]
S
