### ISSUE TITLE
Crash on Sample app start

### ISSUE THREAD

**Issue by elevenetc** [GetStream/stream-chat-android#250]
```java
E  FATAL EXCEPTION: main
E  Process: io.getstream.chat.sdk, PID: 20901
E  java.lang.NullPointerException: Attempt to invoke virtual method 'long java.util.Date.getTime()' on a null object reference
E      at com.getstream.sdk.chat.adapter.ChannelListDiffCallback.areContentsTheSame(ChannelListDiffCallback.java:60)
E      at androidx.recyclerview.widget.DiffUtil$DiffResult.findMatchingItems(DiffUtil.java:635)
E      at androidx.recyclerview.widget.DiffUtil$DiffResult.<init>(DiffUtil.java:578)
E      at androidx.recyclerview.widget.DiffUtil.calculateDiff(DiffUtil.java:198)
E      at com.getstream.sdk.chat.adapter.ChannelListItemAdapter.replaceChannels(ChannelListItemAdapter.java:71)
E      at com.getstream.sdk.chat.view.ChannelListView.lambda$setViewModel$0$ChannelListView(ChannelListView.java:89)
E      at com.getstream.sdk.chat.view.-$$Lambda$ChannelListView$uF0gAyx8MgTxlWgwoc15gxfqE2g.onChanged(Unknown Source:6)
E      at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
E      at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
E      at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
E      at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
E      at androidx.lifecycle.LiveData$1.run(LiveData.java:91)
E      at android.os.Handler.handleCallback(Handler.java:883)
E      at android.os.Handler.dispatchMessage(Handler.java:100)
E      at android.os.Looper.loop(Looper.java:214)
E      at android.app.ActivityThread.main(ActivityThread.java:7682)
E      at java.lang.reflect.Method.invoke(Native Method)
E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```
It seems somehow connected with new channel. Possible steps to reproduce:
1. Create new channel
2. Send new message
3. Leave the app (with back button)
4. Open app again.

**Comment by adrian09h** [comment]
@elevenetc , I've tried to reproduce this problem many times but I can't see this.

Can you check it again the steps to reproduce?

![20191104_184532](https://user-images.githubusercontent.com/11132956/68144297-a64d2780-ff33-11e9-9f2b-ff37568786ed.gif)

**Comment by elevenetc** [comment]
Yeah, can't reproduce it also anymore. Either is was fixed by some other PR or it is some exceptional case. Close it for now.

**Comment by Princess-PN2k19** [comment]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.dailyfaces, PID: 5563
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Date com.getstream.sdk.chat.rest.Message.getDeletedAt()' on a null object reference
        at com.getstream.sdk.chat.rest.response.ChannelState.setLastMessage(ChannelState.java:358)
        at com.getstream.sdk.chat.rest.response.ChannelState.copy(ChannelState.java:145)
        at com.getstream.sdk.chat.model.Channel.copy(Channel.java:373)
        at com.getstream.sdk.chat.adapter.ChannelListItemAdapter.replaceChannels(ChannelListItemAdapter.java:68)
        at com.getstream.sdk.chat.view.ChannelListView.lambda$setViewModel$0$ChannelListView(ChannelListView.java:89)
        at com.getstream.sdk.chat.view.-$$Lambda$ChannelListView$uF0gAyx8MgTxlWgwoc15gxfqE2g.onChanged(lambda)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at androidx.lifecycle.LiveData$1.run(LiveData.java:91)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
D/WebSocketService: WebSocket # 1 Response : {"connection_id":"3c65d787-d83d-45f6-8afe-8bde6728a464","cid":"*","type":"health.check","created_at":"2019-11-18T10:00:52.586810892Z"}
    Received event of type HEALTH_CHECK
I/Process: Sending signal. PID: 5563 SIG: 9
Process 5563 terminated.

It leaves me with this error. How can I fix it?

**Comment by elevenetc** [comment]
@Princess-PN2k19 which version of SDK you're using? `setLastMessage` NPE is fixed in `3.2.1`.

**Comment by Princess-PN2k19** [comment]
> @Princess-PN2k19 which version of SDK you're using? `setLastMessage` NPE is fixed in `3.2.1`.

I'm not really familiar with Android Studio yet. Where can I find which SDK version am I using?

**Comment by elevenetc** [comment]
It's in `build.gradle` file. Something like:
```groovy
implementation 'com.github.getstream:stream-chat-android:3.2.1`
```

**Comment by Princess-PN2k19** [comment]
@elevenetc mine is :
implementation 'com.github.getstream:stream-chat-android:3.0.0'

**Comment by elevenetc** [comment]
@Princess-PN2k19 You need to replace `3.0.0` with `3.2.1` . You can read about adding/changing dependencies here: https://developer.android.com/studio/build/dependencies

**Comment by Princess-PN2k19** [comment]
@elevenetc okay. I'll do that. Thanks.

**Comment by Princess-PN2k19** [comment]
@elevenetc  there is just a progress bar. The channels don't appear. And here's what the error says;
E/ChannelListViewModel: onError for loading the channels Unable to encode user details json: {"server_determines_connection_id":true,"user_id":"billowing-art-2","user_details":{"name":"Paranoid Android","id":"billowing-art-2","image":"https:\/\/bit.ly\/2TIt8NR"}}

**Comment by elevenetc** [comment]
@Princess-PN2k19 could you create new issue? This issue is closed and it's not relevant to your problem.
