### ISSUE TITLE
[Compose] - Allow customization of reactions in `DefaultMessageContainer`

### ISSUE THREAD

**Issue by samiuelson** [GetStream/stream-chat-android#2501]
### Context

`MessageReactions` composable is rendered on top of the Column in `DefaultMessageContainer`. It would be good to:
1. Allow customizing `MessageReactions` position to top and bottom.
2. Add slot API allowing passing custom composable content in place of default `MessageReactions` 

### Change Proposal

1. Add param to `DefaultMessageItem` allowing to customize the position of MessageReactions composable
2. Add slot API param to `DefaultMessageItem` allowing to set custom composable instead of MessageReactions

### Acceptance criteria

To accept this task we need to complete the following items:

- [ ] As a user I'm able to customize the position of reactions
- [ ] As a developer I'm able to set a custom composable for displaying reactions

**Comment by filbabic** [comment]
Closing off this one given that we've exposed customization options through another PR/ticket.
