### ISSUE TITLE
[Compose] - Customize avatar position in `DefaultMessageItem` 

### ISSUE THREAD

**Issue by samiuelson** [GetStream/stream-chat-android#2502]
### Context

Avatar's position in the `DefaultMessageItem` should be customizable.

### Change Proposal

Add argument to `DefaultMessageItem` composable allowing to customize the position of Avatar (TOP, BOTTOM, END, START)

### Acceptance criteria

To accept this task we need to complete the following items:

- [ ] User is able to customize the position of the avatar

**Comment by filbabic** [comment]
Closing this off as it seems like it would mess up our `DefaultMessageItem` logic by a lot, without really providing too much value to the customizability.

If users want to customize the position in terms of start/end, they can always use our Slot APIs (that we provided).

In case they want to display the avatar top/bottom in the item, it's easy to just provide a custom list item component that uses our Avatar and the rest of the Message content components!

cc @bychkovdmitry
