### ISSUE TITLE
Channel unread count  getting reset

### ISSUE THREAD

**Issue by ping-anil** [GetStream/stream-chat-android#2520]
Greeting GetStream Team

Issue:
We need the channel count in which user have unread messages, for that we are using  the 
live data `channelUnreadCount` provide in `io.getstream.chat.android.livedata.ChatDomain`. It works fine User opens the chat screen which uses `io.getstream.chat.android.ui.message.list.MessageListView`. Whenever a new message arrives it is getting marked as read for sender (double blue tick appears) and we do get a update from live data `channelUnreadCount` but twice. First update contains correct value but second one is 0 (zero).

**SDK version**
- 4.20.0

1. open channel list with some unread message in a channel
2. open the channel
3. move back to channel list
4. send a message to same channel
5. channel message unread count is being update twice first update is correct and second one is not

**Expected behavior**
Should get single update and the correct value

**Device:**
 - Multiple (Samsun M31, Nokia 6.1, Pocco F9+, etc)
 - above Oreo (version below not checked)

**Comment by ping-anil** [comment]
@samiuelson Will this be resolved in next release?

**Comment by bychkovdmitry** [comment]
Hello @ping-anil 

Sorry for the delayed response. Unfortunately, the fix won't make it to the next release. But the issue is on our radar and we will likely start looking into it in the next sprint.

**Comment by amitkma** [comment]
Hi @ping-anil, I tried to reproduce this issue but it seems to work fine. Could you please try with the latest release `4.22.0` and confirm?
