### ISSUE TITLE
New input messages are inserted at wrong place initially

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#2528]
**Describe the bug**
When I send a new message, it is not inserted at the end of message-list sometimes. New message is inserted at ~2 or ~4 position and then, animated back to bottom of `MessageListView`. I am following default implementation for `MessageInputView` and `MessageListView` as mentioned in docs.

**SDK version**
- 4.20.0

**To Reproduce**
1. Send a message to new user.
2. Send several messages consecutively. Not too fast, not too slow.
3. Observe how messages are inserted.

**Expected behavior**
Insert messages at bottom.

**Device:**
 - Vendor and model: Samsung Galaxy A50
 - Android version: 11

**Screenshots**
https://user-images.githubusercontent.com/14011726/138855690-d2951a3f-56f6-4766-a2cb-6c1319e59429.mp4

**Comment by rupinderjeet** [comment]
Yes, you're right. My testing device's clock was 9 minutes off the regular time. Thank you.

**Comment by samiuelson** [comment]
I'll close this issue because we are not going to support this corner case at the moment as it's quite rare.
