### ISSUE TITLE
Channel list avatar not showing if the user is not online

### ISSUE THREAD

**Issue by savked** [GetStream/stream-chat-android#253]
The channel list avatar of the user (channel is with two people only, 1:1) is not visible, only empty circle with the first letter of the user's name. The "getImage()" field from Channel is empty, but sometimes when the user comes online, the image is available too.

The images are also missing from the ChannelActivity (messaging activity).

**Comment by adrian09h** [comment]
@savked , I have a questions atm about your create new channel.

Did you add the opponent as `member` of the channel?
 It seems you didn't add opponent as `member` when create the channel.
We provide user avatars show up by members and watchers. 
So even if someone is not a member of a channel and someone can watch the channel, avatar view shows them.
That's means, when opponent is online, the user starts watch the channel at same time.

This code is for creating new channel with adding member.
```java
Client client = configureStreamClient();
HashMap<String, Object> extraData = new HashMap<>();
extraData.put("name", channelName);

List<String> members = new ArrayList<>();
members.add(client.getUser().getId());
members.add("opponent-user-id");
extraData.put("members", members);
...

Channel channel = new Channel(client, ModelType.channel_messaging, channelId, extraData);
ChannelQueryRequest request = new ChannelQueryRequest().withMessages(10).withWatch();

viewModel.setLoading();
channel.query(request, new QueryChannelCallback() {
	@Override
	public void onSuccess(ChannelState response) {
		 ...
	}

	@Override
	public void onError(String errMsg, int errCode) {
	  ...
	}
});
```

**Comment by savked** [comment]
I am actually not using GetStream channel list component anymore, but I'll try to help with this issue.

However, I was never adding members through code it was all done on the back-end, checking the response from the back-end now I see that both users are labeled as members and "member_count" in fact is 2.

The app is using chat only for 1:1 chatting, but the avatar did not show (they should see each other's avatars) at all times and I didn't manage to recognize the pattern or what is happening.
