### ISSUE TITLE
Newly created channel is not coming at top with DEFAULT_SORT

### ISSUE THREAD

**Issue by JayeshMohan4** [GetStream/stream-chat-android#2533]
**Describe the bug**
While creating a new chat its showing at the bottom of the chat with DEFAULT_SORT option on querying channels.

**SDK version**
- 4.20.0

**To Reproduce**
1. Create new chat
2. load channel list
3. not showing the newly created chat at top

**Expected behavior**
Need to display newly created chat at the top of channel list.

**Device:**
 - All device

**Comment by JayeshMohan4** [comment]
Any update for this issue?

**Comment by bibinkrishnan** [comment]
I also having same issue in 4.21.0. Default Sort is not working now

**Comment by samiuelson** [comment]
@JayeshMohan4, @bibinkrishnan,

we've added several fixes to channel sorting and they are available in the `4.22.1-SNAPSHOT` version. 

Could you test this release? If any issue still exists can you record your screen and share it with us? 

To use snapshot version you will need this repository to your grade script: 
`maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }` (more info [here](https://getstream.io/chat/docs/sdk/android/basics/dependencies/#snapshot-builds) in docs)

cc @leandroBorgesFerreira

**Comment by bibinkrishnan** [comment]
Sure, We will check and let you know
