### ISSUE TITLE
Adjustable initials text size in avatars

### ISSUE THREAD

**Issue by bychkovdmitry** [GetStream/stream-chat-android#2542]
### Context

Our avatar components can have different sizes. At the same time the size of initials text is fixed. This leads to the following problems:

- Text too big when for a section in avatar matrix
- Text too big for a very small avatar
- Text too small for a very big avatar 

### Change Proposal

Possible solutions:

- Pass text size as a parameter
- A smarter solution which internally adjusts the text size according to the avatar size

### Acceptance criteria

To accept this task we need to complete the following items:

- There are no cases when the initials text is too big and is cropped
- There are no cases when the initials text is too small

**Comment by filbabic** [comment]
We haven't received any issues around this so far, so I'll close the issue. We can look at improving this in the future if needs be.
