### ISSUE TITLE
User is online but still receives push notifications

### ISSUE THREAD

**Issue by ma7moudovic** [GetStream/stream-chat-android#2571]
### Discussed in https://github.com/GetStream/stream-chat-android/discussions/2568

<div type='discussions-op-text'>

<sup>Originally posted by **ma7moudovic** November  3, 2021</sup>
I am updating the user to isOnline = true with calling ChatClient.updateUser(user),
but the user still receives push notifications.
so what should i do to stop user receives push notification when he is online and active in some chat</div>

**Comment by adasiewiczr** [comment]
Hey @ma7moudovic,
members of channels should receive push notifications only if they don't have an open socket connection.
Can you check if the socket connection is open? You can use this method:
```kotlin
ChatClient.instance().isSocketConnected
```
