### ISSUE TITLE
MessageListView is scrolling/blinking for every new message

### ISSUE THREAD

**Issue by lukenowakcom** [GetStream/stream-chat-android#26]
## What did you do?
Sent/received new message.

## What did you expect to happen?
The list to scroll to the bottom if it was scrolled before sending/receiving message, so that I can see the last message.

## What happened instead?
The whole list blinks when the message is received/sent and scrolls a little bit to the top - more or less the height of 1-2 single line text messages

## GetStream Environment
**GetStream Chat version:** 1.8.7
**Android version:** 9.0
**Android Studio version:** 3.5
**Device:** OnePlus 6

## Additional context
Seems like the chat is scrolling every time something updates(reaction etc.)

**Comment by tschellenbach** [comment]
This issue has been fixed in master, i'll update this ticket when we release a new version from master.

**Comment by lukenowakcom** [comment]
Awesome! Thanks a lot 👍

**Comment by tschellenbach** [comment]
quick update, we are a few days away (doing the last bit of testing) with a major new release, which fixes these (and many other) issues. it also adds support for threads, commands and offline storage.

**Comment by tschellenbach** [comment]
1

![image](https://user-images.githubusercontent.com/265409/65376465-6bca4c80-dc5d-11e9-8efb-c185303bcd64.png)

2
![image](https://user-images.githubusercontent.com/265409/65376468-771d7800-dc5d-11e9-9c61-15b91740b5cd.png)

3

![image](https://user-images.githubusercontent.com/265409/65376471-7e448600-dc5d-11e9-
8d65-72fe463d73fa.png)


Looks good to me on master. Let me know if you're still seeing this issue
