### ISSUE TITLE
Write a guide/blog post about custom attachment factories in Compose

### ISSUE THREAD

**Issue by filbabic** [GetStream/stream-chat-android#2623]
### Context

Given that we've recently supported a new way of providing attachments, we should cover this change in a piece of tech content that we post on our website.

This can be a huge push for the Compose SDK, as it'll showcase how easy it is to integrate our SDK and customize it towards our users' needs.

### Change Proposal

Write a blog post about "Integrating Custom Attachments Using The Stream Compose Chat SDK" (title TBD).

Some of the topic points:
- How our Compose AttachmentFactories work
- Custom attachment factories (overriding default ones)
- Adding new attachment factories to the existing default
- Building a Custom attachment factory for both the sent content and the preview

### Acceptance criteria

To accept this task we need to complete the following items:

- [ ] Blog post written about the aforementioned topics
- [ ] Meaningful sample project provided that showcases this behavior (e.g. similar to what Jaewoong did with the Avengers idea)
- [ ] Make sure the SEO and everything is optimized (talk to Craig)

**Comment by zsmb13** [comment]
We should update this existing article https://getstream.io/blog/custom-attachments-jetpack-compose/
