### ISSUE TITLE
>20mb files can't be uploaded

### ISSUE THREAD

**Issue by elevenetc** [GetStream/stream-chat-android#264]
Currently SDK allows to upload any file, but uploading stop if file is bigger than 20mb. And error message doesn't say anything about it. So it might be annoying especially with slow network connection.

Possible solution: when user tries to upload file we check file size and tell user that currently it's not possible to upload the file, because file limit is 20mb.

**Comment by tbarbugli** [comment]
very good point, atm the SDK fails once the 20MB watermark is hit but we could easilly detect that upfront

**Comment by elevenetc** [comment]
Moved to Jira.
