### ISSUE TITLE
Add support for Huawei push notifications

### ISSUE THREAD

**Issue by bychkovdmitry** [GetStream/stream-chat-android#2654]
### Context

We don't support Huawei push notifications at the moment.

### Change Proposal

1. Add the following to the Compose sample app `build.gradle`:

```
repositories {
    // huawei maven
    maven {
        url 'https://developer.huawei.com/repo/'
        content {
            includeGroup("com.huawei.agconnect")
            includeGroup("com.huawei.android.hms")
            includeGroup("com.huawei.hms")
            includeGroup("com.huawei.hmf")
        }
    }
}

...

implementation project(":stream-chat-android-pushprovider-huawei")
```

2. And the following to the `Application` class:

```kotlin
private fun createNotificationConfig(): NotificationConfig {
        return NotificationConfig(
            pushDeviceGenerators = listOf(
               ...
                HuaweiPushDeviceGenerator(
                    context = this,
                    appId = "..." // app id from Huawei console
                )
            )
        )
}
```

3. Add the `agconnect-services.json` file from Huawei console

### Acceptance criteria

To accept this task we need to complete the following items:

- [ ] Compose sample app application id and agconnect-services.json file are obtained from Huawei console
- [ ] Huawei push provider is added to the Compose sample app

**Comment by filbabic** [comment]
Closing for now as this is not requested or required
