### ISSUE TITLE
[Compose] - Convert interfaces for functional interfaces

### ISSUE THREAD

**Issue by bychkovdmitry** [GetStream/stream-chat-android#2658]
### Context

We have several interfaces that are supposed to be used by our clients that are not "functional". For convenience, in order for the SAM conversion to work we need to make them functional.

### Change Proposal

Make interfaces functional where possible

### Acceptance criteria

To accept this task we need to complete the following items:

- [ ] The `ChannelNameFormatter` interface is functional
- [ ] The `ClipboardHandler` interface is functional
- [ ] The `MessagePreviewFormatter` interface is functional

**Comment by zsmb13** [comment]
Nice idea! (As long as we don't expect these interfaces to get more methods in the future, which would need us to walk back the functional aspect.)

I'm curious about how this will work for `MessagePreviewFormatter`, given that it has a `@Composable` function in it. Really complex Kotlin things going on there 😃
