### ISSUE TITLE
Limit for sqlite variable needs to be increased

### ISSUE THREAD

**Issue by jisusushi** [GetStream/stream-chat-android#2663]
**Describe the bug**

`Fatal Exepction: too many SQL variables`

<img width="1189" alt="image" src="https://user-images.githubusercontent.com/52556621/142975468-e5aae85c-12b4-433c-b537-854de36a0d10.png">

I'm currently calling some messages for each chatroom when initializing my app. And as my service grows up, it started calling more than 1000 messages at the same time. But I found that stream returns error when calling more than 1000 messages in `MessageDao`'s `insert` (I'm not sure whether the limit is exactly 1000). 

**SDK version**
- 30

**To Reproduce**
Just calling more than 1000 messages at the same time would reproduce this problem

**Expected behavior**
Messages should be called without exception

**Device:**
 - Vendor and model: Samsung S21
 - Android version: 11

**Screenshots**
![image](https://user-images.githubusercontent.com/52556621/142975484-2f08b340-9839-49f3-9eb5-f354c7ae8448.png)

**Comment by ogkuzmin** [comment]
Hello @jisusushi 
What version of stream SDK do you use?

**Comment by ogkuzmin** [comment]
Could you try our latest 4.22? We fixed the issue there

**Comment by jisusushi** [comment]
> Hello @jisusushi
> What version of stream SDK do you use?

Now I'm currently using 4.2.0
I'll try 4.22 out asap

**Comment by jisusushi** [comment]
It's working well now. 
Thanks for your help
