### ISSUE TITLE
Scroll state is lost when returning from a thread

### ISSUE THREAD

**Issue by bychkovdmitry** [GetStream/stream-chat-android#2691]
**Describe the bug**

The scroll state is lost when returning from a thread mode to the message list.

**To Reproduce**

1. Open the message list screen
2. Scroll up to a message with a thread
3. Enter the thread
4. Exit the thread (doesn't matter if hardware or software back button is used)

**Actual behavior**
Scroll state is lost. The message list is scrolled to the bottom.

**Expected behavior**
Scroll state is preserved and the message with the thread is in the viewport.

**Not reproducible every time**

**Device:**
 - Any

**Comment by filbabic** [comment]
This should no longer happen with our new implementation of the scroll state as we hoisted it up to larger components.
