### ISSUE TITLE
MessageListView scrolls up when keyboard is opened/closed

### ISSUE THREAD

**Issue by lukenowakcom** [GetStream/stream-chat-android#27]
## What did you do?
Opened/closed keyboard in an activity with `android:windowSoftInputMode="adjustPan"`

## What did you expect to happen?
The list to get panned in a way that whatever was visible on the list is still visible after opening/closing keyboard

## What happened instead?
When the keyboard is opening the list scrolls up a little bit(more or less the height of 1-2 single line text messages). If you scroll it back to the bottom and close the keyboard the same issue occurs.

## GetStream Environment
**GetStream Chat version:** 1.8.7
**Android version:** 9.0
**Android Studio version:** 3.5
**Device:** OnePlus 6

**Comment by tbarbugli** [comment]
thank you for reporting this, we'll fix it soon!

**Comment by adrian09h** [comment]
The issue was fixed on master, Thank you.

**Comment by lukenowakcom** [comment]
Just tried it on master. Unfortunately the list still scrolls up, and now as an effect of 
https://github.com/GetStream/stream-chat-android/blob/fb551acc68d844aed81bca5ad086792fc1fd0a25/library/src/main/java/com/getstream/sdk/chat/view/MessageInputView.java#L163-L166
The keyboard hides itself a fraction of a second after opening. This is happening up until the point the list can`t scroll up anymore.
