### ISSUE TITLE
Crash when querying channel

### ISSUE THREAD

**Issue by lukenowakcom** [GetStream/stream-chat-android#274]
We just encountered an issue when trying to query channels.
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.getstream.sdk.chat.rest.User.e()' on a null object reference
       at com.getstream.sdk.chat.rest.core.Client$5.onSuccess(Client.java:747)
       at com.getstream.sdk.chat.rest.core.Client.onSetUserCompleted(Client.java:533)
       at com.getstream.sdk.chat.rest.core.Client.queryChannels(Client.java:744)
       ...
```

Seems like the User returned in `onSuccess` is null.
Earlier the `onSetUserCompleted` returned with `onSuccess` too when setting the user. And because it did I've tried to fetch the channel, and above happened :/

**SDK Version:** 3.2.0

**Comment by tbarbugli** [comment]
@bevzaanton

**Comment by tbarbugli** [comment]
@lukenowakcom can you reproduce this from your end or was this a one time crash?

**Comment by lukenowakcom** [comment]
Wasn't able to reproduce on my end.
But so far there were 2 occurrences on production. Both for different users on different phones.
One at Nov 4, and one at Nov 8

**Comment by bevzaanton** [comment]
@lukenowakcom I was trying to reproduce this issue in every way I could think of. Without results. Still there were cases of crashes?

**Comment by lukenowakcom** [comment]
@bevzaanton There were no occurrences since 8th Nov. But I also didn't update the library since then

I just spoke with our backend guys. They say there was an issue on their end(fixed on Sunday) that the user might not have been created before the app tried to query it for the first time(e.g. right after signup). 
I would put my money that it could've been the issue here. But then again, the `onSuccess` should'nt be called if the user I was trying to set on the client returned `null` right?

**Comment by bevzaanton** [comment]
@lukenowakcom Yeah, you are right. I managed to get the crash by setting user as null.
