### ISSUE TITLE
UI feedback when executing a message command

### ISSUE THREAD

**Issue by bychkovdmitry** [GetStream/stream-chat-android#2789]
### Context & proposal

There is no UI feedback when:
- A user executes a command on the message list screen such as "mute user" and  the command fails
- A user executes a command on the message list screen such as "mute user" and  the command succeeds

### Acceptance criteria

To accept this task we need to complete the following items:

- [ ] A toast or a snackbar is shown when a command fails
- [ ] A toast or a snackbar is shown when a command succeeds

**Comment by filbabic** [comment]
We can go with a Toast for a simple implementation - improve in the future if required.

**Comment by filbabic** [comment]
Closing this since it's deprioritized.
