### ISSUE TITLE
Using Workmanager On-Demand Initialization causes conflict

### ISSUE THREAD

**Issue by MostafaAnter** [GetStream/stream-chat-android#2798]
**Describe the bug**
I set up work manager initialization on manifest file before integrating workmanager everything was fine till I integrate it i got this issue App context hasn't been initialized 
![Screen Shot 2021-12-20 at 9 09 49 PM](https://user-images.githubusercontent.com/9489649/146820431-03c81bf8-ed9a-4fad-91b6-05480fa0a40c.png)

**SDK version**
- 4.15.1

**To Reproduce**
1. integrate jetpack workmanager 2.7.1 
2. build the project
3. get error of can't inflate some components

**Comment by adasiewiczr** [comment]
Hey @MostafaAnter,
The UI Components library relies on Jetpack App Startup Initializers to initialize certain components and you need to initialize them manually if you disabled automatic initialization. 
You can read more about this [here](https://getstream.io/chat/docs/sdk/android/ui/guides/app-startup-initializers/).

**Comment by MostafaAnter** [comment]
it doesn't work for version 4.15.1 it may be work for the last version thank you @adasiewiczr for resopnse
