### ISSUE TITLE
IllegalCharsetNameException in StreamWebSocketServiceProvider.java

### ISSUE THREAD

**Issue by artemiyutekhin** [GetStream/stream-chat-android#281]
On my device (OnePlus One, Android 6.0) the latest SDK fails to connect, throwing `java.nio.charset.IllegalCharsetNameException: java.nio.charset.CharsetICU[UTF-8]` in `StreamWebSocketServiceProvider.java` on line 558 `json = URLEncoder.encode(json, StandardCharsets.UTF_8.toString());`

**Comment by adrian09h** [comment]
@artemiyutekhin, This is Adrian.
Can you please let me know our library version number you are using and add full stack trace?

**Comment by elevenetc** [comment]
Similar issue and also with Android 6.0: https://github.com/android/uamp/issues/233
The issues is seems within `java.net.URLEncoder.encode` on Android 6.0 and on the latest systems it was resolved. The only thing we can make is introduce some `json` handlers before it's passed to `URLEncoder.encode`. But we need to know what's inside your `json` @artemiyutekhin .

**Comment by elevenetc** [comment]
Closing issue as inactive.
