### ISSUE TITLE
Improve the ChannelItem component

### ISSUE THREAD

**Issue by bychkovdmitry** [GetStream/stream-chat-android#2824]
### Context & proposal

We need to improve the `ChannelItem` component.

### Acceptance criteria

To accept this task we need to complete the following items:

- [ ] There are component previews for the `ChannelItem` component
- [ ] The `ChannelItem` padding is moved to the inner slots
- [ ] The `DefaultX` components within the `ChannelItem` component don't accept modifiers for styling

**Comment by MohitMandalia** [comment]
Hi @bychkovdmitry 

Is this project open to contribution? I didn't find any instructions for that.

Regards.

**Comment by bychkovdmitry** [comment]
Hello @MohitMandalia,

Contributions are welcome! Before opening a pull request make sure to sign our [Contributor License Agreement (CLA)](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) first. Also, we have our internal code styling guidelines that we follow (we should make them public at some point). For now, you can just try to be consistent with the rest of the codebase in terms of naming / styling / formatting.

**Comment by MohitMandalia** [comment]
Sure. Thanks @bychkovdmitry.

**Comment by bychkovdmitry** [comment]
Everything in the OP checklist is already implemented.
