### ISSUE TITLE
Can't send images from camera

### ISSUE THREAD

**Issue by Chikrix** [GetStream/stream-chat-android#285]
When I try to send a picture taken from the camera, it doesn't post anything for both the sender and receiver. 
*How to reproduce:*
- in a chat, hit the +
- Upload from camera
- Tap Camera
- Take a picture and send it
- It does not show the pic on both the sender and receiver. Its like it never happened

Choosing a photo from the gallery works as it should

**Comment by tbarbugli** [comment]
@bevzaanton

**Comment by bevzaanton** [comment]
I tried to reproduce it on Pixel 2, Samsung S8, emulator. Everything works as expected.

**Comment by tbarbugli** [comment]
@Chikrix can you reproduce this from your end? If yes can you provide more information about your setup?

**Comment by Chikrix** [comment]
This is weird. I just tried it now on my testing devices (Pixel 3, S9, Nexus 9), and it works as expected, this wasn't the case yesterday! On my Nexus 9 tablet, I'm noticing some errors, first the image I sent is reduced to a single line, then trying again it kept on failing with error messages like file is empty, file above a certain size, etc

**Comment by elevenetc** [comment]
Also can't reproduce it.

@Chikrix tablet issue sounds differently. Could you created new issue and provide next information if possible:
- reproduce and record video of the issue
- does it happen with any file/image or with particular one? If it happens with particular one could you attach the file?
- Could you try to upload images with another messenger app? Picking up images/files might be a system (state) related issue.
- system version
- logcat logs are always useful

When there is an issue which happens on a particular device we need to narrow down context as much as possible.

**Comment by Chikrix** [comment]
This issue is still open for me. Nothing with attaching a file works for me. This [video](https://youtu.be/xfVtE1t_mWQ) here shows the issue I'm having. 
The issue happens on all files and not with one in particular as you can see from the video linked above. I can do all the actions I want to do on Whatsapp or Slack. My device is a Google Pixel 3 XL running Android 10, API 29. The logcat prints a FileNotFoundException, but the file exists and is selectable from other apps

**Comment by Chikrix** [comment]
I don't think this issue should be closed, it's still not fixed.
