### ISSUE TITLE
Cleanup new message composer implementation 

### ISSUE THREAD

**Issue by adasiewiczr** [GetStream/stream-chat-android#2874]
### Context & proposal

The new message composer view is created on a separate branch [feature/message-composer-view](https://github.com/GetStream/stream-chat-android/tree/feature/message-composer-view). The implementation needs to be reviewed before merging to the develop. Missing things need to be detected and added to the backlog.

### Acceptance criteria
To accept this task we need to complete the following items:

- [x] Make sure new implementation has feature parity with the old one
- [x] Check if anything needs improvements
- [ ] Make sure new implementation is customizable via slots and styles
- [x] Make sure new implementation is documented (KDocs)

**Comment by filbabic** [comment]
I'll close off this one given that we've merged most of the changes here.

We just need to work on the styles I think which is tracked in #3006. I'll create a PR that holds all of these changes and points to dev!
