### ISSUE TITLE
"Active just now" not translated to other languages

### ISSUE THREAD

**Issue by savked** [GetStream/stream-chat-android#292]
Online status below the channel name inside the ChannelActivity when says "Active just now" is not translated to other languages.

I noticed that in older version this used to be working!

**Comment by tbarbugli** [comment]
@adrian09h do we have a consolidated way to use translated versions of strings like this?

**Comment by adrian09h** [comment]
@tbarbugli , yeah. it is not problem, then how many countries languages should we provide?
`strings.xml` file contains all texts as default language.
I'd like you to provide me the translations about that.

**Comment by adrian09h** [comment]
@tbarbugli , What do you think about these languages?

![image](https://user-images.githubusercontent.com/11132956/68546147-e6992380-03d3-11ea-86f1-dbba173fbc7a.png)

**Comment by elevenetc** [comment]
That's not about translation `strings.xml` files. The problem is here:
```java
protected void setHeaderLastActive(ChannelState channelState) {
    Date lastActive = channelState.getLastActive();
    Date now = new Date();
    String timeAgo = getRelativeTimeSpanString(lastActive.getTime()).toString();

    if (now.getTime() - lastActive.getTime() < 60000) {
        timeAgo = "just now";
    }

    binding.setChannelLastActive(String.format("Active %s", timeAgo));
}
```
`"just now"` and `"Active %s"` and should be put in `strings.xml`. Developers could provide language specific `strings.xml` files and override texts. Will create PR.
