### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by tbarbugli** [GetStream/stream-chat-android#304]
Currently we close the WS connection as soon as the app goes to background and recover when comes back. Instead we should keep the WS connection open and show notifications when new messages are received and make sure the WS connection gets closed after a couple minutes so that we'll switch to Firebase PUSH.

- Make sure we make it easy to register notifications (probably the best is to have the developer pass a notification builder or factory to the library)
- We should have a good default on the library
- The sample app should open channel view on tap
- We should try to have 1 way to define how notifications are displayed (instead of 1 way for push and 1 way for webhook events)

**Comment by tbarbugli** [comment]
see StreamChat.init body for relevant code (disconnect/reconnect logic is there)

**Comment by elevenetc** [comment]
Moved to Jira.
