### ISSUE TITLE
Cant able create new channel

### ISSUE THREAD

**Issue by JayeshMohan4** [GetStream/stream-chat-android#3042]
**Describe the bug**
I tried to create a channel with a member that I deleted. its showing error that mentioned below

Status code: 403, with stream code: 17, description: GetOrCreateChannel failed with error: "User with role channel_member is not allowed to access Resource RecreateChannel on channel type messaging"

this is my code to create channel

 client.createChannel(channelType, members, extraData).enqueue(result1 -> {
                if (result1.isSuccess()) {

                } else {
                    Log.e("channel Error", result1.error().getMessage());
                }
            });

**SDK version**
- 4.21.0

**To Reproduce**
1. Create a channel

**Expected behavior**
Need to create channel without error

**Device:**
 - Vendor and model: [e.g. Samsung S8]
 - Android version: [e.g. 9]

**Screenshots**

**Comment by amitkma** [comment]
Hi @JayeshMohan4, It seems that there is a permission issue. We have permission policies that allow/restrict what a user can do. You can read more about them here - https://getstream.io/chat/docs/android/chat_permission_policies/?language=kotlin

Please feel free to share if there is any further issue you face.

**Comment by JayeshMohan4** [comment]
So there is no way to recreate a channel on channel type "messaging" once deleted?

**Comment by filbabic** [comment]
Hey Jayesh!

If the user is deleted, you most likely won't be able to create new channels with them. That's kind of understandable, as the user doesn't exist in the scope of the environment anymore.

But if any member deletes a channel, you can create new channels with those members again.

Hope this helps!

**Comment by JayeshMohan4** [comment]
Actually I am not deleting any user here. For example **A** and **B** are two users. User **A** create a new channel with the above mentioned code with user **B**. Now user **A** is deleting the channel that created with User **B**. Then again **A** tries to create a new channel with B. Now it throws the error "**GetOrCreateChannel failed with error: "User with role channel_member is not allowed to access Resource RecreateChannel on channel type messaging**" like this.

**Comment by JayeshMohan4** [comment]
Hi,
Any solution to this?

**Comment by filbabic** [comment]
Hey!

We took a look at this and basically the user you are trying to recreate the channel with needs to have the "RecreateChannel" permission. You should be able to apply these permissions in the dashboard for your app if I'm not mistaken.

We're researching with the BE team to see if this can be applied in an easier way, so we'll let you know ASAP!

Thanks

**Comment by JayeshMohan4** [comment]
I am waiting for the solution through programmatically. we cannot make every user in dashboard to give permission. Those who are connected to Chatclient need have the permission. In above example User A is connected to the ChatClient and need to have the permission to recreate the channel after deletion. So kindly make a solution to this program because I am stuck with creating channel.

**Comment by filbabic** [comment]
Hello Jayesh.

As mentioned before, you can apply the permission to every single user within a user type in the dashboard.

It's fairly easy to allow RecreateChannel for every user in every channel type and does not require any additional actions from client SDK, so no need for programmatic approach.

We also suggest to switch to version 2 of permissions where you can set it up using UI in the dashboard.

Here's a link with more information: https://getstream.io/chat/docs/android/user_permissions/?language=kotlin As we already shared.

We can help you with tuning the config if you have issues, but we need to know you app ID / have a direct communication channel as it's a bit harder to hand this off to the BE team through GH issues.

**Comment by JayeshMohan4** [comment]
Let me try this on dadhboard and if any issue will update it.

**Comment by adasiewiczr** [comment]
Hey @JayeshMohan4,
did you manage to solve this problem?
