### ISSUE TITLE
There is not such message with messageId

### ISSUE THREAD

**Issue by workspace** [GetStream/stream-chat-android#3059]
**Describe the bug**
#### Description
We separated message list screen and thread screen unlike stream-ui-*'s. When user clicked notification which is related with thread, our client send user to thread screen.  
With 4.22.0, there is no problem with our implementation, however, [this commit ](https://github.com/GetStream/stream-chat-android/commit/37da104a690b384c771cfca5e0fb181a88b08000#diff-05f882b82c05f50f3701f8ac2a7f2f81f40400828184ec7f046887da92a47004R60)and change raise error. (may be released with 4.23~4.25?)

#### My troubleshooting with version 4.28
(I keep an eye on changes implemtation of sdk. Changes to extract your domain logic from ChatDomain and Plugin(Offline) is cool 👍)
I guess the reason is we tried to load thread before message is ready. So, I tried to load message manually before load thread controller like this, however, still has a problem 😢
```
(in suspended function)
chatClient.loadByMessageId(cid, messageId, 0, 0).await() // loadByMessageId will dispatch onGetMessageResult in OfflinePlugin
chatDomain.getThread(cid, messageId).await()
```

**SDK version**
- after release include [this commit](https://github.com/GetStream/stream-chat-android/commit/37da104a690b384c771cfca5e0fb181a88b08000#diff-05f882b82c05f50f3701f8ac2a7f2f81f40400828184ec7f046887da92a47004R60)

**To Reproduce**
I think It is hard to reproduce without our implementation. Apologize for leaving description only.

**Expected behavior**
load thread without any problem.

**Device:**
 - Vendor and model: Samsung Galaxy S21 Ultra
 - Android version: 12

**Comment by amitkma** [comment]
Hi @workspace, Could you please try to use `chatDomain.loadByMessageId(cid, messageId, 0, 0).await()` instead of `chatClient.loadMessageById`?

**Comment by workspace** [comment]
It works as I expected 👍 I don't know why I tried to use chatClient instead of chatDomain! Thank you!
