### ISSUE TITLE
Add method to update the current ChannelListViewModel query

### ISSUE THREAD

**Issue by bychkovdmitry** [GetStream/stream-chat-android#3060]
### Context & proposal

We need to ensure that our channel list ViewModels always react to user changes or provides a way to refresh them manually.

A scenario when channels are not reloaded:

1. Connect as an anonymous user
2. Pass an external filter to ChannelListViewModel 
```
Filters.and(
    Filters.eq("type", "messaging"),
    Filters.`in`("members", currentUserId))
)
```
3. Disconnect and reconnect with a new user
4. Observe that channels are not reloaded as the user is not updated in the filter

A possible solution might be to expose a method to update the existing ViewModel: 

```kotlin
ChannelListViewModel {
    public fun setQueryConfig(queryConfig: QueryConfig) {
        // query channels again with the new sort and filter from QueryConfig
    }
}
```

### Acceptance criteria

To accept this task we need to complete the following items:

- [ ] Compose ChannelListViewModel exposes a method to update the existing query
- [ ] UI components ChannelListViewModel exposes a method to update the existing query

**Comment by MarinTolic** [comment]
PR is finished but merging is temporarily blocked by the following core issue: https://github.com/GetStream/stream-chat-android/issues/3556

**Comment by filbabic** [comment]
Closing for the time being as it's not needed
