### ISSUE TITLE
Update Compose to use the OfflinePlugin

### ISSUE THREAD

**Issue by filbabic** [GetStream/stream-chat-android#3095]
### Context & proposal

As an effort to update all of our code to feature the Offline plugin, we need to migrate compose to this behavior.

### Acceptance criteria

To accept this task we need to complete the following items:

- [x] Migrate ChannelListViewModel.
- [x] Migrate ImagePreviewViewModel.
- [x] Migrate MessageComposerViewModel.
- [x] Migrate MessageListViewModel.
- [x] Migrate AttachmentsPickerViewModel

**Comment by MarinTolic** [comment]
`AttachmentsPickerViewModel` was already not dependent on `ChatDomain`. 
No migration needed.

**Comment by MarinTolic** [comment]
Full migration on  `ImagePreviewViewModel` blocked by `deleteMessage()` not being fully ported in `ChatClient`. 

PR exists but is not yet merged: https://github.com/GetStream/stream-chat-android/pull/3013

**Comment by MarinTolic** [comment]
Full migration `MessageListViewModel` blocked by: 

`deleteMessage()` - https://github.com/GetStream/stream-chat-android/pull/3013
`ChatClient.sendGiphy()` - Extension internal in the offline module **(the team is on it, should be refactored within a few days)** 
`ChatClient.ShuffleGiphy()` - Extension internal in the offline module **(the team is on it, should be refactored within a few days)**
