### ISSUE TITLE
Fix sent/ read receipts for individual messages in Compose

### ISSUE THREAD

**Issue by MarinTolic** [GetStream/stream-chat-android#3115]
### Context & proposal

Currently, the read/ sent receipts are not visible inside the Compose SDK. 
Investigate the issue and take the appropriate actions required to make the receipts show properly.

### Acceptance criteria

To accept this task we need to complete the following items:

- [ ] Fix the issue.
- [ ] Make sure the receipts are showing only on appropriate messages (user's own, have been sent or read)

**Comment by filbabic** [comment]
Resolved in another task.
