### ISSUE TITLE
Chat list question and bug

### ISSUE THREAD

**Issue by savked** [GetStream/stream-chat-android#312]
Screenshot attached.

I want to hide the "Last active" title below the user's name using `'app:streamChannelHeaderLastActiveShow="false"` but the user's name is staying in the same place and not in the center. How could I fix this.

Is there any way to hide the user's name and date displayed below message, circled red thing on screenshot?

![image](https://user-images.githubusercontent.com/22063573/69139968-e37ff080-0ac1-11ea-8119-d4af222eb729.png)

**Comment by tbarbugli** [comment]
this should be exposed in the style file, @adrian09h can you make sure this is there and documented?

**Comment by savked** [comment]
What about the channel title not being centered?

**Comment by savked** [comment]
You can close this issue I found an alternative for my case, not using your ChannelHeaderView, because non if it's features are necessary for our app.

**Comment by savked** [comment]
I found the alternative for the title, not using your ChannelHeaderView but custom header since non of it's features are necessary for our app. However I still need the ability to hide the date and name.

**Comment by adrian09h** [comment]
@savked , I will fix the Channel Title position issue when lastActive is hidden soon.
And will provide the way to hide user name and message date.

**Comment by adrian09h** [comment]
@savked , just fixed and merged the position issue of Channel Title when is hidden last active

**Comment by savked** [comment]
Thank you, I need to use custom header anyway because of the avatar not loading bug I have, but it's good I noticed the issue. I'd need this hide option as soon as possible.

**Comment by adrian09h** [comment]
I will provide the hide options soon.
