### ISSUE TITLE
Channel member counter only counts up to 30

### ISSUE THREAD

**Issue by teamsupermomos** [GetStream/stream-chat-android#3150]
ways to replicate:
1) add more than 30 users into a channel
2) open a channel to see the member counter

expected: correct number of member count
actual: 30 members

**Comment by adasiewiczr** [comment]
hey @teamsupermomos,
do you mean `channel.memberCount` property?

**Comment by filbabic** [comment]
Hey @teamsupermomos !

Just noticed we haven't received any attachments here in the GH panel, could you provide us with more info on this?

**Comment by adasiewiczr** [comment]
Hey @teamsupermomos,
could you provide us with more information on this?

**Comment by teamsupermomos** [comment]
![2273a090-1930-45fe-9b47-c82af375753c](https://user-images.githubusercontent.com/95665624/161509430-e4568402-0718-4dba-905c-4fe565594d73.png)

This channel has hundred of members, but it always show 30 members

**Comment by adasiewiczr** [comment]
Hey @teamsupermomos,
we released a new version (5.0.3) that includes the fix mentioned above. You can find more details [here](https://github.com/GetStream/stream-chat-android/releases/tag/v5.0.3).
Don't hesitate to contact us if the issue still exists.

**Comment by teamsupermomos** [comment]
@adasiewiczr Thank you!
