### ISSUE TITLE
Skip empty message on Client level.

### ISSUE THREAD

**Issue by elevenetc** [GetStream/stream-chat-android#317]
iOS SDK currently doesn't allow to send empty messages (without text, attachment or anything else), Android doesn't allow to send it from UI, but allows to send it from Client. Hence empty messages do appear on iOS.

Possible solution to align SDKs is to check if message is empty and finish request with error:
```java
public void sendMessage(Channel channel, @NonNull Message message, MessageCallback callback) {
    if(message.isEmpty()){
    	callback.error(new EmptyMessagesNotAllowed())
    }else{
    	sendMessage(message)
    }
}
```

**Comment by tbarbugli** [comment]
@elevenetc can you provide more context? I have no idea what this means

**Comment by elevenetc** [comment]
@tbarbugli updated description.

**Comment by elevenetc** [comment]
Moved to Jira.
