### ISSUE TITLE
Pinned messages not loaded correctly (visually) if surrounded by expanding content.

### ISSUE THREAD

**Issue by MarinTolic** [GetStream/stream-chat-android#3174]
### Context & proposal

Currently we have an issue where if a user opens a pinned message that is surrounded by expanding content (such as loading images) the pin will be displayed at the correct position for a brief moment before being knocked off screen. 

One of the possible solutions for this is to fetch image dimensions from attachments if they are provided by the backend.
This might introduce the need of having placeholders for images that do not load properly.

<img src="https://user-images.githubusercontent.com/37080097/157010869-f5ee8852-28a2-4fe5-a9c6-c3e4d0ff3f0d.gif" width="360" height="760"/>

### Acceptance criteria

To accept this task we need to complete the following items:

- [ ] Make sure attachments have the correct fixed size even before they load

**Comment by filbabic** [comment]
Closing as we'll work on this improvement through other tickets #3176
