### ISSUE TITLE
`AvatarView` does not remove the online indicator when a channel member goes offline

### ISSUE THREAD

**Issue by MarinTolic** [GetStream/stream-chat-android#3179]
### Context & proposal

Currently `AvatarView` will refresh the online indicator to display online status right after a channel member goes online. However, when a channel member goes offline the online indicator will not disappear until the screen is refreshed.

Note: this applies to members in the channel who are not the currently logged in user.

### Acceptance criteria

To accept this task we need to complete the following items:

- [ ] Make sure the online indicator correctly follows the member state

**Comment by filbabic** [comment]
@adasiewiczr @amitkma @leandroBorgesFerreira this is an item for the core team it seems!
