### ISSUE TITLE
MessageInputView crash on Xiaomi

### ISSUE THREAD

**Issue by spvince** [GetStream/stream-chat-android#3255]
**Describe the bug**
I have a crash with MessageInputView.  It's a crash which happen only on Xiaomi phone. It seems to be a known issue [stackoverflow](https://stackoverflow.com/questions/53435237/nullpointerexception-int-android-widget-editorselectionmodifiercursorcontrolle)

**SDK version**
- 4.30.1

**Crash**
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.widget.Editor$SelectionModifierCursorController.getMinTouchOffset()' on a null object reference
       at android.widget.Editor.touchPositionIsInSelection(Editor.java:1336)
       at android.widget.Editor.performLongClick(Editor.java:1431)
       at android.widget.TextView.performLongClick(TextView.java:12424)
       at android.view.View.performLongClick(View.java:7624)
       at android.view.View$CheckForLongPress.run(View.java:28673)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:8019)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

**Device:**
 - Vendor and model: Xiaomi
 - Android version: 10

**Comment by filbabic** [comment]
Hey @spvince !

Sorry for the late reply - we had triaged this issue and have prioritized it based on our capacity, but we missed responding to let you know of the progress.

Thank you for making us aware of this - we'll use the SO answer you've provided to implement and test this to see if the issue still occurs. We can also let you know once the SNAPSHOT release is available so you can test it on your end.

We'll prioritize this issue this week and we'll try to have a patch release maybe this week (or early next).

Thanks!

**Comment by TGazica** [comment]
Hey @spvince !

Could you please describe how to replicate the exception you are getting?

Thanks!

**Comment by spvince** [comment]
Hi @TGazica,

I don't know how to reproduce exactly but i think you should make a long press. You have more detail here [stackoverflow](https://stackoverflow.com/questions/53435237/nullpointerexception-int-android-widget-editorselectionmodifiercursorcontrolle)

Thanks!

**Comment by filbabic** [comment]
Hey @spvince 

We've tried reproducing thing but had no luck - could you paste here your XML for the Input view and the code you use to set it up?

We're trying to figure out if there's a specific setting in XML or in the java/kotlin code that you're using that triggers this or if it's just the device vendor + OS version (as we tried xiaomi devices but had no luck).

Thanks!

**Comment by spvince** [comment]
Hi @filbabic 

No problem.

This my xml code:
``` 
    <io.getstream.chat.android.ui.message.input.MessageInputView
            android:id="@+id/chat_message_input_view"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:background="@color/white"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:streamUiLightningButtonEnabled="false" />
```

This my kotlin code :
```
 private val messageInputViewModel: MessageInputViewModel by viewModels { factory }
 
     private fun initMessageInputViewModel() {
        Timber.d("initMessageInputViewModel")

        messageInputViewModel.apply {
            bindView((mBinding as ActivityChatBinding).chatMessageInputView, this@ChatActivity)

            messageListViewModel.mode.observe(this@ChatActivity) {
                when (it) {
                    is MessageListViewModel.Mode.Thread -> {
                        messageInputViewModel.setActiveThread(it.parentMessage)
                    }
                    is MessageListViewModel.Mode.Normal -> {
                        messageInputViewModel.resetThread()
                    }
                }
            }

            (mBinding as ActivityChatBinding).chatMessageListView.setMessageEditHandler(::postMessageToEdit)
        }
    }
```

**Comment by filbabic** [comment]
Hey @spvince!

Thanks - we'll try to replicate this and test on more xiaomi devices!

Thank you so much for being patient, hope you're doing well ^^
