### ISSUE TITLE
Users are unable to unblock/ unban members

### ISSUE THREAD

**Issue by MarinTolic** [GetStream/stream-chat-android#3265]
### Context & proposal

Currently we do not provide sufficient information for unblocking/ unbanning members. The issue is that we only provide the `User` and not the `Member` in the event we use for blocking called `BlockUser(val user: User, val cid: String) ` inside `MessageListViewModel`.

A `User` is simply a user and does not belong to any particular `Channel`, where as a `Member` does. Banning/ blocking is done with respect to the membership of a particular user in a particular channel, therefor we need to fetch the `Member`.

### Acceptance criteria

Find a way to pass sufficient information to allow for both blocking/ banning and unblocking/ unbanning a user.

- [ ] Allow the user to both block/ ban and unblock/ unban a user

**Comment by filbabic** [comment]
https://www.notion.so/stream-wiki/09-05-2022-37d7aaf0e064433aa16aa0bf9d483e3f

**Comment by MarinTolic** [comment]
As per the notion document above, the decision has been made to remove blocking / banning and muting the user from message options.
