### ISSUE TITLE
More than one reaction support like iOS stream SDK

### ISSUE THREAD

**Issue by JayMehta97** [GetStream/stream-chat-android#3287]
Currently in Android stream SDK, users can only add one reaction at a time for a message. Adding a new reaction will override the previous one whereas in Stream iOS SwiftUI SDK it supports adding multiple reactions for a user on the same message. As we support both platforms, we would need both user base to have same set of features.

**Comment by filbabic** [comment]
Hey @JayMehta97 !

Are you using Compose or UI Components (View/XML toolkit)? 

In Compose, it's possible to customize this behavior by passing in `enforceUniqueReactions = false` to the ViewModelFactory.

**Comment by JayMehta97** [comment]
Hey @filbabic, 

Currently we are using UI Components toolkit.

**Comment by filbabic** [comment]
Hey @JayMehta97 !

It's not available in UI components currently, so I'll work on providing this functionality in the next release!

Thank you so much for the input.

**Comment by filbabic** [comment]
Hey Jay!

We've opened a PR for this as you can see in the linked PRs. Once it's merged and we release a patch version, you'll be able to use this! :]

We also have SNAPSHOT releases, so feel free to use that to test reactions once the PR is merged.

**Comment by filbabic** [comment]
Hey @JayMehta97 !

We've merged this PR and you can check it out in our snapshot release. You can also wait for the next patch/minor when it'll be available officially!

Thanks!
