### ISSUE TITLE
Previews of videos are not visible in messageList on Android, but on iOS yes

### ISSUE THREAD

**Issue by JeromeCHA** [GetStream/stream-chat-android#3369]
**Describe the bug**
When you send a video via Stream on a channel, you don't have any preview on Android, but on iOS yes. (see screenshots below)

**SDK version**
- 5.0.2

**To Reproduce**
1. Click on the attachment button on the input view
2. Choose a video
3. Send it
4. Check on both Android and iOS and see the difference

**Expected behavior**
It would be glad if we could also have a preview of the video on the message list. It would avoid both apps to have different designs and also different behaviors. It is also more convenient to have the preview rather than the filename so we can figure out what the video is.

**Device:**
 - Vendor and model: Pixel 3
 - Android version: Android 12

**Screenshots**
| iOS | Android |
|:-:|---|
| ![file](https://user-images.githubusercontent.com/11457628/164579971-a1c96491-1cf7-4a07-916d-b94bb9216a0e.jpeg) | ![Screenshot_20220422_103554](https://user-images.githubusercontent.com/11457628/164579993-369077f5-7a2e-4922-984a-987222a320ce.png) |

**Comment by MarinTolic** [comment]
Hey Jerome,

Thank you for reporting this discrepancy.

Video thumbnail previews are indeed on the roadmap for the Android SDKs, however we are currently waiting for certain backend optimizations before we can proceed with the work. Once we implement this we will notify you. :D

In the meantime I will assign this issue to myself and change it from a `bug` to a `feature request`.

Kind regards,
Marin.

**Comment by kylecfoley** [comment]
Hey @MarinTolic,

Is there someone we could speak with at Stream regarding moving this up on the priority list? It will have a significant impact on our chat experience (users will be paying to unlock video content within the chat).

Thanks for your help,
Kyle

**Comment by filbabic** [comment]
Hey @kylecfoley !

We'll see what we can do in terms of the roadmap - in the case, as Marin mentioned, it's a change for the BE team as well and their roadmap is pretty packed. Hopefully we can work something out to have this support ASAP.

As an alternative, we'll look into providing a guide on how to build this custom message item type so that you're not blocked by the request.

As far as speaking to someone from the team about shifting the priority here, we'll look into that as well. We'll let you know as soon as we know more info!

Thanks!

**Comment by kylecfoley** [comment]
Hey @filbabic ! Regarding your note on providing a guide to build custom message type, that would be great :) Thanks

**Comment by JeromeCHA** [comment]
Hey @filbabic, regarding the guide to build a custom message type that would help us, it would be awesome to have it with your UI Component, not Compose UI Component 🙇 
Thank you very much 🙏

**Comment by filbabic** [comment]
Hey @JeromeCHA @kylecfoley !

We'll see if we're able to provide something soon, as we are working through the rest of the items you suggested as well as some other higher priority items.

I'll keep you posted as soon as I know more! :]

**Comment by JayMehta97** [comment]
Hey @filbabic @MarinTolic !

Any updates on this feature or on the guide providing how to build this custom message item type?

Thanks.
