### ISSUE TITLE
Make `MessageInputFieldView`'s `switchToCommandMode` to be open so we can change it via our own button or event

### ISSUE THREAD

**Issue by JeromeCHA** [GetStream/stream-chat-android#3371]
# Describe the feature you'd like to see in the SDK

## What we want
Until now, if we want to switch the `MessageInputFieldView`'s `command mode` we need to trigger the event via the lightning button. It should be nice to have the `switchToCommandMode` command open so we can trigger it via our own button. https://github.com/GetStream/stream-chat-android/blob/0f1f54e912baf7a7284d9a4d1435fb6743aa9c78/stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/internal/MessageInputFieldView.kt#L414

## The problem
The switch to command mode is actually pretty limited since it is only triggerable via the lightning button.

## The solution
I think it should be nice if we can switch the mode as we want, via our own button or event

**Comment by filbabic** [comment]
@JeromeCHA just letting you know an engineer will be taking a look at this this sprint!

We've resolved some of your items already and they've been merged so once more of these are up I'll let you know!

**Comment by filbabic** [comment]
@JeromeCHA Just letting you know this was merge into dev and is available in a [SNAPSHOT ](https://getstream.io/chat/docs/sdk/android/basics/dependencies/#snapshot-builds) release (if you want to test it out).

It'll be available in the next release! :]
