### ISSUE TITLE
Allow left/right padding in `messageEditText`

### ISSUE THREAD

**Issue by JeromeCHA** [GetStream/stream-chat-android#3372]
# Describe the feature you'd like to see in the SDK

## What we want
To allow customization on the `messageEditText` I think it should be better to have a specified `dimens` for the `paddingStart` and `paddingEnd`
https://github.com/GetStream/stream-chat-android/blob/main/stream-chat-android-ui-components/src/main/res/layout/stream_ui_message_input_field.xml#L108-L110

## The problem
Since the `paddingStart` and `paddingEnd` is `@dimen/stream_ui_spacing_medium` we cannot "override" them in our `dimens.xml` to customize it.

## The solution
Same as `stream_ui_attachment_button_size` and `stream_ui_command_button_size`, it would be nice to have a custom dimension so we can override them depending on the design we want.

| Overrides on our `dimens.xml` |
|:-:|
| ![image](https://user-images.githubusercontent.com/11457628/164603957-bb6671e2-ba7b-4215-b75a-b830a9ab8caf.png) |

**Comment by filbabic** [comment]
Hey @JeromeCHA!

Thank you for this item - do you mean you'd like the padding start/end for the input view? Not each specific button.

So something like: `stream_ui_input_padding_end/start`?

Once you confirm this, we'll prioritize it in our sprint and focus on the task!

**Comment by JeromeCHA** [comment]
Hey @filbabic 
> So something like: stream_ui_input_padding_end/start?

Yes exactly! It would be awesome to have it :)

**Comment by filbabic** [comment]
Hey @JeromeCHA!

We have a PR up with this proposed change. https://github.com/GetStream/stream-chat-android/pull/3392

Can you please check if this is what you're looking for, or if it's something else? :]

Thanks!

**Comment by JeromeCHA** [comment]
Hey @filbabic !
That's perfect! Since it was merged, I will close this issue :)
Thank you for the quick support! 🙇
