### ISSUE TITLE
Allow Enable/Disable Ripple Effect on `attachmentsButton` and `commandsButton`

### ISSUE THREAD

**Issue by JeromeCHA** [GetStream/stream-chat-android#3373]
# Describe the feature you'd like to see in the SDK

## What we want
An option to enable/disable Ripple effect on `attachmentsButton` and `commandsButton` as you can see here
![Screen Recording 2022-04-22 at 13 48 01](https://user-images.githubusercontent.com/11457628/164605794-5d9a0ec9-f7d8-4a1b-aa4f-c405fb3efa6c.gif)

## The problem
Depending on the design, we might want to be able to enable/disable those ripple effects or even customize them.

## The solution
Maybe it is better to add an attribute as `reference` so we can put what we want as `ripple`. Same as your did for `streamUiScrollButtonRippleColor`.
https://github.com/GetStream/stream-chat-android/blob/0f1f54e912baf7a7284d9a4d1435fb6743aa9c78/stream-chat-android-ui-components/src/main/res/values/attrs_message_list_view.xml#L8

**Comment by filbabic** [comment]
Hey @JeromeCHA !

This makes sense to me :]

I imagine having a transparent/null ripple color will serve as a way to remove it, so this should serve multiple use cases. We'll prioritize it based on other work and see what we can do ^^

Generally, all the tickets we cover in a given sprint (we start a new one today) will be released in the next version, which comes after the sprint. So in ~2 weeks you can expect these changes, unless we release a patch version in the meantime.

Additionally, we have SNAPSHOT releases whenever something is merged to develop, so once this ticket is closed/merged you'll be able to test the changes out! :]

**Comment by JeromeCHA** [comment]
Hi @filbabic 
Nice! Thank you! I will check it once it will be released 🙇
