### ISSUE TITLE
Multiple query requests are being fired

### ISSUE THREAD

**Issue by kanat** [GetStream/stream-chat-android#3399]
**Steps to reproduce**:

- `UserB` opens the app and stays on the Channel list screen
- `UserA` creates channel `X`
- `UserA` adds UserB to channel `X`
- `UserB` opens channel `X`

**Actual result**:       multiple query requests are being fired from `UserB`

**Expected result**:  single query request should be fired from `UserB`

This behaviour can be verified by [Proxyman](https://proxyman.io) or [CharlesProxy](https://www.charlesproxy.com)

Charles log:
<img width="689" alt="Screenshot 2022-04-25 at 19 38 36" src="https://user-images.githubusercontent.com/1286516/165254042-39f13ecf-86b3-4bf1-bb6b-0f2053f01f8e.png">

**Comment by leandroBorgesFerreira** [comment]
Note: only opening a channel reproduces this problem.
