### ISSUE TITLE
Make sure the `when` expression in `ChatClient::setUser`  handles all possible cases

### ISSUE THREAD

**Issue by adasiewiczr** [GetStream/stream-chat-android#3402]
### Context & proposal
Make sure the `when` expression in `ChatClient::setUser`  handles all possible cases. For example: consider a case when the user is set and we are trying to connect a user with the same id but the socket is already connected/connecting - should we return an error?

**Comment by JcMinarro** [comment]
This issue was covered and fixed on this PR: https://github.com/GetStream/stream-chat-android/pull/3605
