### ISSUE TITLE
Investigate Compose PN sample issues

### ISSUE THREAD

**Issue by filbabic** [GetStream/stream-chat-android#3417]
### Context & proposal

We've had a few PN issues in the Compose sample app that need investigating.

### Acceptance criteria

To accept this task we need to complete the following items:

- [x] Investigate why we sometimes show 2 push notifications (PN and "loading data" PN).
- [x] Clicking on a PN from the BG sometimes doesn't open channels.
- [x] Clicking on a PN from the BG sometimes doesn't update the message list.

**Comment by MarinTolic** [comment]
All three issues seem to be related to installing multiple build types of the same app on your phone and logging in with the same user.

Once either one is deleted and there is only one left on the phone, the issues with PNs disappear. 

Note that #1 did not happen on my phone but did on @bychkovdmitry s.
However, he also had multiple build types present at the time.
