### ISSUE TITLE
Library does not work on API level 23 and lower

### ISSUE THREAD

**Issue by savked** [GetStream/stream-chat-android#343]
Just tested the library via your sample app too and it does not initialize/load on any device API level 23 or lower.

In your build.gradle file it says that the minSdkVersion is 21

https://github.com/GetStream/stream-chat-android/blob/master/library/build.gradle#L13

**Comment by adrian09h** [comment]
@savked Thanks for your this issue reporting. Let me check soon.

**Comment by adrian09h** [comment]
@elevenetc if api level is lower than 23, `URLEncoder.encode(json, StandardCharsets.UTF_8.toString())` occurs `IllegalCharsetNameException`.

https://github.com/GetStream/stream-chat-android/blob/master/library/src/main/java/com/getstream/sdk/chat/rest/core/providers/StreamWebSocketServiceProvider.java#L46

What reason?
