### ISSUE TITLE
Add semantics to Lazy lists

### ISSUE THREAD

**Issue by MarinTolic** [GetStream/stream-chat-android#3431]
### Context & proposal

Semantics need to be added to lazy lists so they can be accessed by UiAutomator for implementing instrumented tests and benchmark tests

### Acceptance criteria

To accept this task we need to complete the following items:

- [ ] Add semantics in the format of purpose + Composable name, e.g. "channelListLazyColumn"

**Comment by filbabic** [comment]
Closing for now to deprioritize
