### ISSUE TITLE
Notifications not working

### ISSUE THREAD

**Issue by Chikrix** [GetStream/stream-chat-android#350]
For many days now I've tried to get notifications working on the app but haven't been successful with this. I've checked my application's Stream Dashboard (push logs), and it tells me that the device isn't registered, even though I successfully added the device, other times it'll say "success" on the Chat Push Logs on my dashboard. I do put my other (receiving) device in the background or closed so it'll get the notification but I don't see any notification even though I could see something from the push logs. What could I be doing wrong?

**Comment by tbarbugli** [comment]
@Chikrix did you look at how the sample app handles push notifications? can you post here the templates you are using? (both notification and data templates)

**Comment by Chikrix** [comment]
Yeah, I copied from the notifications on the library sample and it's still not working. I'm looking at my pushlogs and I'm seeing `publishing the message failed with error: MismatchSenderId`, what could that possibly mean. Adding the device was successful

**Comment by andriizhumela** [comment]
Hi @Chikrix.
Could you show me your code (with logs). I wanna check device registration. Also, could you provide me logs with FCM token?

**Comment by Chikrix** [comment]
I've looked into this and see what was causing it, it was my issue, I was running production firebase project on debug build, we have different stream apps for this the way it was set up.

**Comment by andriizhumela** [comment]
@Chikrix So, do you have others broblem witch can be associated with this issue?

**Comment by Chikrix** [comment]
No problem with notifications again. I'll close the issue now. Thanks for your help
