### ISSUE TITLE
Long clicking a single attachment in a message containing multiple attachments does not trigger showing message options

### ISSUE THREAD

**Issue by MarinTolic** [GetStream/stream-chat-android#3503]
### Context & proposal

In UI Components, long clicking on an individual attachment in a message containing multiple file attachments will trigger message options. In Compose however, this does not happen.

### Acceptance criteria

To accept this task we need to complete the following items:

- [ ] Expose a `Modifier` parameter inside `FileAttachmentItem`
- [ ] Pass the long click action from `FileAttachmentContent` to individual `FileAttachmentItem`s inside the `Column`

**Comment by filbabic** [comment]
Duplicate.
