### ISSUE TITLE
Consider different arrangement for a case with few reactions

### ISSUE THREAD

**Issue by bychkovdmitry** [GetStream/stream-chat-android#3525]
### Context & proposal

Clients can provide their set of reactions. We need to ensure that any number of reactions look good on the reaction options menu.

![telegram-cloud-photo-size-2-5195448181230516963-y](https://user-images.githubusercontent.com/9600921/168751682-034f3b1e-f8a0-42dc-b7b8-235e73eb7a8a.jpg)

### Acceptance criteria

To accept this task we need to complete the following items:

- [ ] Ensure that layout is responsive to any number of reactions

**Comment by filbabic** [comment]
Closing since this is lower priority.
