### ISSUE TITLE
Emojis should be centered vertically inside the EditReaction Bubble & Reaction Bubble

### ISSUE THREAD

**Issue by JeromeCHA** [GetStream/stream-chat-android#3535]
## What are you trying to achieve?
I want to try using our own custom reactions, with custom sizes.

## Current status
Currently, we can override those two `dimens` to have a custom size reactions item, with a custom edit reaction bubble height.
```xml
<dimen name="stream_ui_edit_reactions_item_size">30dp</dimen>
<dimen name="stream_ui_edit_reactions_bubble_height">30dp</dimen>
```
However, if `stream_ui_edit_reactions_bubble_height` is higher than `stream_ui_edit_reactions_item_size`, emojis are stuck on the top.

## How can we handle this
There are two ways to handle this.
1. Center vertically emojis inside the reactions edit bubble.
or
2. Add `stream_ui_edit_reactions_vertical_padding` dimens so we can override it and set our own padding. There is a horizontal padding, but nothing for vertical.
https://github.com/GetStream/stream-chat-android/blob/6eda2c3c6201d04c06d790e3db821e4d475cfffe/stream-chat-android-ui-components/src/main/res/values/dimens.xml#L98

## Screenshots
| What we have | What we want |
|:-:|:-:|
| ![Screen Shot 2022-05-17 at 18 40 32](https://user-images.githubusercontent.com/11457628/168935143-4791d2cc-98c4-4c22-bf7a-cea73e3504d7.png) | ![new](https://user-images.githubusercontent.com/11457628/168935169-7818c426-6774-47c3-a8a3-ed0427aed6dc.png) |

**Comment by JeromeCHA** [comment]
I also changed the title, because if we change this value according to our emoji's size, emojis are also not centered vertically inside the reaction bubble.  
https://github.com/GetStream/stream-chat-android/blob/6eda2c3c6201d04c06d790e3db821e4d475cfffe/stream-chat-android-ui-components/src/main/res/values/dimens.xml#L100

**Comment by filbabic** [comment]
Hey Jerome!

We'll be taking a look at this in the next couple of days! :]

Will LYK around updates ^^

**Comment by filbabic** [comment]
Hey @JeromeCHA !

This one has also been resolved: https://github.com/GetStream/stream-chat-android/pull/3541
