### ISSUE TITLE
`stream_ui_edit_reactions_horizontal_padding` doesn't work when there is only 1 reaction

### ISSUE THREAD

**Issue by JeromeCHA** [GetStream/stream-chat-android#3537]
**Describe the bug**
Currently, we can override `stream_ui_edit_reactions_horizontal_padding` to use our own horizontal padding. Therefore, when there is only 1 reaction, there is no horizontal padding. It is frustrating because we want our designs to be the same no matter how many reactions there are.

**SDK version**
- 5.2.0

**To Reproduce**
1. Override this value in your `dimens.xml` file.
https://github.com/GetStream/stream-chat-android/blob/6eda2c3c6201d04c06d790e3db821e4d475cfffe/stream-chat-android-ui-components/src/main/res/values/dimens.xml#L98

2. Set 1 reaction. You will see no horizontal padding
3. Ask someone to set a reaction, different from yours. There is a horizontal padding

**Expected behavior**
Add horizontal padding when there is only 1 reaction too

**Device:**
 - Vendor and model: pixel 3a
 - Android version: 12

**Screenshots**
![image](https://user-images.githubusercontent.com/11457628/168945058-eaf2ced1-0ebd-4d63-bb6f-7caf79c7dd0d.png)
_I set a high horizontal padding on purpose for the screenshot_

**Comment by filbabic** [comment]
Hery Jerome!

Thank you for raising this - it would seem we're using the padding as a way to space the items evenly with the padding, so in case of one reaction, it doesn't get applied as per:

```
val horizontalPadding = if (isSingleReaction) 0 else reactionsViewStyle.horizontalPadding
            setPadding(horizontalPadding, 0, horizontalPadding, 0)
```

What we could do is maybe expose a property, something like: `applyPaddingToSingleReaction` to override this behavior. Alternatively, we could investigate if this default behavior is something we could change to just apply the padding regardless.

I'll put this into the sprint and we'll let you know once it's resolved!

**Comment by filbabic** [comment]
Hey @JeromeCHA !

This has been added and merged in the following PR: https://github.com/GetStream/stream-chat-android/pull/3541 so be sure to check the behavior either via a snapshot, or when we release (in the next few days)! :]
