### ISSUE TITLE
Global chat search

### ISSUE THREAD

**Issue by teamsupermomos** [GetStream/stream-chat-android#3540]
Most chat app has a global chat search (one at the top of chat channel directory) where you can search for particular keyword and the search result shows you all of its occurrence in all chat channels. You can also click it to quickly be redirected to that particular message. 

Streamchat is a great product for both developers and end users but I think this is one of the most useful "basic" feature missing from the platform.

**Comment by filbabic** [comment]
Hey @teamsupermomos !

We have this feature available in our XML counterpart (UI Components) where we search messages from all available channels for the user and then display them. You can also click on items to be redirected to the channel and/or the message.

Have you tried using our [Search view](https://getstream.io/chat/docs/sdk/android/ui/utility-components/search-view/)?

If you're on Compose - the search implementation there instead looks up channels and members by the query, so it's a bit different. Then this would be an improvement point on the Search feature of the Compose SDK.

Thanks!

**Comment by teamsupermomos** [comment]
Hi Filip,

Thanks for your prompt reply. Do you know if iOS Swift has similar support already in place? I couldn’t find it in the documentation:

https://getstream.io/chat/docs/sdk/ios/

Regards,
Kaizhong (KZ)
CTO and Co-Founder | Supermomos

Follow Supermomos at: LinkedIn<https://www.linkedin.com/company/supermomos/> | Instagram<https://www.instagram.com/team.supermomos/> for latest event updates!

From: Filip Babic ***@***.***>
Date: Wednesday, 18 May 2022 at 15:23
To: GetStream/stream-chat-android ***@***.***>
Cc: Supermomos Dev Team ***@***.***>, Mention ***@***.***>
Subject: Re: [GetStream/stream-chat-android] Global chat search (Issue #3540)

Hey @teamsupermomos<https://github.com/teamsupermomos> !

We have this feature available in our XML counterpart (UI Components) where we search messages from all available channels for the user and then display them. You can also click on items to be redirected to the channel and/or the message.

Have you tried using our Search view<https://getstream.io/chat/docs/sdk/android/ui/utility-components/search-view/>?

If you're on Compose - the search implementation there instead looks up channels and members by the query, so it's a bit different. Then this would be an improvement point on the Search feature of the Compose SDK.

Thanks!

**Comment by teamsupermomos** [comment]
Thanks Filip will do that.

Regards,
Team Supermomos
________________________________
