### ISSUE TITLE
Hot switching from an anonymous user causes the unread count to be null

### ISSUE THREAD

**Issue by MarinTolic** [GetStream/stream-chat-android#3556]
### Context & proposal

Please note that the functionality to hot switch users is contained in the patch in the following [PR](https://github.com/GetStream/stream-chat-android/pull/3550). It is still possible in Compose even without the PR, but needs the PR to be merged in order to be possible in UI Components.

1. Login with an anonymous user (any of the regular users)
2. Hot switch to a non-anonymous user as explained in the testing section of the linked PR
3. Check that this works for switching both from an anonymous to non-anonymous user and between two non-anonymous users

Result: The channel unread count will be null for all channels. If it isn't instantly, repeat the process a few times.

### Acceptance criteria

To accept this task we need to complete the following items:

- [ ] Make sure that the correct unread count is received every time.

**Comment by adasiewiczr** [comment]
Check after merging disonnect refactor
