### ISSUE TITLE
Eliminate `Member.isOwnerOrAdmin` and `List<Member>?.isCurrentUserOwnerOrAdmin` usages

### ISSUE THREAD

**Issue by adasiewiczr** [GetStream/stream-chat-android#3575]
### Context & proposal

In order to remove `Member::role` we need to get rid of `Member.isOwnerOrAdmin` and `List<Member>?.isCurrentUserOwnerOrAdmin` usages from our sample app.
Extension functions should be replaced with `Channel::ownCapabilities`

**Comment by filbabic** [comment]
We've merged the deprecated checks, so we're clear to proceed with removing the role and other extensions that are now invalid (as we should use capabilities).
