### ISSUE TITLE
NullPointerException in Channel.equals

### ISSUE THREAD

**Issue by Nepherpitou** [GetStream/stream-chat-android#358]
Obvious typo in `Channel` class - null pointer exception in https://github.com/GetStream/stream-chat-android/blob/master/library/src/main/java/com/getstream/sdk/chat/model/Channel.java#L395.

**Comment by tbarbugli** [comment]
@Nepherpitou thank you for sharing this! can you share the stack-trace?

**Comment by Nepherpitou** [comment]
@tbarbugli type code into Kotlin REPL:
```
import com.getstream.sdk.chat.model.Channel

val a = Channel()
val b: Channel? = null
a == b
java.lang.NullPointerException
	at com.getstream.sdk.chat.model.Channel.equals(Channel.java:395)
	at kotlin.jvm.internal.Intrinsics.areEqual(Intrinsics.java:162)
```
This issue is critical because when you use Kotlin operator `foo == bar` is equals to `foo.equals(bar)`, unlike java `==` which compares pointers and is safe in that case.
