### ISSUE TITLE
AvatarView customisation options

### ISSUE THREAD

**Issue by TGazica** [GetStream/stream-chat-android#3581]
### Context & proposal

Explore how avatar background and text is populated and see how to expose customisation options for them.

### Acceptance criteria

To accept this task we need to complete the following items:

- [ ] Explore how avatar background and text is populated
- [ ] Expose customisation options for these parameters if they currently can't be customised

**Comment by filbabic** [comment]
Maybe expose a factory for:
- Placeholder drawables
- Background/text factories

We lost a bit of flexibility with new avatars, but we can still do some work.

**Comment by filbabic** [comment]
Closing as we've improved avatars in V6 and this is out of prio.
