### ISSUE TITLE
Safeguarding against disconnects on the messages screen

### ISSUE THREAD

**Issue by MarinTolic** [GetStream/stream-chat-android#3614]
### Context & proposal

Currently, it is possible to disconnect the user on the messages screen and reconnect with another user all while viewing the same channel. The channel can be viewed even if the newly connected user is not a member of it.

Ideally, this should be safeguarded against by the SDK users, however it might be prudent for us to safeguard against it as well.

### Acceptance criteria

To accept this task we need to complete the following items:

- [ ] Discuss safeguarding with the other frontend SDK teams to see if they have implemented it or think it needs to be implemented
- [ ] Proceed according to the consensus reached in the discussion

**Comment by filbabic** [comment]
Closing as it's an edge case.
