### ISSUE TITLE
ChatClient::disconnect should return a Call

### ISSUE THREAD

**Issue by adasiewiczr** [GetStream/stream-chat-android#3643]
### Context & proposal
`ChatClient::disconnect` method should return a `Call` so users are allowed to await it and make sure the client is disconnected.
While disconnecting, we should make sure the socket is closed.

**Comment by JcMinarro** [comment]
Making `ChatClient::diconnect` method to return a `Call` type is a breaking change in our public API.
We can create another method with the same name and returning different type (It is not allowed by the language).
So, alternatively, what we can do is deprecate this method and create new one (`logout()` :thinking:) that return this `Call`type.
BTW, new PR (#3817) has been created that keep `disconnect()` process synchronous to be sure all connections are closed and DB is cleared
