### ISSUE TITLE
Investigate when ChatClient::scope should be cancelled

### ISSUE THREAD

**Issue by adasiewiczr** [GetStream/stream-chat-android#3648]
- [x] #3761
- [ ] #3813
- [ ] #3814

**Comment by filbabic** [comment]
One thing to note is that scope and derivative scopes created from it won't be connected unless they share an underlying `Job` object for lifecycle.

We need to make sure we have a job sitting at the top of the hierarchy by default, to make sure that we can launch stuff in a connected way.

It's also encouraged to have a `SupervisorJob` at the top to make sure that if one of the calls fails, the scope and all its other coroutines are not!
