### ISSUE TITLE
User is able to see channel members even though their role does not have that permission

### ISSUE THREAD

**Issue by JayMehta97** [GetStream/stream-chat-android#3652]
**Describe the bug**
We have upgraded to security permissions v2 and have created few roles in a channel type scope. One of those roles doesn't have the `read-channel-members` permission but yet when they swipe the channel and click on the options button they are able to see the horizontal list of all the members in the chat.

**SDK version**
- 5.3.1

**To Reproduce**
1. Create a role which doesn't have `read-channel-members` permission
2. Add a user to that channel with our newly created role
3. Login with that user and on the channel list screen, swipe the channel and click on the `3 dots` or more options button
4. In the bottom sheet that opens, user will be able to see all channel members

**Expected behavior**
User should not be able to see those channel members

**Device:**
 - Vendor and model: VIVO V2033
 - Android version: 11

**Screenshots**
These are the grants to that role type

![Screenshot 2022-06-07 at 5 59 43 PM](https://user-images.githubusercontent.com/12833091/172379030-dd5e8c0e-209f-4d58-82fb-277dfb4067d1.png)

**Comment by MarinTolic** [comment]
Hey Jay,

This is indeed a missing feature.
Thank you for notifying us, we will implement it and report back once it's done. :D

**Comment by MarinTolic** [comment]
Hey Jay,

After discussing the topic with our backend team I was informed that `read-channel-members` is part of the [actions](https://getstream.io/chat/docs/react/permissions_reference/) section of our permission system, and as such it only guards against querying channel members using the `query_members` endpoint.

It is not intended to hide the members inside a `Channel`.

For now I am closing this issues but if you have explicit need for this, please feel free to leave a comment.

**Comment by JayMehta97** [comment]
Hey @MarinTolic,

Thanks for the replies. We do have a specific use case where we want to hide the members list from a certain channel memeber role. Not sure about how it is implemented but we expected the `read-channel-members` permission to handle this. Can we get an option in Android UI SDK to programatically hide the members list view from the bottom sheet itself?

Thanks.
