### ISSUE TITLE
Write tests for `ChatSocket` events parsing

### ISSUE THREAD

**Issue by amitkma** [GetStream/stream-chat-android#3717]
### Context & proposal
Events parsing is moved in `ChatSocket`. Test cases must be written that check if our parsing logic is correct.

### Acceptance criteria

To accept this task we need to complete the following items:

- [x] Validate all events are parsed as expected. 
- [x] Make sure State is changed based on the server's error code return in events.

**Comment by JcMinarro** [comment]
As far as it has been refactored and created the new `ChatSocketStateService` with its tests, it is covered
