### ISSUE TITLE
Automate compose compiler reports

### ISSUE THREAD

**Issue by MarinTolic** [GetStream/stream-chat-android#3720]
### Context & proposal

In order to keep better tabs on our recomposition performance, Compose compiler reports should be generated on every Compose related PR.

### Acceptance criteria

To accept this task we need to complete the following items:

- [ ] Automate compose compiler reports in a way that makes then front-facing and obvious to the PR author

**Comment by filbabic** [comment]
Closing out since it's deprioritized
