### ISSUE TITLE
Evaluate the possibility of removing legacy View dependencies

### ISSUE THREAD

**Issue by MarinTolic** [GetStream/stream-chat-android#3721]
### Context & proposal

Due to the fact that certain dependencies such as our media player are written using legacy Views, we are not able to reduce SDK bloat.

Analyze all of the bloat points and write them down for future improvements when replacements become available.

### Acceptance criteria

- [ ] Write down all bloat points.

**Comment by filbabic** [comment]
Closing as this seems to be resolved.
