### ISSUE TITLE
Write compose performance guidelines

### ISSUE THREAD

**Issue by MarinTolic** [GetStream/stream-chat-android#3722]
### Context & proposal

We have already covered Compose code style and organization internal guidelines, however we are lacking guidelines focusing on writing good skippable composables that would favor smart recomposition.

### Acceptance criteria

To accept this task we need to complete the following items:

- [ ] Write internal guidelines on writing recomposition optimzed composables.
- [ ] Condense these guidelines into a short public facing docs guide for users.

**Comment by filbabic** [comment]
Closed the PR for now, will do the same with this ticket, let's review this once we have more time for content.
