### ISSUE TITLE
Explore improvements for changing `DeletedMessageVisibility` at runtime

### ISSUE THREAD

**Issue by MarinTolic** [GetStream/stream-chat-android#3737]
### Context & proposal

Due to the way  `messageListItemViewHolderFactory.decoratorProvider` is initialized inside `MessageListView` the runtime mutability of `DeletedMessagesVisibility` is limited.

Explore if we can make the footer respond to changes which allows greater runtime mutability.

### Acceptance criteria

To accept this task we need to complete the following items:

- [ ] Try to improve runtime mutability.

**Comment by filbabic** [comment]
Should be done within #4157
