### ISSUE TITLE
# [Codecov](https://codecov.io/gh/GetStream/stream-chat-react/pull/1610?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=GetStream) Report

### ISSUE THREAD

**Issue by Akusimr** [GetStream/stream-chat-android#3757]
# [Codecov](https://codecov.io/gh/GetStream/stream-chat-react/pull/1610?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=GetStream) Report
> Merging [#1610](https://codecov.io/gh/GetStream/stream-chat-react/pull/1610?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=GetStream) (d408822) into [develop](https://codecov.io/gh/GetStream/stream-chat-react/commit/dd53d5c1fe2707d8807cfec341fbbdd612ff7cfd?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=GetStream) (dd53d5c) will **not change** coverage.
> The diff coverage is `n/a`.

```diff
@@           Coverage Diff            @@
##           develop    #1610   +/-   ##
========================================
  Coverage    79.30%   79.30%           
========================================
  Files          228      228           
  Lines         5789     5789           
  Branches      1636     1636           
========================================
  Hits          4591     4591           
  Misses        1060     1060           
  Partials       138      138           
```

------

[Continue to review full report at Codecov](https://codecov.io/gh/GetStream/stream-chat-react/pull/1610?src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=GetStream).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=GetStream)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/GetStream/stream-chat-react/pull/1610?src=pr&el=footer&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=GetStream). Last update [dd53d5c...d408822](https://codecov.io/gh/GetStream/stream-chat-react/pull/1610?src=pr&el=lastupdated&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=GetStream). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=GetStream).

_Originally posted by @codecov[bot] in https://github.com/GetStream/stream-chat-react/issues/1610#issuecomment-1164084895_

**Comment by JcMinarro** [comment]
Hello @Akusimr 
I am closing this issue because it is not related to our repository.
