### ISSUE TITLE
Ability to add custom button inside message composer input

### ISSUE THREAD

**Issue by kylecfoley** [GetStream/stream-chat-android#3821]
We are looking to add a custom button inside the composer input. Please see desired layout below. We have been able to achieve this using the Swift UI SDK, but not the Android SDK.

<img width="721" alt="Screen Shot 2022-06-30 at 7 33 35 PM" src="https://user-images.githubusercontent.com/13056226/176812213-29c01ad1-f0f8-4422-aba5-3ea89a9f78a8.png">

**Comment by filbabic** [comment]
Hey @kylecfoley!

Are you using the XML or Compose SDK in Android? :]

Since you've already customized a bit of the content, I imagine it's Compose?

You can actually achieve this in Compose too - we have a slot called  `input` and within the `MessageInput`, we have a slot called `innerTrailingContent`.

You can do something like this to replicate your behavior:

```
        val state by composerViewModel.messageComposerState.collectAsState()

        MessageComposer(
            viewModel = composerViewModel,
            input = {
                MessageInput(
                    messageComposerState = state,
                    onValueChange = { composerViewModel.setMessageInput(it) },
                    onAttachmentRemoved = { composerViewModel.removeSelectedAttachment(it) },
                    innerTrailingContent = {
                        // my custom icon goes here
                    }
                )
            }
        )
```

**Comment by kylecfoley** [comment]
Hi @filbabic! Thank you for the fast reply. We actually haven't introduced Compose yet, apologies for not including that in my notes 🙂

**Comment by filbabic** [comment]
Ohh okay in that sense, I'm afraid we don't have a direct way of exposing this customization. SwiftUI is declarative, like Compose, so it's much easier to customize.

In this case, you'd have to alternatively build your own component that represents the UI and actions you'd like. We are working on releasing a more customizable XML variant of the MessageComposerView, but at this point it's not available yet!

**Comment by filbabic** [comment]
This is covered in the MessageComposerView impl and will be available from v6 on as a default.
