### ISSUE TITLE
Can we have option for welcome message text alignment?

### ISSUE THREAD

**Issue by JayMehta97** [GetStream/stream-chat-android#3822]
Currently whenever an user joins a channel with a welcome message then the welcome message text is center aligned in Android UI SDK whereas for iOS SDK it is left aligned. Because of this the UI in Android and iOS look different. Can we have a option to choose the alignment for welcome message text?

**Comment by adasiewiczr** [comment]
hey @JayMehta97,
thanks for reporting this feature request. We added a possibility to customize system message alignment in the PR mentioned above and it'll be shipped in the next version.
I'll notify you once the release is ready

**Comment by MarinTolic** [comment]
@JayMehta97 Please keep in mind that as @adasiewiczr specified we have provided the ability to customize system message alignment. Welcome messages are also system messages as are other things such as moderation related system messages etc.

Once you align one of them, all of them will be aligned using the same approach.
