### ISSUE TITLE
Investigate the lifecycle of the `.asLiveData()` transformation

### ISSUE THREAD

**Issue by MarinTolic** [GetStream/stream-chat-android#3908]
### Context & proposal

Currently we are using `.asLiveData()` without passing in a `CoroutineContext`. Depending on how smart the implementation of `.asLiveData()` is, this may or may not lead to issues.

### Acceptance criteria

To accept this task we need to complete the following items:

- [ ] Investigate the matter talked about in the 'Context & proposal' section and take appropriate steps if necessary.

**Comment by filbabic** [comment]
We've already investigated - things should be fine.
