### ISSUE TITLE
In some situation, upsertMessage needs to check whether message is existed

### ISSUE THREAD

**Issue by workspace** [GetStream/stream-chat-android#3986]
**Describe the bug**
Unexpected message is shown in channel's message list. 

**SDK version**
- 5.6.1

**To Reproduce**

case 1
1. search message which is sent in past
2. add reaction to it
3. SendReactionListenerImpl.doOptimisticMessageUpdate upsert reaction's message into ChannelLogic -> message will be placed in the top of message list and pagination is broken.

case 2
1. in ChannelLogic, I think messages of events which are related with Reaction should be upserted when it is existed. (also MessageUpdatedEvent...)

**Expected behavior**
Message should be upserted to ChannelState when it is existed for some situation. 

**Device:**
- all

**Comment by adasiewiczr** [comment]
Hey @workspace,
that's a good observation. We have it in our roadmap and hopefully, we'll be able to improve it soon!

**Comment by workspace** [comment]
@adasiewiczr Thank you for reply. I see some related issues with this and understand how it will be improved!
