### ISSUE TITLE
Display user avatars in messaging chat notifications

### ISSUE THREAD

**Issue by cvb941** [GetStream/stream-chat-android#4053]
### Context & proposal

Messaging-style notifications currently display only the users' initials next to their names.
![image](https://user-images.githubusercontent.com/2351527/185177430-5f916fb1-cdf0-42a6-8e40-0705335f4035.png)

### Acceptance criteria

Messaging notifications should **display the users' avatar images** if they have one.

This is the line of code where the icon logic should be added:
https://github.com/GetStream/stream-chat-android/blob/c5d084f4199c38a6d22e0b857f3b08ee5604576b/stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/handler/MessagingStyleNotificationHandler.kt#L150

**Comment by JcMinarro** [comment]
Hello @cvb941 
We are going to investigate how to properly implement it, because `Person.Builder` only accepts `IconCompact`, and an `IconCompact` can't be created from an URL.
We need to try to download it and convert it to a Bitmap or file

**Comment by adasiewiczr** [comment]
hey @cvb941,
I'm closing the issue as the fix was shipped in version 5.9.0. You can find more information [here](https://github.com/GetStream/stream-chat-android/releases/tag/v5.9.0)
