### ISSUE TITLE
Hide the commands button in MessageComposer when no commands are enabled for a channel

### ISSUE THREAD

**Issue by cvb941** [GetStream/stream-chat-android#4054]
### Context & proposal

When the default giphy command in a channel is turned off (there are no commands for the channel), the MessageComposer still displays the lightning bolt button on the composing bar. Tapping on the button in this case currently does not do anything.

![image](https://user-images.githubusercontent.com/2351527/185199503-ff5bd82c-1171-4580-82c0-9c1aded75c45.png)

### Acceptance criteria

Hide the command button when no commands are available in the channel.

**Comment by TGazica** [comment]
Hey @cvb941,

thanks for bringing it to attention, a pr has been opened, please check it out and let me know if you need anything else. It will be inside a SNAPSHOT release after it is merged and will be in the next release.

**Comment by cvb941** [comment]
The PR looks OK, thanks for the fast action!
