### ISSUE TITLE
Review embedded Activity themes 

### ISSUE THREAD

**Issue by bychkovdmitry** [GetStream/stream-chat-android#4091]
### Context & proposal

Currently embedded activities in UI Components like gallery Activity show purple status bar. Activities in Compose don't have explicit themes at all. That means that if a client has application theme with toolbar our `ImagePreviewActivity` will show two toolbars. We need to specify themes explicitly not to rely on the inherited app theme. 

Also, clients should be aware how to override a theme. E.g.:
```
<activity
       android:name="io.getstream.chat.android.compose.ui.attachments.preview.ImagePreviewActivity"
       android:theme="@style/Theme.MaterialComponents.DayNight.NoActionBar"
       tools:replace="android:theme"
/>
```

We need to improve the themes that we use for activities in our SDKs. 

### Acceptance criteria

To accept this task we need to complete the following items:

- [x] All embedded activities in UI Components specify theme explicitly
- [x] All embedded activities in Compose specify theme explicitly
- [x] UI Components Activities have reasonable status bar colors in both light and dark modes
- [x] Compose Activities have reasonable status bar colors in both light and dark modes

**Comment by filbabic** [comment]
We can work on the small "guide" as a separate ticket.
