### ISSUE TITLE
MessageInputView XML attributes app:streamUiAttachButtonEnabled doesn't work as intended

### ISSUE THREAD

**Issue by florian-do** [GetStream/stream-chat-android#4097]
**Describe the bug**
When you use the XML attributes `streamUiAttachButtonEnabled` for the UI component `io.getstream.chat.android.ui.message.input.MessageInputView` it doesn't hide the attachement button

Edit : When you tap on the editTextField and start writing something the view is updated and the attachement button is correctly hide, but on the default state the attribute is not applied correctly

**SDK version**
- 5.8.2

**To Reproduce**
* Implement a basic `io.getstream.chat.android.ui.message.input.MessageInputView`
* bind the viewModel to the view
* add the XML attributes `app:streamUiAttachButtonEnabled="false"`
* build

**Expected behavior**
The attachement button should be GONE

**Device:**
 - Vendor and model: Pixel 3
 - Android version: Android 12

**Screenshots**
<img width="530" alt="image" src="https://user-images.githubusercontent.com/3480529/186712472-e422eb09-384d-4138-abc3-4881bf0b23f4.png">

![image](https://user-images.githubusercontent.com/3480529/186712637-dad39b3b-806f-4866-bac1-c0bdf2beb76d.png)

FYI:  there is the same behaviour on the `io.getstream.chat.android.ui.message.composer.MessageComposerView`, both `streamUiMessageComposerAttachmentsButtonVisible` and `streamUiMessageComposerCommandsButtonVisible` doesn't hide the target button

**Comment by MarinTolic** [comment]
Hi @florian-do ,

We were able to confirm the bug with `MessageInputView` and fix it.

When it comes to the situation you described with `MessageComposerView` we were only able to reproduce it given that the View was not previously bound. Whenever it was bound, it would work fine. However, we've still made some changes that mitigate the previously mentioned situation and make the View respect the attributes even when no `ViewModel` is bound to it.

If you want to, you can test out the PR  #4107 and let us know if this fixes your issue.  :smile: 

Kind regards,
Marin.

**Comment by adasiewiczr** [comment]
hey @florian-do ,
I'm closing the issue as the fix was shipped in version 5.9.0. You can find more information [here](https://github.com/GetStream/stream-chat-android/releases/tag/v5.9.0)

**Comment by florian-do** [comment]
Hey @MarinTolic @adasiewiczr 
Thanks you for your fast answer !

I'm waiting that the version 5.9.0 is available in maven to test and I will let you know
thanks a lot !
