### ISSUE TITLE
Improve slow mode

### ISSUE THREAD

**Issue by bychkovdmitry** [GetStream/stream-chat-android#4121]
### Context & proposal

Our countdown timer has a lifecycle bound to `MessageComposerController`. We should rely on channel state to display it so that leaving the screen and coming back doesn't reset the timer.

### Acceptance criteria

To accept this task we need to complete the following items:

- [ ] #4147

**Comment by filbabic** [comment]
We've improved the slowdown mode a lot on our end, but this ticket still can be worked on.

I'll leave it as open but merged, if we decide to continue.

**Comment by filbabic** [comment]
Closing this issue, but pulling out the rest as a separate task.
