### ISSUE TITLE
Missing proper rationale after first time permission denial

### ISSUE THREAD

**Issue by better-dmitriy** [GetStream/stream-chat-android#4128]
**Describe the bug**
The first time you deny permissions after clicking on attackButton, a snackbar appears that sends you to the settings instead of a dialog with an explanation

**SDK version**
- 5.9.0

**To Reproduce**
1. Go to `MessageInputView`
2. Click on `attachmentsButton`
3. Decline permissions for the first time

**Expected behavior**
A dialog should appear explaining why these permissions are needed and suggesting that you ask for permissions again (the "Grant" button)

In the sdk code I found this logic, but the condition is true all the time and the first block is executed instead of the second one:

 ```
if (mumultiplePermissionsReport.isAnyPermissionPermanentlyDenied) {
    snackbarPermissionsListener(view, snackbarMessage).onPermissionsChecked(
        mumultiplePermissionsReport
    )
} else {
    dialogPermissionsListener(
        view.context,
        dialogTitle,
        dialogMessage
    ).onPermissionsChecked(mumultiplePermissionsReport)
}
```

**Device:**
 - Any
 - Android version: Any 23+

**Screenrecord**

https://user-images.githubusercontent.com/105278930/188436796-d20a18fa-22fe-4fe4-b2db-12d0ec89394e.mp4

**Comment by TGazica** [comment]
Hey @better-dmitriy,

in case of our SDK the ratinale dialog is replaced with snackbar. If the permission is denied for good, we cant request it again and need to send the user to the settings.
