### ISSUE TITLE
Text colors for the chat message bubbles is not configurable

### ISSUE THREAD

**Issue by monil-shah-13** [GetStream/stream-chat-android#4171]
**Bug Description**
We are migrating from **Android xml** based sdk to the latest version of **Jetpack Compose** sdk for chat. In xml based ui, we were getting an option to change the text color of the chat message bubble for the sender and the receiver. But in the new **Jetpack Compose** based ui we do not have that option. We are only able to change the background color for the chat message bubbles.

With the help of typography there is an option for text style where we can pass color, but it also does not apply to the text. But still no option for own message and other message.

**SDK version**
- 5.9.0 Jetpack Compose UI

**Expected behavior**
We should be getting the option to modify the text color as black might not always look good on the background color.

**Comment by filbabic** [comment]
Hey @monil-shah-13 !

This is now customizable, as seen in https://github.com/GetStream/stream-chat-android/pull/4175.

I'll close this ticket for now!

**Comment by monil-shah-13** [comment]
Thanks @filbabic
