### ISSUE TITLE
Not able to configure the visibility of subtitle in the Message Screen Header Jetpack Compose

### ISSUE THREAD

**Issue by monil-shah-13** [GetStream/stream-chat-android#4178]
**Bug Description*
We have a case wherein we want to hide the member count, typing status etc for some channels. This was supported in the XML based ui but not in the Jetpack Compose UI.
In Jetpack Compose, we do not have option to set the visibility of the subtitle of the Message Screen Header component. In XML based ui there was an option to hide the subtitle of the header. 

**SDK version**
- 5.9.0

**Expected behavior**
A simple configuration should be made available to hide the subtitle for the **MessageScreen** Component.

**Comment by filbabic** [comment]
Hey @monil-shah-13!

Given that you're using the MessagesScreen and ChannelsScreen components, it's likely that most of the issues you've reported can be easily resolved, if you used Bound components instead and combined them in a way that works for you.

For example in this case, you could easily use our [header component](https://getstream.io/chat/docs/sdk/android/compose/message-components/message-list-header/) and override the `centerContent` slot to show the channel name. That way it won't show the subtitle.

For this [ticket](https://github.com/GetStream/stream-chat-android/issues/4179), you can just use a ChannelList and override its `onChannelLongClick` parameter allowing you to control the long tap of each item, as seen in the [documentation](https://getstream.io/chat/docs/sdk/android/compose/channel-components/channel-list/). We can also expose this as an extra param to the ChannelsScreen, but these Screen components are used for very simple use cases, without a lot of customization.

As for this [ticket](https://github.com/GetStream/stream-chat-android/issues/4180), it's a valid point, we'll work on adding the parameter of the focused message to Compose.

**Comment by filbabic** [comment]
You can also see what each component type is best used for here in our documentation: https://getstream.io/chat/docs/sdk/android/compose/component-architecture/

As you can see, Screen components are meant to be very easy to use, but mostly for MVP like use cases or cases which don't require a lot of control or customization.

Alternatively, it is very easy to just combine two bound components that let you customize pretty much anything from slots, handlers of clicks, long taps, events etc to data sets.

**Comment by monil-shah-13** [comment]
Hi @filbabic,

Thanks for the quick response.

For this [ticket](https://github.com/GetStream/stream-chat-android/issues/4179), we are able to solve the issue by using the ChannelList and override its onChannelLongClick parameter.

**Comment by monil-shah-13** [comment]
Hi @filbabic,

By using the [header component](https://getstream.io/chat/docs/sdk/android/compose/message-components/message-list-header/) and overriding the centerContent slot to show the channel name works for us. That solves the issue of hiding the subtitle. 

Thanks for the quick response and providing solution.

**Comment by filbabic** [comment]
Hey @monil-shah-13 !

No worries - I'm glad we could help - as I mentioned, having Screen components is good for lower level of customization, if you want a clean and fresh experience that doesn't change too many things design wise or feature wise - but bound components are also very easy to use and give you tons of customization!

closing this ticket for now!
