### ISSUE TITLE
Cannot disable long press on a Channel in ChatScreen in Jetpack Compose

### ISSUE THREAD

**Issue by monil-shah-13** [GetStream/stream-chat-android#4179]
**Bug Description**
We are using the **ChatScreen** component from the Jetpack Compose UI components SDK. There is an option for long pressing the channel to get options like View Channel Info, Mute Channel etc. We have a case where we would like to disable it for some channels. Currently there is no option to disable or enable it.

**SDK version**
- 5.9.0

**Expected behavior**
There should be an option to enable or disable the long press on a channel.

**Comment by filbabic** [comment]
Resolving this as we expose the handler on the ChannelList!

Thanks!
