### ISSUE TITLE
ANR from Gson

### ISSUE THREAD

**Issue by jeffdgr8** [GetStream/stream-chat-android#418]
I have logs indicating ANRs caused by the Stream SDK doing JSON deserialization on the main UI thread. This should be done on a background thread.

```
java.util.HashSet.<init> (HashSet.java:105)
com.google.gson.internal.$Gson$Types.resolve ($Gson$Types.java:337)
com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields (ReflectiveTypeAdapterFactory.java:160)
com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create (ReflectiveTypeAdapterFactory.java:102)
com.google.gson.Gson.getAdapter (Gson.java:458)
com.google.gson.Gson.toJson (Gson.java:696)
com.google.gson.Gson.toJson (Gson.java:683)
com.google.gson.Gson.toJson (Gson.java:638)
com.google.gson.Gson.toJson (Gson.java:618)
com.getstream.sdk.chat.rest.StreamWebSocketService$1.run (StreamWebSocketService.java:88)
android.os.Handler.handleCallback (Handler.java:873)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:193)
android.app.ActivityThread.main (ActivityThread.java:6971)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:865)
```

Looking at the code in `StreamWebSocketService`, it seems this routine gets [run every 30 seconds](https://github.com/GetStream/stream-chat-android/blob/master/library/src/main/java/com/getstream/sdk/chat/rest/StreamWebSocketService.java#L90).

It's actually getting posted to run again [here](https://github.com/GetStream/stream-chat-android/blob/master/library/src/main/java/com/getstream/sdk/chat/rest/StreamWebSocketService.java#L120) after a 1 second delay, with what seems to be a bug. Seems `mMonitor` should be posting `mMonitor` to run again after `monitorInterval`, right? Definitely don't want that running every 1 second on the main UI thread though. As is, `mMonitor` only gets run once after `startMonitor()` is called. But then `mHealthCheck` gets called twice every 30 seconds, each 1 second apart.

And it seems the code actually doesn't intend to run these routines on the main UI thread. There is a `EventHandlerThread`, `eventThread` being created and started. But `EventHandlerThread.mHandler` is not associated with this thread. `Handler`s are associated with the thread they are constructed on, which is whatever thread `EventHandlerThread` is constructed on, which is apparently the main UI thread.

`EventHandlerThread.mHandler` should be constructed in the thread's `run()` method, so that it's constructed on this thread. But `Handler`s can only be associated with a thread that has a `Looper` associated with it, so `Looper.prepare()` and `Looper.loop()` also need to be called. [See docs](https://developer.android.com/reference/android/os/Looper).

**Comment by jeffdgr8** [comment]
I ran the master branch on a debugger and confirmed everything is happening as I described. Made the changes to fix in https://github.com/GetStream/stream-chat-android/pull/419.

Considering the `mMonitor` routine wasn't being run on any interval before, is it really necessary for this to run every second?

**Comment by samiuelson** [comment]
I believe the issue is already fixed. If you spot any other related faults, please raise new issue in https://github.com/GetStream/stream-chat-android-client project.
