### ISSUE TITLE
Giphy action doesn't appear in commands button

### ISSUE THREAD

**Issue by JayMehta97** [GetStream/stream-chat-android#4189]
**Describe the bug**
I have commands enabled and giphy as the allowed commands from dashboard for a channel type but in UI the commands button doesn't appear at all.

I tried to enable all commands (giphy, mute, unmute, ban and unban) and also tried them in different combinations, it seems like only mute and unmute are sent in config.commands array of a channel to frontend, other options don't appear in the commands menu. If I only have giphy, ban and unban as commands from dashboard then the commands button is not shown as the frontend SDK gets empty commands array. Although giphy command didn't appear in commands menu, I was able to use giphy by typing `/giphy` in message text field and it was working fine.

This issue is also happening in iOS SDK.

**SDK version**
- 5.10.0

**To Reproduce**
1. Go to stream dashboard
2. Enable `commands` for a channel type and keep giphy as the allowed command3. 
3. Go to a chat in app of same channel type
4. The commands button should be missing in the footer but you should be able to use giphy by typing `/giphy`

**Expected behavior**
Commands menu should show all enabled commands

**Device:**
 - Vivo V2033
 - Android version: 11

**Comment by JcMinarro** [comment]
Hello @JayMehta97 
We need to investigate it with our backend team and we will need some private info of your account.
Would you mind opening a ticket [here](https://getstream.io/contact/support/) with your AppId, channel type, and users you are using?
If you could add a link to this issue on the ticket would be great to be able to join them and handle it together

**Comment by filbabic** [comment]
Closing as this seems to be resolved.
