### ISSUE TITLE
ChannelListViewModel filters aren't obeyed as new messages come in

### ISSUE THREAD

**Issue by hustoj2** [GetStream/stream-chat-android#4190]
**Describe the bug**

When viewing a list of Channels populated by the `ChannelListViewModel`, any Channels for which the current user is a member will temporarily appear in the channel list when a new message is added, even if they don't match the filter provided to the `ChannelListViewModel`.

**SDK version**
- 5.11.0 (seems to be an issue since at least 5.6.0 as well)

**To Reproduce**
1. In the `stream-chat-android-components-ui-sample`, change the `ChannelListFragment`'s `type` filter from "messaging" to any other value (I used "team")
2. Run the sample app with the changes from Step 1, and select a user (User A). Let's call this Device 1.
3. Observe that the "Chats" tab has no items, assuming User A isn't a member of any channels with the `type` you entered in Step 1
4. On another device (this other device _shouldn't_ have the change made in Step 1) as a different user (User B), send a new message to any Channel for which User A is a member. This could probably be done from a web browser as well.
5. [Bug] Observe that on Device 1 (User A), the Channel with a new message from Step 4 appears in the list temporarily, even though it doesn't match the filter specified in the `ChannelListFragment`.
6. After some amount of time (or kill the app and relaunch), this incorrect channel then disappears from the list again.

**Expected behavior**

The Channel from Step 4 should never appear in the list on Device 1, since it doesn't match the filter.

**Device:**
 - Vendor and model: Samsung GS21
 - Android version: 12

(Also occurs on Google Pixel 5, Android 13)

**Comment by JcMinarro** [comment]
Thanks for reporting it.
I will investigate it

**Comment by JcMinarro** [comment]
Hello @hustoj2 
It is the default behavior of our `ChannelListView`.
As we explain in [our docs](https://getstream.io/chat/docs/sdk/android/client/guides/channel-list-updates/), you can override this behavior by setting your own `ChatEventHandler`.
Let us know if this fix your issue

**Comment by hustoj2** [comment]
Thank you so much for the link to the docs - they are very helpful and clear! I haven't implemented this yet but it appears straightforward.

Out of curiosity, can you help me understand a valid use case where the current default behavior is more desirable and/or intuitive than the alternative? In my mental model, it seems I have to set up the ChannelListView and give it a query filter, and then also override an event handler with the same filter as if to tell the ChannelListView that I really meant it during my initial setup.

**Comment by hustoj2** [comment]
As mentioned above, what I really want to do in my `ChatEventHandler` is apply the identical filter that I'm passing into my `ChannelListViewHolder` in the first place. The example `ChatEventHandler`s in your docs only show checking for a single attribute. Is there a simple way to check if an incoming `Channel` matches the criteria of a `FilterObject`? I'm having a little trouble figuring that out. While I could check the attributes of the filter one by one, that seems quite redundant. And in my case the `FilterObject`s often have more than a handful of attributes to check. Thanks in advance for the help! I'm trying to get this fix into our release early Monday CT if possible.

**Comment by hustoj2** [comment]
Also, for `handleCidEvent()`, the `cachedChannel` param is nullable. Some of my filter criteria relies on the `extraData` of the `Channel`.  So it seems I won't have enough information within the `handleCidEvent()` method to filter out irrelevant `Channel`s unless it has a `cachedChannel`. What will the behavior be if I have `handleCidEvent()` skip all updates where `cachedChannel` is null? Would it still be able to reliably show new `Channel`s right when I get added as a member?

**Comment by hustoj2** [comment]
> Also, for `handleCidEvent()`, the `cachedChannel` param is nullable. Some of my filter criteria relies on the `extraData` of the `Channel`. So it seems I won't have enough information within the `handleCidEvent()` method to filter out irrelevant `Channel`s unless it has a `cachedChannel`. What will the behavior be if I have `handleCidEvent()` skip all updates where `cachedChannel` is null? Would it still be able to reliably show new `Channel`s right when I get added as a member?

In my testing so far, for channels I'm newly added to, it seems like I'm reliably getting events that do have `cachedChannel` populated. However, this `cachedChannel` often has its `messages` list empty even though there are messages in the Channel. My filter logic on some of our lists intend to only show Channels if they have at least one message in them, so it seems like I might not be able to replicate that filter behavior exactly if I want to have channels I'm newly added to immediately appear in the list.

At the moment, ignoring the messages in my filter criteria seems like an okay sacrifice on our end. Better in our case to show empty channels than to lose the immediacy when being added to existing channels.

Overall, I think I have this working well enough to move forward. But if you have any additional guidance here that would help me, it would be appreciated! Once I hear back, I'll close the issue. Thanks again.

**Comment by JcMinarro** [comment]
> Thank you so much for the link to the docs - they are very helpful and clear! I haven't implemented this yet but it appears straightforward.
> 
> Out of curiosity, can you help me understand a valid use case where the current default behavior is more desirable and/or intuitive than the alternative? In my mental model, it seems I have to set up the ChannelListView and give it a query filter, and then also override an event handler with the same filter as if to tell the ChannelListView that I really meant it during my initial setup.

Hello @hustoj2 
The problem we have with the SDK is that `Filters` can't be applied locally because they could be complex and maybe we don't have all data we need to apply those filters properly. Because of that, we chose the "more common behavior" our customers use but allowing them to override this behavior if they need anything more different. Some time ago we implemented some "[local filtering](https://github.com/GetStream/stream-chat-android/blob/main/stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/utils/internal/CustomObjectFiltering.kt)" functionality, but as I said before, the entities we have in local could not contain all data we need to perform the filters, and they would create false positives/negatives.

Related `cachedChanel`, it shouldn't be null whenever you have it in local.  If you don't have it in local, it is normally because you are being added to this channel (No messages to it yet), then, when a new message arrive to this channel, a new events should arrive to you with the needed `cachedChanel`

Related messages into the Channel, the channel data is loaded from local (From or device db) and we are not loading all messages into on this case to not penalize performance, but `Channel` should have the property `lastMessageAt` that indicate the date of the last message. It is a nullable property, so if it is `null` the channel was created but no messages has been sent to it. Could you use this property for your custom filter? 

Let us know if it help you and if you need anything else.

**Comment by hustoj2** [comment]
> Channel should have the property lastMessageAt that indicate the date of the last message. It is a nullable property, so if it is null the channel was created but no messages has been sent to it.

That is perfect, thank you! I should have thought of that, since that's what we use on the `FilterObject`
