### ISSUE TITLE
Notifications don't appear when app is killed

### ISSUE THREAD

**Issue by JayMehta97** [GetStream/stream-chat-android#4210]
**Describe the bug**
Chat notifications are not shown when app is killed and are only shown when app is in foreground or background.

We recently upgraded from `4.28.2` to `5.11.0`. In `4.28.2`, notifications were shown correctly in all scenarios but after we upgraded the SDK to `5.11.0` we have started facing this issue.

In `4.28.2` the app shows 2 notifications, one with correct data and another with `Loading notification data` text which would disappear in few seconds. In `5.11.0` its the same behaviour of 2 notifs when app is in foreground or background but when app is  killed then the app shows only 1 notification with `Loading notification data` text which would disappear in few seconds.

Also raising support ticket with app, channel and user info.

**SDK version**
- 5.11.0

**To Reproduce**
1. Kill the app in device A
2. Send a message from device B to device A
3. Device A won't show notification with correct data

**Expected behavior**
User should receive notification with correct data

**Device:**
 - Vendor and model: Vivo V2033
 - Android version: 11

**Screenshots**

When app is in foreground or background. The `Loading notification data` notification will disappear in few seconds:-
<img width="407" alt="Screenshot 2022-09-28 at 4 44 29 PM" src="https://user-images.githubusercontent.com/12833091/192765532-c0db86db-9ff9-420b-aa5c-5ed826627f21.png">

When app is killed. The `Loading notification data` notification will disappear in few seconds:-
<img width="411" alt="Screenshot 2022-09-28 at 4 45 03 PM" src="https://user-images.githubusercontent.com/12833091/192765567-eae22d3d-ddf6-4137-b522-0511619e5fe9.png">

**Comment by JayMehta97** [comment]
Hey @JcMinarro,

We are initializing the SDK as recommended in the docs inside `onCreate` method of the app.

We do you use custom notification handler. We don't directly use stream chat inside our app, we have created a chat module which uses stream and then we import that chat module in our main app.

Initialising our module app from main app:
```
override fun onCreate() {
        super.onCreate()
        ...
        CustomChatModule.init(
            apiKey = STREAM_CHAT_KEY,
            this,
            notificationIcon = R.drawable.ic_logo
        ) { messageId: String, channelType: String, channelId: String ->
            Intent(this, SomeActivity::class.java).apply {
                flags = FLAG_ACTIVITY_NEW_TASK
                val url =
                    AppConstants.DeepLink.Path.chatMessageUrl + messageId + "/" + channelType + "/" + channelId
                data = Uri.parse(url)
            }
        }
       ...
}
```

Initialising stream chat from chat module:
```
fun init(
    apiKey: String,
    context: Context,
    @DrawableRes notificationIcon: Int?,
    getNotificationHandlerIntent: (messageId: String, channelType: String, channelId: String) -> Intent
) {
    val notificationConfig = NotificationConfig(
        pushDeviceGenerators = listOf(
            FirebasePushDeviceGenerator()
        )
    )

    val notificationHandler = CustomNotificationHandler(
        context = context,
        getNotificationHandlerIntent = { messageId: String, channelType: String, channelId: String ->
            getNotificationHandlerIntent(messageId, channelType, channelId)
        },
        notificationIcon = notificationIcon
    )

    val offlinePluginFactory = StreamOfflinePluginFactory(
        config = Config(
            backgroundSyncEnabled = true,
            userPresence = true,
            persistenceEnabled = true,
            uploadAttachmentsNetworkType = UploadAttachmentsNetworkType.NOT_ROAMING,
        ),
        appContext = context,
    )

    ChatClient
        .Builder(apiKey = apiKey, appContext = context)
        .withPlugin(offlinePluginFactory)
        .notifications(notificationConfig, notificationHandler)
        .build()

    log(message = "Created chat client")
    CustomChatConfiguration.setup(context)
}
```

Custom notification handler:
[CustomNotificationHandler.txt](https://github.com/GetStream/stream-chat-android/files/9672582/CustomNotificationHandler.txt)

Let me know if any more details are needed. Most of the code inside custom notification handler is taken from stream's notification handler but of earlier version, not sure if we need to update it as we have updated streams SDK version.

Thanks.

**Comment by JayMehta97** [comment]
Hey @JcMinarro,

Any update on this?

**Comment by JcMinarro** [comment]
Hello @JayMehta97 
Sorry for the delay. 
I have been reviewing your implementation and it looks good. I have been trying to replicate this issue on our side but I couldn't replicate it.
Could you verify that when the app is killed and a Push Notification is received (You said the "loading notification data" notification is shown, it should only be shown when a PN is received from our server and we are fetching the message data) our Chat SDK is initialized by the code you show us on your previous comment?
On the other hand, I would like to know if you are manually disconnecting the user by calling `ChatClient.disconnect()`, and on that case if you are passing true/false on the `flushPersistence` arguments.
If you pass true as argument, the userCredentials will be deleted, and on that case PN can be dropped.

**Comment by JayMehta97** [comment]
Hey @JcMinarro,

We are manually disconnecting the user but with argument as `false` and still it has the same behaviour. 

This issue is a blocker for our next priority release. Can we connect over a quick call so that we can resolve this?

Thanks.
