### ISSUE TITLE
Move ClientState.user to GlobalState.user

### ISSUE THREAD

**Issue by leandroBorgesFerreira** [GetStream/stream-chat-android#4227]
### Context & proposal

The state of `User` can only be properly updated using plugins (state plugin handles events). This way we should you provide the state of `User` in the `state` module. 

### Acceptance criteria

- [ ] ClientState.user is moved to GlobalState.user and the usages of ClientState.user are refactored in the SDK.

**Comment by kanat** [comment]
We would also need to alter `ChatClient.getCurrentUser(): User`, since we agreed that `ChatClient` should not expose `user`.
We might turn it into either `ChatClient.getCurrentUserId(): String` or `ChatClient.getCurrentUser(): InputUser`
