### ISSUE TITLE
Show more overlay is too light when the device is in dark theme mode

### ISSUE THREAD

**Issue by MarinTolic** [GetStream/stream-chat-android#4256]
### Context & proposal

The overlay used to show how much more media is left in a message is too light when the device is in dark mode and creates an ugly clashing UI.

| Light Theme | Dark Theme |
| --- | --- |
| ![Screenshot_1665390157](https://user-images.githubusercontent.com/37080097/194825181-7b6abd6c-930b-4e4f-977d-4bfe015c8667.png) | ![Screenshot_1665390146](https://user-images.githubusercontent.com/37080097/194825185-b5df618d-9f0e-4360-9c70-04313bd56ddd.png) |

### Acceptance criteria

- [ ] Find a good design solution.

**Comment by filbabic** [comment]
Hardcode a "dark" overlay for the last item and put literal white text color
