### ISSUE TITLE
Remove guides from Android-Samples repo

### ISSUE THREAD

**Issue by bychkovdmitry** [GetStream/stream-chat-android#4277]
### Context & proposal

The guides were moved to the main repo. We need to remove them from [Android-Samples](https://github.com/GetStream/Android-Samples) repo.

### Acceptance criteria

To accept this task we need to complete the following items:

- [ ] https://github.com/GetStream/Android-Samples/tree/main/compose-custom-attachments guide is removed
- [ ] https://github.com/GetStream/Android-Samples/tree/main/custom-attachments-message-composer guide is removed
- [ ] https://github.com/GetStream/Android-Samples/tree/main/custom-attachments-message-input guide is removed

**Comment by filbabic** [comment]
We can keep them there for now, not a huge issue.
