### ISSUE TITLE
Text color issue in Quoted Message

### ISSUE THREAD

**Issue by monil-shah-13** [GetStream/stream-chat-android#4326]
**Describe the bug**
When the `ownMessageText` is set as `white` and the user quotes a reply to his own message, the quoted message bubble text gets camouflaged with background as the background is always white. This happens only in the jetpack compose sdk. In the xml based sdk, it used to work as expected with same color configuration. Can we have the same behaviour as same as in xml?

**SDK version**
- 5.11.2

**To Reproduce**
1. Set the colours as follows:
   
```
ownMessageText = colorResource(R.color.white),
otherMessageText = colorResource(R.color.black)
```

2. Go to any 'chat channel'. 
3. Send a message in the channel
4. Now quote a reply for the previously sent message. 
5. See the error
  
**Expected behavior**
The text color should be always black in the `QuotedMessageText` as the background is always white.

**Screenshots**
![Screenshot_20221028-163712_2](https://user-images.githubusercontent.com/87702626/198573835-fca70ae7-d2a5-48ae-904c-d3ee8607baae.png)

**Comment by bychkovdmitry** [comment]
Hello @monil-shah-13,

Thanks for reaching out. We'll take a look into this as soon as we can.

**Comment by bychkovdmitry** [comment]
Hello @monil-shah-13,

We've opened a [PR](https://github.com/GetStream/stream-chat-android/pull/4335) with the changes that will allow you to modify the text color of quoted messages. The improvement will be available in the next release.

**Comment by monil-shah-13** [comment]
Hi @bychkovdmitry,

Thanks for the quick response. Looking forward for the next release.

**Comment by bychkovdmitry** [comment]
Hello @monil-shah-13,

We've just release a new version: https://github.com/GetStream/stream-chat-android/releases/tag/v5.11.4-hotfix

You can now use four additional parameters to control the color of quoted message background and text:

```
implementation "io.getstream:stream-chat-android-compose:5.11.4"

setContent {
    ChatTheme(         
        colors = StreamColors.defaultColors().copy(
            ownMessageQuotedBackground = Color.Green,
            otherMessageQuotedBackground = Color.Red,
            ownMessageQuotedText = Color.Blue,
            otherMessageQuotedText = Color.Yellow,
        ),
   ) {
           // Message screen
     }
}
```

Closing the issue. Feel free to reopen if you feel that something else can be improved. Thanks!
