### ISSUE TITLE
Recent chat screen very slow to load compared to iOS recent chat screen

### ISSUE THREAD

**Issue by ronnieguha** [GetStream/stream-chat-android#434]
Not sure why this is the case .. 
On iOS - the recent chat screen is VERY fast.
On Android - logged in with same (or another) user - the same recent chat screen takes a long time to load.

**Comment by elevenetc** [comment]
Hi @ronnieguha , could you check logcat logs? SDK logs socket connection events and http requests. If connection happens fast and requests are finished fast as well then problem might be somewhere else.

**Comment by elevenetc** [comment]
Closing as not active.
