### ISSUE TITLE
java.lang.OutOfMemoryError at com.getstream.sdk.chat.utils.roundedImageView.PorterImageView.createMaskCanvas(PorterImageView.java:83) [Bugsee]

### ISSUE THREAD

**Issue by DhirajG** [GetStream/stream-chat-android#435]
java.lang.OutOfMemoryError: Failed to allocate a 1440012 byte allocation with 919944 free bytes and 898KB until OOM

**Comment by elevenetc** [comment]
Fixed in [3.6.11](https://github.com/GetStream/stream-chat-android/releases/tag/3.6.11)
