### ISSUE TITLE
java.lang.OutOfMemoryError at com.bugsee.library.view.DrawingView.onSizeChanged(SourceFile:180)

### ISSUE THREAD

**Issue by DhirajG** [GetStream/stream-chat-android#436]
java.lang.OutOfMemoryError: Failed to allocate a 3586932 byte allocation with 2809424 free bytes and 2MB until OOM

**Comment by elevenetc** [comment]
`com.bugsee.library.view.DrawingView.onSizeChanged` doesn't target to any source of SDK. `bugsee` is apparently a crash log service, but message doesn't tell anything.
