### ISSUE TITLE
Notification issue

### ISSUE THREAD

**Issue by DhirajG** [GetStream/stream-chat-android#438]
If I remove the template from the getstream console app and save then I receive the messages in onMessageReceived method of the FCM service. But There is no data in remoteMessage.getData(). 

If I put the template back I do not receive the message in the FCM Service.  But Notifications are displayed. 

I want the messages to be received in my service along with data since I want to redirect my users to ChannelActivity whenever they click on Notification. Also the I want to display some custom message in the Notification as well. Please help with the same.

**Comment by elevenetc** [comment]
`remoteMessage.data` should exist. It seems there might be a problem with Dashboard and templates. What is your app id?

**Comment by DhirajG** [comment]
remoteMessage.data is not available remoteMessage.getData() is there but it returns null. My APP ID: 67851 please check this..

**Comment by elevenetc** [comment]
@DhirajG data is indeed empty. We have issue in Dashboard, trying to fix it right now. I can save data template for, so you can post it either here or send email to `support@getstream.io`

**Comment by DhirajG** [comment]
I would need the channel name and also the message that was sent. I would also like to have channel id and channel type. I want it to be redirected directly to the channel activity.  Please provide the data and I will do the rest..

**Comment by elevenetc** [comment]
If you would like that Firebase SDK opens activity for you, then notification should contain `click_action`, what activity would you like to open? Also there should be body and title.
`notification`:
```json
{
    "body": "-",
    "title": "-",
    "click_action" : "-"
}
```
I will set this `data`  for you:
```json
{
    "channelId": "{{ channel.id }}",
    "channelType": "{{ channel.type }}"
}
```
And keep in mind, if you define `notification`, then `onMessageReceived` will not be called. And you can get `data` in you activity only. More here: https://firebase.google.com/docs/cloud-messaging/concept-options#notifications_and_data_messages

**Comment by DhirajG** [comment]
@elevenetc  Thanks a lot. This really helped. I was thinking of putting this thing in data template the way you did but then I thought lets ask support before I do anything silly..   ;)
