### ISSUE TITLE
Infinite Permissions dialog on Android 13

### ISSUE THREAD

**Issue by kanat** [GetStream/stream-chat-android#4402]
The issue was detected in SDK version `5.11.0`

**Comment by kanat** [comment]
### Steps to Reproduce

1. open sample app
2. go to Channel with photos
3. open Photo Gallery
4. tap on 3 dots
5. tap `Save Image`
6. `Enable Permission on App Settings` dialog appeared
7. tap `Settings`
8. provide all permissions
9. go back to the gallery
10. repeat steps 4-5

### Actual result 
 - `Enable Permission on App Settings` dialog appeared

### Expected result 
- Image saved + on step 5 permissions have to be requested

[permission.webm](https://user-images.githubusercontent.com/1286516/201195924-e33bb3a9-af23-4f77-9b75-f418854b41ec.webm)

**Comment by bychkovdmitry** [comment]
Has been fixed [here](https://github.com/GetStream/stream-chat-android/pull/4219).
