### ISSUE TITLE
No access to files in Android 10

### ISSUE THREAD

**Issue by skgwazap** [GetStream/stream-chat-android#441]
Due [privacy changes in Android 10](https://developer.android.com/about/versions/10/privacy/changes) the SDK doesn't work properly with media attachments. Lots of open `failed: EACCES (Permission denied)   ` in Logcat. There is a workaround, use `android:requestLegacyExternalStorage="true"` in the AndroidManifest, but it doesn't seem as a proper solution.

**Comment by elevenetc** [comment]
Thanks for report. We will update permission handling.

**Comment by tschellenbach** [comment]
JC is going to work on a new message input view which will handle this

**Comment by samiuelson** [comment]
Thank you for reporting this, we are currently pushing on a new major release which will not be affected by this problem. You can subscribe to this issue to stay up-to-date to the release https://github.com/GetStream/stream-chat-android/issues/554
