### ISSUE TITLE
MessageInputView leaks fragment

### ISSUE THREAD

**Issue by skgwazap** [GetStream/stream-chat-android#444]
I use MessageInputView inside a fragment. Inside MessageInputView there is a piece of code that subscribes to keyboard events without proper unsubscription.
Here is [related bug](https://github.com/yshrsmz/KeyboardVisibilityEvent/issues/48) from the library that causes the leak.

**Comment by elevenetc** [comment]
@skgwazap thanks for report.

**Comment by elevenetc** [comment]
Fixed in [3.6.12](https://github.com/GetStream/stream-chat-android/releases/tag/3.6.12)
