### ISSUE TITLE
Firebase cloud messaging extended setup

### ISSUE THREAD

**Issue by skgwazap** [GetStream/stream-chat-android#445]
I'm not sure is this repo a proper place to ask my question, please, point me to the correct place if it is not.
Question: 
How can I set `"android"` config in [FCM "message"](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages)?
`"data"` and `"notification"` parts are easily tweakable via Dashboard or CLI tool, but I couldn't find a way to setup `"android"` section. The reason I need this is to set up at least these fields:
```
 "notification_priority": "PRIORITY_HIGH",
 "channel_id": "channel_chat"
```

**Comment by elevenetc** [comment]
Hi @skgwazap 
It's not exposed right now and configured only on our backed side.
What exactly you would like to change in `android`?

**Comment by skgwazap** [comment]
I want notifications appear as a popup on the top of the screen. It requires some special setup for Android O+ in NotificationChannel, so I want to control "channel_id" value in the "android" section

**Comment by AlexWih** [comment]
+1
@elevenetc basically we need to set "channel_id" as showing "heads up" push notifications require this. Afaiu without this it is not possible to do.

**Comment by elevenetc** [comment]
Hm, there is either misunderstanding from my side or from Google, according to the mentioned [docs page](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages) json structure looks like this:
```json
{

  "data": {},
  "notification": {},

  "android": {

    "data": {},
    "notification": {
      "title": "",
      "body": "",
      "channel_id": "",
      "notification_priority": "",
      "click_action": ""
    }

  }
}
```
So there're two pairs of `data` and `notification`. One of `notification` has fields like `click_action`, `notification_priority`, `channel_id` and others. And this `notification` you can edit in Dashboard. 
@AlexWih @skgwazap Did you try to do it? If you tried and notification is still not handled properly let me know your apps ids, I will check if we're handling your notification template properly.

**Comment by skgwazap** [comment]
Thanks for the reply. I've tried to add `channel_id` to `notification` section but without success.
Here is the template I've used:
```
{
    "title": "{{ sender.name }} @ {{ channel.name }}",
    "body": "{{ message.text }}",
    "sound": "default",
    "notification_priority": "PRIORITY_HIGH",
    "channel_id": "channel_chat"
}
```
And here is the json that works if I send a push using Firebase's REST api:
```
curl -X POST -H "Authorization: Bearer <token>" -H "Content-Type: application/json" -d '{
"message":{
   "notification":{
      "body" : "Push test",
      "title" : "YOLO"
    },
    "data" : {
        "message": "message-id",
        "sender": "sender-id"
    },
    "android":{
      "priority":"high",
      "notification":{
      	"notification_priority": "PRIORITY_HIGH",
      	"channel_id": "channel_chat"
      }
    },
   	"token":"<FB token>"
}}' https://fcm.googleapis.com/v1/projects/<project-id>/messages:send
```
Org id: 44948
App id: 73027

**Comment by elevenetc** [comment]
Checked database and it's stored correctly. Also checked Dashboard push log and it's empty (you can also check it, there should be visible all push messages). So either backend didn't send message to Firebase deliberately (because of muted channel or users are online or something else) or because of some bugs/issues on our side
- Is it correct that you don't see any push notification on your device?
- Could you mentation user ids and channel id where you try to chat?

**Comment by skgwazap** [comment]
> Is it correct that you don't see any push notification on your device?
Nope, I can see messages but they are being added to the wrong channel "Miscellaneous" not to the "channel_chat" that was specified.

**Comment by samiuelson** [comment]
@skgwazap `channel.id` should be available under `{{ channel.id }}` template. You can find more about available push data in docs: https://getstream.io/chat/docs/push_template/

**Comment by skgwazap** [comment]
@samiuelson Thanks for the reply, but the initial question was about Android channel id (which was introduced in Android 8.0 https://developer.android.com/training/notify-user/channels) and not about GetStream's channel id. So, on the screenshot you can see 5 channels. All pushes come to the channel Miscellaneous and we want them to come to Chat notifications. The field `"channel_id": "channel_chat"` is designed for this purpose.
![Screenshot 2020-07-03 at 15 22 28](https://user-images.githubusercontent.com/6984712/86464647-043f4280-bd41-11ea-9dc1-8003d5bb1a91.png)

**Comment by samiuelson** [comment]
Hi @skgwazap, could you test this issue with the latest [version](https://github.com/GetStream/stream-chat-android/releases/tag/4.3.1-beta-2) of the SDK?

We are not able to replicate this issue using our sample app.

**Comment by skgwazap** [comment]
Unfortunately, I can't. We've dropped support of GetStream's push notification solution and use another solution.
