### ISSUE TITLE
ChannelState.currentUserUnreadMessageCount throws NPE

### ISSUE THREAD

**Issue by AlexWih** [GetStream/stream-chat-android#446]
I have following code where I am trying to get count of unread messages for current user:

```
channel.watch(request, object : QueryWatchCallback {
    override fun onSuccess(response: ChannelState) {
        response.currentUserUnreadMessageCount
    }
    ...
```
I am getting Null Pointer Exception:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.getstream.sdk.chat.rest.core.Client.getUserId()' on a null object reference
        at com.getstream.sdk.chat.rest.response.ChannelState.getCurrentUserUnreadMessageCount(ChannelState.java:488)
```

Seems like inside method `getCurrentUserUnreadMessageCount()` for some reason we can't get `Client` object - `this.getChannel().getClient()` returns `null`.

Currently I can workaround the issue with the reflection:
```
val userId = channel.client.userId
channel.watch(request, object : QueryWatchCallback {
    override fun onSuccess(response: ChannelState) {
        val unreadCount = try {
            val method = ChannelState::class.java.getDeclaredMethod("getUnreadMessageCount", String::class.java)
            method.isAccessible = true
            method.invoke(response, userId) as Int
        } catch (throwable: Throwable) {
            0
        }
       ...
```

**Comment by elevenetc** [comment]
@AlexWih thanks for report. Looks bad. Internally client has in memory list of channels and has complicated sync mechanism and apparently it is broken at some moment.

**Comment by tschellenbach** [comment]
Note that you can get the channel unread counts like this in 4.2.1 and up:

```
var queryChannelResult = chatDomain.useCases.queryChannels(data.filter1, null).execute()
val queryChannelsController = queryChannelResult.data()
// don't use observe forever in a real app, just an example, use observe
queryChannelsController.channels.observeForever {
    for (channel in it) {
       channel.unreadCount
    }
}
```

Let us know if that helps solves your problem

**Comment by AlexWih** [comment]
@tschellenbach Currently we use version 3.6.12. Afaik from @elevenetc the version 4 is not stable yet and we depend on ViewModel(s) from version 3.

**Comment by tbarbugli** [comment]
@AlexWih sorry to bring this update but we are not going to be able to fix this problem on v3 in a timely manner. Most of our dev resources are focused on the v4 release which will provide a far superior SDK experience. My recommendation is to either patch this (happy to merge a PR) or to switch app development to the current v4.
