### ISSUE TITLE
Cannot receive updates on channel after subscribed to it using "channel.watch()"

### ISSUE THREAD

**Issue by AlexWih** [GetStream/stream-chat-android#447]
I want to receive updates on amount of unread messages and receive updates on last unread message.

Here is the code:
```
val request = ChannelWatchRequest()
val watchCallback = object : QueryWatchCallback {
                override fun onSuccess(response: ChannelState) {
                    val lastMessage = response.lastMessage?.text
                    val unreadCount = channel.channelState.currentUserUnreadMessageCount
                    ...
                }

                override fun onError(errMsg: String, errCode: Int) {
                    ...
                }
            }
channel.watch(request, watchCallback)
```

The issue is that when some interlocutor writes new message to the chat - the `onSuccess()` callback is not called. This callback is called only once at subscription time.
I am expecting `onSuccess()` to be called every time channel state gets updated - as described in the documentation: `watch - Loads the initial channel state and watches for changes`

**Comment by elevenetc** [comment]
The documentation is indeed might be misleading. Internally `channel.watch` is just an http call which `enables watching`, so probably method should be called `channel.enableWatch` or something similar.
To get updates of the channel you can subscribe to events:
```kotlin
channel.addEventHandler(object: ChatChannelEventHandler() {
  fun onAnyEvent(event: Event) {
  
  }
})
channel.watch()
```

**Comment by AlexWih** [comment]
@elevenetc Thank you for explanation!
There is another related question - besides `channel.watch()` we have symmetrical `channel.stopWatching()`. Please consider this scenario:
1. In component A we do `channel.watch()`.
2. In component B we also do `channel.watch()`.
3. Component A becomes eligible for garbage collection (i.e. not needed any more)

How can I call `channel.stopWatching()` for component A in order to avoid memory leak, but in the same time do not interrupt operation in component B?

I would expect when `channel.watch()` is called - some kind of subscription has to be returned (similar to what we have with `channel.addEventHandler`) and later I can use this subscription to drop background job started at step (1). 
But seems there is no such functionality?

**Comment by elevenetc** [comment]
`channel.stopWatching()` is also an http call. So when you call `watch/stopWatching` you're not starting/stopping any background job on mobile device. It just backend setting where to distribute events.

So for your case I think the best option is not to call `stopWatching`. But call `client.disconnect` when app is either destroyed (so component A and component B are destroyed). Or call `client.disconnect` when user leaves the app (moves it to background).

1. when app (or chat screen) is started call `client.setUser`.  So socket is connected and user is online
2. call watch whenever it's needed
3. call `client.disconnect` when watching is not needed and user is not online.

**Comment by tschellenbach** [comment]
@AlexWih did that help resolve your issue? Let us know if we can close this one.

Also I recommend using the 4.x branch if you're not yet live on 3.x with an existing app.

**Comment by tbarbugli** [comment]
@samiuelson we should definetely make sure that our docs (and code doc) are clear about this. the callback of watch is the HTTP request callback and it's not called when new messages are received.

**Comment by samiuelson** [comment]
@AlexWih I'm closing the issue now due to no response. If you have any further issues or questions on using the Channel API let us know.
