### ISSUE TITLE
NewMessageEvent notifications for member-based chats I'm not a part of

### ISSUE THREAD

**Issue by remvst** [GetStream/stream-chat-android#4484]
**Describe the bug**
Client A messages client B, in a `!members-xxx` channel, client C (not a member of the channel) receives a `NewMessageEvent`.

**SDK version**
- 5.11.2

**To Reproduce**
I'm not sure what the exact repro is, but I have this code:

```kotlin
client.subscribeFor(NewMessageEvent::class.java) { event ->
            event as NewMessageEvent

            println("new message in ${event.channelId}")

            val request = QueryChannelRequest().withState()
            client.queryChannel(event.channelType, event.channelId, request).enqueue { channelResult ->
                if (!channelResult.isSuccess) {
                    return@enqueue
                }

                val channel = channelResult.data()

                val currentUser = client.getCurrentUser()

                // This prints `null`, meaning the current user isn't a member of the channel
                println("are we in channel? ${channelResult.data().members.find { it.user.id == currentUser?.id }}")
            }
        }
```

I am not seeing this issue on the iOS SDK, but I haven't dug too deep.

**Expected behavior**
I should NOT see `NewMessageEvent` events for member-based channels that I am not a part of.

[Docs](https://getstream.io/chat/docs/android/creating_channels/) seem to indicate that only the members of the channel should be subscribed to it:

![Screen Shot 2022-11-21 at 12 01 05 PM](https://user-images.githubusercontent.com/3472387/203115259-d0800825-aff1-4931-81ef-0bb03ddfe99e.png)

This is extremely worrisome because we're planning on having thousands of 1-1 member-based channels, and we don't want each client to receive notifications for each channel. We expect those channels to be private.

**Device:**
 - Vendor and model: Pixel 3, Pixel 3 XL
 - Android version: 11 and 12

**Comment by adasiewiczr** [comment]
Hello @remvst 
We need to investigate it with our backend team and we will need some private info about your account.
Would you mind opening a ticket [here](https://getstream.io/contact/support/) and provide your `AppId`, `channelId`, and the users you are using?
If you could add a link to this issue on the ticket would be great to be able to join them and handle it together

**Comment by remvst** [comment]
> Hello @remvst We need to investigate it with our backend team and we will need some private info about your account. Would you mind opening a ticket [here](https://getstream.io/contact/support/) and provide your `AppId`, `channelId`, and the users you are using? If you could add a link to this issue on the ticket would be great to be able to join them and handle it together

I can't reproduce the issue anymore, however I am positive it was happening.

We did create fresh new projects yesterday (for reasons unrelated to this issue), so I can't revert back to the state I saw the issue in, however I'll keep an eye on it and try to grab logs when it happens again.

**Comment by filbabic** [comment]
Closing this as resolved! Let us know if this keeps happening for any reason.
