### ISSUE TITLE
AppBindData timeout when starting app

### ISSUE THREAD

**Issue by tristan-garaud** [GetStream/stream-chat-android#4489]
**Describe the bug**
Hi,
I'm working on how to improve the start time when opening my app. I noticed that i have an error on my log but not on all my phones. I have it on my oppo cph2219. When i start the app on the chat version 4.9.0 i don't have error on my log but on version 4.17.0 there is this type of error:
`E/ANR_LOG: >>> msg's executing time is too long
E/ANR_LOG: Blocked msg = { when=-1s635ms what=110 target=android.app.ActivityThread$H obj=AppBindData{appInfo=ApplicationInfo{814fe04 com.xxxxx.xx}} } , cost  = 1612 ms
E/ANR_LOG: >>>Current msg List is:
E/ANR_LOG: Current msg <1> = { when=-1s622ms what=159 target=android.app.ActivityThread$H obj=android.app.servertransaction.ClientTransaction@f0d902b }
E/ANR_LOG: Current msg <2> = { when=-1s621ms what=159 target=android.app.ActivityThread$H obj=android.app.servertransaction.ClientTransaction@f627ca1 }
E/ANR_LOG: Current msg <3> = { when=-683ms what=164 target=android.app.ActivityThread$H obj=com.xxxxx.xx }
E/ANR_LOG: Current msg <4> = { when=-668ms what=0 target=android.os.Handler callback=com.google.firebase.perf.metrics.AppStartTrace$StartFromBackgroundRunnable }
E/ANR_LOG: Current msg <5> = { when=-579ms what=114 target=android.app.ActivityThread$H obj=CreateServiceData{token=android.os.BinderProxy@5e5f670 className=com.google.firebase.auth.api.fallback.service.FirebaseAuthFallbackService packageName=com
E/ANR_LOG: Current msg <6> = { when=-579ms what=121 target=android.app.ActivityThread$H obj=BindServiceData{token=android.os.BinderProxy@5e5f670 intent=Intent { act=com.google.firebase.auth.api.gms.service.START pkg=com.xxxxx.xx }} }
E/ANR_LOG: Current msg <7> = { when=-547ms what=0 target=android.app.ActivityThread$H callback=android.app.ActivityThread$$ExternalSyntheticLambda1 }
E/ANR_LOG: Current msg <8> = { when=-489ms what=0 target=com.google.android.gms.internal.tasks.zzb callback=com.google.android.gms.tasks.zze }
E/ANR_LOG: Current msg <9> = { when=-414ms what=0 target=android.app.ActivityThread$H callback=android.app.LoadedApk$ServiceDispatcher$RunConnection }
E/ANR_LOG: Current msg <10> = { when=+501ms what=131 target=android.app.ActivityThread$H obj=android.app.ActivityThread$ProviderRefCount@ea03de9 }
E/ANR_LOG: >>>CURRENT MSG DUMP OVER<<<`

**SDK version**
4.17.0
**### I know this SDK version is old and it's not this one that I used on the app currently but it is still occuring. I would like to know what is this message and why does it appear since 4.17.0. Maybe even before this version but I pass from 4.9 to 4.17 directly.**

**Comment by MarinTolic** [comment]
Hi @tristan-garaud,

The stacktrace does not seem to originate from our codebase directly and seems to come from Firebase/ GMS. The only possible connection we see is with Firebase Cloud Messaging that we use.

It would be preferable if you could migrate to `v5` (latest `5.11.7`) because among many other improvements we have also separated Push Notifications which include Firebase Cloud Messaging into an independent artefact.

**Comment by tristan-garaud** [comment]
Thanks for your answer.
We are using the io.getstream:stream-chat-android-pushprovider-firebase dependency too :disappointed:. I change my dependency from 5.11.4 to 5.11.7 and this log still there.
I tried the sample getstream-chat-android-compose-sample and I have the same issue and the app takes 6seconds before displaying the activity. I don't know if it's related to this problem.
One of my phone is timing it out but the other one is waiting this appbinding process.

I don't know why getstream take 6 seconds on my phone to start. I'm not sure it is related to the problem above.
