### ISSUE TITLE
Crash IllegalStateException("Result is not successful. Check result.isSuccess before getting data: result.data()

### ISSUE THREAD

**Issue by spvince** [GetStream/stream-chat-android#449]
Sometimes i have crash in class **ChannelViewModel** method **watchChannel**

You call method **channelResult.data()** before method channelResult.isSuccess().
If i look code of method data. I can see 

`throw IllegalStateException("Result is not successful. Check result.isSuccess before getting data: result.data()")`

**Comment by tschellenbach** [comment]
Hi, what are you building?

**Comment by spvince** [comment]
Hi,

I'm not sure to understand which information you want.

I build an app with stream-chat-android SDK (v 1.0.14). My app is write in kotlin and i use binding.

I've had this issue when tried to display channel list. In my layout i use your component:

- com.getstream.sdk.chat.view.MessageListView
- com.getstream.sdk.chat.view.MessageInputView

I've had this issue with your sample too

**Comment by tschellenbach** [comment]
Which version of stream-chat-android are you using (1.0.14 is the version number of stream-chat-android-client)

**Comment by tschellenbach** [comment]
@samiuelson this is another good to look at when working on the new sample app

**Comment by spvince** [comment]
@tschellenbach I used stream-chat-android  4.0.14

**Comment by samiuelson** [comment]
Thank you for reporting this, we are currently pushing on a new major release which will not be affected by this problem. You can subscribe to this issue to stay up-to-date to the release https://github.com/GetStream/stream-chat-android/issues/554
