### ISSUE TITLE
ChannelState.getCurrentUserUnreadMessageCount() doesn't return proper value

### ISSUE THREAD

**Issue by maxmaxandr** [GetStream/stream-chat-android#450]
I have subscribed on events like this:
`
 val chatClient = StreamChat.getInstance(context)
 chatClient.addEventHandler(object : ChatEventHandler() {
         override fun onMessageNew(channel: Channel, event: Event?) {
                super.onMessageNew(channel, event)
               val unread = channel.channelState.currentUserUnreadMessageCount
            }
}
`

But when it gets a new message from another user - channel.channelState.getCurrentUserUnreadMessageCount() returns 0,  
channel.channelState.getCurrentUserUnreadMessageCount() should return correct count of unread messages.

**Comment by tschellenbach** [comment]
Have a look here for our new approach to unread message counts:
https://getstream.io/chat/docs/livedata/?language=kotlin

I would recommend using that as soon as 0.3 is released (probably a week out or so)

**Comment by tschellenbach** [comment]
PS. what are you working on/building?

**Comment by maxmaxandr** [comment]
I use the latest 3.6.12

**Comment by maxmaxandr** [comment]
> PS. what are you working on/building?

I can't answer now, it's NDA

**Comment by tschellenbach** [comment]
Do you want to use our custom views?

If you don't need the custom views I recommend using https://getstream.io/chat/docs/livedata/?language=kotlin

The latest version of stream-chat-android is 4.2.0

**Comment by maxmaxandr** [comment]
> Do you want to use our custom views?
> 
> If you don't need the custom views I recommend using https://getstream.io/chat/docs/livedata/?language=kotlin
> 
> The latest version of stream-chat-android is 4.2.0

Yes, we use custom views. 
But on main page wrote that 4.x.x is  Beta version.  Do you recommend to update to 4.2.0?

**Comment by tschellenbach** [comment]
If your launch date is still a few weeks out I recommend the 4.2.0 beta
branch.

**Comment by maxmaxandr** [comment]
I've updated on 4.2.0  and now channel doesn't have channelState. 
So how can I  get an unread message count for the current user for some channels?
There is no info about it in the documentation: https://getstream.io/chat/docs/unread_channel/?language=swift - only swift or js. 
Also, I found one sample in ChannelActivity: 
`   this.viewModel.getCurrentUserUnreadMessageCount().observe(this, (Number count) -> {
                Log.i(TAG, String.format("The current user unread count is now %d", count));
            });
`
But it also doesn't work. 
And this variant looks not satisfactory for me, I have to show which channel is unread.  Current info in the user can get only total count of unread messages or count of unread channels. 
But how to receive unread channels?

**Comment by tschellenbach** [comment]
The biggest change in the 4.x branch is that:

- the low level client is split from the UX repo: https://github.com/GetStream/stream-chat-android-client
- livedata/offline support is handled separately: https://getstream.io/chat/docs/livedata/?language=kotlin

Both of these now have extensive test coverage. So it's a much better foundation to build upon. Not 100% done yet though, sample app and UX library still need some work to bring it all together.

Here is how you can get livedata objects for the 2 unread counts:

```
val chatDomain = ChatDomain.instance()
val totalUnreadCountLive = chatDomain.useCases.getTotalUnreadCount().execute().data()
val unreadChannelCountLive = chatDomain.useCases.getUnreadChannelCount().execute().data()
```

**Comment by maxmaxandr** [comment]
> The biggest change in the 4.x branch is that:
> 
> * the low level client is split from the UX repo: https://github.com/GetStream/stream-chat-android-client
> * livedata/offline support is handled separately: https://getstream.io/chat/docs/livedata/?language=kotlin
> 
> Both of these now have extensive test coverage. So it's a much better foundation to build upon. Not 100% done yet though, sample app and UX library still need some work to bring it all together.
> 
> Here is how you can get livedata objects for the 2 unread counts:
> 
> ```
> val chatDomain = ChatDomain.instance()
> val totalUnreadCountLive = chatDomain.useCases.getTotalUnreadCount().execute().data()
> val unreadChannelCountLive = chatDomain.useCases.getUnreadChannelCount().execute().data()
> ```

thank for the reply, but it's for total unread count. 
But I need next:  
The user has 100 channels.   Total unread count returns 50 unread messages in 7 channels. 
How I can understand what channels have unread messages?

**Comment by tschellenbach** [comment]
It's exposed at the individual channel level

```
val result = chatDomain.useCases.watchChannel("messaging:123", 0).execute()
var channelController = result.data()
// livedata objects for messages and unread Count
channelController.messages
channelController.unreadCount
```

Do you want show the unread count on a list of channels?

**Comment by tschellenbach** [comment]
Looping in @elevenetc, at the moment we have this data but it should be easier to work with

**Comment by maxmaxandr** [comment]
> It's exposed at the individual channel level
> 
> ```
> val result = chatDomain.useCases.watchChannel("messaging:123", 0).execute()
> var channelController = result.data()
> // livedata objects for messages and unread Count
> channelController.messages
> channelController.unreadCount
> ```
> 
> Do you want show the unread count on a list of channels?

Yes, some kind to this. It's a bit more complex than a list of channels (I mustn't give more detail by NDA), but the user should see that have a new message in the channel and go to it for a read.  
But If I will use calc by single-channel I will get errors with limitation on requests per minute. 
And what is limit watching channel? How many channels I can watch in the same time?

**Comment by tschellenbach** [comment]
Alright, we'll get back to you on this

**Comment by tschellenbach** [comment]
This is fixed in the next upcoming release. It will work like this:

```kotlin
var queryChannelResult = chatDomain.useCases.queryChannels(data.filter1, null).execute()
val queryChannelsController = queryChannelResult.data()
// don't use observe forever in a real app, just an example, use observe
queryChannelsController.channels.observeForever {
    for (channel in it) {
       channel.unreadCount
    }
}

```

**Comment by tschellenbach** [comment]
I'll post an update here when the new release is ready

**Comment by tschellenbach** [comment]
Starting from 4.2.1 you can now do this:

```
var queryChannelResult = chatDomain.useCases.queryChannels(data.filter1, null).execute()
val queryChannelsController = queryChannelResult.data()
// don't use observe forever in a real app, just an example, use observe
queryChannelsController.channels.observeForever {
    for (channel in it) {
       channel.unreadCount
    }
}
```

Let me know if you run into any other issues. The 4.x branch is improving rapidly.

**Comment by maxmaxandr** [comment]
> Starting from 4.2.1 you can now do this:
> 
> ```
> var queryChannelResult = chatDomain.useCases.queryChannels(data.filter1, null).execute()
> val queryChannelsController = queryChannelResult.data()
> // don't use observe forever in a real app, just an example, use observe
> queryChannelsController.channels.observeForever {
>     for (channel in it) {
>        channel.unreadCount
>     }
> }
> ```
> 
> Let me know if you run into any other issues. The 4.x branch is improving rapidly.

channel.unreadCount is missed in 4.2.1.  Looks like it added in com.github.getstream:stream-chat-android-client:1.4.1 but 4.2.1 depends on com.github.getstream:stream-chat-android-client:1.2.2 
![image](https://user-images.githubusercontent.com/837498/80933327-77821200-8ded-11ea-8c2b-2b0057d6018f.png)


I can't update it manual,  it cause errors in other parts.

**Comment by tschellenbach** [comment]
I'll have more time to review tomorrow. But it looks like the 4.2.1 build
ran against an older commit.
4.2.2 is using the latest versions of the low level client and livedata lib.

**Comment by tschellenbach** [comment]
No longer relevant since you're on 4.x branch now. Closing.
