### ISSUE TITLE
Duplicate message item when sending outcoming message and receiving incoming message same time using ChannelViewModel

### ISSUE THREAD

**Issue by CMyae** [GetStream/stream-chat-android#452]
I'm observing message list from MessageListItemLiveData in ChannelViewModel and call viewmodel.sendMessage(message) to send message. When sending message each other at the same time, livedata emit duplicate message items.

Steps to Reproduce
- Logged in as two different users at two devices
- In one to one channel, press send button on two device at same time

Expected results - Two messages in list appear, outcoming and incoming message 
Actual results - Message duplicate and more than two message appears at one user

**Notes**: Duplication only happens in local list. When fetching again from network, all data are correct.
**stream-chat-version** - 3.6.12

**Comment by tschellenbach** [comment]
Support for offline has been completely reworked in 4.x branch. I recommend using the latest 4.x release, currently 4.2.0. Also see these docs: https://getstream.io/chat/docs/livedata/?language=kotlin

**Comment by CMyae** [comment]
In Readme file, version 4.x.x is still beta version and I want to know that can I use this version in production app. Also the sample app from 4.2.0 project is slow, laggy and not working smoothly as expected.

**Comment by tschellenbach** [comment]
Yes there are some known issues with the example app on 4.x branch. @samiuelson is about to start working on that. 

It mostly depends on your intended launch date. 4.x branch looks like it will be production-ready in the coming weeks

**Comment by tschellenbach** [comment]
Performance improvements are now live on the 4.x branch
