### ISSUE TITLE
ExtraData don't save in the message

### ISSUE THREAD

**Issue by maxmaxandr** [GetStream/stream-chat-android#453]
SDK version 4.2.2
I create a message and extra data and send it. 
`message.extraData["Test"] = "Check it"
viewModel.sendMessage(message)
`
but the next time I received a message in the channel without extra data
It works on 3.6.12

**Comment by tschellenbach** [comment]
@elevenetc looked at this today. I expect we'll have an update for you ready shortly

**Comment by tschellenbach** [comment]
Do you still have this problem with 4.2.3? I just tried to replicate it and it's working in my tests.

**Comment by maxmaxandr** [comment]
> Do you still have this problem with 4.2.3? I just tried to replicate it and it's working in my tests.

It works on 4.2.3. Thank you
