### ISSUE TITLE
Misleading time limit for video in chat message.

### ISSUE THREAD

**Issue by AlexWih** [GetStream/stream-chat-android#457]
When I capturing video to be sent as a message it says it can be up to `10 min` 👇 
![image](https://user-images.githubusercontent.com/3289717/81055038-8f7e9200-8ed0-11ea-93c9-bb5759fb2ac8.png)

 But if I capture the video longer than 5 sec - it says that file is too large as it can be max 20mb.

I haven't found any Chat API allowing adjusting limits or somehow decreasing quality of the video.
Currently it very misleading as UI says the limit is 10 min, but it is actually less that 10 sec.

**Comment by AlexWih** [comment]
We can solve this issue by providing our own `ChatNavigationHandler` and some dirty workarounds:
Intercept `CameraDestination` and execute our own implementation of `CameraDestination`:
```
val config = StreamChat.Config(appContext, streamApiKey)
config.navigationHandler {
    if (it is CameraDestination) {
        CameraDestinationWithFix(activity).navigate()
        return@navigationHandler true
    }
    false
}

private class CameraDestinationWithFix(context: Activity) : ChatDestination(context) {

    override fun navigate() {
        val takePictureIntent = CaptureController.getTakePictureIntent(context)
        val takeVideoIntent = CaptureController.getTakeVideoIntent(context)
        takeVideoIntent.putExtra(MediaStore.EXTRA_VIDEO_QUALITY, 0)
        takeVideoIntent.putExtra(MediaStore.EXTRA_SIZE_LIMIT, 20 * 1024 * 1024)
        val chooserIntent =
            Intent.createChooser(takePictureIntent, context.getString(R.string.stream_input_camera_title))
        chooserIntent.putExtra(Intent.EXTRA_INITIAL_INTENTS, arrayOf(takeVideoIntent))
        startForResult(chooserIntent, Constant.CAPTURE_IMAGE_REQUEST_CODE)
    }
}
```

Where the `CameraDestinationWithFix` is just a copy of `CameraDestination` where we set `MediaStore.EXTRA_VIDEO_QUALITY` to `0`.

But unfortunately this solution doesn't work best because Android allows setting either best quality or absolutely terrible one. There is no option to set a bitrate or quality in between.
The video quality with `MediaStore.EXTRA_VIDEO_QUALITY` set to `0` really doesn't look nice.

To have a real value from this video functionality we need increase video limit from 20 mb 🙏 
Additional field for improvement is extensibility of this functionality - there is no way to add additional intent flags - as you can see I was forced to completely copy the library code and do all by myself.

**Comment by tschellenbach** [comment]
JC is working on revamping some of our UX components. Adding him to this ticket.

**Comment by JcMinarro** [comment]
Hello @AlexWih 
We have released a new [UI-Components artifact](https://github.com/GetStream/stream-chat-android/tree/main/stream-chat-android-ui-components) where this timer is not present anymore.
You will be able to use all the apps that allow you to record video from your device.
You can record the video with the quality that you want, but keep in mind that the limit of 20Mb is present yet on backend.
If you would like to send files bigger than 20Mb you need to use your own CDN server.
You can find more info [here](https://getstream.io/chat/docs/android/file_uploads/?language=kotlin)
