### ISSUE TITLE
ChannelItemPayloadDiff has package visibility

### ISSUE THREAD

**Issue by maxmaxandr** [GetStream/stream-chat-android#458]
ChannelItemPayloadDiff has package visibility so I can't implement BaseChannelListItemViewHolder because it requires to implement method "bind"
`
    public abstract void bind(Context context, Channel channelState, int position, @Nullable ChannelItemPayloadDiff payloads);
`
but ChannelItemPayloadDiff is not available outside of com.getstream.sdk.chat.adapter

**Comment by tschellenbach** [comment]
Fixed in 4.2.3, thanks for letting us know
