### ISSUE TITLE
https://github.com/GetStream/stream-chat-android/releases/tag/v5.11.10-hotfix

### ISSUE THREAD

**Issue by Asep3466** [GetStream/stream-chat-android#4603]
No Telepon

No Pin

Kode Otp

Nama Ibu Kandung

No Nik Ktp

**Comment by Asep3466** [comment]
> No Telepon
> 
> No Pin
> 
> Kode Otp
> 
> Nama Ibu Kandung
> 
> No Nik Ktp

**Comment by filbabic** [comment]
@Asep3466 I'm closing this ticket given that it's not understandable what's going on and it feels like spam.

Please follow our guidelines on opening issues in the future.
