### ISSUE TITLE
Is this library really FREE to use?

### ISSUE THREAD

**Issue by coolcool1994** [GetStream/stream-chat-android#465]
I am not and probably will not be Stream customer as I already have my own backend. I am building a consumer facing Android app so that is not competing against Stream. Can I use this android library for FREE to build chat interface in my Android app - I do monetize in my app? Is the company granting general public to use this client side library for FREE as an open source and possibly let the public contribute back to the library to make it better?

**Comment by tschellenbach** [comment]
No, you need a paid plan to use this library. (See the LICENSE)
