### ISSUE TITLE
Images are getting cropped when loading for the first time in MessageListView

### ISSUE THREAD

**Issue by SamiranShil007** [GetStream/stream-chat-android#4657]
We have a functionality where we are generating a bitmap from a recycler view item and then converting it in an image and sending it with MessageInputView. When the new message is getting received the image is getting cropped and upon scrolling the image is getting perfectly fit into the message list view. Looking forward to your help. Attaching two screenshots for better understanding.

SDK version
- 5.11.10

This image showing the cropped image when loading for the first time
![MicrosoftTeams-image (14)](https://user-images.githubusercontent.com/124438844/216911120-a13ba8b0-d6d0-49a9-bc60-7d509f703efb.png)

Upon scrolling or nevigating back to this page fixes the problem
![MicrosoftTeams-image (15)](https://user-images.githubusercontent.com/124438844/216911262-c5a3351b-67b5-4813-9fe8-aef4576cbbb6.png)

**Comment by TGazica** [comment]
Hey @SamiranShil007,

can you please describe how you are taking the image and sending it so we can try to reproduce the issue? Also is the problem happening on multiple devices/aspect ratios?

**Comment by SamiranShil007** [comment]
![MicrosoftTeams-image (17)](https://user-images.githubusercontent.com/124438844/216983320-179eec7b-aa7b-4e0e-9043-cbd83d0413b6.png)

Try attaching this image, in the messageinputview and send it in the chat. you will get to see the bug

**Comment by TGazica** [comment]
Hey @SamiranShil007,

thanks for the image, I was able to replicate the issue. I will let you know when I get some more info on it.

**Comment by TGazica** [comment]
Hey @SamiranShil007,

I have opened the pr fixing the issue you reported, you can check it out. It will be included in the next release.

**Comment by SamiranShil007** [comment]
Thanks a lot, I will be check it soon.  Thanks and Regards,Samiran Shil(Android Developer)Mob:7278682875CodelogicX Technologies PVT LTD6th floor, WEBEL IT PARK Tower II, BN-9, BN Block, Sector V,Salt lake, Kolkata 700091, Indiawww.codelogicx.comDigital Transformation and Product Engineering CompanyCodelogicx is one of the leading digital transformation and product engineering company in India providing a wide range of digital transformation services. Learn more.www.codelogicx.com***Confidential: If you are not the intended recipient of this email, please delete it.--------------------------------------------------------------------------------------------------------------Kindly consider the environment before printing the content of this email. Let us help our planet stay greener and merrier. From: Tomislav GazicaSent: 07 February 2023 16:59To: GetStream/stream-chat-androidCc: SamiranShil007; MentionSubject: Re: [GetStream/stream-chat-android] Images are getting cropped when loading for the first time in MessageListView (Issue #4657) Hey @SamiranShil007,I have opened the pr fixing the issue you reported, you can check it out. It will be included in the next release.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by filbabic** [comment]
Closing this down as we've merged and shipped it! :]
