### ISSUE TITLE
Message after edit don't updated in the list

### ISSUE THREAD

**Issue by maxmaxandr** [GetStream/stream-chat-android#466]
SDK 4.2.3. 
Run sample for stream-chat-android
Open any channel, write a message -> edit this message. The message text doesn't change.  
Expected result: the message has a changed text. 
Only after reopening the channel, you can see an edited message.  It looks like that message already has been changed in the adapter before notifying the adapter. 
When it arrives in MessageListItemAdapter.replaceEntities - there compares identical lists (messageListItemList and newEntities)

**Comment by tschellenbach** [comment]
@samiuelson this feels like an issue with the example app, what do you think? Pretty sure the livedata repo has test coverage on editing messages.

**Comment by maxmaxandr** [comment]
> @samiuelson this feels like an issue with the example app, what do you think? Pretty sure the livedata repo has test coverage on editing messages.

I don't think that relates to sample app issues.  I think issues that the message has been changed after editing so messageListItemList has the changed the message object already. 
So this code don't find diff between messageListItemList & newEntities.  If don't use DiffUtil 
messages will be updated but it cause a lot of re-drawing items in RecycleView. 

Maybe need to have a full copy of message inside MessageListItem instead of link on a message from LiveDate. 

```
    public void replaceEntities(List<MessageListItem> newEntities) {
        final DiffUtil.DiffResult result = DiffUtil.calculateDiff(
                new MessageListItemDiffCallback(messageListItemList, newEntities), true);

        // only update those rows that change...
        result.dispatchUpdatesTo(this);
        messageListItemList = newEntities;

    }
```

**Comment by tschellenbach** [comment]
We have test coverage in the livedata repo for this exact use case. I wonder what's going wrong here. (see `EditMessageImplUseCase`)

**Comment by tschellenbach** [comment]
@samiuelson i suspect this is an issue with either `MessageListItemDiffCallback` and/or `MessageListItem` in the sample app

**Comment by samiuelson** [comment]
@tschellenbach `MessageListItemDiffCallback` should be improved, nevertheless, the issue is probably with implementation of `MessageListItem::equals()` or with the view model.

@maxmaxandr I'll keep this in mind when working on a new sample app. I'll be rewriting view models from scratch and probably `MessageListItemDiffCallback` will require cleaning up too.

**Comment by samiuelson** [comment]
Thank you for reporting this, we are currently pushing on a new major release which will not be affected by this problem. You can subscribe to this issue to stay up-to-date to the release https://github.com/GetStream/stream-chat-android/issues/554
