### ISSUE TITLE
Fix non positional substitutions for japanese and korean strings

### ISSUE THREAD

**Issue by matteinn** [GetStream/stream-chat-android#4666]
### Context & proposal

Japanese and Korean strings lack positional annotations on the `stream_compose_member_count_online` string, below you can see the self-explanatory warning that is printed when building an app that simply integrates the android SDK.

```
/Users/REDACTED/.gradle/caches/transforms-3/64aa686dcdf1f02ef2bf6ba07a46e6fd/transformed/stream-chat-android-compose-5.12.0/res/values-ja/values-ja.xml:20:4: Multiple substitutions specified in non-positional format of string resource string/stream_compose_member_count_online. Did you mean to add the formatted="false" attribute?
/Users/REDACTED/.gradle/caches/transforms-3/64aa686dcdf1f02ef2bf6ba07a46e6fd/transformed/stream-chat-android-compose-5.12.0/res/values-ko/values-ko.xml:23:4: Multiple substitutions specified in non-positional format of string resource string/stream_compose_member_count_online. Did you mean to add the formatted="false" attribute?
```

### Acceptance criteria

To accept this task we need to complete the following items:

- [x] TODO - replace `%s` and `%d` with `%1$s` and `%2$d` respectively for `values-ja` and `values-ko`

**Comment by MarinTolic** [comment]
Hi @matteinn ,

Thanks for raising this issue.
It has been addressed in #4674 and will be bundled in the next release once it gets approved and merged.
