### ISSUE TITLE
Compose ChannelList doesnt always respect filters

### ISSUE THREAD

**Issue by moretanjames** [GetStream/stream-chat-android#4669]
**Describe the bug**
I am using the stateful ChannelList Composable. I am using the ChannelListViewModel to set filters on that ChannelList. This works  to filter the Channels properly, as long as there are no events on channels that don't fit the filter. But if a channel that doesn't fit the current filter has a message sent in it, that channel will show up in my current list of supposedly filtered channels. Re-setting the filter will get rid of the unwanted channels (which in a way confirms that the channel was not supposed to be in the list in the first place).

**SDK version**
- 5.12.0 (Latest)

**To Reproduce**
1. Be a member of at least two different types of channels
2. Using the Statefull ChannelList composable with the ChannelListViewModel, call ChannelListViewModel.setFilters to a filter that only includes one of the two channel types of which you are a member
3. On another device, send a message in a channel that should be filtered out based on the current filters for the ChannelListViewModel
4. Observe that the channel that does not fit the filters is not present in the list of channels

**Expected behavior**
Only channels that fit the current filters in the ChannelListViewModel should show in the ChannelList

**Device:**
 - Vendor and model: Pixel 6 Pro
 - Android version: 13

*AND*

 - Vendor and model: Samsung Galaxy Z Fold 4
 - Android version: 13 (One UI 5.0)

**Screenshots**

The 4 screenshots show the following sequence. I have a ChannelList that is filtered to channels of type "direct". A message is sent on another device in a channel with type "support". The channel of type "support" now shows, ignoring the set filters. I switch to a filter that only shows the "support" messages. That works. Then I switch back to my original filter of only channels of type "direct". The "support" channel doesn't show up this time.

![Screenshot_20230213-115042](https://user-images.githubusercontent.com/47016211/218534653-19176106-8901-47a6-87c6-5428c3ab4db8.png)
![Screenshot_20230213-115053](https://user-images.githubusercontent.com/47016211/218534658-b121760a-6998-4eb1-9083-4cd1b08c8fe3.png)
![Screenshot_20230213-115057](https://user-images.githubusercontent.com/47016211/218534661-30d52b8a-db18-49a3-b6a3-1cf2c54b1bb7.png)
![Screenshot_20230213-115100](https://user-images.githubusercontent.com/47016211/218534664-b61d2153-f9c3-4207-ae80-7caab4129d38.png)

**Comment by filbabic** [comment]
Hey @moretanjames!

Have you had a chance to look into what Marin suggested? :]

Let me know if there's been any movement!

**Comment by moretanjames** [comment]
@filbabic @MarinTolic I just now had the chance to check this out and as far as I can tell I was able to make a ChatEventHandler that fixed my problem. Thanks!

**Comment by filbabic** [comment]
Awesome!

Closing this one for now! :]
