### ISSUE TITLE
Inconsistent and wrong totalUnreadCount

### ISSUE THREAD

**Issue by bhargavsavasani** [GetStream/stream-chat-android#4684]
I am using 5.8.0. I am trying to get totalUnreadCount for all channels using the below code but not getting the proper chat count Do you have any idea to make it work properly? Thanks!

```
ChatClient.instance().getCurrentUser()?.totalUnreadCount

ChatClient.instance()
                .connectUser(user, token)
                .enqueue { result ->
                    if (result.isSuccess) {
                        val user = result.data().user
                        val unreadChannels = user.unreadChannels
                        val totalUnreadCount = user.totalUnreadCount
                       

                    }
                }
```

**Comment by filbabic** [comment]
Hey @bhargavsavasani!

While this property should be updated properly, could you try fetching the global state instead?

```kotlin
ChatClient.instance().globalState.totalUnreadCount.collect { // process the unread count
            
}
```

Something like this should basically be the same implementation, but it might be that the unread state is not properly updated in the current user.

Let me know if this works!

**Comment by Bhargav-IndiaNIC** [comment]
Hello @filbabic 

It's working now 
Thank you so much for your quick response

**Comment by bhargavsavasani** [comment]
Hello @filbabic 

It's working now 
Thank you so much for your quick response

**Comment by filbabic** [comment]
Thank you @bhargavsavasani!

Glad we managed to resolve it! :]
