### ISSUE TITLE
Wrong online state for channel members

### ISSUE THREAD

**Issue by VasiliZ** [GetStream/stream-chat-android#4685]
I am using android compose version your lib "5.11.10" and try to implement p2p chat. In chat header i want to see online indicator for another chat member, and all data from another participant. 

I try to collect data from member state flow in channel state  

```   
 channelState?.members?.collect {
                if (it.isNotEmpty()) {
                    participant = it.first {
                        it.user.id != 'id current user'
                    }.user
                }
            }

```
When I call in my MainActivity following code, user state in dashboard is changing but channel state doesn't emit new data with user.online = false value

```
ChatClient.instance().disconnect(false).enqueue()
```

**Comment by filbabic** [comment]
Hey @VasiliZ !

Could you give us a bit more info?

- How are you initializing the SDK and the offline plugin/state?
- Are you observing the user presence?
- Are you applying any custom filters or queries for channels?
- Are you perhaps overriding the default events implementation?

These things can affect how the events are processed and the state is updated, so it'll help us debug better!

**Comment by VasiliZ** [comment]
Hi, of course 

1. 
```
 val offlineFactory = StreamOfflinePluginFactory(
            config = Config(
                userPresence = true,
                persistenceEnabled = true,
                useSequentialEventHandler = true,
            ),
            this
        )

        ChatClient.Builder(GET_STREAM_APP_KEY, this)
            .withPlugin(offlineFactory)
            .logLevel(if (BuildConfig.DEBUG) ChatLogLevel.ALL else ChatLogLevel.NOTHING)
            .build()
```
initializing SDK in MainActivity when app is start.

2. I thought when I init SDK user sets own state isOnline to true state.
3. Channel without filters. Current channel state i'm observe in code below
```
chatClient.watchChannelAsState(
            cid = chatId,
            messageLimit = MESSAGE_LIMIT,
            coroutineScope = channelCoroutineScope
        )
``` 
4. All events I get from sdk without overriding 

I watch state with debug help. When I start app on one device user is offline. When I open chat on second device user online state sets to online. And after kill app on the second device it state still is online.

**Comment by VasiliZ** [comment]
@filbabic I am so sorry. It was my mistake. For this I must use observeChannel() method and handle members states. All works. Best regards.

**Comment by filbabic** [comment]
Hey @VasiliZ!

No worries - I was just checking in with the team and they I was about to ask about that as per their suggestions.

Hope you've managed to resolve it!

**Comment by VasiliZ** [comment]
@filbabic Could help me again? I have the same problem again. I try to observing chat members state. But state automatically changing. 

```
 private fun observeMembers() {
        channelCoroutineScope.launch {
            channelState?.filterNotNull()?.flatMapLatest { it.members }?.collect {
                if (it.isNotEmpty()) {
                    participant = it.first { member ->
                        member.user.id != profileId //<- current user id
                    }.user
                    Log.d("participant", "observeMembers: ${participant.id}, ${participant.online}")
                }
            }
        }
    }

```
I use this method for observing. And put log here for debug.
After second user closed app I see in logs next line 

observeMembers: 210fc2ee-38a6-4352-9a0d-7fc851fa1f55, false
observeMembers: 210fc2ee-38a6-4352-9a0d-7fc851fa1f55, true 

flow emits few states sequentially and states on the screen steel online :(

**Comment by filbabic** [comment]
Hey @VasiliZ!

I'll see with the team if they have an idea why this is happening. Could you compare the full state between these two emissions? It could be that there are two emissions queued and there is a race condition - in this case we need to fix that.

Also - does the state ever go to "offline" (false) after this second emission?

**Comment by filbabic** [comment]
@VasiliZ COuld you please check that the user in this case, that goes offline then online, isn't logged in somewhere else?

For example, if you use the same account on multiple devices, it could be the case that triggers the online flag once the user goes offline first.
