### ISSUE TITLE
[V6] Connection state is 'Disconnected' after clicking push notification

### ISSUE THREAD

**Issue by workspace** [GetStream/stream-chat-android#4718]
**Describe the bug**
Connection, User state is not updated when entering app via push notification. after shutting down completely

**SDK version**
- 6.0.0-develop (https://github.com/GetStream/stream-chat-android/commit/d3d806360b2c808f5f92bc3428e618cc35dfb16f)

**To Reproduce**
Using sample app

1. close app
2. receive and click notification
3. User avatar is gone and 'Disconnected' state is shown

https://user-images.githubusercontent.com/7759511/224253511-d9846e50-f6e7-40dd-be4a-2f6cea688b55.mp4

**Expected behavior**
User and Connection state is updated with latest state

**Device:**
 - Vendor and model: Galaxy S23 Ultra
 - Android version: 13

**Screenshots**
### Expected
<img width="367" alt="image" src="https://user-images.githubusercontent.com/7759511/224251375-997b7d18-0b1a-4c98-ae36-40815cfac664.png">
### Actual
<img width="365" alt="image" src="https://user-images.githubusercontent.com/7759511/224251932-a9c7de33-9d44-4411-a1cb-c1e73845bcd7.png">

**Comment by MarinTolic** [comment]
Hey @workspace ,

Thank you for reporting this issue.
We are able to reproduce it and will look into it.

**Comment by workspace** [comment]
@JcMinarro Thank you!
