### ISSUE TITLE
No way to unselect messages in MessageListViewModel

### ISSUE THREAD

**Issue by stevie-patreon** [GetStream/stream-chat-android#4726]
`MessageListViewModel` lets you select messages, but doesn't give you any way to unselect them!

https://github.com/GetStream/stream-chat-android/blob/54d1385de899c1085f1d75ef34e96ea8e2b1eab0/stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessageListViewModel.kt#L602

Either `selectMessage` should not take null or passing null should clear the selected message state

**Comment by filbabic** [comment]
HEy @stevie-patreon!

We expose the following:

https://github.com/GetStream/stream-chat-android/blob/54d1385de899c1085f1d75ef34e96ea8e2b1eab0/stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessageListViewModel.kt#L1156

It's a way to reset the selected state in both threads and regular messages. The naming might be a bit unfriendly, but it's generally aimed to be a bit more abstract in what it does (in this case dismissing any overlay state).

**Comment by stevie-patreon** [comment]
Doesn't that also clear the thread state? What if you're selecting a message in a thread?

**Comment by filbabic** [comment]
Well generally if you're in a thread and leave it, the message gets unselected (the state is cleared).

So if you're not in a thread and you clear the state then join a thread, nothign should break. This only clears the thread state in a way that the `selectedMessage` is set to null, it doesn't mutate anything else

**Comment by JcMinarro** [comment]
Fixed on #4798
