### ISSUE TITLE
Confusing documentation and "Channel without name" issue

### ISSUE THREAD

**Issue by psylinse** [GetStream/stream-chat-android#474]
I'm trying to create a private one-on-one channel between two users. I'm not fully understanding what the documentation is trying to say [here](https://getstream.io/chat/docs/channel_conversations/?language=kotlin#channel_conversations):

<img width="916" alt="Screen Shot 2020-05-13 at 6 09 32 PM" src="https://user-images.githubusercontent.com/161737/81878349-06590200-9545-11ea-8e09-f5927b782311.png">

AFAICT, `ChannelController` does not have the method `.create`. Further, I'm not sure if it makes sense, since in order to create a `ChannelController` I'd have to call `ChatClient#channel` which requires me to give it a `type` and `id` which defeats the purpose. 

I ended up finding `ChatClient#createChannel` and am using it like so:

```kotlin
fun createPrivateChannel(otherUser: String): Channel {
    val users = listOf(user.id, otherUser)

    return client
        .createChannel(ModelType.channel_messaging, users)
        .execute()
        .data()
}
```

This works, however a strange UI issue happens:

<img width="391" alt="Screen Shot 2020-05-13 at 6 13 10 PM" src="https://user-images.githubusercontent.com/161737/81878484-6cde2000-9545-11ea-95d0-d6db598bed84.png">

It flashes the other user's name for a second, then reverts to "Channel without name". I then thought, why not just update the channel to have a name. I couldn't find a simple way to update the channel name from the client (maybe this is by design?). I found `ChatClient#updateChannel` but that requires a `Message` which I don't want/have at this point. I also feel like starting a one-on-one chat should just show the other person's name as the channel title.

Let me know if that makes sense! Sorry if I missed something obvious. 

dependencies:
```gradle
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.core:core-ktx:1.2.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'

    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.5'
    implementation 'com.squareup.okhttp3:okhttp:4.4.1'
    implementation 'com.google.android.material:material:1.1.0'
    implementation "io.getstream.client:stream-java:3.2.3"
    implementation 'com.github.GetStream:stream-chat-android:4.0.13'
    implementation 'com.github.bumptech.glide:glide:4.9.0'
    implementation 'androidx.recyclerview:recyclerview:1.1.0'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'

    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.annotation:annotation:1.1.0'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
}
```

**Comment by elevenetc** [comment]
Thanks for report. Added new channel creation signature to `ChannelController` and updated documentation.
Will look into the bugs.

**Comment by psylinse** [comment]
This is now inconsistent on `4.2.7`. Sometimes the channel will show the other user's name sometimes "Channel without name".

**Comment by tbarbugli** [comment]
@JcMinarro looks like the channel header UI is not representing the data correctly here (or perhaps not getting the full channel object). Can you have a look at this?

**Comment by JcMinarro** [comment]
Hello @psylinse 
`ChannelHeaderView` has been totally refactored on #491 and it fixes the problem you reported.
On this PR I added the new `ChannelHeaderView` to the sample app, you can see how it works now #497 
It is already part of the version [4.2.11-beta-6](https://github.com/GetStream/stream-chat-android/releases/tag/4.2.11-beta-6), not a final release yet, we will update #554 when the final version is ready
