### ISSUE TITLE
Struggling in sending a test push notification on android via Stream.

### ISSUE THREAD

**Issue by zeeshansuleman** [GetStream/stream-chat-android#4765]
### Discussed in https://github.com/GetStream/stream-chat-android/discussions/4764

<div type='discussions-op-text'>

<sup>Originally posted by **zeeshansuleman** March 30, 2023</sup>
Hey folks, I am having an issue in sending test notifications from the stream dashboard, I have successfully configured fcm on the dashboard and integrated the SDK on the mobile end, But when I try to send notifications from the dashboard I get the error attached in the screenshot. Can anybody help me to identify the cause of this issue?

<img width="529" alt="Screen Shot 2023-03-30 at 3 15 14 PM" src="https://user-images.githubusercontent.com/12757747/228955347-23d1e59b-04b0-48d1-8496-0b38c98c56ef.png">
</div>

**Comment by DanielNovak** [comment]
Sorry - we lost track of this issue. Are you still experiencing problems? If yes - please reply and we will look into it.
