### ISSUE TITLE
Push Notifications Empty RemoteMessage

### ISSUE THREAD

**Issue by prarthnastockgro** [GetStream/stream-chat-android#477]
I have configured the GetStream Dashboard as per the documentation https://getstream.io/chat/docs/push_android/?language=kotlin alongwith the templates. However, the remoteMessage.data is empty and the Notification never gets displayed. Could someone from your team look into this? Thanks
@elevenetc

**Comment by elevenetc** [comment]
Hi @prarthnastockgro 
 - Whats your app id?
 - What version of SDK you're using?

**Comment by prarthnastockgro** [comment]
@elevenetc App ID: 78300
SDK version: 4.0.13

**Comment by prarthnastockgro** [comment]
@elevenetc @tschellenbach Any idea on how to resolve this one?

**Comment by elevenetc** [comment]
Checked templates of your app in database. And they are empty, so push payload is empty as well.
Could you verify that data template is filled in Dashboard for `78300` app?

**Comment by prarthnastockgro** [comment]
It was a template issue, this is fixed. Thanks closing this
