### ISSUE TITLE
Stream error code 4: UpdateApp failed with error: "cannot enable nameless configurations when push V2 is enabled

### ISSUE THREAD

**Issue by Andrew-Rel** [GetStream/stream-chat-android#4789]
**Describe the bug**

**SDK version**
implementation "io.getstream:stream-chat-android-ui-components:5.5.0"
implementation "io.getstream:stream-chat-android-pushprovider-firebase:5.5.0"

**To Reproduce**
1. [Go to 'https://dashboard.getstream.io/app/xxxx/chat/push/single/firebase/']
2. Click on Push Notifications
3. Paste Credentials JSON I got from Firebase.
4. Click Enable for Edit Puch Config. Firebase. 
5. Click Enable & Save
6. See error: "Stream error code 4: UpdateApp failed with error: "cannot enable nameless configurations when push V2 is enabled"

**Expected behavior**
Firebase Push Notification is enabled. Pasting Credentials JSON from Firebase is enough.

**Device:**
 - Chrome Version 112.0.5615.137 (Official Build) (arm64)

**Screenshots**
![image](https://user-images.githubusercontent.com/131261476/233063510-0d8b68e3-1236-48ff-9e80-fac8927f3630.png)
![image](https://user-images.githubusercontent.com/131261476/233063638-af24f541-4d29-4182-b5dd-21e456bda287.png)

**Comment by ffenix113** [comment]
Hello Andrew-Rel,

Thank you for the issue. As [mentioned](https://getstream.io/chat/docs/node/upgrading_to_push_v2/?language=javascript#how-to-migrate-to-push-v2?) in the docs when Push version V2 is enabled it will not be possible to enable nameless configurations.

The solution is to create new named configuration using a dropdown button `New configuration` on the `Push Notifications` page.
