### ISSUE TITLE
Multiple 'META-INF/library_release.kotlin_module' in dependencies

### ISSUE THREAD

**Issue by psylinse** [GetStream/stream-chat-android#479]
I'm getting this error with version `4.2.5`:

`More than one file was found with OS independent path 'META-INF/library_release.kotlin_module'`

The culprit seems to be two sub-dependencies of this library. Both `stream-chat-android-client` and `stream-chat-android-livedata` contain this file when building. 

Current workaround is adding this to app's build.gradle:

```
    packagingOptions {
        pickFirst 'META-INF/library_release.kotlin_module'
    }
```

However, not sure what this changes.

**Comment by tschellenbach** [comment]
It looks like I can safely exclude this file from the build process on the livedata repo. Will update this ticket when the new version is live

**Comment by psylinse** [comment]
I also found this which may be helpful: https://stackoverflow.com/a/56329676

**Comment by tschellenbach** [comment]
Fixed the naming for livedata to prevent this issue. This will get included in the next release of stream-chat-android 

https://github.com/GetStream/stream-chat-android-livedata/releases/tag/0.4.3

**Comment by psylinse** [comment]
Awesome, thanks!

**Comment by tschellenbach** [comment]
Do you still have this problem on this version?
https://github.com/GetStream/stream-chat-android/releases/tag/4.2.7

**Comment by tschellenbach** [comment]
I believe this is fixed, let us know if you still encounter the issue.

**Comment by psylinse** [comment]
I'll check this when I get a chance and let you know.
