### ISSUE TITLE
Deleting a message through the API doesn't delete it from Android

### ISSUE THREAD

**Issue by mararzu** [GetStream/stream-chat-android#4797]
**Describe the bug**
We are deleting messages from our server using your API
But on the Android app they are still visible, probably because of some cache
The only way to make them disappear is to clear storage and cache from the Android Settings

iOS SDK seems to be working fine, the messages are disappearing without the need to do anything

**SDK version**
- 5.15.0

**To Reproduce**
1. Send messages with user A
2. Using the Android app and the default chat UI components of the SDK open the channel where those messages are on
3. Using the API do a HardDelete of the messages of user A (see code we are using below)
4. Notice that the Android app still shows the messages. You could close the app and open it again but messages still there

**Expected behavior**
After deleting the messages using the API the android UI components should delete those messages (maybe delete them from cache?)

**Device:**
 - Vendor and model: Pixel 5
 - Android version: 12

**Backend code, using Go, that deletes the user and their messages**
_, err = s.client.DeleteUsers(ctx, []string{user.StreamUserID}, stream.DeleteUserOptions{
	User:     stream.HardDelete,
	Messages: stream.HardDelete,
})

**Comment by JcMinarro** [comment]
Hello @mararzu 
A lot of improvements have been made on our v6 release, some of them related to the cache/db the SDK uses internally to keep the state of the list of messages. 
The issue you reported should be fixed on this version.
Could you check it?
