### ISSUE TITLE
No Notification Pop-up when receiving new message

### ISSUE THREAD

**Issue by SSaleemSSI** [GetStream/stream-chat-android#4853]
**Describe the bug**
When we receive a new notification no Notification pop-ups are shown instead only icon in toolbar and sound came, we have to drop down and open notification tray to view the message. 

**SDK version**
- 5.17.3

**Expected behavior**
Pop-up must show when receive a push notification. 

**Device:**
 - Vendor and model: [e.g. Samsung S8]
 - Android version: [e.g. 9]

**Screenshots**

**Comment by DanielNovak** [comment]
Sorry for a late reply here. The SDK is fully cusomisable in terms of push notifications - you can define your own `NotificationHandler` and show the Notification from your code - in this case you can fully customise it. I hope this helps with your question.
