### ISSUE TITLE
Customize Message Components

### ISSUE THREAD

**Issue by muaviyaijaz123** [GetStream/stream-chat-android#4864]
Hi,

We are using Stream Chat Android Messaging SDK in Kotlin.

We want to have a feature in our app where we are able to customize Chat Screen in such a way so that we can add these two components on Chat Screen

- An Accept/Decline View at bottom of chat screen where message composer gets shown

- A User Chat Header (showing as first message in chat) where user Name And Profile Picture is shown (like in Messenger App)

SDK Version we are using
Version: 5.17.3

I am also attaching some images for both components and a video for User Chat Header

![Accept Deline View](https://github.com/GetStream/stream-chat-android/assets/90596703/8923147e-8d92-4dc3-812f-da507ab5fffd)
![Chat Header View](https://github.com/GetStream/stream-chat-android/assets/90596703/c072e16a-0a49-4e05-8eae-0aca06aca11e)

https://github.com/GetStream/stream-chat-android/assets/90596703/901594a2-dace-42b8-b156-f8d5c4ebf5ec

**Comment by JcMinarro** [comment]
Hello @muaviyaijaz123 
We already implemented this header component on #5145 and you can start to use if by upgrading to our [last version](https://github.com/GetStream/stream-chat-android/releases/latest)
