### ISSUE TITLE
Filter All Chats Except Requests Chats

### ISSUE THREAD

**Issue by muaviyaijaz123** [GetStream/stream-chat-android#4872]
**Describe the bug**

Hi,

I have a scenario where we want to filter all chats except those ones in which user is invited. For this we use the following filter block in ChannelListViewModelFactory:

      ChannelListViewModelFactory(filter = Filters.and(Filters.eq("type", "messaging"),
                                                                       Filters.`in`("members", listOf(userId)),
                                                                       Filters.eq("joined",true)))
  
  It works fine initially BUT when a message comes in a chat in which user was invited, that chat also gets shown in that list. We want to eliminate that.We also looked at CustomEventHandler to handle channel updates but couldn't find a way to make the requested chat go away from all chats list when a message comes in that chat.

I also raised a similar issue for filtering requests chats and handling updates in:

https://github.com/GetStream/stream-chat-android/issues/4782

but here i require the exact opposite, meaning I only want those chats which are not invitations and also want to handle updates on any receiving events for such chats

**SDK version**
- 5.17.3

**Expected behavior**
All Chats except invited ones should be visible and on any events received, requests chats shouldn't show up in these chats

**Device:**
 - Vendor and model: Samsung A30
 - Android version: 11

**Comment by kanat** [comment]
Hi @muaviyaijaz123,

You van provide custom [ChatEventHandler](https://getstream.io/chat/docs/sdk/android/client/guides/channel-list-updates/#custom-chateventhandler) and just ignore the event by returning `EventHandlingResult.Skip`.

However, you need to think of the data on which you base the decision of whether or not to return `EventHandlingResult.Skip`. For instance, you could check `Channel.membership`, and if it’s `null`, skip the event.
