### ISSUE TITLE
Sample app doesn't handle process death

### ISSUE THREAD

**Issue by VGJohn** [GetStream/stream-chat-android#488]
There are multiple areas in the sample where process death isn't being handled correctly, the app crashes when you select one of the chats, background the app, enact process death and then resume the app. A couple of the static instances in the `stream-chat-android-livedata` and `stream-chat-android-client` libraries are no longer initialised. I fixed that crash by moving around the initialisation logic to an early part of the app's lifecycle but then another uninitialised part of those libraries resulted in another crash so I'm not sure how deep the rabbit hole goes there.

I think its a good idea to address these issues otherwise developers using the sample app as a guide will setup their apps incorrectly as well. I know its still in beta but these are quite fundamental issues.

Also, I find the builders, in the libraries mentioned above, that set the static instances come across as side effects or at least its not obvious that they also initialise those instances. The previous `getInstance` in the stable version of the sample app suggests that more since its also more common among other libraries. I don't know just thought I'd mention it, some of the required initialisation isn't obvious enough.

**Comment by tschellenbach** [comment]
Samuel is rewriting the sample app at the moment.

**Comment by VGJohn** [comment]
Awesome! Great to hear, looking forward to seeing it.

**Comment by samiuelson** [comment]
Thank you for reporting this, we are currently pushing on a new major release which will not be affected by this problem. You can already try the beta release and subscribe to this issue to stay up-to-date to the release https://github.com/GetStream/stream-chat-android/issues/554
