### ISSUE TITLE
How to be notified for typing events for all channels

### ISSUE THREAD

**Issue by lukicmarko** [GetStream/stream-chat-android#4909]
**Describe the bug**
I want to be informed whenever someone starts or ends typing in any channel where the current user is a participant.
I tried 2 options, but no callback is called.

**SDK version**
- 5.17.6

**To Reproduce**
Subscribe to the specific events, but no callback is called.
```kotlin
      viewLifecycleOwner.lifecycleScope.launch {
            chatClient.globalState.typingChannels.collect {
                println("Keys: " + it.keys)
                println("TYPING CHANNELS $it")
            }
        }

        // Add typing start event handling
        chatClient.subscribeFor<TypingStartEvent> { typingStartEvent ->
            // Handle event
            println("TYPING start event $typingStartEvent")

        }

       // Add typing stop event handling
        chatClient.subscribeFor<TypingStopEvent> { typingStopEvent ->
            // Handle event
            println("TYPING end event $typingStopEvent")
        }
```

**Expected behavior**
Expect that the methods listed above be called.

**Device:**
 - Vendor and model: Samsung S8

**Comment by JcMinarro** [comment]
Hello @lukicmarko 

Are you "watching" the channels?
`TypingStartEvent` and `TypingStopEvent` events are only received for channels that you are already watching.
Watching channels can be achieved by including `watch = true` when query channels or by individual channel calling `ChannelClient.watch()`
[Here](https://getstream.io/chat/docs/sdk/android/client/channels/) you can find the docs

**Comment by lukicmarko** [comment]
Tnx it works.
