### ISSUE TITLE
Message List Header - no title change option

### ISSUE THREAD

**Issue by lukicmarko** [GetStream/stream-chat-android#4924]
**Describe the bug**
There is no option (or I'm not aware of it) to change the Message List Header title text
**SDK version**
5.17.10

**Expected behavior**
I expect the option (like on iOS) to change the Message List Header title text

**Comment by lukicmarko** [comment]
Furthermore, I wanted to extend either MessageListHeader or MessageListHeaderViewModel and change behavior but can't do that since classes are not open (so they are final)

**Comment by JcMinarro** [comment]
Hello @lukicmarko 
The `MessageListHeaderView` already have a `setTitle()` method, is [it](https://github.com/GetStream/stream-chat-android/blob/main/stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/header/MessageListHeaderView.kt#L92) not enough?

If you are using our Compose SDK, we expose a way to format channel title within [ChatTheme](https://github.com/GetStream/stream-chat-android/blob/main/stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/ChatTheme.kt#L220)

Let us know if it is enough for you.
