### ISSUE TITLE
Error while exiting a channel

### ISSUE THREAD

**Issue by prarthnastockgro** [GetStream/stream-chat-android#493]
Getting this error while trying to remove a valid user id from the channel:

```json
{
  "code": 4,
  "message": "UpdateChannel failed with error: \"cannot add or remove members in a distinct channel, please create a new distinct channel with the desired members\"",
  "StatusCode": 400,
  "duration": "0.00ms"
}
```

**Comment by elevenetc** [comment]
`distinct channel` is a channel which was created without `id`, so backend creates `id` out of member `ids`. You can't remove or add members into such kinds of channels after they created.

So if you would like to add or remove members from channel you need to define unique `id` when creating this channel.
