### ISSUE TITLE
Edit option not working on message long press

### ISSUE THREAD

**Issue by prarthnastockgro** [GetStream/stream-chat-android#496]
Version 4.0.13 - Edit option not working for messages from the bottomsheet that appears when message is long pressed

**Comment by elevenetc** [comment]
Thanks for report. UI components are currently under refactoring and updating.

**Comment by prarthnastockgro** [comment]
@elevenetc As a temporary fix, how to hide only "Edit" option from the MessageMoreActionDialog? I am not able to access the view in my CustomMessageMoreActionDialog class.

**Comment by samiuelson** [comment]
Thank you for reporting this, we are currently pushing on a new major release which will not be affected by this problem. You can already try the beta release and subscribe to this issue to stay up-to-date to the release https://github.com/GetStream/stream-chat-android/issues/554
