### ISSUE TITLE
membersToShowCount wrong number

### ISSUE THREAD

**Issue by Testtaccount** [GetStream/stream-chat-android#5009]
**Describe the bug**
The number of users displaying in channel info view is wrong

**SDK version**
- 6.0.4

**To Reproduce**
1. Go to ChannelListFragment
2. Open the channel
3. Click on Channel title or on channel avatar view
4. See error when there is on option  show more - its showing just first 30 members when in channel almost more then 30 and displaying wrong number (it calculating only for 30 members)

**Expected behavior**
Show all users in channel info maybe with pagination and display correct number for load more text

**Device:**
 - Vendor and model: Pixel 7
 - Android version: 13

**Screenshots**
![photo_5300964940598857642_y](https://github.com/GetStream/stream-chat-android/assets/30685005/0f3f7fca-e0cd-4053-a099-a2bb8a5b4887)

**Comment by JcMinarro** [comment]
Hello @Testtaccount 

This view is not part of our SDK, it is only an example in our Sample App.
If you would like to show the full list of members, you will need to paginate the channel's members and implement a view that will be querying for more members until arrive at the last member in the list
