### ISSUE TITLE
ChatController .create causes stackoverflow

### ISSUE THREAD

**Issue by tschellenbach** [GetStream/stream-chat-android#501]
![image](https://user-images.githubusercontent.com/265409/82767980-f7960900-9de8-11ea-87ef-ba973de96146.png)

**Comment by tschellenbach** [comment]
this looks like a loop
![image](https://user-images.githubusercontent.com/265409/82768002-214f3000-9de9-11ea-858b-c16233907aec.png)

**Comment by elevenetc** [comment]
Fixed with llc `1.4.17`.
