### ISSUE TITLE
App no longer receives push after updating to 6.0.5 - (Related: App crashes on Android 14 when receiving chat push message)

### ISSUE THREAD

**Issue by devjsonjuliane** [GetStream/stream-chat-android#5019]
**Describe the bug**
After upgrading to 6.0.5, Android 14 devices are no longer receiving push notification.
Might be related to: https://github.com/GetStream/stream-chat-android/issues/4995

**SDK version**
- 6.0.5

**To Reproduce**
1. Test push notification on device (with Android 14) that is using sdk version 6.0.3, the app will crash upon receiving push notification.
2. Test push notification on device (with Android 14) that is using SDK version 6.0.5, the app will no longer receive push notification.

**Expected behavior**
1. The app should be able to receive push notification without crashing on Android 14

**Device:**
 - Vendor and model: Emulated device
 - Android version: Android 14

**Comment by DanielNovak** [comment]
Thank you for reporting the issue. We will look into it today.

**Comment by DanielNovak** [comment]
We are not able to reproduce it. But we are seeing some cases where the messages get delivered with a delay of even few minutes (this could be the result of FCM de-prioritisation based on usage patterns / testing: https://firebase.google.com/docs/cloud-messaging/android/message-priority#using_high_priority_messages_for_android). 

Do you maybe have logs from the device? When you send the message - do you see any log movement on the device which isn't receiving the push message? (I was wondering if maybe the push message is received but for some reason dropped).

**Comment by devjsonjuliane** [comment]
May I ask if you got any specifics on what to look for in the logs or at least some filter I can utilize?

I've recorded my testing, please refer to the scenario below.
1. Used stream version 6.0.3

https://github.com/GetStream/stream-chat-android/assets/124203061/08788d52-12db-4c2f-ab80-79d2bf385f25

Scenario:
1. Received a push notificaion
2. Crash with android.app.InvalidForegroundServiceTypeException: Starting FGS with type none callerApp=ProcessRecord{9c477c0 959:xxxxxxxxxxxxxxx/u0a650} targetSDK=34 has been prohibited

2. Used stream version 6.0.4

https://github.com/GetStream/stream-chat-android/assets/124203061/9c5c7946-ac7a-46ea-bd80-bb54c132658c

Scenario:
1. No push notification received
2. Able to receive events through `client.subscribe()`

I'll follow up with the logs, I just need to know more info on what to look for.

**Comment by DanielNovak** [comment]
Can you try the same test with 6.0.5 but with the application in background? We don't process or display push notifications if the application is in foreground since 6.0.4. Here is the change: https://github.com/GetStream/stream-chat-android/pull/4979. This behaviour can be changed in `NotificationConfig` but in general and for performance reason the default setting makes more sense because if the application is in foreground and the websocket is connected then the same messages are also delivered through the websocket. 

```
public data class NotificationConfig @JvmOverloads constructor(
...
    /**
     * Push notifications are ignored and not displayed when the user is online (when there is an
     * active WebSocket connection). Set to false if you would like to receive and handle push
     * notifications even if user is online. Default value is true.
     */
    val ignorePushMessagesWhenUserOnline: Boolean = true,
...
```

**Comment by devjsonjuliane** [comment]
@DanielNovak, apologies for missing this part of the update. Everything works as expected now, we can close this thread.
Thanks a lot for the help!

**Comment by DanielNovak** [comment]
No worries. We could have communicated the change a bit better :-).
