### ISSUE TITLE
Add ability to mark a channel as read/unread

### ISSUE THREAD

**Issue by matteinn** [GetStream/stream-chat-android#5032]
Describe the feature you'd like to see in the SDK

Are there any chances to implement this feature, which is already available in the iOS SDK?

Here are the endpoints for read/unread found in the iOS SDK...
https://github.com/GetStream/stream-chat-swift/blob/develop/Sources/StreamChat/APIClient/Endpoints/EndpointPath.swift#L72-L73
...and the SDK methods to trigger that:
```
    /// Marks the channel as read.
    ///
    /// - Parameter completion: The completion will be called on a **callbackQueue** when the network request is finished.
    ///                         If request fails, the completion will be called with an error.
    ///
    public func markRead(completion: ((Error?) -> Void)? = nil) {
```
```
    /// Marks a subset of the messages of the channel as unread. All the following messages, including the one that is
    /// passed as parameter, will be marked as not read.
    /// - Parameters:
    ///   - messageId: The id of the first message id that will be marked as unread.
    ///   - completion: The completion will be called on a **callbackQueue** when the network request is finished.
    public func markUnread(from messageId: MessageId, completion: ((Error?) -> Void)? = nil) {
```

Here instead are the channel-related endpoints used in the Android SDK, as you see the `/read` and `/unread` endpoints are not present:
https://github.com/GetStream/stream-chat-android/blob/1e57cb3e5ba684fb74430ca5838770aba564cbe2/stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/endpoint/ChannelApi.kt

Also please mention this functionality in the docs, it's currently not listed there.

Thanks!

**Comment by matteinn** [comment]
Apparently the ability to mark as read is available, unread is not

<img width="772" alt="Screenshot 2023-11-16 at 10 13 59" src="https://github.com/GetStream/stream-chat-android/assets/531755/2f50e049-6e98-4244-8ab4-745c638f277f">

**Comment by DanielNovak** [comment]
Hi @matteinn , sorry for the late reply. We are actively working on this feature and we may have something ready in 1-2 weeks.

**Comment by matteinn** [comment]
Thanks @DanielNovak! I have noticed the ongoing work, good luck! 💪
