### ISSUE TITLE
 Issue with Reply Message Functionality in Push Notifications

### ISSUE THREAD

**Issue by Testtaccount** [GetStream/stream-chat-android#5034]
**Describe the bug**
The reply message functionality, when offline plugin is connected, is not working as expected. When application is in a killed state and a push notification is displayed, users can reply to a message within the notification. However, after replying to a message, typing directly in notifications input area and sending a message, the chat with the current user stops being displayed, conversations are lost. Instead, it shows "No Messages" until the app's cache is cleared. This behavior is unexpected and disrupts the user experience.

**SDK version**
- 6.0.5

**To Reproduce**
1. Ensure the application has offline chat support and it is in a killed state.
2. Receive a push notification.
3. Click on the notification's  "reply" action and write message in input area and send it
4. After replying, observe that the chat with the current user , chat is no longer displayed
5. The conversation shows "No Messages."

**Expected behavior**
We expect that when a user replies to a message in a push notification, the chat with the current message should continue to be displayed in the user's conversations. The "No Messages" issue should not occur, and users should not need to clear the app's cache to resolve this.

**Device:**
 - Vendor and model: Pixel 7
 - Android version: 14

**Device:**
 - Vendor and model: Redmi note 6 pro
 - Android version: 9

**Comment by DanielNovak** [comment]
Thank you for reporting the issue. We have been able to reproduce the problem with your instructions and we are looking into it now.

**Comment by DanielNovak** [comment]
Fixed in https://github.com/GetStream/stream-chat-android/releases/tag/v6.0.9
