### ISSUE TITLE
Show Reply in Channel

### ISSUE THREAD

**Issue by hashlin** [GetStream/stream-chat-android#510]
[Show Reply in Channel is implemented in iOS SDK a few weeks ago](https://github.com/GetStream/stream-chat-swift/pull/271). 
Is this feature implemented in Android SDK?

**Comment by hashlin** [comment]
If a reply message is sent to main channel using iOS SDK, this message is visible in iOS but not in Android.

StreamChatAndroid SDK Version : 3.6.12

**Comment by elevenetc** [comment]
Hi @hashlin right now it's implemented only on iOS, other platforms do not support it.

**Comment by hashlin** [comment]
Is there any workaround to query thread's message(which is also replied to main channel) from main channel?

**Comment by elevenetc** [comment]
There are few things which might help you:
- you can get replies like this:
```kotlin
StreamChat.getInstance(this).getReplies(parentMessageId, limit, firstMessageIdOrNull, listener)
// or
channel.getReplies(parentMessageId, limit, firstMessageIdOrNull, listener)
```
- message (reply) object has map `extraData` and you can identify if it is visible in channel or not:

```kotlin
boolean showInChannel = (boolean) message.getExtraData().get("show_in_channel", false);
```
- to send reply visible in channel you need to set the same boolean to true:

```kotlin
Message newMessage = new Message();
newMessage.getExtraData().put("show_in_channel", true);
```

**Comment by hashlin** [comment]
Thank you so much @elevenetc . I will have a look.

**Comment by samiuelson** [comment]
@hashlin Thanks for getting in touch, we are currently pushing on a new major release which will implement sending replies to the channel. You can subscribe to this issue to stay up-to-date to the release https://github.com/GetStream/stream-chat-android/issues/554
