### ISSUE TITLE
Push Notification

### ISSUE THREAD

**Issue by Zee-93** [GetStream/stream-chat-android#5113]
**When app is in background**
When app is in background push notifications are not working and displaying rather than when app have been killed then notifications work perfectly.

**SDK version**
- 5.15.0

**To Reproduce**
1. Go to background 
2. Send Push notification
3. you will see notification trigger but did not display

**Expected behavior**
It should display push notification but did not show any notification.

**Device:**
 - Vendor and model: [Google Pixel]
 - Android version: [12]

**Screenshots**

**Comment by aleksandar-apostolov** [comment]
Hi @Zee-93

We have done several updates regarding push notification and by using the latest v5 SDK I was unable to reproduce the issue anymore.

Please update to a later version (e.g [v5.17.19](https://github.com/GetStream/stream-chat-android/releases/tag/v5.17.19-hotfix))

Let us know if this resolves the issue.

**Comment by rusmichal** [comment]
@Zee-93 have you figured it out? I have the same issue.

**Comment by abdulmanum** [comment]
I am also not getting the notification.
If I apply the firebase broadcast receiver. then I get the data. but there is no title, body, message etc, also not in the notification object. But I get the data like 

in data object I get below data in which there is no title, body or message
{
"receiver_id": "16",
"channel_id": "product_97_30",
"message_id": "30-f4748f2c-69bb-491c-9994-b19b6b07185f",
"sender": "stream.chat",
"channel_type": "messaging",
"id": "30-f4748f2c-69bb-491c-9994-b19b6b07185f",
"cid": "messaging:product_97_30",
"type": "message.new",
"version": "v2"
}
