### ISSUE TITLE
Time stamp is not correct in message list 

### ISSUE THREAD

**Issue by adadhich1** [GetStream/stream-chat-android#5125]
**Describe the bug**
After updating the SDK to 6.0.9 i'm getting the issue of not displaying the time correct according to time zone in message list for sent and received message 

**SDK version**
- 6.0.9
- 
**To Reproduce**
Open the chat and send or receive any message and time below any message is not according to the time zone in which you are.

**Expected behavior**
Once a user sends or receive any message the time shown should be according to the time zone in which the user is.

**Device:**
 - All the devices

**Comment by JcMinarro** [comment]
Hello @adadhich1 
We already fixed it on https://github.com/GetStream/stream-chat-android/pull/5101 and it should be ready on the last release.
Could you check it?

**Comment by adadhich1** [comment]
@JcMinarro , thank you, it worked
