### ISSUE TITLE
Video thumbnail not showing

### ISSUE THREAD

**Issue by adadhich1** [GetStream/stream-chat-android#5127]
**Describe the bug**
After attaching the video attachment in the chat, thumbnail is not showing even after making it enabled using videoThumbnailsEnabled = true, 
**SDK version**
- 6.0.10

**To Reproduce**
1. Go to message list
2. Click on attachment and send any video attachment
3. once attachment is sent, video thumbnail is not showing

**Expected behavior**
After sending video attachment, it should show video thumbnail in message list

**Device:**
 -  all the devices

**Comment by DanielNovak** [comment]
Can you try it with our sample application? I tried the latest version (Compose) and video previews seem to work - both when recorded directly and uploaded or when attached as file.

**Comment by adadhich1** [comment]
@DanielNovak, I am using xml and not compose, and even though videoThumbnailsEnabled is enabled by default but its not visible to me, i've tried with almost 5-6 devices, its not working in any of those.

**Comment by DanielNovak** [comment]
I tried our XML sample application (in this repo) and video thumbnails work there. Are you using our UI components? Any customisation that could affect this? Did this work before and stopped working after updating to a newer version?

**Comment by adadhich1** [comment]
Yes, we are using your UI components, earlier we were using very old sdk version, that time we could see video files as other doc files and not as video thumbnail, 
Also we did not make any customisation to the message list
