### ISSUE TITLE
Cancel giphy in a channel, leave channel and come back, it still shows.

### ISSUE THREAD

**Issue by zeroarst** [GetStream/stream-chat-android#5151]
**Describe the bug**
Cancel giphy in a channel, leave channel and come back, it still shows.

**SDK version**
- 6.0.8

**To Reproduce**
1. Open a channel.
2. Send giphy command
3. Canel giphy
4. Leave channel
5. Go back to the channel
6. The giphy is still there.

**Expected behavior**

**Device:**
 - Vendor and model: Samsung S23
 - Android version: 14

**Screenshots**
https://github.com/GetStream/stream-chat-android/assets/1834837/f7eff57d-8e6b-4e1d-8164-5bf1b9d161b0

**Comment by allanswer** [comment]
I had the same issue, please help to check it.

**Comment by kanat** [comment]
Hi @zeroarst,

Thank you for reporting about this issue.
We were able to replicate it 👍

**Comment by zeroarst** [comment]
Just to add, I dug into the source code and suspect it might have something to do with `channelCache` in `DatabaseChannelRepository`.
