### ISSUE TITLE
Incoming attachments are not displaying

### ISSUE THREAD

**Issue by Zee-93** [GetStream/stream-chat-android#5176]
**Incoming attachments not displaying**
Incoming attachments are not showing attachments content like image or any other file. This is showing just a text attachment sent. But attachments that i am sending are showing.

**SDK version**
- 5.17.21

**To Reproduce**
1. Go to all channels
2. Click on any channel to open detail screen
3. Scroll down to any other user attachment
4. It will just showing "attachment sent"

**Expected behavior**
Attachment content should be visible to me.

**Device:**
 - Google Pixel 3
 - Android version: 12

**Screenshots**

**Comment by JcMinarro** [comment]
Hello @Zee-93 

Are you customizing the MessageListView?
Could you share with us which customization you are doing there?
