### ISSUE TITLE
how to remove chat domain when the user logs out

### ISSUE THREAD

**Issue by abhirup-patra** [GetStream/stream-chat-android#520]
java.util.InputMismatchException: received connect event for user with id user30462 while chat domain is configured for user with id user30499. create a new chatdomain when connecting a different user.

this is the error i am receiving when trying to set up a new chat domain

I am using `new ChatDomain.Builder(getApplicationContext(), client, user).build();` everytime when the app is opened and also while logging in

**Comment by abhirup-patra** [comment]
Hi,
Any fix date when the issue if any is going to be solved?

**Comment by abhirup-patra** [comment]
I am also facing several issues when the chat tries to access chat domain in the background. The app keeps crashing with report.-

`
Caused by kotlin.UninitializedPropertyAccessException
lateinit property instance has not been initialized
io.getstream.chat.android.livedata.ChatDomain$Companion.instance (ChatDomain.kt:140)
io.getstream.chat.android.livedata.ChatDomain$-CC.instance (Unknown Source:2)
com.getstream.sdk.chat.viewmodel.ChannelListViewModel.<init> (ChannelListViewModel.java:77)
java.lang.reflect.Constructor.newInstance0 (Constructor.java)
java.lang.reflect.Constructor.newInstance (Constructor.java:343)
androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create (ViewModelProvider.java:267)
androidx.lifecycle.SavedStateViewModelFactory.create (SavedStateViewModelFactory.java:106)
androidx.lifecycle.ViewModelProvider.get (ViewModelProvider.java:185)
androidx.lifecycle.ViewModelProvider.get (ViewModelProvider.java:150)
abentra.com.views.fragments.stream_chat.ChannelListFragment.onCreateView (ChannelListFragment.java:185)
androidx.fragment.app.Fragment.performCreateView (Fragment.java:2698)
androidx.fragment.app.FragmentStateManager.createView (FragmentStateManager.java:310)
androidx.fragment.app.FragmentManager.moveToState (FragmentManager.java:1185)
androidx.fragment.app.FragmentManager.moveToState (FragmentManager.java:1354)
androidx.fragment.app.FragmentManager.moveFragmentToExpectedState (FragmentManager.java:1432)
androidx.fragment.app.FragmentManager.moveToState (FragmentManager.java:1495)
androidx.fragment.app.BackStackRecord.executeOps (BackStackRecord.java:447)
androidx.fragment.app.FragmentManager.executeOps (FragmentManager.java:2167)
androidx.fragment.app.FragmentManager.executeOpsTogether (FragmentManager.java:1990)
androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute (FragmentManager.java:1945)
androidx.fragment.app.FragmentManager.execPendingActions (FragmentManager.java:1847)
androidx.fragment.app.FragmentManager.dispatchStateChange (FragmentManager.java:2621)
androidx.fragment.app.FragmentManager.dispatchActivityCreated (FragmentManager.java:2569)
androidx.fragment.app.Fragment.performActivityCreated (Fragment.java:2722)
androidx.fragment.app.FragmentStateManager.activityCreated (FragmentStateManager.java:336)
androidx.fragment.app.FragmentManager.moveToState (FragmentManager.java:1186)
androidx.fragment.app.FragmentManager.moveToState (FragmentManager.java:1354)
androidx.fragment.app.FragmentManager.moveFragmentToExpectedState (FragmentManager.java:1432)
androidx.fragment.app.BackStackRecord.executeOps (BackStackRecord.java:442)
androidx.fragment.app.FragmentManager.executeOps (FragmentManager.java:2167)
androidx.fragment.app.FragmentManager.executeOpsTogether (FragmentManager.java:1990)
androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute (FragmentManager.java:1945)
androidx.fragment.app.FragmentManager.execPendingActions (FragmentManager.java:1847)
androidx.fragment.app.FragmentManager$4.run (FragmentManager.java:413)
android.os.Handler.handleCallback (Handler.java:873)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:214)
android.app.ActivityThread.main (ActivityThread.java:7094)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:494)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:975)
`

**Comment by samiuelson** [comment]
@abhirup-patra To set a new user `ChatDomain.disconnect()` should be called first.

**Comment by tbarbugli** [comment]
@samiuelson beside updating the docs, do you think we can return a more informative error message? Sounds like an easy configuration mistake to make

**Comment by tbarbugli** [comment]
let's move this into #524

**Comment by abhirup-patra** [comment]
> @abhirup-patra To set a new user `ChatDomain.disconnect()` should be called first.

chatdomain.disconnect is called when i am logging out from the app. Still the issue arrives of

**`received connect event for user with id user30462 while chat domain is configured for user with id user30499. create a new chatdomain when connecting a different user.`**

**Comment by abhirup-patra** [comment]
What to pass inside chatdomain.disconnect function?

**Comment by samiuelson** [comment]
`disconnect()` is a suspend function it requires `Continuation`. 
More info on coroutines: https://kotlinlang.org/docs/reference/coroutines/basics.html
sample usage of `disconnect()`: https://github.com/GetStream/stream-chat-android/blob/develop/library/src/main/java/com/getstream/sdk/chat/ChatImpl.java#L147
