### ISSUE TITLE
custom design when the channle list is empty

### ISSUE THREAD

**Issue by abhirup-patra** [GetStream/stream-chat-android#521]
unable to check whether the channel list is empty or not to add a custom empty image view

**Comment by samiuelson** [comment]
@abhirup-patra In the new version of SDK it's going to be easy to subscribe to `ChannelsViewModel.State.NoChannelsAvailable` event and display custom view in such a case. 

You can see sample usage here: https://github.com/GetStream/stream-chat-android/pull/533

The change will be available soon in the beta.

**Comment by abhirup-patra** [comment]
is it implemented in this beta 5 release? because i am not able to find that in this beta 5 release as well

**Comment by samiuelson** [comment]
Not yet. It will be released in one of the next releases along with a new sample app, revamped view models, and bunch of technical improvements.

**Comment by JcMinarro** [comment]
Hello @abhirup-patra 
As Samuel said, we have added an option to show an EmptyState View when no channels on #533 
It is already part of the version [4.2.11-beta-6](https://github.com/GetStream/stream-chat-android/releases/tag/4.2.11-beta-6), not a final release yet, we will update #554 when the final version is ready

**Comment by abhirup-patra** [comment]
may i know how to implement that? @JcMinarro

**Comment by JcMinarro** [comment]
Hello @abhirup-patra we are working to improve our documentation, it will be ready when we release the final version.
In the meantime you can check the sample apps in the repo, where we integrate the different SDK Views.
The new `ChannelsView` has two methods that allow you to define a customView for LoadingState and a customView for EmptyState.

You should do something like:
```
val myEmptyStateView = generateMyEmptyStateView()
channelsView.setEmptyStateView(myEmptyStateView)
```

With that, it should show your emptyState when no channels are found

**Comment by abhirup-patra** [comment]
how to check whether the channel is empty or not?

**Comment by JcMinarro** [comment]
If you are binding the UI to the ViewModel with the following method:
```
ChannelListViewModelBindingKT.bindView(channelsViewModel, channelsView, lifecycleOwner)
```

It will do it automatically. If you are not using the ViewModel, you can handle it by yourself calling:
```
channelsView.hideEmptyStateView() // Hide the empty state
channelsView.showEmptyStateView() // Show the empty state
channelsView.hideLoadingView() // Hide the loading state
channelsView.showLoadingView() // Show the loading state
```
