### ISSUE TITLE
Unable to input Japanese text using MessageComposer

### ISSUE THREAD

**Issue by k0goto** [GetStream/stream-chat-android#5215]
**Describe the bug**

Unable to input Japanese text using MessageComposer.
Japanese is a language composed of three types of characters: Hiragana, Katakana, and Kanji. When input Japanese text on a app, we use software called an[ Input Method Editor (IME)](https://www.google.com/intl/en/inputtools/services/features/input-method.html) to convert the character types.
Since updating my app's Stream SDK to version 6.1.0, The MessageComposer now confirms the input result with each character inputted. As a result, it has become impossible to input Japanese text because the IME cannot be used.

**SDK version**
- 6.1.0

**To Reproduce**

**Expected behavior**

**Device:**
 - Vendor and model: Google Pixel7
 - Android version: 14

**Screenshots**

| 6.0.14 | Since 6.1.0 |
| --- | --- |
| <video src="https://github.com/GetStream/stream-chat-android/assets/13537816/35dcfdb4-963c-45ae-899e-c15d28a3e9c9" /> | <video src="https://github.com/GetStream/stream-chat-android/assets/13537816/aac3ad58-7a5a-4b7a-be64-f2f84110b058" /> |

**Comment by DanielNovak** [comment]
This looks like an issue on our side, we will investigate it as soon as possible. Thanks for reporting.

**Comment by kanat** [comment]
Hi @k0goto,

I was unable to replicate it with [v6.5.0](https://github.com/GetStream/stream-chat-android/releases/tag/v6.5.0) on Pixel 7 (Android 14). Could you please double-check with the latest version?

https://github.com/user-attachments/assets/967982d6-00f6-4263-aa43-2d5e0f8b90ca
