### ISSUE TITLE
Message sender not being updated

### ISSUE THREAD

**Issue by prarthnastockgro** [GetStream/stream-chat-android#523]
User A logs out, and user B logs in -> the setUser method is working fine and updating the user.
LlcMigrationUtils.getCurrentUser() gets the right user.
But the message sender still shows User A. I even updated the user using:
message.user = LlcMigrationUtils.getCurrentUser()
How can i update the sender properly?
@elevenetc @tschellenbach

**Comment by elevenetc** [comment]
That's a bug, sender should be set by SDK, no need to set it manually.
And `LlcMigrationUtils` is a beta migration utility class, we will remove it when SDK is stable.

**Comment by JcMinarro** [comment]
Hello @prarthnastockgro 
There was a bug with the logout behavior that has been fixed here #563 
Could you test with the version [4.2.11-beta-6](https://github.com/GetStream/stream-chat-android/releases/tag/4.2.11-beta-6)?
It is not a final version yet, but we are planning to release it soon, you can follow this issue #554  where we will notify when the final version is ready
