### ISSUE TITLE
Unable to use scrollToMessage when the message is not present in list

### ISSUE THREAD

**Issue by rixon08** [GetStream/stream-chat-android#5237]
**Describe the bug**
I tried to use scrollToMessage in MessageListView to message that not present in list and nothing happend. But it works when message is already present in list. How to make scroll to message that not present in list?

**SDK version**
- 6.2.3

**Comment by JcMinarro** [comment]
Hello @rixon08 
The method `MessageListView.scrollToMessage()` as described on its [Javadoc](https://github.com/GetStream/stream-chat-android/blob/main/stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/MessageListView.kt#L771-L776), only scroll to messages that are already added to the view.
If you want to scroll to a message that hasn't been fetched yet, it needs to be fetched before to scroll to it.
If you are using our ViewModel, you can call the `MessageListViewModel.onEvent()` method providing a [ShowMessage](https://github.com/GetStream/stream-chat-android/blob/main/stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/viewmodel/messages/MessageListViewModel.kt#L676-L687) instance with the desired message id to scroll to.
