### ISSUE TITLE
After reacting on message, message list scrolls down to bottom

### ISSUE THREAD

**Issue by dhaivat29** [GetStream/stream-chat-android#5241]
**Describe the bug**
I am getting a strange issue after migrating chat sdk to **6.3.1** from **5.17.23**, when there are many messages in the thread and reacting on any message that is on top, after adding a reaction to it, the view automatically scrolls down to the bottom. Which is very inappropriate behaviour. This same happens with the mark as an unread feature. 

**SDK version**
- 6.3.1

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the messages list and establish the long conversation.
2. Now select any message from the topmost of the list
3. Try to react to it or make it marked as unread 
4. It scrolls down automatically to the latest message

**Expected behaviour**
It should stay in the same position whichever message gets reacted. 

**Device:**
 - Any device
 - Android version: [14,13]
 
 Here is the video for the reference. 
 
 https://drive.google.com/file/d/141TF2yhQRPIvlAHNRx3axu9VpvUyeDZW/view?usp=sharing

**Comment by JcMinarro** [comment]
It has been fixed on #5280 and will be release in a new version in a couple of days

**Comment by dhaivat29** [comment]
Hello,

I am trying to update the latest version for the Stream chat Android, which
is currently 6.4.1.
After updating that I am facing following issue which I am attaching
with this email.

I am using the below gradle dependencies.

implementation "io.getstream:stream-chat-android-ui-components:6.4.1"
    implementation "io.getstream:stream-chat-android-offline:6.4.1"
    implementation "io.getstream:stream-chat-android-client:6.4.1"
    implementation "io.getstream:stream-log:1.1.4"
    implementation "io.getstream:stream-android-push:1.1.8"
    implementation "io.getstream:stream-android-push-firebase:1.1.7"




*Thanks & RegardsDhaivat ShahSr. Software Engineer*

**Comment by JcMinarro** [comment]
Hello @dhaivat29 
It looks like the reply by email to the Github Issue is not attaching all the info to the issue itself. 
Could you add the information on the Github Issue website (https://github.com/GetStream/stream-chat-android/issues/5241)
Thanks

**Comment by dhaivat29** [comment]
Hello,

Let me look into this and get back to you.

I will add information on the same issue tickets.



*Thanks & RegardsDhaivat ShahSr. Software Engineer*
