### ISSUE TITLE
When the giphy is the first message of the channel, it won't disappear when the user click cancel 

### ISSUE THREAD

**Issue by allanswer** [GetStream/stream-chat-android#5246]
Describe the bug
When the giphy is the first message of the channel, it won't disappear when the user click cancel 

SDK version
6.1.0

To Reproduce
Create an new channel with a user 
Send giphy as the first message of the channel
Click cancel
The giphy won't disappear

Device:
Vendor and model: Pixel 8 Pro API 34
Android version: 14

Recording:
https://drive.google.com/file/d/1OlR4k8MepqjYgVpphp-vpTdfYtSHCd_Q/view?usp=sharing

**Comment by allanswer** [comment]
Can anyone help to take a look on this issue ?

**Comment by JcMinarro** [comment]
Hello @allanswer 
We are investigating it and will fix it

**Comment by allanswer** [comment]
@JcMinarro Any update for this issue ?

**Comment by aleksandar-apostolov** [comment]
Hey @allanswer, 
This issue is fixed.
Thanks for updating to the latest version.
