### ISSUE TITLE
Issue in Compiling the Project 

### ISSUE THREAD

**Issue by VigneshKSI** [GetStream/stream-chat-android#5255]
**Describe the bug**
I am using the android studio of version (Koala) when trying to open the app and sync then getting the issue which I have attached screenshots
error 
Task 'wrapper' not found in project ':stream-chat-android-ui-components-sample'.

* Try:
> Run gradle tasks to get a list of available tasks.
> For more on name expansion, please refer to https://docs.gradle.org/8.5/userguide/command_line_interface.html#sec:name_abbreviation in the Gradle documentation.
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Get more help at https://help.gradle.org.
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
For more on this, please refer to https://docs.gradle.org/8.5/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
BUILD FAILED in 2s
4 actionable tasks: 1 executed, 3 up-to-date
Watched directory hierarchies: [C:\Users\VigneshR\AndroidStudioProjects\stream-chat-android]

**SDK version**
- 33

**To Reproduce**
1. When opening the app on android studio then when the app is syncing the gradle the app is not compiling

**Expected behavior**
It should compile the project without any errors and I need to run the app without any issues

**Device:**
 - Vendor and model: [e.g. Samsung S8]
 - Android version: [e.g. 9]

**Screenshots**![image](https://github.com/GetStream/stream-chat-android/assets/37724418/5ed37a63-2f13-496e-a87a-07317b820654)

![image](https://github.com/GetStream/stream-chat-android/assets/37724418/9026ddf3-a496-4242-b161-5ce24ac11114)

![image](https://github.com/GetStream/stream-chat-android/assets/37724418/2f24eb12-7f0c-4771-83db-40ed5e31ecd5)

**Comment by JcMinarro** [comment]
Hello @VigneshKSI 
You need to open the full project and then run the Ui Components Sample App.
The Sample App depend on the rest of modules of the project
