### ISSUE TITLE
Highlighting and tapping on user mentions

### ISSUE THREAD

**Issue by matteinn** [GetStream/stream-chat-android#5263]
Describe the feature you'd like to see in the SDK

Recently on the iOS SwiftUI repo you have rolled out the ability to highlight and tap on user mentions.
With feature parity in mind, it is reasonable to expect to see the same feature on the android library at some point.
Do you have any plans for that?

See release 4.53.0: https://github.com/GetStream/stream-chat-swiftui/releases/tag/4.53.0

**Comment by VIPlearner** [comment]
Hi @matteinn Can you please share more info on how we expect this behaviour to look like

Maybe share how it works on the iOS App 

should clicking the user mention navigate you to the user chat or do we expect a dialog to show
Or is the goal to keep it open for the user to decide what to do?

Apologies if my questions are "useless" I'm very much new to this project and just trying to find my way around

**Comment by matteinn** [comment]
Hello!
The iOS implementation is shown [in this PR](https://github.com/GetStream/stream-chat-swiftui/pull/473/files): user mentions (e.g. `@matteinn`) are highlighted inside messages and clicking on them will trigger a special link to be opened, which has this format `getstream://mention/{messageId/{userId}`. That link can be intercepted by the app using the SDK and do whatever is needed with that.
In my case, that will open the user profile page after extracting the userId from that url.

**Comment by aleksandar-apostolov** [comment]
This was solved [here](https://github.com/GetStream/stream-chat-android/pull/5408).
