### ISSUE TITLE
Google Play's Photo and Video Permissions

### ISSUE THREAD

**Issue by Nyan274** [GetStream/stream-chat-android#5278]
By August 2024, Google requires the Apps with one-time or infrequent use of photos are requested to remove READ_MEDIA_IMAGES and READ_MEDIA_VIDEO permissions from their app manifest and migrate to a system photo picker if necessary.

Since the client app doesn't use photo and video messaging feature, it's hard to pass the app review by play store.

[https://support.google.com/googleplay/android-developer/answer/14115180?hl=en](https://support.google.com/googleplay/android-developer/answer/14115180?hl=en)

[https://support.google.com/googleplay/android-developer/answer/13986130?sjid=2278959419600922286-AP](https://support.google.com/googleplay/android-developer/answer/13986130?sjid=2278959419600922286-AP)

**Comment by JcMinarro** [comment]
Hello @Nyan274 
The SDK needs those permissions to work, because it is a core functionality.
If your app doesn't use this functionallity at all, you can remove those permission from the Andorid Manifest by using the following line:
```
    <uses-permission android:name="android.permission.READ_MEDIA_IMAGES" tools:node="remove" />
    <uses-permission android:name="android.permission.READ_MEDIA_AUDIO" tools:node="remove" />
    <uses-permission android:name="android.permission.READ_MEDIA_VIDEO" tools:node="remove" />
```

**Comment by aleksandar-apostolov** [comment]
Hey @Nyan274 
We've added support for this in our SDK so you can use the native pickers instead of the built in picker. 
You can check this [PR](https://github.com/GetStream/stream-chat-android/pull/5380) 
Also you need to remove the permissions as mentioned above by @JcMinarro 

Regards,
Alex
