### ISSUE TITLE
Is there a way to check the read status when a custom message view factory is used?

### ISSUE THREAD

**Issue by abhirup-patra** [GetStream/stream-chat-android#530]
I am not able to fetch the read status of the particular message when the message is read. Is there a way to detect the read status in custom messageview factory?

**Comment by abhirup-patra** [comment]
Hi, Any comments here?

**Comment by tschellenbach** [comment]
The read status is exposed when you watch a channel: https://getstream.io/chat/docs/livedata/?language=js#watching-a-channel

Are you using the low level client, offline lib or the UX?
