### ISSUE TITLE
totalUnreadCount is always 0

### ISSUE THREAD

**Issue by KobyGini** [GetStream/stream-chat-android#5301]
Which packages are you using?
stream_chat_compose

On what platforms did you experience the issue?
Android

What version are you using?
6.4.0

What happened?
When I log the totalUnreadCount it's always 0 even when the user hasn't read the messages

Steps to reproduce
with either of the following:
   
val currentUser = ChatClient.instance().getCurrentUser()
           
currentUser.totalUnreadCount
ChatClient.instance().globalState.totalUnreadCount.value

Create two instances of the app

Send a message from one user

With the second user ensure no channel pages have yet been opened

**Comment by JcMinarro** [comment]
Hello @KobyGini 
You should use `ChatClient.instance().globalState.totalUnreadCount`

Keep in mind this property is an `StateFlow`, and you shouldn't directly access to its value, instead of that you should subscribe to any new change it emit:
```
ChatClient.instance().globalState.totalUnreadCount.collect {
    println("The current user has $it unread messages")
}
```
