### ISSUE TITLE
MessageTheme.quotedTextStyle has no effect

### ISSUE THREAD

**Issue by zeroarst** [GetStream/stream-chat-android#5307]
**Describe the bug**

**SDK version**
- 6.4.0

**To Reproduce**
Set the quoteTextStyle as below:
```kotlin

 ChatTheme(
        ownMessageTheme = MessageTheme.defaultOwnTheme().let { theme ->
            theme.copy(
                backgroundColor = Color(0xff343F93),
                textStyle = theme.textStyle.copy(
                    color = Color.Red
                ),
                quotedBackgroundColor = Color.White,
                quotedTextStyle = theme.quotedTextStyle.copy(
                    color = Color.Green // This has no effect.
                ),
            )
        },
    ) {
        // Stream components.
    }
)

```

Does not apply the color to quoted text. With above example, the quoted text should show green text color.
![image](https://github.com/GetStream/stream-chat-android/assets/1834837/7e600975-1ff3-4dbe-bea5-4e14b7d19fe8)

I look at the source code, I cannot find `quotedTextStyle` is used anywhere. Checked `QuotedMessage`, `QuotedMessageContent`, `QuotedMessageText`.

![image](https://github.com/GetStream/stream-chat-android/assets/1834837/36383dc0-686c-4a48-9f0e-e55620b6bfb7)

**Expected behavior**
Quoted text color is changed.

**Device:**
 - Vendor and model: Pixel 3a
 - Android version: 14

**Comment by aleksandar-apostolov** [comment]
Hey @zeroarst thanks for the report, indeed its has no effect. We will fix this in the next release.

**Comment by zeroarst** [comment]
I tried the latest version (6.4.4) and the issue still persists. `ChatTheme.ownMessageTheme.quotedTextStyle` is correctly passed to the `Text` compose, but the color seems to be ovewritten by `styledText: AnnotatedString` color. As you can see from below's screenhot.
`style` has green color;
`styledText` has a red color `SpanStyle`;
![Stream Chat Bug - Invalid Quoted Message Color](https://github.com/user-attachments/assets/082b79ba-7dd1-47d6-90c8-d7df19248dc4)

**Comment by kanat** [comment]
Hey @zeroarst,

Thank you letting us know.
We'll address this issue asap.

**Comment by kanat** [comment]
Hi @zeroarst,

[This](https://github.com/GetStream/stream-chat-android/pull/5373) PR should fix the problem.
It will be available with the next upcoming release.
