### ISSUE TITLE
App crash on long click on message in single chat screen

### ISSUE THREAD

**Issue by Zee-93** [GetStream/stream-chat-android#5309]
**Describe the bug**
All other things works well but when i long press on any message in a chat to copy message , instead of opening the menu , app crashes.

**SDK version**
- 5.15.0
  implementation 'io.getstream:stream-chat-android-ui-components:5.15.0'

**To Reproduce**
1. Go to 'Chats listing screen'
2. Click on 'Any chat'
3. Long press on 'Any Message'
4. See App crash

**Expected behavior**
Menu should open there having option to reply and copy message

**Device:**
 -  Google Pixel 3
 - Android version: 12

**Comment by aleksandar-apostolov** [comment]
Hi @Zee-93 thanks for your report. Is it possible for you to migrate to v6 of the SDK?

**Comment by Zee-93** [comment]
Hi @aleksandar-apostolov i have migrted to V6 now , but issue remains the same , it is consistent with Google Pixel 3 (Android 12) and Oppo (Android 11) and Infinix (Android 11) and Samsung s22 .

SDK version
6.4.0
implementation 'io.getstream:stream-chat-android-ui-components:6.4.0'

To Reproduce
Steps to reproduce the behavior:

Go to 'Chats listing screen'
Click on 'Any chat'
Long press on 'Any Message'
See App crash
Expected behavior
Menu should open there having option to reply and copy message
