### ISSUE TITLE
Connect user doesn't return error callback

### ISSUE THREAD

**Issue by VasiliZ** [GetStream/stream-chat-android#5331]
I try to refresh user token for chats.
At first login in an app i have got a token from backend and save it. I use this token couple of days. After that token expired and I have the next sessages in my logs 

> (DefaultDispatcher-worker-7:54528) [handleError] error: NetworkError(message=JWTAuth error: token is expired (exp), serverErrorCode=40, statusCode=401, cause=null)

> (DefaultDispatcher-worker-7:54528) [onNetworkError] error: NetworkError(message=JWTAuth error: token is expired (exp), serverErrorCode=40, statusCode=401, cause=null)

I try to solve it problem with connect user method callback 
![image](https://github.com/user-attachments/assets/a020c008-d768-4456-81c3-6ccc681f8203)
If I have valid token I get a success callback and all works. But if I have a wrong token I get nothing.
And my get stream token doesn't resresh.
![image](https://github.com/user-attachments/assets/d6eccba8-4227-413b-b505-acdae700fec1)
How must it work?

**SDK version**
- android compose - 6.4.0

**Comment by JcMinarro** [comment]
Hello @VasiliZ 
If you want the SDK refresh the expired tokens, you need to provide a [TokenProvider](https://github.com/GetStream/stream-chat-android/blob/main/stream-chat-android-client/src/main/java/io/getstream/chat/android/client/token/TokenProvider.kt) implementation, instead of connect user with an static token.

Something like:
```
class MyTokenProvider(api: MyServerApi) : TokenProvider {
   override fun loadToken(): String {
     val newToken = api.fetchNewToken()
     return newToken
  }
}

val chatClient = ChatClient.Builder(...)
  [...]
  .build()

val myApi: MyServerApi = [...]
val myTokenProvider = MyTokenProvider(myApi)
chatClient.connectUser(
  user = User(id = userId),
  tokenProvider = myTokenProvider,
```

**Comment by VasiliZ** [comment]
I'm so sorry. I try to implement it.
