### ISSUE TITLE
Wrong member query

### ISSUE THREAD

**Issue by Bobbykart** [GetStream/stream-chat-android#5334]
**Describe the bug**
I use the query members function described [ here]( https://getstream.io/chat/docs/android/query_members/?language=kotlin)
My code looks like this: 

```
val channelClient = ChatClient.instance().channel(channelType = channelType, channelId = channelId)
val filter = Filters.neutral()
val offset = 0
val limit = 10
val sort = QuerySortByField<Member>().desc("created_at")

channelClient.queryMembers(offset, limit, filter, sort).enqueue { result ->
            if (result.isSuccess) {
                onSuccess(result.getOrNull() ?: emptyList())
            } else {
                Log.e("ChatRepository", String.format("There was an error %s", result.errorOrNull()))
            }
        } 
```

It returns me this error: 

> Failure(value=NetworkError(message=QueryMembers failed with error: "Can't find channel with id JnLWRlwhtKpHZlgUMXaU:messaging"
More information available at https://getstream.io/chat/docs/api_errors_response, serverErrorCode=16, statusCode=404, cause=null))

The problem is that when i create a channel like [here](https://getstream.io/chat/docs/android/creating_channels/?language=kotlin)
```
val channelClient = client.channel(channelType = "messaging", channelId = "general")

channelClient.create(memberIds = emptyList(), extraData = emptyMap()).enqueue { result ->
    if (result.isSuccess) {
        val newChannel: Channel = result.data()
    } else {
        // Handle result.error()
    }
}
```
The channel id is like this: **messaging:JnLWRlwhtKpHZlgUMXaU**.

The channel ID and channel type is in reverse order compared to the member query error.

**SDK version**
- 6.4.0

**To Reproduce**
Follow the code above.

**Expected behavior**
A list of members in a given chanel.

**Device:**
 - Android Studio Emulator

**Comment by kanat** [comment]
Hey @Bobbykart ,

The right order is `<channel_type>:<channel_id>`

It feels like `channelType` and `channelId` are mixed up here:
```
ChatClient.instance().channel(channelType = channelType, channelId = channelId)
```

`ChannelClient` is just a wrapper which call `ChatClient.queryMembers` under the hood.

**Comment by Bobbykart** [comment]
> Hey @Bobbykart ,
> 
> The right order is `<channel_type>:<channel_id>`
> 
> It feels like `channelType` and `channelId` are mixed up here:
> 
> ```
> ChatClient.instance().channel(channelType = channelType, channelId = channelId)
> ```
> 
> `ChannelClient` is just a wrapper which calls `ChatClient.queryMembers` under the hood.

Hi kanat,
thanks a lot for the hint!  found the error, i mixed up those two parameters when calling the function.
