### ISSUE TITLE
totalUnreadCount is not updated properly 

### ISSUE THREAD

**Issue by allanswer** [GetStream/stream-chat-android#5344]
**Describe the bug**
Unread messages are stuck even when there are no unread messages. Whenever I retrieve the totalUnreadCount, it returns 3 unread messages. The dashboard shows 0 in total_unread_count.

**SDK version**
6.4.0

**To Reproduce**
https://github.com/user-attachments/assets/e7dd4f50-8969-43ad-8833-670996d19b4e

Here is the code I used to get totalUnreadCount

1.
```
chatClient.subscribeFor(
    NewMessageEvent::class,
    NotificationMessageNewEvent::class,
    MarkAllReadEvent::class,
    NotificationMarkReadEvent::class
) { event ->
    val currentUser = chatRepository.getCurrentUser()
    Timber.d("received chat event: ${event.type}")
    when (event) {
        is NewMessageEvent -> {
            unreadChatsCount.value = event.totalUnreadCount
            if (event.message.user.id == currentUser?.id) {
                sendChatNewMessageAnalytics(event, userType)
            }
        }
        is NotificationMessageNewEvent -> {
            unreadChatsCount.value = event.totalUnreadCount
        }
        is MarkAllReadEvent -> {
            unreadChatsCount.value = event.totalUnreadCount
        }
        is NotificationMarkReadEvent -> {
            unreadChatsCount.value = event.totalUnreadCount
        }
        else -> {}
    }
}
```

2.
`ChatClient.instance().globalState.totalUnreadCount.collect { println("The current user has $it unread messages") }`

**Expected behavior**
Bothe above codes got 3 for totalUnreadCount with no unread messages.
The totalUnreadCount should be 0, but it always return 3.

Is there any method to sync and clear the stuck unread messages? Thanks!

**Device:**
 - Vendor and model: Pixel 8 Pro
 - Android version: 14

**Comment by kanat** [comment]
Hey @allanswer,

Could you please share your:
- app_id
- user_id
