### ISSUE TITLE
Message not changed to translated messsage after call client.translate

### ISSUE THREAD

**Issue by rixon08** [GetStream/stream-chat-android#5349]
**Describe the bug**
I tried to use ChatClient.translate to translate the message to French. After get success, the message won't change anything. But there is description below message "Translated to French".

**SDK version**
- 6.4.4

**To Reproduce**
1. Call function ChatClient.translate
2. After success, message won't change anything, but there is description below message "Translated to French".

**Expected behavior**
Message will change after success get translated message

**Device:**
 - Android version: 14

**Screenshots**
<img width="312" alt="Screenshot 2024-08-12 at 16 47 57" src="https://github.com/user-attachments/assets/8ff3fe29-c3bc-42eb-8887-3f583f101cd7">

**Comment by kanat** [comment]
Hi @rixon08,

It seems like you've enabled auto translation.
If so, you don't need to manually call `ChatClient.translate`

Here are the docs you could follow instead:
- https://getstream.io/chat/docs/sdk/android/ui/guides/custom-translations/#automatic-translation
- https://getstream.io/chat/docs/node/translation/

**Comment by rixon08** [comment]
Hi @kanat 
Should I set those 2 docs to make translation work? 
Because I just set from this docs only https://getstream.io/chat/docs/sdk/android/ui/guides/custom-translations/#automatic-translation.

**Comment by kanat** [comment]
Hi @rixon08,

Yes, both setups are required.

**Comment by rixon08** [comment]
Hi @kanat 
What if I want to translate one message only that I choose, not all message in that channel. Should I call `ChatClient.translate` and set this docs https://getstream.io/chat/docs/node/translation/#enabling-automatic-translation?

**Comment by kanat** [comment]
Hi @rixon08,

If you'd like translate just a single message, you don't need to enable `auto_translation` at all.
You can just call `ChatClient.translate`

**Comment by rixon08** [comment]
Hi @kanat 
I've tried to add this doc https://getstream.io/chat/docs/sdk/android/ui/guides/custom-translations/#supporting-auto-translation-in-the-custom-chatmessagetexttransformer and after I call ChatClient.translate, message doesn't changed. But after I close View then I open again, the message has changed. How to make message changed after call ChatClient.translate?

**Comment by kanat** [comment]
Hey @rixon08,

What UI components do you use: Compose or XML?

**Comment by rixon08** [comment]
Hi @kanat 
I'm using XML

**Comment by kanat** [comment]
Hey @rixon08,

We’ve created a [PR](https://github.com/GetStream/stream-chat-android/pull/5437) that adds a `Translate` action to the sample app, so you can implement something similar.

Please note that although the SampleApp uses ChatClient.getCurrentUser().language, it’s not mandatory to follow this approach. You can pass any language you prefer, such as the language stored in your app.

<table>
<thead>
<tr>
<th>Manual Translation to User's language</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://github.com/user-attachments/assets/f013f871-0ba3-4fa6-93f3-a0044b20ca52" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>

**Comment by rixon08** [comment]
Hi @kanat ,
I've tried it and it works. Thank you very much. I will close this
