### ISSUE TITLE
The channel object returned has empty data

### ISSUE THREAD

**Issue by prarthnastockgro** [GetStream/stream-chat-android#537]
When a channel's members are updated, the Channel object returned has empty values for "id", "cid", extradata, etc
@elevenetc @tschellenbach

**Comment by samiuelson** [comment]
@prarthnastockgro thank you for reporting this. Can you share more details on what SDK version and what specific API are you trying to use?

**Comment by tbarbugli** [comment]
@samiuelson the API returns a full channel response when you add/remove members. Perhaps this is something that gets lost in the LLC? @prarthnastockgro if you can share SDK version and a code snippet that would be wonderful :)

**Comment by JcMinarro** [comment]
Hello @prarthnastockgro 

Could you share with us which SDK Version you are using?
Where are you getting empty data into the channel object?
