### ISSUE TITLE
How to create list of contacts that are registed in app like WhatsApp using XML

### ISSUE THREAD

**Issue by Niksha36** [GetStream/stream-chat-android#5372]
Guys, I really need help. I know that you can show chats and filter them, but how can you display all users from contacts like in WhatsApp? I have already made an implementation that gets all user contacts and checks whether they are registered or not. The next step is to make an adapter and show these contacts in your recycler view. That is not so easy and i look for a tool in stream sdk to make this right. I also have another idea - just for each registered contact, create a chat with our user and contact where the name of this chat will be the name of the contact, but then what to do with name and chat picture? I can't call different pictures and names for different users for the same chat. Please give me an advise

**Comment by aleksandar-apostolov** [comment]
Hey @Niksha36 
Having the list of contacts as you describe is not part of the SDK, but rather of the application.

Lets continue the discussion that you've already opened here: https://github.com/GetStream/stream-chat-android/discussions/5371
