### ISSUE TITLE
Crash while fetching channel

### ISSUE THREAD

**Issue by prarthnastockgro** [GetStream/stream-chat-android#540]
Getting frequent crashes while fetching channels or getting channel information, could you please help in resolving this one. Here is the stacktrace:
@elevenetc @tschellenbach 
`com.getstream.sdk.chat.viewmodel.ChannelListViewModel.getChannelByCid (ChannelListViewModel.java:310)
com.getstream.sdk.chat.viewmodel.ChannelListViewModel.lambda$initEventHandlers$2 (ChannelListViewModel.java:291)
com.getstream.sdk.chat.viewmodel.-$$Lambda$ChannelListViewModel$PlCqFm2P_CYNqxW60YVyyF8fKSs.invoke (-.java:4)
io.getstream.chat.android.client.utils.observable.Subscription.deliver (Subscription.java:43)
io.getstream.chat.android.client.utils.observable.Subscription.onNext (Subscription.java:23)
io.getstream.chat.android.client.utils.observable.ChatObservableImpl.onNext (ChatObservableImpl.java:17)
io.getstream.chat.android.client.utils.observable.ChatObservableImpl$EventsMapper.onEvent (ChatObservableImpl.java:103)
io.getstream.chat.android.client.socket.ChatSocketServiceImpl.onRemoteEvent (ChatSocketServiceImpl.java:54)
io.getstream.chat.android.client.socket.EventHandler.handleMessage (EventHandler.java:10)`

**Comment by JcMinarro** [comment]
Hi @prarthnastockgro  Could you copy/paste the full stacktrace of the error?
Which version are you using?

**Comment by samiuelson** [comment]
@prarthnastockgro Thank you for reporting this, we are currently pushing on a new major release which will not be affected by this problem. You can subscribe to this issue to stay up-to-date to the release https://github.com/GetStream/stream-chat-android/issues/554
