### ISSUE TITLE
Active chat window shows user messages from other chats

### ISSUE THREAD

**Issue by prarthnastockgro** [GetStream/stream-chat-android#541]
Problem Statement: While being active on a chat window, the messages and "typing" view are shown from users from other active chats.
How can this be resolved?
@elevenetc @tschellenbach

**Comment by tschellenbach** [comment]
Which SDK version?

**Comment by prarthnastockgro** [comment]
4.0.13 @tschellenbach

**Comment by JcMinarro** [comment]
Hello @prarthnastockgro 
Several updates have been done from this version, could you confirm it is happening to you with the version 4.2.11-beta-6?
On that case, could you share the code to reproduce it?

**Comment by emitenma** [comment]
I can confirm -> by 4.0.14 the error was happening / i was able to reproduce it.
That in our latest version 4.2.11-beta-6 -> Is fixed / no longer happening.

Please update to the last version 👍
