### ISSUE TITLE
InputField background shape not aligned with border

### ISSUE THREAD

**Issue by AlanChienHouzz** [GetStream/stream-chat-android#5429]
**Describe the bug**
The InputField background shape not aligned with border if border's shape higher then 4 dp 

Commit: 027a606560554bb43f3d12e7f10332336bcd8907
Code: https://github.com/GetStream/stream-chat-android/commit/027a606560554bb43f3d12e7f10332336bcd8907#r147561735

I customized inputField's shape. It will cause the background still keep 16 dp because of you use `pollOptionInput` to clip. not sure if it's expected?

```kotlin
            val shapes = StreamShapes.defaultShapes().copy(
                inputField = RoundedCornerShape(4.dp),
            )
```

to fix this we should also add 
```kotlin
               pollOptionInput = RoundedCornerShape(4.dp)
```

**Screenshots**
![Screenshot_20241004_113419](https://github.com/user-attachments/assets/04af44ee-1fc3-4a20-9379-f5778f601d05)

**Comment by aleksandar-apostolov** [comment]
Hi @AlanChienHouzz 

Its a bug, thanks for reporting it. `pollOptionsInput` is just for the input fields on the "Create poll" component.
We will update this issue when this is fixed.

Regards,
Alex
