### ISSUE TITLE
Picture not sent in channel

### ISSUE THREAD

**Issue by spvince** [GetStream/stream-chat-android#545]
<h2>What did you do?</h2>
I want send photo in channel

<h2>What did you expect to happen?</h2>
Picture sent in channel

<h2>What happened instead?</h2>
Picture not sent in channel

<h2>GetStream Environment</h2>

Application: Sample stream chat
GetStream Chat version:
4.2.11-beta-4

**Comment by samiuelson** [comment]
Hi @spvince, thank you for reporting this. We are currently pushing on a new major release which will not be affected by this problem. You can already try the beta release and subscribe to this issue to stay up-to-date to the release https://github.com/GetStream/stream-chat-android/issues/554

**Comment by JcMinarro** [comment]
Hi @spvince 
Take picture and record video has been refactored and it is implemented on #531
This is a beta version and it is not completed yet. We will notify when it is ready to be used on #554
