### ISSUE TITLE
Deprecated Edge-to-Edge methods usage warning in Play Console

### ISSUE THREAD

**Issue by Lingviston** [GetStream/stream-chat-android#5458]
### Context & proposal

Update APIs used to implement edge-to-edge design in order to be compatible with Android 15.
Right now there's a warning in Play Console

> One or more of the APIs you use or parameters that you set for edge-to-edge and window display have been deprecated in Android 15. Your app uses the following deprecated APIs or parameters:

> `android.view.Window.setNavigationBarColor`
`android.view.Window.setStatusBarColor`

> These start in the following places:
`io.getstream.chat.android.ui.feature.gallery.AttachmentMediaActivity.setupSystemUi`
To prepare for the change to Android 15, migrate away from these APIs or parameters.

### Acceptance criteria

- Edge-to-edge design works on GetStream screens
- Play Store doesn't complain on deprecated APIs usage.

**Comment by VelikovPetar** [comment]
Hi @Lingviston,

Thank you for reporting this! We are working on providing support related to 'edge-to-edge' for apps targeting Android 15, and we plan to release it in some of the following releases.

Best regards,
Petar

**Comment by VelikovPetar** [comment]
Hi @Lingviston,

Support for edge-to-edge to was added and is now available in the [6.6.0](https://github.com/GetStream/stream-chat-android/releases/tag/v6.6.0) version of the SDK.


Best regards,
Petar
