### ISSUE TITLE
Migrate to Indication and Ripple APIs

### ISSUE THREAD

**Issue by Jacks0N23** [GetStream/stream-chat-android#5468]
### Context & proposal

Please, migrate to Indication and Ripple APIs according [docs](https://developer.android.com/develop/ui/compose/touch-input/user-interactions/migrate-indication-ripple). This blocks us from updating

### Acceptance criteria

ANDROIDX_COMPOSE >=1.7.0

**Comment by VelikovPetar** [comment]
Hi @Jacks0N23,

Thank you for bringing this to our attention!
We will have a look at the request and keep you posted.

Best regards,
Petar

**Comment by VelikovPetar** [comment]
Hi @Jacks0N23 ,

We updated compose to v1.7.5 and the usage of `RippleTheme` is removed. It is now available in the [6.6.0](https://github.com/GetStream/stream-chat-android/releases/tag/v6.6.0) version of the SDK.

Best regards,
Petar
