### ISSUE TITLE
Update user is not work

### ISSUE THREAD

**Issue by AlexanderKolesnikovSaritasa** [GetStream/stream-chat-android#551]
SDK 4.2.11-beta-5

I tried to update user avatar by Update User method:

```
    val extraData = hashMapOf("image" to newAvatarUrl)
    val user = User(userId, extraData = extraData)
    chatClient.updateUser(user)
```

As a result it was updated alright. But unfortunately, when you pause/resume your application, it retrieves the old avatar from some cache (ChatClientImpl.state maybe?) and updates avatar again. So, the user has old avatar.

**Comment by elevenetc** [comment]
Do you have any reproduction steps? Or it doesn't happen always?

**Comment by AlexanderKolesnikovSaritasa** [comment]
It doesn't happen always, but often.
I haven't any reproduction steps more.

**Comment by tschellenbach** [comment]
probably related to this : https://github.com/GetStream/stream-chat-android/issues/599
closing this ticket
