### ISSUE TITLE
custom message input typing is getting slower as one types fast

### ISSUE THREAD

**Issue by abhirup-patra** [GetStream/stream-chat-android#552]
i am using edit text as a input field where i have coded as it is provided in the documentation.

`<EditText
                    android:layout_weight="2"
                    android:id="@+id/messageInput"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:layout_marginStart="12dp"
                    android:visibility="visible"
                    android:text="@={viewModel.messageInputText}"
                    android:background="@android:color/transparent"
                    android:hint="Type a message"/>`

but using this is making the field get slow

**Comment by elevenetc** [comment]
- Could you paste full layout? 
- Could you mention Android system version and device model?
- Does it depend on battery level of the device?

**Comment by abhirup-patra** [comment]
`<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools">

    <data>

        <import type="android.text.TextUtils"/>
        <import type="android.view.View"/>
        <variable
            name="viewModel"
            type="com.getstream.sdk.chat.viewmodel.ChannelViewModel" />

    </data>

    <androidx.constraintlayout.widget.ConstraintLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintLeft_toLeftOf="parent">


        <LinearLayout
            android:id="@+id/messageInputContainer"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_margin="6dp"
            android:weightSum="2"
            android:layout_marginEnd="12dp"
            tools:context="com.example.chattutorial.ChannelActivity">

            <ImageView
                android:id="@+id/attachmentIv"
                android:layout_width="@dimen/dimen_50"
                android:layout_height="match_parent"
                android:padding="@dimen/dp_10"
                android:background="@color/white"
                android:src="@drawable/ic_attachment"
                app:layout_constraintLeft_toLeftOf="parent" />

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_marginStart="@dimen/dimen_5"
                android:background="@drawable/rounded_view"
                android:orientation="horizontal">

                <androidx.constraintlayout.widget.ConstraintLayout
                    android:id="@+id/imageViewLayout"
                    android:layout_width="0dp"
                    android:layout_height="wrap_content"
                    android:layout_weight="2"
                    android:gravity="center"
                    android:visibility="gone"
                    android:orientation="vertical"
                    android:padding="@dimen/dp_10">


                    <ImageView
                        android:id="@+id/closeBtn"
                        android:visibility="gone"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:src="@drawable/stream_ic_close"
                        app:layout_constraintEnd_toStartOf="@+id/imageAttachment"
                        app:layout_constraintStart_toStartOf="parent"
                        app:layout_constraintTop_toTopOf="parent" />

                    <ImageView
                        android:id="@+id/imageAttachment"
                        android:layout_width="@dimen/dp_150"
                        android:layout_height="@dimen/dp_150"
                        android:src="@drawable/stream_ic_logo"
                        android:visibility="gone"
                        android:scaleType="centerInside"
                        app:layout_constraintEnd_toEndOf="parent"
                        app:layout_constraintStart_toStartOf="parent"
                        app:layout_constraintTop_toTopOf="parent" />

                    <TextView
                        android:id="@+id/textOfAttachment"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:fontFamily="@font/roboto_medium"
                        android:text="Something.pdf"
                        android:textColor="@color/text_heading"
                        android:textSize="@dimen/font_15"
                        android:visibility="gone"
                        app:layout_constraintEnd_toEndOf="parent"
                        app:layout_constraintStart_toStartOf="parent"
                        app:layout_constraintTop_toBottomOf="@+id/imageAttachment" />
                </androidx.constraintlayout.widget.ConstraintLayout>

                <EditText
                    android:layout_weight="2"
                    android:id="@+id/messageInput"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:layout_marginStart="12dp"
                    android:visibility="visible"
                    android:background="@android:color/transparent"
                    android:hint="Type a message"/>

                <TextView
                    android:id="@+id/sendButton"
                    android:layout_width="@dimen/dimen_50"
                    android:layout_height="match_parent"
                    android:text="Send"
                    android:gravity="center"
                    android:layout_marginEnd="@dimen/dimen_5"
                    android:textSize="@dimen/dp_18"
                    android:textColor="@color/blue"/>

            </LinearLayout>





        </LinearLayout>

        <LinearLayout
            android:id="@+id/attachmentLayout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal"
            android:paddingTop="@dimen/dp_10"
            android:visibility="gone"
            android:paddingBottom="@dimen/dp_10"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/messageInputContainer"
            android:weightSum="3">

            <ImageView
                android:id="@+id/cameraAttachment"
                android:layout_width="30dp"
                android:layout_height="30dp"
                android:layout_weight="1"
                android:src="@drawable/ic_photo_camera_blue_24dp"/>
            <ImageView
                android:id="@+id/galleryAttachment"
                android:layout_width="30dp"
                android:layout_height="30dp"
                android:layout_weight="1"
                android:src="@drawable/ic_photo_blue_24dp"/>
            <ImageView
                android:id="@+id/fileAttachment"
                android:layout_width="30dp"
                android:layout_height="30dp"
                android:layout_weight="1"
                android:src="@mipmap/ic_files_blue"/>

        </LinearLayout>

        </LinearLayout>



    </androidx.constraintlayout.widget.ConstraintLayout>
</layout>`

- android 10 and device model is poco f1
- similar thing is happening with emulator as well so i dont think it depends on battery level

**Comment by abhirup-patra** [comment]
removing the `android:text="@={viewModel.messageInputText}` improves the performance to a much better way.

**Comment by JcMinarro** [comment]
This attribute is not needed anymore
