### ISSUE TITLE
Back button in ChannelHeaderView closes the entire app

### ISSUE THREAD

**Issue by pixnbit** [GetStream/stream-chat-android#553]
I'm the latest 4.2.11-beta-5, ChannelHeaderView has a back button. I have the view inside a Fragment, the behavior closes the entire app instead of going back to the previous page. It would be nice to have a setBackButtonClickListener similar to:

setHeaderOptionsClickListener
setHeaderAvatarGroupClickListener

I'm going to use findViewById for the time being:

```kotlin
    binding.channelHeader.findViewById<Button>(R.id.btn_back).setOnClickListener {
      requireActivity().findNavController(R.id.rootNavHostFragment).popBackStack() // with navigation component
    }
```

**Comment by samiuelson** [comment]
Thank you for reporting this, we are currently pushing on a new major release which will not be affected by this problem. You can already try the beta release and subscribe to this issue to stay up-to-date to the release https://github.com/GetStream/stream-chat-android/issues/554

**Comment by pixnbit** [comment]
Great to hear! But this is the issue on 4.2.11-beta-5, which is part of the 4.x release.

**Comment by samiuelson** [comment]
Yes, `ChannelHeaderView` is already refactored, on the `develop` branch. However, it couldn't be yet released without other components that we are working on at the moment.

**Comment by pixnbit** [comment]
Ah awesome 👏

**Comment by tschellenbach** [comment]
@pixnbit what are you working on?

**Comment by pixnbit** [comment]
Hey @tschellenbach! I'm evaluating a chat solution for our team, a seed-stage startup. My use-case is for communications between hourly workers and management team, we would have customized message types with user interactions.  I'm very impressed by the extensive dev support and documentation. We would be integrating the SDK into our iOS, Android, Flutter, and web clients. So far I'm very leaning towards Stream.io based on my research.

There're two concerns from my team, one is the upfront cost. It's not very friendly to smaller teams that just started with less volume of usage (vs PubNub's). Another is the worry about commitment from smaller players, after seeing Pusher dropped its chat efforts. I read some of the blog posts on the Stream website, I'm very biased as my team calls it, but I'd love to hear your thoughts.

**Comment by tschellenbach** [comment]
Glad to hear that. We're not that small anymore these days :) Stream and Sendbird are the biggest in the chat space atm. Pubnub has a chat product but its tiny compared to their realtime business. I don't think they are investing much into it and we rarely see people choose PubNub. Feel free to email me if you have any questions (thierry at getstream dot io)

**Comment by JcMinarro** [comment]
Hello @pixnbit 
`ChannelHeaderView` has been refactored
You can see it here #491 and how to integrate into your app on this sample #497 
It is already part of the version [4.2.11-beta-6](https://github.com/GetStream/stream-chat-android/releases/tag/4.2.11-beta-6), not a final release yet, we will update #554 when the final version is ready

**Comment by pixnbit** [comment]
Thank you will check out!

**Comment by JcMinarro** [comment]
Hello @pixnbit 
Were you able to check it out on the last version?
Is it working to you?

**Comment by pixnbit** [comment]
Hey @JcMinarro I did checkout beta-7 today. The new SDK APIs works great with our setup, we also use Jetpack Navigation Component I noticed you have that in your sample code. I managed to put together a search bar with autocomplete name search to start a DM (iOS version here: https://github.com/GetStream/stream-chat-swift/issues/379)

But on Android, the channels list is not updated with new messages and channeled created, also I see inconsistent "Channel without name" with DM 1:1 messages. I already filed a couple of bugs and improvements requests. I hope the future release would address these issues.

![out](https://user-images.githubusercontent.com/729730/89603103-297e0f80-d81d-11ea-816b-e7ecb5202c80.gif)

**Comment by JcMinarro** [comment]
Hello @pixnbit 
Thank you for your feedback, it is really useful, we really appreciate it.
We are going to investigate those two bugs you reported and will let you know when they are ready

**Comment by pixnbit** [comment]
This is my code for initiating the DM messages, after the autocomplete search query is back:

```kotlin
        val me = ChatClient.instance().getCurrentUser()!!
        val other = (searchSuggestion as ChatSearchSuggestion).user
        val memebers = listOf(Member(me), Member(other)).sortedBy { it.getUserId() }
        val channel = Channel().apply {
          this.cid = "messaging:" + memebers[0].getUserId() + "-" + memebers[1].getUserId()
          this.type = "messaging"
          this.members = memebers
        }
        val result = ChatDomain.instance().useCases.createChannel.invoke(channel).execute()
        when {
          result.isSuccess -> {
            Log.d("xydebug", "success")
            val direction = ChatChannelsFragmentDirections.chatChannelsToChatMessages()
            direction.channelId = channel.cid
            findNavController().navigate(direction)
          }
        }
```

**Comment by JcMinarro** [comment]
Hello @pixnbit 
Your last report seems to be covered on #698, and the previous ones seems to be fixed, so I am closing this issue for now.
Feel free to reopen if some of them are not working fine on our [last version](https://github.com/GetStream/stream-chat-android/releases/latest) or open a new ticket if you find another issue ;)
