### ISSUE TITLE
NoSuchElementException

### ISSUE THREAD

**Issue by AlexanderKolesnikovSaritasa** [GetStream/stream-chat-android#561]
SDK 4.2.11-beta-5

It seems that there is incorrect work with collections because today I got the next exception:

![image](https://user-images.githubusercontent.com/58584469/86872023-9b234a80-c105-11ea-9e14-87c8473cbe4f.png)

I haven't special steps to reproduce. Just simple workflow like opening channels, writing/reading messages, etc...
Check it, please.

**Comment by JcMinarro** [comment]
Hello @AlexanderKolesnikovSaritasa 

It should be fixed on the last version, 4.2.11-beta-7
Could you check?
