### ISSUE TITLE
unable to build 4.2.11-beta-6

### ISSUE THREAD

**Issue by abhirup-patra** [GetStream/stream-chat-android#566]
Throwing exception in channelviewbinding auto generated class

**Comment by JcMinarro** [comment]
Hello @abhirup-patra could you share the code of your integration and the log of the exception?

**Comment by abhirup-patra** [comment]
@JcMinarro  this is the error:

/home/nav15/Documents/abhirup/app latest/app/build/generated/data_binding_base_class_source_out/liveDebug/out/abentra/com/databinding/FragmentChannelListBinding.java:19: error: cannot find symbol
import com.getstream.sdk.chat.view.ChannelListView;
                                  ^
  symbol:   class ChannelListView
  location: package com.getstream.sdk.chat.view

**Comment by ezet** [comment]
I had a similar issue. `ChannelListView` has been moved, so you need to update all your references to this view.
