### ISSUE TITLE
All mesages on one side

### ISSUE THREAD

**Issue by Seg9** [GetStream/stream-chat-android#567]
Hi, I tried your 4.2.11 version and all messages are on one side. Is this a new approach, or am I something missing? I tried to debug the code, and isMine method is always false. Thanks

**Comment by JcMinarro** [comment]
Hello @Seg9 
It was fixed on #556 and added to version [4.2.11-beta-6.](https://github.com/GetStream/stream-chat-android/releases/tag/4.2.11-beta-6) Is it the one you are using?

**Comment by Seg9** [comment]
I tried 4.2.11-beta-5 and versions below, so I'll try the latest one. Thank you
