### ISSUE TITLE
Empty members

### ISSUE THREAD

**Issue by iqbalza** [GetStream/stream-chat-android#569]
I'm using 4.2.11-beta-6 and when I watch a channel using ChatDomain's useCases It always return empty members in data().toChannel().members and data().toChannel().memberCount

**Comment by JcMinarro** [comment]
Hello @iqbalza 
We aren't able to reproduce it.
Could you show us what code you are using that is not working for you?
Using something like the following code should work fine:
```
ChatDomain.instance().useCases.watchChannel(it.cid, 30).enqueue {
  if (it.isSuccess) {
    val channel = it.data().toChannel()
    println("Membbers of channel ${channel.cid} are:")
    channel.members.forEach { println("-. ${it.user.name}") }
  }
}
```
