### ISSUE TITLE
new update removed setting of viewmodel to the channelList and also custom factory to the channel list.

### ISSUE THREAD

**Issue by abhirup-patra** [GetStream/stream-chat-android#571]
Improper documentation and removal of setViewModel method from the channel list totally crashed the previously build project. Any documentation to rectify these? Even client is removed too. GetClient is not working anymore and as a result unable to use the query function

gz#4470

**Comment by shodgetts** [comment]
Agent comment from Séni Gueye in <a href='https://getstream.zendesk.com/agent/tickets/4470'>Zendesk ticket #4470</a>:<br><br>Hi,

Thanks for getting in touch.
I'm passing this on to our Android team to provide information regarding your issue.
They'll get back to you as soon as they can.

Best regards.
Seni

**Comment by shodgetts** [comment]
Agent comment from Jc Miñarro in <a href='https://getstream.zendesk.com/agent/tickets/4470'>Zendesk ticket #4470</a>:<br><br>Hello Abhirup-patra

We are working to update the documentation and wirte a migration guide to the new V4 version.
It is not completed yet.
The motivation to remove `setViewModel()` method is because it was coupled to the view and could produce some Memory Leaks.
Now the binding is on the oposite way. We are creating extension function over our `ViewModel` to bind the view.
So you can bind ViewModel on the following way:
```
val channelsListView: ChannelsListView = findChannelsListViewFromXML() // Find your view
val viewModel: ChannelsViewModelImpl = ChannelsViewModelImpl()
viewModel.bindView(channelsListView, lifecycleOwner)
```

**Comment by abhirup-patra** [comment]
can you provide a java code? That would be helpful

**Comment by abhirup-patra** [comment]
how to apply the custom factory to the channelList now?

Previously i used to do it like this.
```

CustomViewHolderFactory factory = new CustomViewHolderFactory(ChannelListFragment.this, context);
        binding.channelList.setViewHolderFactory(factory);
```

**Comment by JcMinarro** [comment]
Hello @abhirup-patra 
It continues working on the same way, this method has not been changed: https://github.com/GetStream/stream-chat-android/blob/master/library/src/main/java/com/getstream/sdk/chat/view/channels/ChannelListView.java#L89

You need to find your `ChannelList` view instance and then set the `ViewHolderFactory` as it was done before.

**Comment by abhirup-patra** [comment]
ok @JcMinarro , how to access the client in stream chat? it was previously accessed by this method. `Chat.getInstance().getClient()`
But now the getclient is showing as error

**Comment by abhirup-patra** [comment]
Previously i used to call the channelview view using binding function and used dot operator to access the setViewHolderFactory function. Now it throws error there.


`class ChannelsView @JvmOverloads constructor(
        context: Context,
        attrs: AttributeSet? = null,
        defStyleAttr: Int = 0
) : FrameLayout(context, attrs, defStyleAttr) {
    private var emptyStateView: View = defaultEmptyStateView()
    private var loadingView: View = defaultLoadingView()
    private val channelListView: ChannelListView = ChannelListView(context, attrs, defStyleAttr).apply { id = CHANNEL_LIST_VIEW_ID }

    init {
        addView(channelListView, LayoutParams(LayoutParams.MATCH_PARENT, LayoutParams.MATCH_PARENT))
        emptyStateView.apply {
            visible(false)
            addView(this, defaultChildLayoutParams())
        }
        loadingView.apply {
            visible(false)
            addView(loadingView, defaultChildLayoutParams())
        }
    }

    fun setEmptyStateView(view: View, layoutParams: LayoutParams = defaultChildLayoutParams()) {
        removeView(this.emptyStateView)
        this.emptyStateView = view.apply { id = EMPTY_STATE_VIEW_ID }
        addView(emptyStateView, layoutParams)
    }

    fun setLoadingView(view: View, layoutParams: LayoutParams = defaultChildLayoutParams()) {
        removeView(this.loadingView)
        this.loadingView = view.apply { id = LOADING_VIEW_ID }
        addView(loadingView, layoutParams)
    }

    fun setOnChannelClickListener(listener: (Channel) -> Unit) {
        channelListView.setOnChannelClickListener(listener)
    }

    fun setOnLongClickListener(listener: ChannelClickListener) {
        channelListView.setOnLongClickListener(listener)
    }

    fun setOnEndReachedListener(listener: () -> Unit) {
        channelListView.setOnEndReachedListener(listener)
    }

    fun setChannels(channels: List<Channel>) {
        channelListView.setChannels(channels)
    }

    fun hideLoadingView() {
        this.loadingView.visible(false)
    }

    fun showLoadingView() {
        this.loadingView.visible(true)
    }

    fun showEmptyStateView() {
        this.emptyStateView.visible(true)
    }

    fun hideEmptyStateView() {
        this.emptyStateView.visible(false)
    }

    private fun defaultChildLayoutParams() =
            LayoutParams(LayoutParams.WRAP_CONTENT, LayoutParams.WRAP_CONTENT, Gravity.CENTER)

    private fun defaultLoadingView(): View = ProgressBar(context).apply {
        id = LOADING_VIEW_ID
    }

    private fun defaultEmptyStateView(): View = TextView(context).apply {
        setText(R.string.stream_channels_empty_state_label)
        id = EMPTY_STATE_VIEW_ID
    }
}`

as you see this channelsview doesnt contain any setCustomViewHolderFactory function

**Comment by abhirup-patra** [comment]
`ChannelListViewModelBindingKt.bindView(viewModel, binding.channelList, getViewLifecycleOwner());`

this method is asking for channelView whereas i am passing channelListView.

When i pass channel view it doesnt contain the setCustomViewHolderFactory function. Please look into this.
In order to use the empty state i will have to use the channelView view. I think you have omitted to include the setCustomViewHolderFactory function for channelView

**Comment by JcMinarro** [comment]
Hello @abhirup-patra 

The new method has been added on #579 and it is now on the last version 4.2.11-beta-7 ;)
