### ISSUE TITLE
Add a method to identify streamchat related notifications

### ISSUE THREAD

**Issue by ezet** [GetStream/stream-chat-android#578]
As we already have a `FirebaseMessagingService` implementation, which handles a lot of different types of push notifications, we cannot directly add your `ChatFirebaseNotificationService` to the manifest. Instead, we need to be able to determine which type of push message it is, and then call the appropriate handler.

A common pattern for this on Android (e.g. intercom and others) is to provide a `isStreamChatMessage: Boolean` method, which we can use to then call `Client.onMessageReceived()`.

gz#4564

**Comment by shodgetts** [comment]
Agent comment from Séni Gueye in <a href='https://getstream.zendesk.com/agent/tickets/4564'>Zendesk ticket #4564</a>:<br><br>Hi,

Tanks for reaching out.
I'm passing this on to our Android team.
They'll get back to you shortly.

Best regards,

**Comment by JcMinarro** [comment]
Hello @ezet 
For now we don't have this feature on the SDK, but you are able to add your custom attribute to the data of your push notification from the Stream Dashboard.

**Comment by tschellenbach** [comment]
@tbarbugli can you chat with Jc about this?

**Comment by JcMinarro** [comment]
Hello @ezet 

We have done lot of changes into our SDK, and we have added a new method to know if a push payload is valid for Stream, you can use `ChatClient::isValidRemoteMessage` method now.
Could you update to the last version?
