### ISSUE TITLE
ChannelsView doesn't sort channels by last message.

### ISSUE THREAD

**Issue by DmitriiAfonin** [GetStream/stream-chat-android#582]
There is issue with Channels list on Android. Sorting by last message doesn't work.

**Used control:** com.getstream.sdk.chat.view.channels.ChannelsView
**SDK version:** 4.2.11-beta-6

**Example code:**
val filter = and(eq("type", "messaging"), in("members", presenter.profile.id))
        val sort = QuerySort().desc("last_message_at")

        val viewModel = ChannelsViewModelImpl(ChatDomain.instance(), filter, sort)
        viewModel.state.observe(this) {
            when (it) {
                is ChannelsViewModel.State.Result -> {
                    channelsList.setChannels(it.channels)
                    channelsList.hideEmptyStateView()
                    channelsList.hideLoadingView()
                }
                is ChannelsViewModel.State.Loading -> {
                    channelsList.hideEmptyStateView()
                    channelsList.showLoadingView()
                }
                ChannelsViewModel.State.NoChannelsAvailable -> {
                    channelsList.showEmptyStateView()
                    channelsList.hideLoadingView()
                }
            }
        }

**Result screenshot:** https://imgur.com/a/E5QaDb8

**Comment by JcMinarro** [comment]
It is a bug on the Stream-Livedata SDK. It is already reported here https://github.com/GetStream/stream-chat-android-livedata/issues/21 and a path will be release soon with this PR https://github.com/GetStream/stream-chat-android-livedata/pull/22

**Comment by JcMinarro** [comment]
Hello @DmitriiAfonin 
New version has been release that contains the improvement done into our Stream-Livedata SDK, and should be fixed it now.
Could you use the version 4.2.11-beta-7 and check if it is working fine to you now?

**Comment by DmitriiAfonin** [comment]
Hello,

Push notifications and channels sorting looks fixed by new version.

Thank you.


чт, 6 авг. 2020 г., 16:16 Jc Miñarro <notifications@github.com>:

**Comment by JcMinarro** [comment]
Thanks @DmitriiAfonin 

I am going to close this issue then
