### ISSUE TITLE
gif messages not rendering 

### ISSUE THREAD

**Issue by pixnbit** [GetStream/stream-chat-android#588]
Android (4.11-beta7) vs iOS
![Screenshot_1596739448](https://user-images.githubusercontent.com/729730/89569899-37f70780-d7da-11ea-8932-4fa065e76dc5.png)

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-08-06 at 11 44 10](https://user-images.githubusercontent.com/729730/89569878-32012680-d7da-11ea-8d2b-487e99b1493d.png)

**Comment by JcMinarro** [comment]
Hello @pixnbit 
It was fixed on #619 and added to the last released.
Could you check if it is working fine for you now?

**Comment by pixnbit** [comment]
Yes this has been resolved with upgrading to the latest SDK
