### ISSUE TITLE
Message ExtraData not being sent through. 

### ISSUE THREAD

**Issue by KonradWinkowski** [GetStream/stream-chat-android#599]
When we create a simple message and put some extra data on it as per the docs, the extra data is not present on the receivers end. The LinkedHashMap is always empty. 

For Example we setup the message with :
`val reactionMessage = Message().apply {
            text = value
            extraData[ChatMessageData.USER_ID_KEY] = userId
            extraData[ChatMessageData.IS_REACTION_KEY] = true
            userProfilePictureUrl?.let { extraData[ChatMessageData.PROFILE_PICTURE_URL_KEY] = it }
        }`
 
or with :
`message.extraData["userId"] = userId`
`message.extraData["isReaction"] = false`
`message.extraData["profilePictureUrl"] = userProfilePictureUrl!!`

the message before being sent contains 3 objects in the LinkedHashMap for extraData
then we send the message 

Once the message is received on it's own client or other clients that are connected to the same chat room. The extraData field is always empty. Doesn't matter if we set the value from iOS or Android. The Android clients never seem to receive the extra data.

**Comment by JcMinarro** [comment]
Hello @KonradWinkowski 
We are investigating it.
Could you tell us which version are you using?

**Comment by samiuelson** [comment]
Hi @KonradWinkowski, can you test the latest SDK version 4.2.11-beta-11?

**Comment by KonradWinkowski** [comment]
We'll give that a try

**Comment by tschellenbach** [comment]
Did that work? Feel free to open back up if needed.
