### ISSUE TITLE
Duplicate class PrimitivesKt with latest beta9

### ISSUE THREAD

**Issue by tonyfarag** [GetStream/stream-chat-android#603]
We are experiencing a crash with the signature at the end of this issue.  It may be resolved in beta9, but I am not able to integrate beta9 due to this build error.   The fix in beta9 that may be related is the null check over the wathers:

https://github.com/GetStream/stream-chat-android-client/releases/tag/1.15.1

Build Error:
`Duplicate class PrimitivesKt found in modules jetified-stream-chat-android-4.2.11-beta-9-runtime.jar (com.github.GetStream:stream-chat-android:4.2.11-beta-9) and jetified-stream-chat-android-livedata-0.7.2-runtime.jar (com.github.GetStream:stream-chat-android-livedata:0.7.2)

Go to the documentation to learn how to Fix dependency resolution errors.`

Crash stacktrace: 

`08-29 18:27:30.709  6082  6194 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String io.getstream.chat.android.client.models.User.getId()' on a null object reference
08-29 18:27:30.709  6082  6194 E AndroidRuntime:        at io.getstream.chat.android.livedata.controller.ChannelControllerImpl.setWatchers(ChannelControllerImpl.kt:877)
08-29 18:27:30.709  6082  6194 E AndroidRuntime:        at io.getstream.chat.android.livedata.controller.ChannelControllerImpl.updateLiveDataFromChannel(ChannelControllerImpl.kt:857)
08-29 18:27:30.709  6082  6194 E AndroidRuntime:        at io.getstream.chat.android.livedata.controller.ChannelControllerImpl.runChannelQueryOnline(ChannelControllerImpl.kt:358)
08-29 18:27:30.709  6082  6194 E AndroidRuntime:        at io.getstream.chat.android.livedata.controller.ChannelControllerImpl$runChannelQueryOnline$1.invokeSuspend(Unknown Source:12)
08-29 18:27:30.709  6082  6194 E AndroidRuntime:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
08-29 18:27:30.709  6082  6194 E AndroidRuntime:        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
08-29 18:27:30.709  6082  6194 E AndroidRuntime:        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
08-29 18:27:30.709  6082  6194 E AndroidRuntime:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
08-29 18:27:30.709  6082  6194 E AndroidRuntime:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
08-29 18:27:30.709  6082  6194 E AndroidRuntime:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
08-29 18:27:30.709  6082  6199 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-6
08-29 18:27:30.709  6082  6199 E AndroidRuntime: Process: com.mindmissiles.BusyBeesBabysitting, PID: 6082
08-29 18:27:30.709  6082  6199 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String io.getstream.chat.android.client.models.User.getId()' on a null object reference
08-29 18:27:30.709  6082  6199 E AndroidRuntime:        at io.getstream.chat.android.livedata.controller.ChannelControllerImpl.setWatchers(ChannelControllerImpl.kt:877)
08-29 18:27:30.709  6082  6199 E AndroidRuntime:        at io.getstream.chat.android.livedata.controller.ChannelControllerImpl.updateLiveDataFromChannel(ChannelControllerImpl.kt:857)
08-29 18:27:30.709  6082  6199 E AndroidRuntime:        at io.getstream.chat.android.livedata.controller.ChannelControllerImpl.runChannelQueryOnline(ChannelControllerImpl.kt:358)
08-29 18:27:30.709  6082  6199 E AndroidRuntime:        at io.getstream.chat.android.livedata.controller.ChannelControllerImpl$runChannelQueryOnline$1.invokeSuspend(Unknown Source:12)
08-29 18:27:30.709  6082  6199 E AndroidRuntime:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
08-29 18:27:30.709  6082  6199 E AndroidRuntime:        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
08-29 18:27:30.709  6082  6199 E AndroidRuntime:        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
08-29 18:27:30.709  6082  6199 E AndroidRuntime:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
08-29 18:27:30.709  6082  6199 E AndroidRuntime:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
08-29 18:27:30.709  6082  6199 E AndroidRuntime:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)`

Anybody else running into this and is there a solution ? 

Thanks,
Tony

**Comment by JcMinarro** [comment]
Hello @tonyfarag 
The problem with it was a class that we had duplicated on both SDKs.
It has been fixed on version 4.2.11-beta-10
