### ISSUE TITLE
ChannelListItemAdapter has incorrect channels

### ISSUE THREAD

**Issue by AlexanderKolesnikovSaritasa** [GetStream/stream-chat-android#618]
SDK 4.2.11-beta-6

I have the next part of code in my fragment:

```
private const val CHANNEL_FILTER_TYPE = "type"
private const val CHANNEL_FILTER_TYPE_VALUE = "messaging"
private const val CHANNEL_FILTER_ARCHIVED = "archived"
private const val CHANNEL_FILTER_MEMBERS = "members"

        val arrayId = arrayOf(userId)
        val filter = Filters.and(
            Filters.eq(CHANNEL_FILTER_TYPE, CHANNEL_FILTER_TYPE_VALUE),
            Filters.ne(CHANNEL_FILTER_ARCHIVED, arrayId),
            Filters.`in`(CHANNEL_FILTER_MEMBERS, userId)
        )

        // This query sort doesn't work, so we use custom sort in DirectMessagesAdapter.
        val querySort = QuerySort().desc("last_message_at")
        channelsViewModel.setQuery(filter, querySort)
```

As comment said, query sort doesn't work well, and sometimes there are non-sorted channels.
So, I have the next custom adapter:

```
class DirectMessagesAdapter(private val context: Context) : ChannelListItemAdapter(context) {

    override fun replaceChannels(channelList: MutableList<Channel>?) {
        Timber.i("DirectMessagesAdapter: replaceChannels before ${channelList?.map { it.id }}")
        val newChannelList = channelList?.filter { !it.isArchived() }?.sortedByDescending { it.lastMessageAt }
        Timber.i("DirectMessagesAdapter: replaceChannels after ${newChannelList?.map { it.id }}")
        super.replaceChannels(newChannelList)
    }
}

fun Channel.isArchived() : Boolean  {
    val currentUserId = ChatDomain.instance().currentUser.id
    val archives = this.extraData["archived"] as? ArrayList<*>
    return (archives?.any { it == currentUserId } ?: false)
}
```

This adapter helps to avoid incorrect sorting, but I found a new problem here.

Sometimes I get the channelList that has archived channels (but I wrote necessary filter). To avoid this problem, I have the isArchived function that works well sometimes also... I looked for a problem, and I found it - the extraData field of channel sometimes has necessary data, but sometimes not.

I can not list of steps to 100% reproduce this problem, but it reproduces sometimes if users archive/refresh channels.
I don't understand why data are not consistent sometimes. Investigate this problem, please.

**Comment by JcMinarro** [comment]
Hello @AlexanderKolesnikovSaritasa 
Thanks for your feedback.
This issue seems related with #599 where there are some issue with the extraData that an object contains.
We are investigating it and will try to fix it soon

**Comment by samiuelson** [comment]
Hi @AlexanderKolesnikovSaritasa please test with the latest version of the SDK 4.2.11-beta-11? Let us know if you have any problem
