### ISSUE TITLE
Feature Request: Provide custom listener for ChannelHeaderView back button

### ISSUE THREAD

**Issue by josheroff-livly** [GetStream/stream-chat-android#63]
The ChannelHeaderView has a back button that finishes the activity when pressed:
```
binding.tvBack.setOnClickListener(view ->{
      if(viewModel.isThread())
          viewModel.initThread();
      else
          ((Activity) getContext()).finish();
});
```
(ChannelHeaderView, lines: 96-101, v. 1.10.0)

My current use case calls for the Stream hierarchy of custom views to be in Fragments (the entry point being a tab within a `BottomNavigationView`), so it'd be nice to have this back button hook into the `NavigationController` of my Fragment instead. This way, my backstack will be able to coexist with the Stream custom views.

If the consumer were able to provide a click listener for the back button, that would satisfy the backstack use case.

**Comment by josheroff-livly** [comment]
Missed a method in the ChannelHeaderView, that's my mistake.

`setHeaderOptionsClickListener` was right there.

**Comment by Chikrix** [comment]
@josheroff-livly This doesn't look like the problem is solved. I think he meant the back arrow, which would be the `binding.tvBack` and not `binding.tvOption` which the `setHeaderOptionsClicklistener` is handling.
