### ISSUE TITLE
More than one file was found with OS independent path 'META-INF/library_release.kotlin_module'

### ISSUE THREAD

**Issue by CrazyDude1994** [GetStream/stream-chat-android#631]
Hello. While updating to the latest version (beta 11) from latest stable(4.2.7) I'm experiencing error in the title. I looked at your example, and noticed that you just exclude this file (exclude("META-INF/*.kotlin_module"))
But if I do that too, my layouts are messed up. (I've attached screenshot)
There was no any changes but just updating to latest version. Also when I bring the old one, everything looks fine. Also if you check this https://stackoverflow.com/a/56329676 it's actually said that you should NOT use exclude for kotlin_module. 

![Screenshot_1600174424](https://user-images.githubusercontent.com/3825127/93216243-248f7280-f770-11ea-852f-3c6fc7c07b03.png)

**Comment by tschellenbach** [comment]
partially fixed by https://github.com/GetStream/stream-chat-android-client/pull/71

**Comment by JcMinarro** [comment]
Hello @CrazyDude1994 it has been fixed on #637 and a new version has been released ;)
