### ISSUE TITLE
java.lang.ClassCastException caused by RedirectGlide 

### ISSUE THREAD

**Issue by dbogoslovtsev** [GetStream/stream-chat-android#653]
In our project, we use a custom Glide module which extends AppGlideModule. 

At the same time, one of the libraries your library depends on extends AppGlideModule too:
[RedirectGlide](https://github.com/aminography/RedirectGlide/blob/d9479c1ea54c43eabab1914cdcf27ca2b356cef9/redirectglide/src/main/java/com/aminography/redirectglide/OkHttpAppGlideModule.kt)

There is an unambiguous warning in Glide documentation ([Glide v4 Configuration](http://bumptech.github.io/glide/doc/configuration.html#avoid-appglidemodule-in-libraries)) regarding LibraryGlideModule extending instead of AppGlideModule:
>Avoid AppGlideModule in libraries
>Libraries must not include AppGlideModule implementations. Doing so will prevent any applications that depend on the library from managing their dependencies or configuring options like Glide’s cache sizes and locations.

>In addition, if two libraries include AppGlideModules, applications will be unable to compile if they depend on both and will be forced to pick one or other other.

>This does mean that libraries won’t be able to use Glide’s generated API, but loads with the standard RequestBuilder and RequestOptions will still work just fine (see the options page for examples).

So the exact problem is: during code generation, our implementation of GlideApp is being overridden by RedirectGlide, which is leading to this crash:
`java.lang.ClassCastException: com.aminography.redirectglide.GlideRequests cannot be cast to com.**********.util.svg.GlideRequests`

Currently, I have ended up with this workaround:
[Crash when project uses Glide v4.11.0 and stream-chat-android v4.3.2](https://github.com/GetStream/stream-chat-android/issues/468#issuecomment-627971401)
`implementation ('com.github.GetStream:stream-chat-android:4.2.3') {
  exclude group: 'com.aminography', module: 'redirectglide'
}`
but it would be nice to get this thing fixed

**Comment by JcMinarro** [comment]
Hello @dbogoslovtsev 
It was fixed on #473 
You can use the last version https://github.com/GetStream/stream-chat-android/releases/tag/4.3.0-beta-1 that already have this fix included

**Comment by dbogoslovtsev** [comment]
Sorry, I didn't mention the version I'm using, it's 4.3.0-beta-1 and 4.2.11-beta-12 before it. 
I misled you by copypaste from link with 4.2.3 version, my fault

**Comment by dbogoslovtsev** [comment]
@JcMinarro Why did you close it? The issue still reproduces on any latest build

I have previously posted the link to the specific class, which is still extended from AppGlideModule
https://github.com/aminography/RedirectGlide/blob/master/redirectglide/src/main/java/com/aminography/redirectglide/OkHttpAppGlideModule.kt
