### ISSUE TITLE
Android 11 - Picture not sent in channel

### ISSUE THREAD

**Issue by spvince** [GetStream/stream-chat-android#657]
<h2>What did you do?</h2>
I want send photo in channel with android 11

<h2>What did you expect to happen?</h2>
Picture sent in channel

<h2>What happened instead?</h2>
Picture not sent in channel. An a toast is displayed "Failed due to an unknown error."

<h2>GetStream Environment</h2>

Application: Sample stream chat
GetStream Chat version: 3.6.16
Android Version : 11

**Comment by ogkuzmin** [comment]
Hello @spvince 
Thanks for submitting this issue. We're going to investigate and fix it!

**Comment by JcMinarro** [comment]
Hello @spvince 
It was fixed on #602 
Version 3.X is not supported anymore
Could you try with the last [version](https://github.com/GetStream/stream-chat-android/releases/tag/4.3.0-beta-3)?

**Comment by spvince** [comment]
Hi @JcMinarro,
it's not a good news. i think version 3.x is more stable than 4.x. I've had lot of issue with the beta version in the past. So i prefer wait a stable version and a documentation up to date to start integration of this library and lost the less time as possible.
