### ISSUE TITLE
is there a way to get the unread message count in realtime?

### ISSUE THREAD

**Issue by abhirup-patra** [GetStream/stream-chat-android#693]

**Comment by JcMinarro** [comment]
Yes, you can.
To get it you need to observer the `totalUnreadCount` livedata.
Something like:
```
ChatDomain.instance().getTotalUnreadCount().observe(lifecycleOwner, new Observer<Integer>() {
            @Override
            public void onChanged(Integer unreadCount) {
                Log.d("Tag", "You have " + unreadCount + " unread messages");
            }
        });
```

**Comment by tarunkhatri** [comment]
@JcMinarro ChatDomain class is not available, i am using -
  
 implementation 'io.getstream:stream-chat-android-ui-components:5.11.0'
 implementation 'io.getstream:stream-chat-android-client:5.11.0'

these libraries

**Comment by JcMinarro** [comment]
Hello @tarunkhatri 

`ChatDomain` was removed, and instead of that, we introduced `GlobalStates` that simplifies its use.
To obtain the unread messages count, you can use the following code:
```
ChatClient.instance().globalState.totalUnreadCount.collect {
  println("You have $it unread messages")
}
```

You can also know the number of channels that have unread messages using:
```
ChatClient.instance().globalState.channelUnreadCount.collect {
  println("You have $it unread messages")
}
```
