### ISSUE TITLE
The latest build is asking for backgroundSync to be called when declaring chatdomain and upon calling it is showing blank channel list in the latest build 4.3.1 beta 1

### ISSUE THREAD

**Issue by abhirup-patra** [GetStream/stream-chat-android#706]
when backgroundSync is passed with the stream chat api key and the user id the list is coming as blank

**Comment by samiuelson** [comment]
Hi @abhirup-patra, 

the channel list loading logic doesn't depend on `backgroundSyncEnabled()` or `backgroundSyncDisabled()` setting in `Chat.Builder()`. 

Could you test with the latest SDK version `4.3.1-beta-2` and give us more details to reproduce the channel list loading issue?

**Comment by abhirup-patra** [comment]
when i am trying to create chatdomain, it is asking me to call backgroundSyncEnabled. Previous versions didnt ask for this. 

Previously i use to declare chatDomain like this : 

`chatDomain = new ChatDomain.Builder(getApplicationContext(), client, user).build();`

Now here, they are asking me to pass the backgroundSyncEnabled here.

**Comment by samiuelson** [comment]
In the next SDK release `backgroundSync` will be disabled by default. Using the current version you can call `disableBackroundSync` to satisfy `ChatDomain.Builder` if you don't want background sync feature.

**Comment by JcMinarro** [comment]
Hello @abhirup-patra  

It has been fixed on the [last release](https://github.com/GetStream/stream-chat-android/releases/latest)
It should be working fine now
