### ISSUE TITLE
Hiding Channel not working as excepted

### ISSUE THREAD

**Issue by soethan98** [GetStream/stream-chat-android#723]
**Describe the bug**
clear message history not working when hiding a channel

**SDK version**
- 1.16.6

**To Reproduce**

channelController.hide(clearHistory = true).enqueue {
            if (it.isSuccess) {
                Log.i("ChannelEventResult", "Success")

            } else {
                Log.i("ChannelEventResult", it.error().message.toString())

            }
        }

**Expected behavior**
 It actually didn't delete the message history.

**Comment by zsmb13** [comment]
Closing this for now due to inactivity.
