### ISSUE TITLE
Events are not being received after going background

### ISSUE THREAD

**Issue by CrazyDude1994** [GetStream/stream-chat-android#731]
I'm using version 4.2.9-beta-1

When app goes to background, and comes back the old listener does receiving new data anymore.

I also debugged your SDK a little, and I noticed that even onEvent is not being called in ChatSocketServiceImpl, while other users are receiving new events fine (which didn't go to background)

Also socket seems to reconnect fine, but for some reason it does not receive any new events anymore.

**Comment by CrazyDude1994** [comment]
Closing this, as it was issue with calling setUser when not needed

**Comment by daniilbug** [comment]
Hey guy, have the same issue. Please, say where I should call setUser? I'm doing this in my activity ViewModel on its init. Is it wrong?

> Closing this, as it was issue with calling setUser when not needed
