### ISSUE TITLE
Add missing API endpoints

### ISSUE THREAD

**Issue by tbarbugli** [GetStream/stream-chat-android#74]
### Channel methods to implement

- [x] update
- [x] delete
- [x] add members
- [x] remove members
- [x] ban user
- [x] unban user
- [x] get reactions
- [x] accept invite
- [x] reject invite
- [x] deleteFile
- [x] deleteImage
- [x] hide
- [x] show
- [x] message search (https://getstream.io/chat/docs/#search)
- [x] channel.stopWatching (https://getstream.io/chat/docs/#watch_channel)
- [x] queryUsers needs work (it doesn't support filter object like you would expect)

**Comment by bevzaanton** [comment]
- [x] hide #80 
- [x] show #80

**Comment by bevzaanton** [comment]
- [x] ban user #87  
- [x] unban user #87

**Comment by bevzaanton** [comment]
- [x] delete #94

**Comment by bevzaanton** [comment]
- [ ] update #102

**Comment by bevzaanton** [comment]
- [ ] add members #121 
- [ ] remove members #121

**Comment by bevzaanton** [comment]
- [x] get reactions

**Comment by tschellenbach** [comment]
added message search to the list

**Comment by tschellenbach** [comment]
added stopWatching to the list

**Comment by bevzaanton** [comment]
- [ ] channel.stopWatching #164

**Comment by bevzaanton** [comment]
- [ ] accept invite #163 
- [ ] reject invite #163

**Comment by bevzaanton** [comment]
- [ ] deleteFile #185
- [ ] deleteImage #185
