### ISSUE TITLE
Mute function does nothing on success

### ISSUE THREAD

**Issue by CrazyDude1994** [GetStream/stream-chat-android#745]
So when using mute function, it does nothing, but I receive a success message. I know it's up to you to implement the way how user will be muted, but I expected to currentUser.mutes list to be updated. It's not being update. Am I missing something?

**Comment by tschellenbach** [comment]
`chatDomain.muted: LiveData<List<Mute>>` live updates when you receive a mute event.

see https://getstream.io/chat/docs/livedata/?language=js#building-the-chatdomain for a full list of livedata objects exposed on the chatDomain. Let us know if you run into any issues.
