### ISSUE TITLE
Filter direct message

### ISSUE THREAD

**Issue by bibibilu** [GetStream/stream-chat-android#834]
I am using FilterObject to divide the channels into Group Messages and Direct Messages. I used eq("category", "group") for Group Messages, but I have no idea of how to filter out direct channels. What would be the equivalent to field isDirectMessage on iOS? Any suggestions?

**Comment by tschellenbach** [comment]
you typically want to use different channel types for group vs direct messages. (the permissions and features tend to be different for these.)

see channel type docs: https://getstream.io/chat/docs/channel_features/?language=kotlin

**Comment by tschellenbach** [comment]
to clarify, you can use the FilterObject to filter on the channel types. You could also do something like eq("mycustomfield", "group") or eq("mycustomfield", "dm"). But it's a better approach to have different channel types for this and filter on that.

**Comment by JcMinarro** [comment]
Hello @bibibilu 

If you need to filter only messages that are DM, you can do a filter like the following one:
```
Filters.and(
            Filters.`in`("members", listOf(ChatDomain.instance().currentUser.id)),
            Filters.lessThanEquals("member_count", 2)
        )
```

What it does is request all channels where the current user is member of the channels and there are as max as 2 member into the channel

**Comment by bibibilu** [comment]
Hello @JcMinarro 
It works properly when I filter like following:
```
Filters.and(
            Filters.`in`("members", listOf(ChatDomain.instance().currentUser.id)),
            Filters.lessThanEquals("member_count", 2)
        )
```
However, if I add ```Filters.`in`("members", listOf(ChatDomain.instance().currentUser.id))```, the DM channel list shows "Channel without name".

**Comment by bibibilu** [comment]
Btw, how to use contains in filter? I want to filter out some channel from DM list whose cid contains a substring.

**Comment by tschellenbach** [comment]
You can filter on custom properties you've set in the extra data. You can't do substring lookups on the cid. 

The "Channel without name" issue is a race condition which causes the livedata objects not to load client side. The develop branch has a fix for this and it will go live with the next release cc @ogkuzmin

**Comment by bibibilu** [comment]
Thanks for remind! "channel without name" got solved!
