### ISSUE TITLE
After chat disconnect the connection restored partially: messages are sent and delivered, but events are not tracked

### ISSUE THREAD

**Issue by serbeys** [GetStream/stream-chat-android#839]
**Describe the bug**
I just followed the tutorial https://getstream.io/tutorials/android-chat/#
- Added subscription to all events in Channel Activity
- Opened chat
- Updated channel from web app
- Can see (channel.updated) events in a code where i subscribed for events
- Moved the app to background to disconnect chat (but this may happen by any other reason: like bad internet or server responce)
- Opened the app from a background
on UI chat connected and messages are send/received successfully
- Updated channel from web app
- Can not see (channel.updated) events
- See a lot of continuous ‘connection.error’ messages sometimes (may this is useful)

**SDK version**
- 4.4.1

**To Reproduce**
- Write the app according tutorial https://getstream.io/tutorials/android-chat/#
- Add subscription to all events in Channel Activity
- Open chat
- Update channel from web app
- Can see (channel.updated) events in a code where i subscribed for events
- Move the app to background to disconnect chat (but this may happen by any other reason: like bad internet or server responce)
- Open the app from a background
- on UI chat connected and messages are send/received successfully
- Update channel from web app
- Can not see (channel.updated) events
- See a lot of continuous ‘connection.error’ messages sometimes (may this is useful)

**Expected behavior**
After chat disconnect the connection restored: and events are possible to track

**Device:**
 - Vendor and model: [e.g. Samsung S8]
![image](https://user-images.githubusercontent.com/3114887/98689866-8a763000-2396-11eb-8d58-5bdbe638dc4d.png)

 - Android version: 7

**Screenshots**
https://share.getcloudapp.com/8LurAW55

**Comment by daniilbug** [comment]
The same problem 😔

**Comment by JcMinarro** [comment]
Hello @serbeys 
On the video you are sharing I can't see any connection.error message. The `health.check` is a periodically events that is sent/received to/from the server to keep the connection opened.
Could you share the error you are talking about?
What are you updating from the web when you click on `Show Showtimes` button?

**Comment by serbeys** [comment]
Sometimes connection.error happens - sometimes no
It did not appear when i recorded video

Issue is not with it - issue with an absent "channel.updated" event
Show Showtimes executes channel.update() adding channel custom field and I expect to see "channel.updated" as it was before disconnection

**Comment by tschellenbach** [comment]
Are you using chatDomain or the lower level chat client? if you're using the lower level client you need to call client.getSyncHistory after the network recovers. if you use the chat domain the recovery logic is handled for you by the library.

@JcMinarro i wonder if we could move some of this logic to the lower level client..

**Comment by tschellenbach** [comment]
@serbeys did the getSyncHistory API call solve your problem? In general we recommend using the chatDomain which handles this logic for you automatically.

**Comment by tschellenbach** [comment]
I think the most actionable thing here is to improve our documentation around the getSyncHistory API call. Thanks for letting us know and feel free to reach out if you run into further issues
