### ISSUE TITLE
Feature request: Allow for custom viewhlder view types in MessageViewHolderFactory

### ISSUE THREAD

**Issue by lukenowakcom** [GetStream/stream-chat-android#86]
In `MessageViewHolderFactory`:
```
public MessageListItemType getEntityViewType(MessageListItem messageListItem, Boolean mine, List<Position> positions) 
```
requires that returned type is MessageListItemType, effectively making it impossible to provide custom viewhodlder in 
```
 public BaseMessageListItemViewHolder createMessageViewHolder(MessageListItemAdapter adapter, ViewGroup parent, MessageListItemType viewType)
```

Would it be possible to make `getEntityViewType` return `Int` like in regular adapter, so that we could provide custom `BaseMessageListItemViewHolder`  in `createMessageViewHolder`?

**Comment by tschellenbach** [comment]
Good idea. That's silly. Adrian, can you pick this up?

**Comment by adrian09h** [comment]
I see, I will update it.
