### ISSUE TITLE
Firebase push notification app in foreground handling

### ISSUE THREAD

**Issue by beckmartin** [GetStream/stream-chat-android#871]
**Describe the bug**
Not really a bug, but I could not find anything in the docs about this.
I could confirm retrieval of a Firebase RemoteMessage object within the OfflineSyncFirebaseMessagingService's onMessageReceived when the app was in foreground. I want to handle this message, but in the ChatNotifications class it does not handle it. Do I have to write my own Service or is there an easier way?

**SDK version**
- latest

**To Reproduce**
1. Sent push when app is in foreground

**Expected behavior**
Make use of RemoteMessage object when app is in foreground

**Device:**
 Samsung S9
Android 10

**Screenshots**

**Comment by samiuelson** [comment]
Hey @beckmartin, 

Stream's backend doesn't send the notification to the device if there is an ongoing active web socket connection. You will receive the message when the app is in background only (WS connection is disconnected).

In the foreground, we provide our websocket-based implementation which allows subscribing and listening for events of different types. You can learn more in our docs here: https://getstream.io/chat/docs/event_listening/?language=kotlin

Let us know if you need any help with it. I'm closing the issue for now.

**Comment by beckmartin** [comment]
@samiuelson Thank you for you quick reply, how would I listen to a NewMessageEvent for all channels the user currently has. Do I have to query all channels first and loop over them to have multiple channel controllers?

**Comment by samiuelson** [comment]
@beckmartin This should be a simplier way to achieve this:
```kotlin 
ChatClient.instance().subscribeFor(NewMessageEvent::class.java, MessageUpdatedEvent::class.java) {
            
}       
```
