### ISSUE TITLE
No posibility to get only stream-chat-android-client module

### ISSUE THREAD

**Issue by kstanislav** [GetStream/stream-chat-android#878]
**Description**
No chance to pull only stream-chat-android-client using 
```groovy
dependencies {
    implementation 'com.github.GetStream:stream-chat-android-client:latest-version'
}
```
Latest available version - 1.16.8

**SDK version**
- 4.4.2

**Expected behavior**
```groovy
dependencies {
    implementation 'com.github.GetStream:stream-chat-android-client:4.4.2'
}
```
is working. Because I don't need other modules.

**Comment by JcMinarro** [comment]
Hello @kstanislav 
By some limitation in Jitpack (The platform that we are using currently to publish our artifacts) the artifact group needs to be changed for a single artifact.
So, for now, you need to use the following dependency name:
```
implementation 'com.github.getstream.stream-chat-android:stream-chat-android-client:4.4.2'
```

We have in  our pipeline migrate our artifact to bintray that will remove this limitation

**Comment by kstanislav** [comment]
Sure, thank you. But now the problem is more about the need to update the README.MD, because that leads to a misunderstanding.
