### ISSUE TITLE
[Question] Migration guide from GetStream LLC to GetStream Android SDK

### ISSUE THREAD

**Issue by hashlin** [GetStream/stream-chat-android#892]
Our team is currently using [GetStream Low Level Client](https://github.com/GetStream/stream-chat-android-client). As this repo is archived, we are thinking about switching to this repo's low level client.

I found [a guide](https://github.com/GetStream/stream-chat-android/tree/master/stream-chat-android-client), but it does not seem to be an updated one. 

It would be super helpful if there is a migration guide for it. Thanks. 

Edit : More clarification for my question.
We are currently using `com.github.getstream:stream-chat-android-client:1.16.8`. Which artifact should be used to keep up to date with latest Low Level Client?

**Comment by tschellenbach** [comment]
The codebase was moved to improve how we handle issues and collaborate on pull requests. So it's the same codebase that you are already using. See the changelog for details about the changes: https://github.com/GetStream/stream-chat-android/blob/master/CHANGELOG.md

Let us know if you run into any issues, I suspect the needed changes to update are minimal.

**Comment by hashlin** [comment]
Thanks @tschellenbach .

Just want to clarify which version should we use to keep up to date.
`com.github.GetStream:stream-chat-android-client:4.x.x`
or
`com.github.Getstream:stream-chat-android-client:1.16.8`

**Comment by tschellenbach** [comment]
The 4.x branch. The team standardized version names on our 3 sdks which is
why the version bumped up to 4.x

**Comment by JcMinarro** [comment]
Hello @hashlin 

As Thierry said, we have moved LLC and Offline-Support into this repository to improve our development process.
All of them are into an individual module to allow you to use only the dependencies you need.
As you are using only the LLC, you only need to use the `stream-chat-android-client` dependency.

By some limitation with Jitpack (The platform we currently are using to delivery our artifacts), the groupId of the dependency needs to be updated, you need to use the following one:

```
com.github.getstream.stream-chat-android:stream-chat-android-client:4.4.4
```

To fix this issue we are migrating to MavenCentral, so, from Version 4.4.5 (It is not ready yet) or higher, you can use our company GroupId
```
io.getstream.stream-chat-android:stream-chat-android-client:4.4.5
```

**Comment by hashlin** [comment]
Thanks @tschellenbach, Thanks @JcMinarro for clarification.
It's clear now.
