### ISSUE TITLE
Cannot build Android App after upgrading to 4.4.3

### ISSUE THREAD

**Issue by coachroebuck** [GetStream/stream-chat-android#896]
**Describe the bug**
Android Studio 4.1.1:
All I did was update the version of your library in the gradle file:
```
implementation 'com.github.GetStream:stream-chat-android:4.4.3'
```
Now I can no longer build the Android app. The build never has a chance
```
Could not GET 'https://jitpack.io/com/github/GetStream/stream-chat-android-core/4.4.3/stream-chat-android-core-4.4.3.pom'. Received status code 401 from server: Unauthorized
```
I had the bright idea to copy+paste that url into a web browser. Apparently I don't even have read access to your repository.
**SDK version**
- 4.4.3

**To Reproduce**
1. Update the build.gradle file of the app:
```
implementation 'com.github.GetStream:stream-chat-android:4.4.3'
```
2. Attempt to rebuild the app
3. See error

**Expected behavior**
I can either successfully build the app, or I receive a build error related to my own app.

**Device:**
 - Vendor and model: Samsung S8
 - Android version: 9

**Screenshots**
Not applicable

**Comment by tschellenbach** [comment]
thank you for this detailed report, looks like something went wrong with our build system. the team will investigate.

**Comment by JcMinarro** [comment]
Hello @coachroebuck 
We are having some issues with Jitpack  (The platform that we are using currently to publish our artifacts) and the Version 4.4.3 is not valid anymore. We did a rollback to the version 4.4.2 and created a new version to temporally fix this issue, You can see the changelog [here](https://github.com/GetStream/stream-chat-android/releases).
For now you can use the version 4.4.4 and all should be working fine:
```
implementation 'com.github.GetStream:stream-chat-android:4.4.4'
```
