### ISSUE TITLE
Other language support for string resources

### ISSUE THREAD

**Issue by CrispBull** [GetStream/stream-chat-android#906]
**Describe the bug**
A previous version of this project had the strings localized in some languages, upgrading to this new version breaks everything and it seems like those resources where deleted from this project and the new strings weren't localized.

**Comment by JcMinarro** [comment]
Hello @CrispBull 
Could you tell us which version was you using preivously?
To avoid conflict into application from other devs, we have prefixed all our resources with `stream_`

**Comment by CrispBull** [comment]
I was using the 3.5.1 version, but this isn't a problem before. Then I saw on the readme links to some language translations but I don't see that it's maintained again and has even been deleted as string resources used in the library were changed and deleted. But this isn't an issue for me again so I'll be closing this one out
