### ISSUE TITLE
Can `joined this channel along with 1 others` message be removed for channels, created only for 2 users?

### ISSUE THREAD

**Issue by aengussong** [GetStream/stream-chat-android#909]
![image](https://user-images.githubusercontent.com/26045876/100339005-f9cc6080-2fe1-11eb-8ffa-49e4ede3a149.png)

Can this type of message be removed somewhere on the ChatClient settings or in the chat creation flow? Honestly, I didn't event found any mention of this kind of message in the documentation. Or the only way for me now to not display it is to hide message with this exact text in the custom `BaseMessageListItemViewHolder`?

**Comment by JcMinarro** [comment]
Hello @aengussong 

It is an optional text that could be sent from the SDK.
Previously it was mandatory, but it has been updated on #915 to allow you to disable this message
It will be ready on the next release

**Comment by aengussong** [comment]
@JcMinarro thank you very much, will be looking forward to the next release
