### ISSUE TITLE
Callback errors do not get reported to the SDK client

### ISSUE THREAD

**Issue by jasenmoloy** [GetStream/stream-chat-android#92]
It looks like certain listeners do not allow the SDK client to handles errors. Specifically classes that implement within the SDK:
* `com.getstream.sdk.chat.storage.Storage.OnQueryListener`
* `com.getstream.sdk.chat.rest.interfaces.QueryChannelListCallback`

The anonymous classes that implement these interfaces don't provide a way to let the SDK client know when errors occur. Some are even marked as `// TODO`.

We need this functionality in order to report errors to users, debugging tools, retry, and/or alter our logic.

Some use cases that come to mind:

* User has no network connectivity
* Server is not responding
* Latency is so high that we need to indicate to the user that we're in a loading state

**Comment by tschellenbach** [comment]
We made some progres on that today actually. Adrian can you have a look if
we also caught the ones mentioned above?

**Comment by tschellenbach** [comment]
I think the next android release will be monday. Perhaps friday if testing
goes well

**Comment by tbarbugli** [comment]
#91 handles this
