### ISSUE TITLE
Retry logic when querying channels needs improvement/refactor

### ISSUE THREAD

**Issue by jasenmoloy** [GetStream/stream-chat-android#93]
The anonymous class that is handling the callback for querying channels has retry logic when an error occurs. 

Specifically `ChannelListViewModel` line 311:
```
            public void onError(String errMsg, int errCode) {
                Log.e(TAG, "onError for loading the channels " + errMsg);
                if (attempt > 100) {
                    Log.e(TAG, "tried more than 100 times, give up now");
                    return;
                }
                if (!client().isConnected()) {
                    return;
                }
                int sleep = Math.min(500 * (attempt * attempt + 1), 30000);
                Log.d(TAG, "retrying in " + sleep);
                retryLooper.postDelayed(() -> {
                    queryChannelsInner(attempt + 1);
                }, sleep);
            }
```

The logic in this `onError()` method does not log an error occurs until 100 attempts are made. That's a significant amount of time before it's logged. What's the reason for such a high number of attempts?

This is related to #92 where it would be nice to inform the SDK client that an error occurs so we can present UI to the user that something went wrong.

**Comment by tbarbugli** [comment]
👍 currently the lib does something reasonable by default but it is true that expose retry logic makes a lot of sense

The change is fairly small, I am just waiting for a PR to get merged before we get this one done; 

@jasenmoloy what do you think is the friendlies thing to do for the library? I was thinking maybe we allow you to pass something like an interceptor function with this signature: `ResponseError error`, `int attemptCount` and something like a stop function. With that you can decide what to do about the error and if you want to stop retrying just call `Stop()`

**Comment by jasenmoloy** [comment]
My concern with having retry logic along with an exposed callback is the inflexibility. Depending on the error, we probably won't retry at all. Also having retry logic in the library with an exposed callback opens up to edge cases.

For example, I don't see the `retryLooper`'s runnables getting canceled if there is a lifecycle change.

**Comment by tschellenbach** [comment]
Totally agree, do you have an example of how you've seen other libraries make this customizable? We can come up with something, but if you have an idea of how you'd like it to work let us know

**Comment by tschellenbach** [comment]
Took a quick pass at it, what do you think?
https://github.com/GetStream/stream-chat-android/pull/109

Also made it easier to subclass the viewModel in case you want to change anything else in the business logic
