### ISSUE TITLE
Installing the Java Chat SDK

### ISSUE THREAD

**Issue by alfianyusufabdullah** [GetStream/stream-chat-android#947]
This is right place `implementation` in `compileOptions` scope?
```gradle
compileOptions {
        
        //for java projects
        implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```
AFAIK, `implementation` property just part of dependencies.

**Comment by zsmb13** [comment]
That's correct! As you said, the `implementation` line goes into `dependencies`, it's misplaced in this snippet of our README. We'll update this soon.

**Comment by zsmb13** [comment]
README is now up-to-date if you look at it on `develop` https://github.com/GetStream/stream-chat-android/tree/develop

(It will only be updated on the main repo page and `master` on the next release)
