### ISSUE TITLE
Chat initializes after activity is put in background and then back in foreground

### ISSUE THREAD

**Issue by savked** [GetStream/stream-chat-android#95]
I implemented the Getstream chat into my Android app, but the chat only loads after I put the app in the background and come back to it. Before that, inside onCreate where I do all the logic like in the example [here](https://getstream.io/tutorials/android-chat/#java).

The log shows successful connect to the /connect endpoint and 201 response for device registration on /devices endpoint. After that the progress bar keeps spinning and this is shown in logcat every second:

`2019-10-04 14:33:29.621 9284-9434/de.tourlina.Tourlina.staging D/WebSocketService: WebSocket Response : {"connection_id":"f06c52e2-6628-42b3-a485-796eca46e6ae","cid":"*","type":"health.check","created_at":"2019-10-04T12:33:27.10919249Z"}
2019-10-04 14:33:58.555 9284-9435/de.tourlina.Tourlina.staging W/ourlina.stagin: Accessing hidden method Ljava/lang/ThreadGroup;-><init>()V (greylist-max-o, reflection, denied)
2019-10-04 14:33:58.572 9284-9435/de.tourlina.Tourlina.staging W/ourlina.stagin: Accessing hidden method Ljava/util/concurrent/locks/ReentrantLock$Sync;-><init>()V (greylist-max-o, reflection, denied)
2019-10-04 14:33:58.590 9284-9435/de.tourlina.Tourlina.staging W/ourlina.stagin: Accessing hidden method Ljava/net/InetSocketAddress;-><init>()V (greylist-max-o,core-platform-api, reflection, denied)
2019-10-04 14:33:58.595 9284-9435/de.tourlina.Tourlina.staging W/ourlina.stagin: Accessing hidden method Ljava/net/InetSocketAddress;-><init>()V (greylist-max-o,core-platform-api, reflection, denied)`

I tried putting all the code in onStart, onResume and so on, but nothing worked. What could the issue be?

**Comment by tbarbugli** [comment]
Can you try the same but using the latest version of the SDK (2.1.0) ?

**Comment by savked** [comment]
Hi, thank you for answering. 
Already using 2.1.0 and updated all libraries. I tried different versions of Getstream, but nothing worked.

**Comment by tschellenbach** [comment]
Does the android tutorial work for you?

If it does, what is different with your setup?

Livedata can get funky at times. Which version are you using of Google
lifecycle lib?

**Comment by tschellenbach** [comment]
try using this in your build.gradle

```
    implementation 'androidx.lifecycle:lifecycle-extensions:2.1.0'
```

the 2.2 branch of lifecycle extensions is buggy

**Comment by tschellenbach** [comment]
can you also try upgrading your android studio to make sure there is nothing wrong with your build tools? 

if the above two don't work, can you share which emulator you're testing on and if the default sample app in the repo works for you?

**Comment by savked** [comment]
> Does the android tutorial work for you?

It does.

> If it does, what is different with your setup?

Nothing, I tried using the Activity as a chat (same bug), but since I previously used Fragment, we are using fragment right now. It is all the same.

> try using this in your build.gradle

I believe I am using 2.1.0 right now but will check out for sure on Monday.

> can you also try upgrading your android studio to make sure there is nothing wrong with your build tools?

Will do on Monday, I believe SDK tools is 28 or something.

>if the above two don't work, can you share which emulator you're testing on and if the default sample app in the repo works for you?
I tested on physical devices: Google Pixel, Google Pixel 2XL and Nexus 5X. Now when I think about it, it's all Google devices but the sample app did work on all of them.

**Comment by tschellenbach** [comment]
Which timezone are you in? Happy to do some realtime debugging to figure it
out sometime next week.

**Comment by tschellenbach** [comment]
So far we've seen cases where livedata doesnt work well. Definitely 2.2
breaks reliable when you enable proguard.

**Comment by savked** [comment]
Thank you very much, I am in CEST, but can adjust to meet with your time. Email me at savadimitrijevic99@gmail.com to set the time.

**Comment by tschellenbach** [comment]
Invite sent, let me know if the time doesn't work. Hope to find out exactly when this stuff breaks.
