### ISSUE TITLE
How to implement custom MessageListItemViewHolder

### ISSUE THREAD

**Issue by kplanz** [GetStream/stream-chat-android#951]
We are using version 4.4.2 of the SDK and we successfully implemented a custom `ChannelListItemViewHolder`, which was quite easy and allowed us to override certain UI behaviors.

Now we want to do the same thing for the message list and wanted to implement a custom `MessageListItemViewHolder`. But this class and all the `Configurator`s that are used to build the UI are marked `internal` so we cannot use it.
If we try to extend `BaseMessageListItemViewHolder` we are starting from scratch and would need to implement all the UI logic from scratch.

So implementing E2EE like here is very hard now: https://getstream.io/blog/encrypted-messaging-app-android/
We tried to use `MessageListViewModel.State.Result` to decrypt the messages, which works quite OK, but the encrypted messages still show up for a short time. 

What would be the recommended way with the current version to override the message list UI to implement for example E2EE?

Thank you for your help!

**Comment by zsmb13** [comment]
Our internal `Configurator` classes are very specifically designed to work with the layout used by `MessageListItemViewHolder` at the moment. This means that for customization that requires a new layout, having these public would still not be helpful. If you wanted to apply just a set of `Configurator`s, or create your own `Configurator`s on top of the existing ones (that still works with the same layout), that would work though.

---

For a use case like `MessageListItemViewHolder`, it seems that it would be enough if we opened the ViewHolder class, and let you override its `bind` method, like this:

```kotlin
public class EncryptedMessageViewHolder(
    parent: ViewGroup,
    style: MessageListViewStyle,
    channel: Channel,
    viewHolderFactory: AttachmentViewHolderFactory,
    bubbleHelper: BubbleHelper,
    messageClickListener: MessageClickListener,
    messageLongClickListener: MessageLongClickListener,
    messageRetryListener: MessageListView.MessageRetryListener,
    reactionViewClickListener: ReactionViewClickListener,
    userClickListener: MessageListView.UserClickListener,
    readStateClickListener: ReadStateClickListener,
) : MessageListItemViewHolder(
    parent,
    style,
    channel,
    viewHolderFactory,
    bubbleHelper,
    messageClickListener,
    messageLongClickListener,
    messageRetryListener,
    reactionViewClickListener,
    userClickListener,
    readStateClickListener,
) {
    override fun bind(messageListItem: MessageItem, diff: MessageListItemPayloadDiff) {
        if (messageListItem.message.type != ModelType.message_regular) {
            super.bind(messageListItem, diff)
            return
        }

        val modifiedItem: MessageItem = MessageItem()

        super.bind(modifiedItem, diff)
    }
}
```

Is this the customization you're looking for, or do you also want to modify the work that the `Configurator`s do somehow?

**Comment by kplanz** [comment]
@zsmb13 Yes, that would be super helpful for us, since it would be an easy way to just do some modifications on the `Message` object. 
Thank you!

**Comment by JcMinarro** [comment]
Hello @kplanz 

We already opened the `MessageListItemViewHolder` class on #960  and it is included on the last version we released.
Could you update to version 4.4.6 and check if it helps you?

BTW, recently we migrated our lib to Maven Central, if you are using our Jitpack version yet, you should update your build.gradle integration.

Be sure you have added Maven Central into your repositories
```gradle
repositories {
    mavenCentral()
    ...
}
```

Add the new artifats, the groupId of the artifacts has changed to `io.getstream`
```gradle
dependencies {
    implementation "io.getstream:stream-chat-android:4.4.6"
    ...
}
```

**Comment by kplanz** [comment]
@JcMinarro @zsmb13 Great thank you so much!

After updating from 4.4.2 to 4.4.6 we now have an issue with the `ChannelListItemViewHolder`. We cannot override `bind` anymore because now `ChannelItemPayloadDiff` is marked `internal`.
So one problem fixed, another one appeared 😅 Should I open a new issue for that?

**Comment by JcMinarro** [comment]
Hello @kplanz 

We are working on a new UI components artifact and this change was done because of the new artifact.
Let me update it to allow you to use your custom ViewHolder

**Comment by kplanz** [comment]
Ok, no problem. Currently it's not urgent, we moved our logic from `bind` to `applyStyle` for now.
