### ISSUE TITLE
Vertical scrollbar for the `MessageInputView`

### ISSUE THREAD

**Issue by aengussong** [GetStream/stream-chat-android#961]
Hi!

Can `scrollbars` xml attribute be added for the `MessageInputView`? I would like to add vertical scrollbar to multiline input so the user can see the size of the text that he typed. It seems that I can't do it right now programmatically.

Thanks!

**Comment by JcMinarro** [comment]
Hello @aengussong 

Thanks for the suggestion. We have added it to our backlog

**Comment by zsmb13** [comment]
This was implemented in https://github.com/GetStream/stream-chat-android/pull/981 and will be part of the next release, 4.4.7

**Comment by JcMinarro** [comment]
Hello @aengussong It is ready on the last version, could you update?
